### ISSUE TITLE
Correção da listagem por instituição na "home" do site.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#10]
## Contexto:

Atualmente não existe um campo que representa instituição no SciELO Manager. Existe o campos para o `publisher` que será corrigido em breve o `sponsor` que no modelo é um especialização de instituição.

Precisamos entender melhor qual é o real objetivo da lista por instituição, pois existe uma salada de termos e esses termos confundem o objetivo da listagem, existe nessa listagem o termo "editoras", portanto não sabemos se estamos falando da editora ou instituição ou são a mesma coisa.

Por agora deixamos a listagem agrupado por **financiador**, mas esse ticket visa realizar essa correção.
## O problema:

Como foi visto na ultima apresentação (14/12/15) a listagem de periódicos por "instituição" lista os periódicos por _financiadores_  e deve ser corrigido.
Além disso não temos 100% de clareza.... se a listagem deve ser por Casa Editora (Publishing House) como suspeitamos, ou por outro campo.
## Objetivo desta tarefa:
1. Definir o critério da listagem "por instituição" que aparece no site.
2. Implementar a listagem segundo o critério definido no ponto 1.

**Comment by alexxxmendonca** [comment]
A lista por instituição foi removida do site.

Por ora, fecharemos este ticket e se porventura esta demanda for retomada, retomaremos esta discussão.
