### ISSUE TITLE
Inclusão da funcionalidade de empilhamento de artigos para geração de pdf customizado

### ISSUE THREAD

**Issue by viniciusnunesmacedo** [scieloorg/opac#1001]
Inclusão da funcionalidade da geração de uma lista dos artigos selecionados para geração de um único arquivo no formato pdf.
Esta alteração contempla a inclusão de um botão intitulado "Criar um livro" ao lado do botão "PDF" nos detalhes do artigo.
Abaixo desse mesmo botão será apresentado uma lista com os artigos selecionado com a opção de exclusão.
A biblioteca .js dessa implementação será vinculada com um servidor cdn para que não impacte o projeto

**Comment by BradooDev** [comment]
Senhores,
a necessidade do pull request vem da proposta de criação de coleções para usuários do SciELO. Desta forma, conseguiremos ofertar ferramentas aos usuários, onde poderão organizar, manter e divulgar suas coleções dentro de um portal de serviços criado para este público;

Conforme alinhamento realizado em reunião precisamos adicionar a biblioteca .JS que possuirá o botão para empilhamento de artigos e o pré-visualização dos itens selecionados previamente.

Protótipo das telas aprovadas:
![scielo_prototipopilhaartigosfechadaicone](https://user-images.githubusercontent.com/22329569/44731476-a80e9600-aab9-11e8-9377-748269b7d8d8.png)
![scielo_prototipopilhaartigosfechada](https://user-images.githubusercontent.com/22329569/44731486-a9d85980-aab9-11e8-86d5-87f510833986.png)
![scielo_prototipopilhaartigos](https://user-images.githubusercontent.com/22329569/44731490-aba21d00-aab9-11e8-95f8-ff219e0af09b.png)
![scielo_prototipoadicionarartigo](https://user-images.githubusercontent.com/22329569/44731494-ad6be080-aab9-11e8-867e-6448ebc3d693.png)
![scielo_prototipoempilharartigobusca](https://user-images.githubusercontent.com/22329569/44731506-b0ff6780-aab9-11e8-990d-5e0ed5430525.png)

**Comment by jamilatta** [comment]
@BradooDev 

Sou desenvolvedor no projeto SciELO e irei validar o PR: https://github.com/scieloorg/opac/pull/1007, mas antes de validar o PR, é necessário entendermos o **escopo** dessa nova funcionalidade. 

Diante da última tela que você apresentou... entendo que o armazenamento dos itens na lista "Minha Seleção" terá um escopo de **Rede SciELO**, correto?. Pois, para cada item listado na ferramenta de pesquisa [seach]( https://search.scielo.org), o domínio pode mudar e o domínio da própria aplicação muda, o que significa que a abordagem de utilizar **localStorage** não seria adequada diante da premissa "Pages on other domains can't access the same storage objects.", ref: [Restrição do objeto Storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#Responding_to_storage_changes_with_the_StorageEvent).

Repare que o domínio das primeiras telas são diferentes da última tela.

Precisamos entender como o código enviado para o Projeto OPAC no PR: https://github.com/scieloorg/opac/pull/1007/files irá tratar essa situação e/ou haverá um PR para o Search resolvendo essa restrição e como iremos tratar essa funcionalidade nas demais instâncias do SciELO que estão instaladas em locais distintos com domínios distintos.

Pontualmente a abordagem apresentada deve funcionar no OPAC como sendo **listagem** por **instância** o que significa que nesse caso  a abordagem está correta(ainda precisamos avaliar o código enviado), mas para o caso de envolver outras instâncias e outras aplicações como é o caso do https://search.scielo.org, acredito que devemos ter outra abordagem.

**Comment by BradooDev** [comment]
Jamil,

obrigado por suas considerações. E você esta correto, a primeira versão do agregador foi pensada para trabalharmos no dominio scielosp somente, uma vez que se trata de uma arquitetura de multi-dominios.

Nosso objetivo primeiramente é validar o funcionamento dentro deste domínio, na tela de detalhe do artigo, e em novas versões, serão aboradadas soluções para tratar a arquitetura de toda rede sciELO. 

Foram anexadas todas as telas afim do escopo total fucional seja claro para todos envolvidos.

obrigado.

**Comment by jamilatta** [comment]
@gustavofonseca 

Podemos aprovar a abordagem mencionada pelo @BradooDev?

**Comment by alexxxmendonca** [comment]
Por ora, fecharemos este ticket devido à descontinuidade do projeto.

Podemos avaliar a reabertura desta demanda caso necessário.
