### ISSUE TITLE
Adicionar suporte aos *Visual Abstracts*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1005]
A mensagem abaixo é composta por atividades que se estendem além deste repositório de código, mas será colocada aqui por motivos de simplicidade:

```
O periódico JBN nos solicitou há um tempo atrás se podemos considerar a inclusão de _"visual abstract"_ / _"resumo visual"_ na metodologia SciELO.  A resposta é sim. O como é que está pendente de ser definido. 
Nas conversas que tive com a Solange e Gustavo e minhas leituras, podemos pensar no seguinte:

(a) agregar no SciELO PS um elemento opcional "Visual Abstract" . Penso que isso pode ser feito com relativa facilidade. O elemento deve apontar para um arquivo que pode ser uma imagem ou um pdf. 

(b) agregar no display do artigo uma entrada no menu lateral para o visual abstract. Ao cliclar no mesmo se publica o visual abstract em uma janela popup

(c) agregar um link antes do resumo - visual abstract | resumo visual e que se comporta como (b) ao clicar

(d) futuramente agregar também no sumario

(e) até não resolver os pontos anteriores vamos publicar os visual abstracts como press releases ou como uma entraa específica visual abstract.

Para info sobre o que é visual abstract veja https://bit.ly/2nNACiK
```

**Comment by RPostalli** [comment]
Será documentado tagueamento parar Visual Abstract para SPS versão 1.9 ver em: 
[scieloorg/scielo_publishing_schema#773](https://github.com/scieloorg/scielo_publishing_schema/issues/773)
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/master/tagset/elemento-abstract.html

A interface deve lidar com a informação tanto no âmbito do artigo como no sumário eletrônico.

**Comment by alexxxmendonca** [comment]
Referências e discussão no SPS: https://github.com/scieloorg/scielo_publishing_schema/issues/773

Aplicação no site antigo:
![20190424_02](https://user-images.githubusercontent.com/4059679/56899625-42b8dd80-6a6a-11e9-899e-fb84ce22167d.jpg)

**Comment by paratiuid** [comment]
@alexxxmendonca 

Veja se é dessa maneira que você imagina a solução para este ticket:
Adicionei o item "resumo visual". Abaixo deixo a versão com ele fechado e aberto.

Fechado:
![rv-fechado](https://user-images.githubusercontent.com/22373640/58184946-79a89a80-7c88-11e9-9d80-b797db3352c1.jpg)


Aberto:
![rv-aberto](https://user-images.githubusercontent.com/22373640/58184971-85945c80-7c88-11e9-9aa2-fbe1f55edade.jpg)

**Comment by alexxxmendonca** [comment]
@paratiuid por que está vindo o resumo em formato de texto também? Não deveria ser somente a imagem?

**Comment by paratiuid** [comment]
@alexxxmendonca correto.
Acredito que sim.

Apenas peguei uma imagem postada pelo @gustavofonseca nesse ticket:
https://github.com/scieloorg/scielo_publishing_schema/issues/773

Vou corrigir, exibindo apenas o visual.

**Comment by alexxxmendonca** [comment]
@paratiuid entendi. Aquela imagem é do texto completo, que vem logo abaixo do resumo em texto. Acho que por isso deu a entender que eram ligados um ao outro, porém não são.

**Comment by paratiuid** [comment]
@alexxxmendonca 
segue a correção:

![rv-aberto-v3](https://user-images.githubusercontent.com/22373640/58185902-47983800-7c8a-11e9-8023-498ebe31aa6d.jpg)

**Comment by alexxxmendonca** [comment]
@paratiuid de acordo 👍

**Comment by paratiuid** [comment]
Pessoal, 
ao codificar a interface percebi que o visual abstract ainda não está no sistema.
Conversei com o @jamilatta e ele me disse para enviar o comportamento do sistema funcionando corretamente mas com conteúdo fake, por ora.

Dessa maneira, estou enviando 3 imagens de exemplo, representando os idiomas pt, en e es.

Abaixo segue uma imagem que ilustra como deve ficar a tela com o novo comportamento e com imagens fake, por enquanto.

![Screen Shot 2019-05-22 at 3 32 45 PM](https://user-images.githubusercontent.com/22373640/58200270-cbf9b380-7ca8-11e9-978a-1ad6b78323be.png)

**Comment by robertatakenaka** [comment]
@alexxxmendonca @RPostalli 
Se ao clicar no resumo texto, é aberto a página do artigo. Ao clicar no resumo visual não deveria acontecer a mesma coisa? Abrir a página do artigo e ir até o resumo visual?

**Comment by alexxxmendonca** [comment]
@robertatakenaka ao clicar no resumo texto, não vai para a página do artigo. Abre-se um dropdown com o resumo.

**Comment by robertatakenaka** [comment]
@alexxxmendonca devo ter me confundido

**Comment by cesarbruschetta** [comment]
https://github.com/scieloorg/opac/tree/paratiuid-tk1005
Branch o PR desenvolvido pela parati como proposta inicial de solução da tarefa

**Comment by alexxxmendonca** [comment]
Link do artigo de teste: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0101-28002018005023102&lng=pt&nrm=iso&tlng=pt

**Comment by robertatakenaka** [comment]
- [ ] #1363 
 - [ ] #1364
