### ISSUE TITLE
Ajustar totais da home do OPAC.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1023]
Na home do OPAC atualmente exibimos os totais independente do status do periódico, devemos apresentar apenas os periódicos com status de **ativo**.

**Comment by jamilatta** [comment]
@gustavofonseca 

Poderia me passar qual endpoint do analytics eu poderia utilizar para ter esse campos de **ativo/inativo**?

**Comment by gustavofonseca** [comment]
@jamilatta, acho melhor obter de http://articlemeta.scielo.org/api/v1/collection/?code=scl, para evitar dependência direta de mais um serviço.

**Comment by jamilatta** [comment]
@gustavofonseca 

OK.

**Comment by gustavofonseca** [comment]
Note que eu ainda não inseri os campos na interface Thrift. Se for necessário só me avise por gentileza que eu faço isso.

**Comment by jamilatta** [comment]
@gustavofonseca 

Vou verificar e te aviso!

**Comment by jamilatta** [comment]
@gustavofonseca 

Confirmado não iremos precisar do **Thrift**.

**Comment by jamilatta** [comment]
Item realizado no PR: https://github.com/scieloorg/opac_proc/pull/359
