### ISSUE TITLE
Verificar o funcionamento do link de PDF do ReadCube

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1028]
Verificar o funcionamento do link do PDF do ReadCube no site novo

https://opac.scielo.br/toc/aob/2018.v26n3/

**Comment by robertatakenaka** [comment]
**Análise e Conclusão**
Funciona:
http://www.scielo.br/readcube/epdf.php?doi=10.5935/abc.20180142&pid=S0066-782X2018001400142&pdf_path=https://opac.scielo.br/article/ssm/content/raw/?resource_ssm_path=/media/assets/abc/v111n2/0066-782X-abc-20180112.pdf


Funciona:
http://www.scielo.br/readcube/epdf.php?doi=10.5935/abc.20180142&pid=S0066-782X2018001400142&pdf_path=https://ssm.scielo.br/media/assets/aob/v26n3/1809-4406-aob-26-3-0158.pdf


Não funciona. Abre o PDF fora do ReadCube
http://opac.scielo.br/readcube/epdf.php?doi=10.5935/abc.20180142&pid=S0066-782X2018001400142&pdf_path=https://ssm.scielo.br/media/assets/aob/v26n3/1809-4406-aob-26-3-0158.pdf


Não funciona. Messagem que faltam parâmetros
http://opac.scielo.br/readcube/epdf.php?doi=10.5935/abc.20180142&pid=S0066-782X2018001400142&pdf_path=https://opac.scielo.br/article/ssm/content/raw/?resource_ssm_path=/media/assets/abc/v111n2/0066-782X-abc-20180112.pdf

Conclusão: Somente funciona se a URL é www.scielo.br não importa se o pdf_path é do ssm ou do opac.scielo.br

**Comment by gustavofonseca** [comment]
Enviei uma mensagem para um contato no readcube solicitando informação.

**Comment by gustavofonseca** [comment]
O contrato com o ReadCube vai até o dia 24/10/2018. Vamos manter o serviço indisponível durante o período beta do site e depois avaliarmos a remoção da implementação.
