### ISSUE TITLE
Layout desconfigurado

### ISSUE THREAD

**Issue by odiliohilariomoreirajunior** [scieloorg/opac#1036]
Nas páginas informativas o layout desconfigurou na migração para o site novo conforme exemplo dos links abaixo. Aparentemente o código está correto.

Site antigo
http://www.scielo.br/revistas/remhu/iaboutj.htm

Site novo
https://opac.scielo.br/journal/remhu/about/#about

**Comment by alexxxmendonca** [comment]
Eu vejo e estou usando o Chrome:

![image](https://user-images.githubusercontent.com/4059679/45712068-c3713c00-bb61-11e8-8efe-f938e3d6d6e7.png)
