### ISSUE TITLE
[scielobr] Lista de arquivos HTML baixo htdocs (ativos digitais)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1049]
Listagem de arquivos html presentes em www.scielo.br que podem talvez estejam ausentes no new.scielo.br

[scielo_br_HTMLS.txt](https://github.com/scieloorg/opac/files/2442223/scielo_br_HTMLS.txt)

Exemplos: 
- https://new.scielo.br/article/mioc/1997.v92n4/477-481/en/
   Contém https://new.scielo.br/img/fbpe/mioc/v92n4/html/05fig1.htm, mas não resolve.

   - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02761997000400005&lng=en&nrm=iso&tlng=en
   - http://www.scielo.br/img/fbpe/mioc/v92n4/html/05fig1.htm

- https://new.scielo.br/article/acb/2002.v17n6/381-387/en/
  Contém link para http://new.scielo.br/videos/acb/v17n6/n6a05vd.htm
  - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-86502002000600005&lng=en&nrm=iso&tlng=en

**Comment by patymori** [comment]
Resolvido.
