### ISSUE TITLE
Melhoria na URL das páginas do site

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1067]
Por exemplo:

No lugar de:
https://new.scielo.br/collection/about/

Gerar
``https://new.scielo.br/about/``

No lugar de:
``https://new.scielo.br/collection/about/?page_id=<page_id>``

Gerar
``https://new.scielo.br/about/<page_name>``

**Comment by patymori** [comment]
Nos casos em que as páginas são criadas com o mesmo `slug_name`, como em `Critérios SciELO Brasil` em Português e Espanhol, somente uma delas é sempre aberta (neste caso, a em Português). Reabrindo a issue.
