### ISSUE TITLE
Logs temporariamente deshabilitado devem ser ajustados

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#107]
#### Problema:

a infra para escrever logs da app opac, foram desativamos temporariamente, para atender mais rápido a tarefa de documentar o processo de instalação segundo o Modelo de Implantação de Aplicações SciELO. Porém, a app vai necessitar de logs.
##### Objetivos:

Aprimorar as configurações do logs, para que seja compatível e viável no cenário de deploy.

**Comment by jamilatta** [comment]
@jfunez 

talvez devêssemos dar uma olha com a turma do flask manipula os log, sugestão: 

* http://flask.pocoo.org/docs/0.10/errorhandling/
* https://gist.github.com/ibeex/3257877

**Comment by jfunez** [comment]
fechando por inválido!
