### ISSUE TITLE
"Artigos mais recentes": abrir na mesma janela

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1097]
Na homepage do periódico, os links dos "Artigos mais recentes" estão abrindo em outra janela:

![image](https://user-images.githubusercontent.com/4059679/48350505-911a2180-e66e-11e8-821c-bbebba989aae.png)

O correto é abrir na mesma janela.

**Comment by patymori** [comment]
@alexxxmendonca, feita atualização da nova versão. Pode verificar em new.scielo.br?

**Comment by alexxxmendonca** [comment]
Testado e aprovado!
