### ISSUE TITLE
Revisar mensagens para o usuário, comentários, docstring, etc

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#11]
## Problema:

Atualmente existem mensagens para usuário, comentários, docstrings, arquivos de configuração ou falta de textos em diferentes idiomas, confusos, ambíguos entre outros.

## Objetivo: 

Reescrever os textos utilizando o idioma português de forma clara.

**Comment by jfunez** [comment]
Resolvido para poder continuar com o #12
