### ISSUE TITLE
Link para PDF/Texto completo não aparece no sumário

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1104]
![image](https://user-images.githubusercontent.com/4059679/48482815-d36f6a00-e7f8-11e8-8369-7752da89fa8f.png)

https://new.scielo.br/toc/rlae/2018.v26/

**Comment by robertatakenaka** [comment]
@jfunez @jamilatta @patymori 
Acontece problema na Transformação

uuid: 0ad25fa0-72f1-4dcb-93ca-818cc45db211
PID: S0104-11692018000100205

<img width="948" alt="captura de tela 2018-11-21 as 14 09 24" src="https://user-images.githubusercontent.com/505143/48853655-1bf9cb00-ed97-11e8-9559-ddae91f8e696.png">

**Comment by jfunez** [comment]
@robertatakenaka `StatusCode.UNAVAILABLE` indica que teve um problema de comunicão com o servidor GRPC.

**Comment by jamilatta** [comment]
@robertatakenaka seria alguma indisponibilidade momentânea do GRPC.

É necessário verificar o GRCP e reprocessar.

**Comment by robertatakenaka** [comment]
Sim, resolveu reprocessando. Obrigada @jfunez @jamilatta
