### ISSUE TITLE
Agregar campo de busca de periódicos na página inicial

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1112]
Na página inicial, agregar junto à faixa "Lista de periódicos" um campo de busca com sugestões automáticas conforme o usuário vai digitando o título do periódico:

![image](https://user-images.githubusercontent.com/4059679/49233934-34449800-f3de-11e8-8d06-1781aa06d141.png)

**Comment by julianomaciel** [comment]
@alexxxmendonca 

Alex, minha dúvida é se a lista de sugestões deve aparecer em um dropdown (auto-complete) com os títulos dos periódicos e se deve existir algum evento ao ser selecionado um item ?

A funcionalidade deste issue está relacionada à [issue 51 do scielo.org](https://github.com/scieloorg/scielo.org/issues/51) ?

Atenciosamente,
Juliano.

**Comment by alexxxmendonca** [comment]
@julianomaciel não está relacionada.

Pode ser um dropdown sim, como aquela primeira solução que você propôs para o issue 51 mas eu descartei.

**Comment by julianomaciel** [comment]
> @julianomaciel não está relacionada.
> 
> Pode ser um dropdown sim, como aquela primeira solução que você propôs para o issue 51 mas eu descartei.

@alexxxmendonca, com a seleção de um item na lista abrindo uma nova aba com a url do periódico ?

Atenciosamente,
Juliano.

**Comment by alexxxmendonca** [comment]
@julianomaciel sim, porém mesma aba.

**Comment by paratiuid** [comment]
@alexxxmendonca 

segue o mockup da tela com o componente de busca por periódicos:

Ao carregar a tela:
![screen shot 2019-02-06 at 3 27 59 pm](https://user-images.githubusercontent.com/22373640/52360797-fdb17c00-2a23-11e9-8499-8ce430a53b0e.png)

Ao digitar mais de três caracteres:
![screen shot 2019-02-06 at 3 28 12 pm](https://user-images.githubusercontent.com/22373640/52360905-305b7480-2a24-11e9-9439-bf5be7f9a4be.png)

Ao clicar, ou dar enter na opção selecionada, ele direciona para a home do periódico.

Aguardo suas observações.

**Comment by alexxxmendonca** [comment]
o campo pode ser mais largo?

**Comment by paratiuid** [comment]
Tem sim.
Fiz os ajustes. Veja aí o que você acha:

![screen shot 2019-02-06 at 3 56 58 pm](https://user-images.githubusercontent.com/22373640/52362548-fdb37b00-2a27-11e9-8bdc-aaff100adb31.png)

![screen shot 2019-02-06 at 3 57 07 pm](https://user-images.githubusercontent.com/22373640/52362562-03a95c00-2a28-11e9-9e63-9f6994a8e9aa.png)

![screen shot 2019-02-06 at 3 57 21 pm](https://user-images.githubusercontent.com/22373640/52362568-099f3d00-2a28-11e9-8176-980f5409ce41.png)

Aguardo aprovação.

**Comment by alexxxmendonca** [comment]
Agora sim, ficou ótimo 👍

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.

**Comment by jamilatta** [comment]
Vou atualizar a produção com esse ajuste.
