### ISSUE TITLE
Home do periódico: informações de ISSN na mesma linha

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1114]
Otimizar as informações de ISSN para uma única linha, ao invés de duas.

![image](https://user-images.githubusercontent.com/4059679/49237635-cb611e00-f3e5-11e8-8392-2137f59bea9f.png)

Modelo sugerido:

**ISSN:** XXXX-XXXX (impresso); XXXX-XXXX (online)

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.

**Comment by jamilatta** [comment]
@paratiuid 

Acredito que houve um regressão pois a aprovação desse ticket não refleti o que temos em homologação, veja: 

<img width="1239" alt="screenshot 2019-02-11 17 15 37" src="https://user-images.githubusercontent.com/373745/52587188-a8f57300-2e20-11e9-97c5-32a776c66ec9.png">

**Comment by jamilatta** [comment]
@paratiuid 

Poderiam dar atenção para esse ticket!

**Comment by alexxxmendonca** [comment]
@jamilatta não entendi. Está correto dessa forma. Os ISSNs devem aparecer na mesma linha.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Acho que me confundir, vou fechar.
