### ISSUE TITLE
Home do periódico: encurtar nome do publicador quando ele for muito longo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1115]
Quando o nome do publicador for muito longo, utilizar reticências e exibir o nome completo via tooltip.

![image](https://user-images.githubusercontent.com/4059679/49238292-3e1ec900-f3e7-11e8-8ec0-bab54f531692.png)

**Comment by robertatakenaka** [comment]
@alexxxmendonca : Não acho que seja boa idéia "encurtar". Acho que o ideal é somente separar o publicador da área de atuação que está tudo na mesma linha.

**Comment by alexxxmendonca** [comment]
Porém há nomes muito longos (como esse do exemplo), que pegam 2 linhas.

Essa foi uma solicitação vinda do Abel.

**Comment by paratiuid** [comment]
@alexxxmendonca @robertatakenaka 
Vejam a imagem abaixo. Coloquei (...) quando o publicador é muito extenso e coloquei a área em uma nova linha.

Aguardo retorno

![ajuste - scielo - opac - 1115](https://user-images.githubusercontent.com/22373640/50784832-fe74b800-1295-11e9-8d42-5b3b74ae1eca.jpg)

**Comment by alexxxmendonca** [comment]
Aprovado! 👍

**Comment by alexxxmendonca** [comment]
@paratiuid ficou faltando a exibição do nome completo via tooltip.

**Comment by jamilatta** [comment]
@paratiuid 

Agora esta ok! 


<img width="1029" alt="screenshot 2019-02-15 16 46 35" src="https://user-images.githubusercontent.com/373745/52877490-47dfdf00-3141-11e9-8b58-e37d981b69c9.png">

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia validar em ambiente de homologação

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
