### ISSUE TITLE
Home do periódico: áreas aparecem sempre em inglês

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1116]
Não importa o idioma da interface em que se esteja, a área do periódico aparece sempre em inglês:

![image](https://user-images.githubusercontent.com/4059679/49238838-770b6d80-f3e8-11e8-9649-04e8619bfae7.png)

**Comment by alexxxmendonca** [comment]
Em conversa com Abel, ficou decidido REMOVER as áreas do WoS nessa região da home do periódico.

Manter somente áreas do conhecimento SciELO.

**Comment by patymori** [comment]
@alexxxmendonca, pode validar?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção!
