### ISSUE TITLE
Lidando com periódicos que mudaram de título

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1117]
Na base SciELO, temos muitos periódicos que mudaram de título ou que tinham outros títulos antes de entrarem no SciELO.

A nova interface precisa lidar com essas informações.

1) Na listagem de títulos descontinuados, inserir (quando aplicável), a informação de novo título:

![image](https://user-images.githubusercontent.com/4059679/49239441-ecc40900-f3e9-11e8-9841-b5162c721a50.png)

Mesmo comportamento de:

![image](https://user-images.githubusercontent.com/4059679/49239484-07967d80-f3ea-11e8-9107-5a8f956a6b27.png)

2) No cabeçalho do periódico, incluir a informação de novo título ou título anterior (avaliar cada caso) abaixo da informação de ISSN, com um link para o título novo/anterior:

![image](https://user-images.githubusercontent.com/4059679/49239680-7ecc1180-f3ea-11e8-8e90-a407d5f4d433.png)

- No caso do título descontinuado, incluir informação "Novo título: xxx [link para novo título]"
- No caso do título novo, incluir informação "Título anterior: xxx [link para título anterior {se houver}"

**Comment by RPostalli** [comment]
@alexxxmendonca teste

**Comment by paratiuid** [comment]
Oi @alexxxmendonca , 

conforme conversamos, eu não tenho os registros de periódicos que mudaram de título em meu banco de dados. Conversei com a @patymori , e ela identificou que existem mais ajustes de back end que devem ser feitos além do banco de dados. Dessa maneira, combinamos que devo apenas fazer o ajuste visual, e a equipe da Scielo faz os ajustes restantes.

Vou providenciar os ajuste e volto a informar aqui.

**Comment by alexxxmendonca** [comment]
@paratiuid de acordo.

**Comment by paratiuid** [comment]
Oi @alexxxmendonca 
seguem as telas com os ajustes. 
Aguardo seus comentários.

![screen shot 2019-01-24 at 10 21 04 am](https://user-images.githubusercontent.com/22373640/51677809-ec975280-1fc1-11e9-957a-f0a702c5a977.png)

![screen shot 2019-01-24 at 10 03 22 am](https://user-images.githubusercontent.com/22373640/51677822-f4ef8d80-1fc1-11e9-9ac8-984d20e00636.png)

**Comment by patymori** [comment]
@alexxxmendonca e @paratiuid,

Ainda não está desenvolvida do lado do backend, há ajustes a fazer.

**Comment by paratiuid** [comment]
@alexxxmendonca e @patymori 
vou mandar o pull request então.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca A versão com a correção esta no ambiente de homologação do OPAC,

Vc pode Validar?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca 
sobre o item 1) é possível fazer como no site atual, a gente vai fazer essas modificações que vc mediu e depois te avisa novamente

**Comment by alexxxmendonca** [comment]
@cesarbruschetta fechado!

@paratiuid pode ver os itens 2 e 3?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , nos ja fizemos as 3 modificações, vc mode verificar no site de homolog ex: https://homolog.opac.scielo.br/journal/iao/

**Comment by alexxxmendonca** [comment]
@cesarbruschetta os 3 itens estão ok, mas notei que as informações na parte inferior do grid de fascículos diferem do site atual.

Site novo:

![image](https://user-images.githubusercontent.com/4059679/52562544-fb656e00-2de5-11e9-9804-b956231fbdef.png)

Site atual:

![image](https://user-images.githubusercontent.com/4059679/52562565-0cae7a80-2de6-11e9-999a-f39e20fa91b8.png)

Penso que o texto "admitido na coleção **da SciELO**" não está correto e algumas vezes o motivo aparece em branco, outras vezes aparece "not-open access" mesmo estando na interface em Português.

O comportamento deve ser o mesmo do site atual.

Devo abrir um outro ticket para isso?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca Sim, acredito que é melhor tratar esse assunto num novo ticket

**Comment by alexxxmendonca** [comment]
Foi aberto um novo ticket para lidar com essa questão.

Vou fechar esse ticket que corrige as demais questões.
