### ISSUE TITLE
Apresentação de Subseção

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/opac#1123]
Quando há subseção, ela está aparecendo colada da seção.

Exemplo:

https://new.scielo.br/article/prc/2018.v31/12/en/

![image](https://user-images.githubusercontent.com/16937218/49595567-6797a180-f95f-11e8-9eb0-8ef011533406.png)

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , vc poderia validar no ambiente de homologação?

ex: [https://homolog.opac.scielo.br/article/prc/2018.v31/12/en/](https://homolog.opac.scielo.br/article/prc/2018.v31/12/en/)

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado.

@jenniferamato, poderia testar também?
