### ISSUE TITLE
Na mensagem de erro relatada no formulário de Error Report, incluir a URL da página com problemas

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1129]

**Comment by alexxxmendonca** [comment]
Título da página também, conforme diz no formulário:

_Obs.: Link e título da página são enviados automaticamente._

**Comment by patymori** [comment]
@alexxxmendonca, feita correção. Poderia verificar?

Obrigada

**Comment by alexxxmendonca** [comment]
Testei em produção e está funcionando!
