### ISSUE TITLE
Páginas about devem ter vínculos entre os idiomas

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1130]
Páginas about devem ter vínculos entre os idiomas

### Inplementação
A solução encontrada, foi que os `slug_name` das paginas do sobre deve ser iguais, nos 3 idiomas, assim é possível o vínculos das paginas
E caso a aplicação não encontre uma slug_name, no idioma atual da sessão o usuario sera redirecionado a listagem das paginas do sobre

### Atualização dos Dados 
Apos a atualização do ambiente sera necessário alterar os `slug_name` das paginas manualmente, e sempre manter esse padrão para as novas paginas que forem criadas na aplicação

**Comment by cesarbruschetta** [comment]
@robertatakenaka Ambiente de https://homolog.opac.scielo.br/about/ atualizado, envia o ticket para alguém validar antes de passar para a produção?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , Vc pode testar antes de passar para a produção? 
Esta no ambiente de https://homolog.opac.scielo.br/about/

**Comment by alexxxmendonca** [comment]
@cesarbruschetta o site não está lidando muito bem quando cai numa página 404 e quando utiliza-se o botão de "voltar" do navegador.

Simulação:

1) Acessar https://homolog.opac.scielo.br/about/ (esteja na interface em Portugues)
2) Clicar em  "SciELO – modelo de publicação eletrônica para países em desenvolvimento"
3) alterar para interface em Inglês
4) A página 404 aparece
5) tente usar o "voltar" do navegador e verás que a página não volta, é preciso clicar 2x.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , o que aconteceu e que a pagina que "SciELO – modelo de publicação eletrônica para países em desenvolvimento", não existe em outro idioma, e a pagina de 404 atual não permite uma navegação para o usuario, então quando vc clica 2 vezes no voltar na verdade vc esta voltando o idioma da interface.

A gente ja tinha aberto um outro ticket referente a pagina de 404 do opa ter esses problemas de navegação #1206

**Comment by alexxxmendonca** [comment]
@cesarbruschetta entendo.

Nesse caso, o que devo fazer então? Aprovar esse e aguardar a solução do outro ticket?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca da pagina de 404 acho melhor tratarmos no #1206, ja que ela pode afeta outros lugares da aplicação.

e sobre esse ticket, como ficou descrito na topo do ticket, vamos ter que criar as 3 paginas nos idiomas (pt_br, en, es) mas com a mesma "Slug Name",
