### ISSUE TITLE
Visualização de atualização de páginas - opac

### ISSUE THREAD

**Issue by julianafurlani** [scieloorg/opac#1145]
Ao fazer alterações em páginas no opac notamos que não está sendo possível visualizá-las. Ao clicar em "visualizar" somos direcionados para a seguinte mensagem:

![erro opac](https://user-images.githubusercontent.com/41448861/50656664-1c32dc00-0f7b-11e9-88ce-9f77ae23e5c1.PNG)

Segue o link de uma das páginas que está apresentando este erro: https://opac.scielo.br/admin/pages/details/?url=%2Fadmin%2Fpages%2F%3Fsearch%3Dfloram&id=6b9b6824f5ef4b6e80b57ecd116216f4)

**Comment by patymori** [comment]
@julianafurlani, feita correção. É necessário editar as páginas que deram problema para que o problema seja resolvido. Poderia validar?

Obrigada

**Comment by julianafurlani** [comment]
@patymori agora estou conseguindo visualizar as edições. Problema resolvido. Obrigada!
