### ISSUE TITLE
Site novo carregou problema com limitação da base para armazenar resumos

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1154]
Relação com ticket [537](https://github.com/scieloorg/Web/issues/537). (Ver exemplos neste ticket do site antigo)

No site novo: https://new.scielo.br/toc/rlpf/2000.v3n4/

![image](https://user-images.githubusercontent.com/6084959/50896223-920dcc00-13ef-11e9-8970-93ea62587460.png)

**Comment by robertatakenaka** [comment]
@RPostalli a limitação é na base isis e não no opac.
Este problema somente será resolvido (ainda este ano) com o XC novo que não dependerá de bases ISIS.

**Comment by robertatakenaka** [comment]
@RPostalli não exatamente. Será resolvido com um novo produto mesmo. Uma arquitetura totalmente nova. Até pode se chamar XC, mas não será o mesmo projeto. Por enquanto não precisa abrir nenhum ticket.
