### ISSUE TITLE
Criar site de controle de qualidade interno [opac] BR e SP

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1155]
Criar site de controle de qualidade interno BR e SP.

Hoje o desenho de publicação passa por duas interfaces uma de controle de qualidade interno e outra de homologação.

BR
http://homolog.xml.scielo.br/
http://homolog.scielo.br/

SP
http://homolog.xml.scielosp.org/
http://homolog.scielosp.org/

Segundo infra/TI a homologação foi criada apenas garantir que o site não esteja quebrado, o que não ocorre mais nas interfaces novas.

Por este motivo proponho para o novo desenho de publicação, apenas um site de controle de qualidade interno para cada coleção onde o teste seria realizado direto em produção. (Problemas graves verificados em produção podem fazer o uso do botão "Despublicar" até que a correção seja reenviada.

**Comment by patymori** [comment]
@RPostalli ,

Conforme falamos, será desenvolvido um visualizador da página do artigo, que possibilitará a visualização do conteúdo a ser publicado através do pacote XML com seus ativos digitais, antes mesmo de ser publicado no site.

**Comment by patymori** [comment]
@RPostalli, 

Estou encerrando este ticket no OPAC pois já existe um ticket específico sobre isso:

scieloorg/packtools/issues/176
