### ISSUE TITLE
Lista de Áreas Temáticas de Periódicos exibe áreas temáticas somente em Inglês

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1157]
relacionado #1116 

- Solicitante: @alexxxmendonca 
- Tipo: Defeito
- URL: https://opac.scielo.org/journals/#theme
- Descrição: Na “Lista Temática de Periódicos”, ao tentar mudar o idioma da página, o idioma das áreas temáticas sempre é exibido em inglês.

![screen shot 2019-01-10 at 09 18 49](https://user-images.githubusercontent.com/18053487/50965383-f2b50b80-14b8-11e9-979d-538fb61fa6a4.png)

![screen shot 2019-01-10 at 09 19 50](https://user-images.githubusercontent.com/18053487/50965401-fcd70a00-14b8-11e9-844a-7a0268cac26d.png)

Seguem as traduções esperadas para as áreas temáticas:

```json
{
    "Agricultural Sciences": {
        "en": "Agricultural Sciences",
        "es": "Ciencias Agrícolas",
        "pt": "Ciências Agrárias"
    },
    "Applied Social Sciences": {
        "en": "Applied Social Sciences",
        "es": "Ciencias Sociales Aplicadas",
        "pt": "Ciências Sociais Aplicadas"
    },
    "Biological Sciences": {
        "en": "Biological Sciences",
        "es": "Ciencias Biológicas",
        "pt": "Ciências Biológicas"
    },
    "Engineering": {
        "en": "Engineering",
        "es": "Ingeniería",
        "pt": "Engenharias"
    },
    "Exact and Earth Sciences": {
        "en": "Exact and Earth Sciences",
        "es": "Ciencias Exactas y de la Tierra",
        "pt": "Ciências Exatas e da Terra"
    },
    "Health Sciences": {
        "en": "Health Sciences",
        "es": "Ciencias de la Salud",
        "pt": "Ciências da Saúde"
    },
    "Human Sciences": {
        "en": "Human Sciences",
        "es": "Humanidades",
        "pt": "Ciências Humanas"
    },
    "Linguistics, Letters and Arts": {
        "en": "Linguistic, Literature and Arts",
        "es": "Linguística, Letras y Artes",
        "pt": "Lingüística, Letras e Artes"
    }
}
```

**Comment by patymori** [comment]
@alexxxmendonca, poderia validar no ambiente de homologação? Peço que ignore o item da listagem **TROPICAL MEDICINE**, que está sendo tratado em outro ticket.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
