### ISSUE TITLE
E-mail de Relatório de auditoria de mudanças | Links não funcionam

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1158]
Os links do e-mail automático do relatório de auditoria de mudanças não funcionam.

![image](https://user-images.githubusercontent.com/4059679/51034307-7d673a80-158d-11e9-8920-c3302427555e.png)

Ao clicar nos links aparece a seguinte mensagem:

![image](https://user-images.githubusercontent.com/4059679/51034449-f2d30b00-158d-11e9-9e46-4ab95b6b8f50.png)

**Comment by patymori** [comment]
@RPostalli,

Poderia revisar este ticket? Caso tenha algum exemplo de problema, poderia apontar?

Obrigada

**Comment by RPostalli** [comment]
@patymori basicamente o @alexxxmendonca já descreveu o que acontece bem. É isso:

Ao clicar em Ver Mais
![image](https://user-images.githubusercontent.com/6084959/52204746-238c2480-285c-11e9-8fb2-15b9886b2ad4.png)

Aparece a seguinte página:

![image](https://user-images.githubusercontent.com/6084959/52204805-4ddde200-285c-11e9-94c4-0f79ea427967.png)

Eu não sei o que esperar ao clicar em ver mais, pois nunca consegui acessar esta funcionalidade. Mas acredito que deveríamos ver a auditoria daquela página, tudo o que foi alterado/excluído/incluído.

**Comment by RPostalli** [comment]
O acesso é possível mas antes temos que estar logado no https://new.scielo.br/admin
Aberto novo ticket para corrigir este problema.

**Comment by RPostalli** [comment]
@alexxxmendonca por favor fechar este ticket.
