### ISSUE TITLE
Interface sobrepõem dados de nota de rodapé <fn-group> do tipo supported-by

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1164]
Interface sobrepõem dados de nota de rodapé <fn-group> do tipo supported-by

Exemplo: abcd v32n1: https://new.scielo.br/article/abcd/2019.v32n1/e1412/en/#

![image](https://user-images.githubusercontent.com/6084959/51191213-128a6c00-18cb-11e9-9545-a81748eefe54.png)

No XML: 

```
<fn-group>
				<fn fn-type="supported-by" id="fn01">
					<label>Fonte de financiamento:</label>
					<p> não há</p>
				</fn>
			</fn-group>
```

**Comment by patymori** [comment]
Bug está sendo corrigido em scieloorg/opac/issues/827. Estou encerrando este ticket.
