### ISSUE TITLE
Agregar DOI do artigo no feed RSS

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1174]
https://new.scielo.br/journal/mioc/feed/

Isso facilitará interoperabilidade com outros serviços que utilizam o RSS como fonte de dados.

**Comment by patymori** [comment]
@alexxxmendonca, essa tarefa é no backend do OPAC. Portanto, não cabe à Parati fazê-la.

**Comment by alexxxmendonca** [comment]
@patymori Ok

**Comment by jamilatta** [comment]
@alexxxmendonca , poderia verificar no ambiente de homologação?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação! 👍
