### ISSUE TITLE
Número atual não aparece no menu suspenso nas páginas informativas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1179]
Quando se está visualizando uma página informativa e o menu suspenso do periódico é acessado, o número atual não aparece:

![image](https://user-images.githubusercontent.com/4059679/52069444-df500a00-2565-11e9-82d7-7827dbb7e453.png)

O link funciona, mas aparecem dois traços ao invés do texto.

**Comment by jamilatta** [comment]
Item realizado no PR: #1229
