### ISSUE TITLE
Interface apresenta texto "pub" em data de publicação online

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/opac#1180]
Tanto no site velho quanto no site novo a informação de data de publicação online está sendo apresentada somente como "pub".

De acordo com ticket #903 (já resolvido), o texto apresentado deveria ser:

**Inglês:** Publication: April 26, 2017
**Português:** Publicação: 05 de Julho de 2017
**Espanhol:** Publicación: 05 de Julio de 2015

Seguem links em ambos os sites de um exemplo onde isto ocorre e seus respectivos prints:

**Site velho:** http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-36162018000500521&lng=en&nrm=iso&tlng=en
![image](https://user-images.githubusercontent.com/27728729/52069773-9187d180-2566-11e9-8c4a-a8d9b0b6c1aa.png)

**Site novo:** https://new.scielo.br/scielo.php?script=sci_arttext&pid=S0102-36162018000500521&lng=en&nrm=iso&tlng=en#articleSection3
![image](https://user-images.githubusercontent.com/27728729/52069800-9ba9d000-2566-11e9-9144-e3c76661818c.png)

**Comment by jamilatta** [comment]
@scieloorg/developers-commiters 

Acredito que isso seja no Packtools.

**Comment by RPostalli** [comment]
@jamilatta é opac mesmo, é apresentação de dado.

**Comment by RPostalli** [comment]
Era importante alguém validar o conteúdo dos nomes dos tipos de datas que eu coloquei no ticket  #903 é apenas uma sugestão. @alexxxmendonca poderia validar?

**Comment by alexxxmendonca** [comment]
@RPostalli estou de acordo sim.

**Comment by cesarbruschetta** [comment]
@scieloorg/scielo-brazil-developers @alexxxmendonca 

Me parece que esse problema ja foi corrigido no site segue alguns exemplos

- https://new.scielo.br/article/asas/2019.v41/e43871/
- https://new.scielo.br/article/ac/2019.v19n2/203-217/pt/
- https://new.scielo.br/scielo.php?script=sci_arttext&pid=S0102-36162018000500521&lng=en&nrm=iso&tlng=en#articleSection3

**Comment by RPostalli** [comment]
Qual o texto vocês estão adotando para as datas em <pub-date> ?

Seria Published?
![image](https://user-images.githubusercontent.com/6084959/55079510-14b33880-507b-11e9-87f1-76ba8d6ba827.png)

Ou Online Publication?
![image](https://user-images.githubusercontent.com/6084959/55079562-2e548000-507b-11e9-8909-d3f5df44a0f6.png)

@gustavo com as [novas datas do SPS 1.9](https://github.com/scieloorg/scielo_publishing_schema/issues/565), precisa preparar OPAC e definir quais serão os textos nos 3 idiomas para cada tipo de data.

**Comment by cesarbruschetta** [comment]
@RPostalli 

Montei um tabela com todos os labels e traduções relacionadas aos campos de data que a aplicação esta tratando atualmente, por favor, verifique se esses termos estao corretos e/ou se esta faltando algum campo para ser tratado e considerado tambem 


|CAMPO|PT_BR|EN|ES|
|---|---|---|---|---|
| epub      |     Publicação Online  | Online publication   |   Publicación en línea |
| epub-ppub    |     Publicação     | Publication        |   Publicación |
| pub-date    |     Publicado em    | Published on       |   Publicado en |
| < pub-date>@date-type="received" | Received | Recibido | Recebido  |  
| < pub-date>@date-type="accepted" | Aceito  | Accepted | Acepto    | 
| < pub-date>@date-type="rev-recd" | Revisado | Reviewed | Revisado   | 
| < pub-date>@date-type="corrected" | Corrected | Corregido | Corrigido  | 
| < pub-date>@date-type="pub" |  Publicado | Published | Publicado | 
| < pub-date>@date-type="preprint" | Preprint | Preprint | Preprint | 
| < pub-date>@date-type="retracted" | Retratado | Retracted | Retractado  | 
| < pub-date>@date-type="rev-requested" |   Solicitud de Revisión | Requested | Revision |

**Comment by RPostalli** [comment]
A tag das datas de histórico está incorreta não é pub-date é history:

- https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-history.html
- https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-date.html

<history> @date-type="received" | Received | Recibido | Recebido
<history> @date-type="accepted" | Aceito | Accepted | Acepto
<history> @date-type="rev-recd" | Revisado | Reviewed | Revisado
<history> @date-type="corrected" | Corrected | Corregido | Corrigido
<history> @date-type="pub" | Publicado | Published | Publicado
<history> @date-type="preprint" | Preprint | Preprint | Preprint
<history> @date-type="retracted" | Retratado | Retracted | Retractado
<history> @date-type="rev-requested" | Solicitud de Revisión | Requested | Revision

[Pubdate para 1.9](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-date.html)
<pub-date> @date-type="pub"
<pub-date> @date-type="collection"

Pubdate para 1.8.1 (VER PDF ANEXO)
[SciELO Publishing Schema_v draft 1.8.1-PT.pdf](https://github.com/scieloorg/opac/files/3049473/SciELO.Publishing.Schema_v.draft.1.8.1-PT.pdf)

<pub-date> @pub-type="epub"
<pub-date> @pub-type="collection"

Estas datas representam as mesmas informações em especificações diferentes.
<pub-date> @date-type="pub" = <pub-date> @pub-type="epub"

e

<pub-date> @date-type="collection" = <pub-date> @pub-type="collection"

Portanto devem ter o mesmo termo.

Sugestão:

pub = epub: Publicação em SciELO | Publicación en SciELO | Publication in SciELO
collection = Data do Fascículo | Fecha del número  | Date of issue

@alexxxmendonca, @robertatakenaka @gustavofonseca   o que acham?

Apenas informo que na interface estas datas deve ficar bem separadas. Datas de Histórico são diferentes de datas de publicação. Poderia agregado antes de datas de histórico no Layout do site um seção de "Datas de Publicação".

Hoje está assim:

![image](https://user-images.githubusercontent.com/6084959/55654287-5c4a6a80-57c7-11e9-9a4a-50f56fb8d5b7.png)

Poderia ficar:

![image](https://user-images.githubusercontent.com/6084959/55654410-b4816c80-57c7-11e9-902d-37cabcd35e84.png)

**Comment by cesarbruschetta** [comment]
Ficaria assim a tabela entao ?

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@date-type="pub"` | Publicação em SciELO | Publicación en SciELO | Publication in SciELO |
| `<pub-date>@date-type="collection"` | Data do Fascículo | Fecha del número | Date of issue |
| `<history>@date-type="received"` | Received | Recibido | Recebido  |  
| `<history>@date-type="accepted"` | Aceito  | Accepted | Acepto    | 
| `<history>@date-type="rev-recd"` | Revisado | Reviewed | Revisado   | 
| `<history>@date-type="corrected"` | Corrected | Corregido | Corrigido  | 
| `<history>@date-type="pub"` |  Publicado | Published | Publicado | 
| `<history>@date-type="preprint"` | Preprint | Preprint | Preprint | 
| `<history>@date-type="retracted"` | Retratado | Retracted | Retractado  | 
| `<history>@date-type="rev-requested"` |   Solicitud de Revisión | Requested | Revision |

**Comment by RPostalli** [comment]
Sim. Faltou apenas as datas de pub-date equivalentes que já estão sendo processadas para arquivos com specific-use="1.8" que eu mencionei no comentário anterior

Preciso de validação para os termos definidos de pub-date. @alexxxmendonca acha que está bom, o Abel aprovaria?

Cesar, tenha atenção na questão da legenda bibliográfica que também considera datas de pub-date.
Ela aparece  na primeira linha do âmbito [artigo](https://new.scielo.br/article/rlae/2019.v27/e3110/pt/).

![image](https://user-images.githubusercontent.com/6084959/55721269-47452580-59d9-11e9-9dfd-7f67fdba618a.png)

Recomendo que neste campo apareça apenas as datas usadas para citação (datas pub-date do tipo collection).

De qualquer forma todas as datas de publicação com seus termos definidos, devem ficar agrupadas ao final do documento.

Se necessário abrir outro ticket para esta questão me informe.

**Comment by alexxxmendonca** [comment]
@RPostalli eu não posso falar pelo Abel, mas me parece bom.

Vamos seguir dessa forma e alterar posteriormente caso necessário.

**Comment by alexxxmendonca** [comment]
Acho que a tabela precisa ser revisada.

"Solicitud de Revisión" está na coluna em PT, sendo que é ES. A tradução desse mesmo termo para EN está como "Requested". Não tinha que ser "Revisions Requested"? O mesmo vale para o PT ("Solicitação de Revisão").

Necessário uma revisão geral na tabela.

**Comment by RPostalli** [comment]
Obrigada Alex. Já foi revisado anteriormente. Cesar revisar sua tabela com termos descritos no ticket #903 

Inglês

accepted -Accepted: April 26, 2017
received - Received: April 26, 2017
rev-recd - Revised: April 26, 2017
corrected - Corrected: April 26, 2017
pub - Publication: April 26, 2017
preprint - Preprint: April 26, 2017
retracted - Retracted: April 26, 2017
rev-requested - Requested Revision: April 26, 2017

Português

accepted - Aceito: 05 de Julho de 2017
received - Recebido: 05 de Julho de 2017
rev-recd - Revisado: 05 de Julho de 2017
corrected - Corrigido: 05 de Julho de 2017
pub - Publicação: 05 de Julho de 2017
preprint - Preprint: 05 de Julho de 2017
retracted - Retratado: 05 de Julho de 2017
rev-requested - Solicitado Revisão: 05 de Julho de 2017

Espanhol

accepted - Aprobado: 05 de Julio de 2015
received - Recibido: 05 de Julio de 2015
rev-recd - Revisado: 05 de Julio de 2015
corrected - Corregido: 05 de Julio de 2015
pub - Publicación: 05 de Julio de 2015
preprint - Preprint: 05 de Julio de 2015
retracted - Retractado: 05 de Julio de 2015
rev-requested - Solicitud de Revisión: 05 de Julio de 2015

**Comment by cesarbruschetta** [comment]
@RPostalli A tabela atualizada, ficaria assim entao?

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@date-type="pub"` | Publicação em SciELO | Publication in SciELO | Publicación en SciELO |
| `<pub-date>@date-type="collection"` | Data do Fascículo | Date of issue | Fecha del número |
| `<pub-date>@date-type="epub"` | Publicação em SciELO | Publication in SciELO | Publicación en SciELO |
| `<history>@date-type="received"` | Recebido | Received | Recibido  |  
| `<history>@date-type="accepted"` | Aceito  | Accepted | Aprobado    | 
| `<history>@date-type="rev-recd"` | Revisado | Revised | Revisado   | 
| `<history>@date-type="corrected"` | Corrigido | Corrected |  Corregido | 
| `<history>@date-type="pub"` |  Publicação | Publication | Publicación | 
| `<history>@date-type="preprint"` | Preprint | Preprint | Preprint | 
| `<history>@date-type="retracted"` | Retratado | Retracted | Retractado  | 
| `<history>@date-type="rev-requested"` |   Solicitado Revisão | Requested | Solicitud de Revisión |

**Comment by cesarbruschetta** [comment]
@RPostalli , obrigado.. creio que compreendi 

Esses seriam os labels independente da  versão do SPS

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@date-type="collection"` | Data do Fascículo | Date of issue | Fecha del número |
| `<history>@date-type="received"` | Recebido | Received | Recibido  |  
| `<history>@date-type="accepted"` | Aceito  | Accepted | Aprobado    | 
| `<history>@date-type="rev-recd"` | Revisado | Revised | Revisado   | 
| `<history>@date-type="corrected"` | Corrigido | Corrected |  Corregido | 
| `<history>@date-type="pub"` |  Publicação | Publication | Publicación | 
| `<history>@date-type="preprint"` | Preprint | Preprint | Preprint | 
| `<history>@date-type="retracted"` | Retratado | Retracted | Retractado  | 
| `<history>@date-type="rev-requested"` |   Solicitado Revisão | Requested Revision | Solicitud de Revisión | 

Ja quando o atributo `data-type` for `pub` ou `epub` eles taram o mesmo label, intendo que o `<pub-date> @pub-type="epub"` so existira na versão SPS 1.8.1 e o `<pub-date> @pub-type="pub"` na versão 1.9

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@date-type="(pub\|epub)"` | Publicação em SciELO | Publication in SciELO | Publicación en SciELO |

**Comment by RPostalli** [comment]
@cesarbruschetta não. Vou ai te explicar.

**Comment by cesarbruschetta** [comment]
| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<history>@date-type="received"` | Recebido | Received | Recibido  |  
| `<history>@date-type="accepted"` | Aceito  | Accepted | Aprobado    | 
| `<history>@date-type="rev-recd"` | Revisado | Revised | Revisado   | 
| `<history>@date-type="corrected"` | Corrigido | Corrected |  Corregido | 
| `<history>@date-type="pub"` |  Publicação | Publication | Publicación | 
| `<history>@date-type="preprint"` | Preprint | Preprint | Preprint | 
| `<history>@date-type="retracted"` | Retratado | Retracted | Retractado  | 
| `<history>@date-type="rev-requested"` |   Solicitado Revisão | Requested Revision | Solicitud de Revisión | 


Versao SPS 1.9

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@date-type="pub"` | Publicação em SciELO | Publication in SciELO | Publicación en SciELO |
| `<pub-date>@date-type="collection"` | Data do Fascículo | Date of issue | Fecha del número |

Versao SPS 1.8.1

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@pub-type="epub"` | Publicação em SciELO | Publication in SciELO | Publicación en SciELO |
| `<pub-date>@pub-type="collection"` | Data do Fascículo | Date of issue | Fecha del número |

**Comment by RPostalli** [comment]
Agora sim, tudo OK. 👍🍄

**Comment by cesarbruschetta** [comment]
@RPostalli 

Seque abaixo o exemplo de como ficara no site, eu fiz 3 versões com variação de xmls, e adicionei o trecho do xml que eu utilizei..

------

* Exemplo I
```xml
<pub-date publication-format="electronic" date-type="pub">
   <day>01</day>
   <month>01</month>
   <year>2018</year>
</pub-date>
<pub-date publication-format="electronic" date-type="collection">
   <season>Jan-Feb</season>
   <year>2018</year>
</pub-date>
<history>
    <date date-type="received">
        <day>3</day>
        <month>5</month>
        <year>2013</year>
    </date>
    <date date-type="accepted">
        <day>17</day>
        <month>10</month>
        <year>2013</year>
    </date>
    <date date-type="rev-recd">
        <day>17</day>
        <month>10</month>
        <year>2013</year>
    </date>
    <date date-type="corrected">
        <day>17</day>
        <month>10</month>
        <year>2013</year>
    </date>
    <date date-type="pub">
        <day>17</day>
        <month>10</month>
        <year>2013</year>
    </date>
    <date date-type="preprint">
        <day>17</day>
        <month>10</month>
        <year>2013</year>
    </date>
    <date date-type="rev-requested">
        <day>17</day>
        <month>10</month>
        <year>2013</year>
    </date>
</history>
```
<img width="638" alt="Captura de Tela 2019-04-10 às 15 05 02" src="https://user-images.githubusercontent.com/1105583/55902731-8a9ec000-5ba2-11e9-9b1a-1913f1daf695.png">

-----

* Exemplo II
```xml
<pub-date pub-type="epub-ppub">
    <season>Jan-Feb</season>
    <year>2014</year>
</pub-date>
```
<img width="638" alt="Captura de Tela 2019-04-10 às 15 07 29" src="https://user-images.githubusercontent.com/1105583/55902732-8b375680-5ba2-11e9-9b4b-1560dd0eb043.png">

----

* Exemplo III
```xml
<pub-date pub-type="epub">
    <day>17</day>
    <month>04</month>
    <year>2014</year>
</pub-date>
```
<img width="638" alt="Captura de Tela 2019-04-10 às 15 08 44" src="https://user-images.githubusercontent.com/1105583/55902733-8b375680-5ba2-11e9-9ac8-7e398c6ade50.png">

**Comment by RPostalli** [comment]
@cesarbruschetta o termo usado para `<pub-date publication-format="electronic" date-type="pub">` e para <`pub-date pub-type="epub">` não é o que combinamos e que está descrito na sua tabela.

![image](https://user-images.githubusercontent.com/6084959/55958943-26cad480-5c40-11e9-83c1-6940242fb2ae.png)

Essas datas estão misturando idiomas tem PT_BR e ES:
![image](https://user-images.githubusercontent.com/6084959/55959282-def87d00-5c40-11e9-9dc3-4a8d8a3cc5a5.png)

Como tivemos a variação/correção destas datas a partir de 01/04/2019, é possível aplicar este novo layout de `<pub-date>` (Datas de Publicação) apenas para artigos que estão sendo processados com SPS 1.8 e SPS 1.9 e com ano 2019, (porque podemos reprocessar [reproc] pacotes antigos SPS 1.8 para correção) desde essa data e não considerar os artigos publicados para trás?

As correções em datas de histórico `<history>` devem ser aplicadas para toda a coleção.

**Comment by cesarbruschetta** [comment]
@RPostalli 

> Como tivemos a variação/correção destas datas a partir de 01/04/2019, é possível aplicar este novo layout de <pub-date> (Datas de Publicação) apenas para artigos que estão sendo processados com SPS 1.8 e SPS 1.9 e com ano 2019, (porque podemos reprocessar [reproc] pacotes antigos SPS 1.8 para correção) desde essa data e não considerar os artigos publicados para trás?

sobre esse treco, acredito que não, todos os item dos site OPAC, ficaram com essa divisão de `Historico` e `datas de publicação`

**Comment by RPostalli** [comment]
@cesarbruschetta então tem que levantar todos os tipos de datas de todas as versões SPS de XML inclusive o legado HTML/SGML. O trabalho é bem maior.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca / @RPostalli  , essa modificação esta no ambiente de homologação https://homolog.opac.scielo.br/, vcs podem validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta não há um tratamento de tradução por idioma. Está sempre em inglês, não importa a interface.

**Comment by cinthia-vieira** [comment]
@alexxxmendonca eu notei que em português está aparecendo no idioma correto, só em espanhol aparece em inglês os termos

print retirado do artigo do exemplo: 
![image](https://user-images.githubusercontent.com/27728729/57874680-84c27d00-77e7-11e9-8606-b94ce07b7aa5.png)

https://homolog.opac.scielo.br/article/rbort/2018.v53n5/521-526/pt/

cc @cesarbruschetta

**Comment by RPostalli** [comment]
@cesarbruschetta a legenda continua diferente do que combinamos

![image](https://user-images.githubusercontent.com/6084959/57875028-4a0d1480-77e8-11e9-9efe-acec63177a72.png)

**Comment by gustavofonseca** [comment]
> @cesarbruschetta não há um tratamento de tradução por idioma. Está sempre em inglês, não importa a interface.

Não há mesmo. Pense nessas datas como parte do artigo e não da interface de usuário do site.

**Comment by alexxxmendonca** [comment]
@gustavofonseca não são rótulos? 

Esse conteúdo está vindo do artigo?

Estou confuso.

**Comment by gustavofonseca** [comment]
> @gustavofonseca não são rótulos?
> 
Eles são rótulos para metadados que estão armazenados no XML do artigo e que devem ser apresentados na sua versão em HTML. O ponto é que eles são parte do artigo e não da interface do site.

> Esse conteúdo está vindo do artigo?
> 
Sim. Dos metadados do XML do artigo.

> Estou confuso.

Respira.. rs

**Comment by alexxxmendonca** [comment]
@gustavofonseca então se o artigo estiver em PT vão aparecer os rótulos em PT
Se o artigo estiver em EN vão aparecer os rótulos em EN.
Se o artigo estiver em ES vão aparecer os rótulos em ES.

E se o artigo for em qualquer outro idioma que não sejam esses 3? Os rótulos vão aparecer em EN, é isso? (foi isso que meus testes revelaram).

**Comment by gustavofonseca** [comment]
> @gustavofonseca então se o artigo estiver em PT vão aparecer os rótulos em PT
> Se o artigo estiver em EN vão aparecer os rótulos em EN.
> Se o artigo estiver em ES vão aparecer os rótulos em ES.
> 
> E se o artigo for em qualquer outro idioma que não sejam esses 3? Os rótulos vão aparecer em EN, é isso? (foi isso que meus testes revelaram).

Exato. Nós poderemos suportar outros idiomas que são comuns na Rede, como Afrikaans por exemplo.

**Comment by alexxxmendonca** [comment]
@gustavofonseca Ok, entendido.

Por mim ta aprovado então, mas acho que a @RPostalli e a @cinthia-vieira devem dar um aval mais preciso. Seria interessante tentar encontrar exemplos com múltiplas datas, o maior número possível delas.

**Comment by robertatakenaka** [comment]
@alexxxmendonca , no lugar de colocar "Publicação no SciELO", já que nem todos que usarem a aplicação seria SciELO (ex.: PePsic, RevEnf, ...) talvez colocar "publicação nesta coleção".

**Comment by alexxxmendonca** [comment]
@robertatakenaka sim, faz sentido.

**Comment by cesarbruschetta** [comment]
Os `labels` para o `<pub-date>` ficara igual a tabela abaixo 

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@date-type="pub"` | Publicação nessa coleção | Publication in this collection | Publicación en esta colección|

Versao SPS 1.8.1

| CAMPO | PT_BR | EN | ES |
|-|-|-|-|
| `<pub-date>@pub-type="epub"` | Publicação nessa coleção | Publication in this collection | Publicación en esta colección |

**Comment by RPostalli** [comment]
@cesarbruschetta Ficou ótimo. Concordo com os novos termos.

**Comment by cesarbruschetta** [comment]
@robertatakenaka @alexxxmendonca @robertatakenaka o ambiente de homologação ja foi atualizado com os novos termos , podem verificar

**Comment by RPostalli** [comment]
@cesarbruschetta testado, tudo OK!

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado, tudo ok!
