### ISSUE TITLE
Fórmula sendo renderizada incorretamente

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1184]
O documento https://new.scielo.br/article/sa/2019.v76n2/139-147/en/# está, por padrão, apresentando incorretamente a fórmula da seção "Physical pellet characteristics":

![screen shot 2019-02-04 at 16 44 26](https://user-images.githubusercontent.com/161335/52229639-89989c00-289c-11e9-9c93-f15d5746298d.png)

Ao clicar com botão direito, Math Settings -> Math Renderer -> SVG, a fórmula passa a ser apresentada na forma correta:

![screen shot 2019-02-04 at 16 44 41](https://user-images.githubusercontent.com/161335/52229761-d9776300-289c-11e9-8fbc-4b4a5aef5461.png)

Verificar como redefinir o renderizador padrão para SVG.

**Comment by robertatakenaka** [comment]
@alexxxmendonca pode ver com a parati?, pois me parece que é alguma classe de CSS que está apresentado fora do lugar.

**Comment by RPostalli** [comment]
@gustavofonseca esse ticket tem relação com esse? https://github.com/scieloorg/opac/issues/1161

**Comment by paratiuid** [comment]
@RPostalli pelo que analisamos aqui tem sim.

**Comment by RPostalli** [comment]
@paratiuid então vou replicar o ticket aqui e fecho o outro. Obrigada.
---------------------------
Equações em MathML, quando dentro de parágrafos (<disp-formula>) está desconfigurada

Artigo da tema v19n3: https://new.scielo.br/article/tema/2018.v19n3/391-403/en/

![image](https://user-images.githubusercontent.com/6084959/51046775-23c33800-15ae-11e9-832c-c43a978b20e5.png)

Deveria ser:  http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2179-84512018000300391&lng=en&nrm=iso&tlng=en
![image](https://user-images.githubusercontent.com/6084959/51046853-540ad680-15ae-11e9-92a1-c56580699f47.png)


No XML:

```
<inline-formula id="e1">
					<mml:math>
						<mml:mrow>
							<mml:mi>t</mml:mi>
							<mml:mo>=</mml:mo>
							<mml:mn>1,...</mml:mn>
							<mml:mi>n</mml:mi>
						</mml:mrow>
					</mml:math>
				</inline-formula>, stochastic processes, and <inline-formula id="e2">
					<mml:math>
						<mml:mrow>
							<mml:msup>
								<mml:mi>B</mml:mi>
								<mml:mi>j</mml:mi>
							</mml:msup>
							<mml:msub>
								<mml:mi>X</mml:mi>
								<mml:mi>t</mml:mi>
							</mml:msub>
							<mml:mo>=</mml:mo>
							<mml:msub>
								<mml:mi>X</mml:mi>
								<mml:mrow>
									<mml:mi>t</mml:mi>
									<mml:mo>−</mml:mo>
									<mml:mi>j</mml:mi>
								</mml:mrow>
							</mml:msub>
						</mml:mrow>
					</mml:math>
				</inline-formula>
```

e

```
<disp-formula id="e3">
					<mml:math>
						<mml:mrow>
							<mml:msub>
								<mml:mi>c</mml:mi>
								<mml:mrow>
									<mml:mi>X</mml:mi>
									<mml:mi>Y</mml:mi>
								</mml:mrow>
							</mml:msub>
							<mml:mrow>
								<mml:mo>(</mml:mo>
								<mml:mi>k</mml:mi>
								<mml:mo>)</mml:mo>
							</mml:mrow>
							<mml:mo>=</mml:mo>
							<mml:mrow>
								<mml:mo>{</mml:mo>
								<mml:mrow>
									<mml:mtable>
										<mml:mtr>
											<mml:mtd>
												<mml:mrow>
													<mml:mfrac>
														<mml:mn>1</mml:mn>
														<mml:mi>n</mml:mi>
													</mml:mfrac>
													<mml:mstyle displaystyle="true">
														<mml:munderover>
															<mml:mo>∑</mml:mo>
															<mml:mrow>
																<mml:mi>t</mml:mi>
																<mml:mo>=</mml:mo>
																<mml:mn>1</mml:mn>
															</mml:mrow>
															<mml:mrow>
																<mml:mi>n</mml:mi>
																<mml:mo>−</mml:mo>
																<mml:mi>k</mml:mi>
															</mml:mrow>
														</mml:munderover>
														<mml:mrow>
															<mml:mrow>
																<mml:mo>(</mml:mo>
																<mml:mrow>
																	<mml:msub>
																		<mml:mi>x</mml:mi>
																		<mml:mi>t</mml:mi>
																	</mml:msub>
																	<mml:mo>−</mml:mo>
																	<mml:mover accent="true">
																		<mml:mi>x</mml:mi>
																		<mml:mo>¯</mml:mo>
																	</mml:mover>
																</mml:mrow>
																<mml:mo>)</mml:mo>
															</mml:mrow>
														</mml:mrow>
													</mml:mstyle>
													<mml:mrow>
														<mml:mo>(</mml:mo>
														<mml:mrow>
															<mml:msub>
																<mml:mi>y</mml:mi>
																<mml:mrow>
																	<mml:mi>t</mml:mi>
																	<mml:mo>+</mml:mo>
																	<mml:mi>k</mml:mi>
																</mml:mrow>
															</mml:msub>
															<mml:mo>−</mml:mo>
															<mml:mover accent="true">
																<mml:mi>y</mml:mi>
																<mml:mo>¯</mml:mo>
															</mml:mover>
														</mml:mrow>
														<mml:mo>)</mml:mo>
													</mml:mrow>
													<mml:mo>,</mml:mo>
													<mml:mtable>
														<mml:mtr>
															<mml:mtd>
																<mml:mrow/>
															</mml:mtd>
															<mml:mtd>
																<mml:mrow>
																	<mml:mi>k</mml:mi>
																	<mml:mo>=</mml:mo>
																	<mml:mn>0,1,...,</mml:mn>
																	<mml:mi>n</mml:mi>
																	<mml:mo>−</mml:mo>
																	<mml:mn>1,</mml:mn>
																	<mml:mtable>
																		<mml:mtr>
																			<mml:mtd>
																				<mml:mrow/>
																			</mml:mtd>
																			<mml:mtd>
																				<mml:mrow/>
																			</mml:mtd>
																		</mml:mtr>
																	</mml:mtable>
																</mml:mrow>
															</mml:mtd>
														</mml:mtr>
													</mml:mtable>
												</mml:mrow>
											</mml:mtd>
										</mml:mtr>
										<mml:mtr>
											<mml:mtd>
												<mml:mrow>
													<mml:mfrac>
														<mml:mn>1</mml:mn>
														<mml:mi>n</mml:mi>
													</mml:mfrac>
													<mml:mstyle displaystyle="true">
														<mml:munderover>
															<mml:mo>∑</mml:mo>
															<mml:mrow>
																<mml:mi>t</mml:mi>
																<mml:mo>=</mml:mo>
																<mml:mn>1</mml:mn>
																<mml:mo>−</mml:mo>
																<mml:mi>k</mml:mi>
															</mml:mrow>
															<mml:mi>n</mml:mi>
														</mml:munderover>
														<mml:mrow>
															<mml:mrow>
																<mml:mo>(</mml:mo>
																<mml:mrow>
																	<mml:msub>
																		<mml:mi>x</mml:mi>
																		<mml:mi>t</mml:mi>
																	</mml:msub>
																	<mml:mo>−</mml:mo>
																	<mml:mover accent="true">
																		<mml:mi>x</mml:mi>
																		<mml:mo>¯</mml:mo>
																	</mml:mover>
																</mml:mrow>
																<mml:mo>)</mml:mo>
															</mml:mrow>
														</mml:mrow>
													</mml:mstyle>
													<mml:mrow>
														<mml:mo>(</mml:mo>
														<mml:mrow>
															<mml:msub>
																<mml:mi>y</mml:mi>
																<mml:mrow>
																	<mml:mi>t</mml:mi>
																	<mml:mo>+</mml:mo>
																	<mml:mi>k</mml:mi>
																</mml:mrow>
															</mml:msub>
															<mml:mo>−</mml:mo>
															<mml:mover accent="true">
																<mml:mi>y</mml:mi>
																<mml:mo>¯</mml:mo>
															</mml:mover>
														</mml:mrow>
														<mml:mo>)</mml:mo>
													</mml:mrow>
													<mml:mo>,</mml:mo>
													<mml:mtable>
														<mml:mtr>
															<mml:mtd>
																<mml:mrow/>
															</mml:mtd>
															<mml:mtd>
																<mml:mrow>
																	<mml:mi>k</mml:mi>
																	<mml:mo>=</mml:mo>
																	<mml:mo>−</mml:mo>
																	<mml:mn>1,</mml:mn>
																	<mml:mo>−</mml:mo>
																	<mml:mn>2,...,</mml:mn>
																	<mml:mrow>
																		<mml:mo>(</mml:mo>
																		<mml:mrow>
																			<mml:mi>n</mml:mi>
																			<mml:mo>−</mml:mo>
																			<mml:mn>1</mml:mn>
																		</mml:mrow>
																		<mml:mo>)</mml:mo>
																	</mml:mrow>
																	<mml:mo>,</mml:mo>
																</mml:mrow>
															</mml:mtd>
														</mml:mtr>
													</mml:mtable>
												</mml:mrow>
											</mml:mtd>
										</mml:mtr>
									</mml:mtable>
								</mml:mrow>
							</mml:mrow>
						</mml:mrow>
					</mml:math>
					<label>(2.1)</label>
				</disp-formula>

```

**Comment by gustavofonseca** [comment]
A modificação feita pelo PR #1198 não resolve o problema. Veja a imagem abaixo:

![screen shot 2019-02-19 at 13 43 55](https://user-images.githubusercontent.com/161335/53031901-867cde80-344c-11e9-9795-1cce8dcd0329.png)

Na segunda equação é possível perceber o "fecha parênteses" sobreposto na equação.

**Comment by joffilyfe** [comment]
@RPostalli uma proposta de solução está disponível no ambiente de homologação. Por gentileza você poderia verificar e dar o seu parecer sobre o resultado?

[[1] - https://homolog.opac.scielo.br/article/sa/2019.v76n2/139-147/en/#](https://homolog.opac.scielo.br/article/sa/2019.v76n2/139-147/en/#) [intranet SciELO]

**Comment by cinthia-vieira** [comment]
Alguns comentários:

- Creio que as equações estão sendo renderizadas em fonte muito grande. Não daria pra deixá-las menores, em um tamanho de fonte mais aproximado ao restante do texto?

- Algumas equações em parágrafo estão centralizadas, enquanto outras estão alinhadas à direita. Existe algum parâmetro para decidir o alinhamento das equações? Seria interessante manter todas as equações em uma formatação padrão.

- As equações estão sendo renderizadas em SVG? Seria possível renderizá-las em texto, como no site antigo?

**Comment by gustavofonseca** [comment]
>     * As equações estão sendo renderizadas em SVG? Seria possível renderizá-las em texto, como no site antigo?

Sim, nós decidimos que a renderização padrão seria em SVG para garantir a maior qualidade possível independentemente do navegador, tamanho de tela, zoom de tela ou estilo (HTML+CSS) do site.

**Comment by joffilyfe** [comment]
@cinthia-vieira, @alexxxmendonca e @RPostalli nós atualizamos o ambiente de homologação. Por gentileza vocês poderiam dar validar o resultado da modificação em (https://homolog.opac.scielo.br/article/sa/2019.v76n2/139-147/en/#) e em (https://homolog.opac.scielo.br/article/neco/2018.v28n2/385-416/pt)?

**Comment by alexxxmendonca** [comment]
A mim me parece ok, mas aguardo os comentários da equipe de produção, que tem um olhar mais treinado para esse tipo de coisa.

**Comment by joffilyfe** [comment]
Olá @RPostalli, @cinthia-vieira, vocês poderiam dar um parecer sobre a modificação?

**Comment by cinthia-vieira** [comment]
@joffilyfe as modificações estão ok, o tamanho da fonte está bom e legível. Entretanto, num dos artigos, a equação **(1)** está alinhada à direita. Dei uma olhada no XML mas nada pareceu estar errado. Poderias verificar, por gentileza? O artigo é o que segue: 

https://homolog.opac.scielo.br/article/neco/2018.v28n2/385-416/pt

**Comment by joffilyfe** [comment]
Obrigado pela resposta rápida e pelo feedback preciso @cinthia-vieira, a partir destes nós realizamos modificações. Por gentileza você poderia valida-las no ambiente de homologação?

**Comment by joffilyfe** [comment]
Obrigado pela resposta rápida e pelo feedback preciso @cinthia-vieira, a partir destes nós realizamos modificações. Por gentileza você poderia valida-las no ambiente de homologação?

**Comment by cinthia-vieira** [comment]
@joffilyfe o alinhamento está ok!

tudo certo agora :)

**Comment by joffilyfe** [comment]
@cinthia-vieira muito agradecido (:
