### ISSUE TITLE
Alterar termo "citações" para "referências"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1186]
Na página inicial da Coleção, alterar o termo "citações" para "referências":

![image](https://user-images.githubusercontent.com/4059679/52269346-f35c8880-2924-11e9-81fa-63e447af9c4c.png)

referências
references
referencias

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , vc poderia validar essas alterações no [https://homolog.opac.scielo.br/](https://homolog.opac.scielo.br)

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em homologação.

**Comment by patymori** [comment]
Disponível em produção
