### ISSUE TITLE
Trocar LETTERS para LITERATURE em Areas temáticas

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1187]
<img width="485" alt="captura de tela 2019-02-05 as 13 43 37" src="https://user-images.githubusercontent.com/505143/52284809-47c72e80-294c-11e9-99b8-7cde7cde6216.png">

**Comment by alexxxmendonca** [comment]
Problema corrigido:

![image](https://user-images.githubusercontent.com/4059679/123147897-f98c2a80-d435-11eb-8614-9bfb374fa5ac.png)
