### ISSUE TITLE
Corrigir erro de digitação na busca por periódicos na home

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/opac#1204]
Na home, na caixa de busca por periódico, ao fazer uma busca que não retorna resultados, na mensagem aparece escrito "temo" ao invés de "termo":

![sem titulo](https://user-images.githubusercontent.com/12699183/52784063-05cc7580-303b-11e9-9664-3cec9cab25e9.png)

**Comment by alexxxmendonca** [comment]
Corrigido em produção.
