### ISSUE TITLE
Na home do periódico apresentar somente as Áreas temáticas, não as categorias do WoS

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1209]
<img width="535" alt="captura de tela 2019-02-15 as 14 59 14" src="https://user-images.githubusercontent.com/505143/52876673-0bab7f00-313f-11e9-90df-128f9b0dad5d.png">

Manter apenas as áreas temáticas  (study_areas ou subject_areas)
Remover as categorias WoS (subject_categories)

**Comment by joffilyfe** [comment]
O pull request #1211 resolve.
