### ISSUE TITLE
Exibir área "Multidisciplinar" para periódicos com 3 ou mais áreas do conhecimento

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1216]
Quando o periódico possuir 3 ou mais áreas do conhecimento, deve-se exibir "Multidisciplinar".

É o caso da AABC:

![image](https://user-images.githubusercontent.com/4059679/53041612-2e050b80-3463-11e9-9141-23c744bc70c7.png)

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia validar em homologação: https://homolog.opac.scielo.br

**Comment by alexxxmendonca** [comment]
@jamilatta testado e aprovado.

Dúvida: essa regra da Multidisciplinar, será que deveria ser aplicado aqui nessa lista também?

![image](https://user-images.githubusercontent.com/4059679/54555219-05563000-4995-11e9-809b-3f08b0ee8bcd.png)

**Comment by jamilatta** [comment]
@alexxxmendonca 

Penso que a lista é justamente para que o usuário possa olhar para a Áreas e encontre o periódico, se adicionarmos um temos que não seja um "classificador".... penso que a lista deixa de fazer sentido.

**Comment by jamilatta** [comment]
Por hora vou atualizar o ambiente de produção.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Vou fechar esse ticket, caso decidimos adicionar a categoria "Multidisciplinar" abrimos outro ticket. 🚀

**Comment by alexxxmendonca** [comment]
Ok!
