### ISSUE TITLE
Adicionar o conteúdo dinâmico na lista de logos dos financiadores

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#123]
### Problema: 

Atualmente em todos os templates do site os financiadores são uma lista fixa. 

### Objetivo: 

Garantir que os financiadores da coleção sejam os itens cadastrados no admin do OPAC.

**Comment by jfunez** [comment]
resolvido em dd5d584cbb8efb6d047ecbf7013699d0f1e3222e
