### ISSUE TITLE
Adicionar as notícias no Site

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#124]
### Problema: 

No mockup do site existe uma area que deve exibir as notícias do site, ver: 
![collection](https://cloud.githubusercontent.com/assets/373745/14218916/95342c5c-f82d-11e5-947c-9a5a62bfe443.png)

### Objetivo: 

Definir de onde virá o conteúdo das notícias e se já foi definido detalhar nesse ticket.

**Comment by jamilatta** [comment]
Ler o documento: https://docs.google.com/document/d/189FR5uwgyUFBlFxLGN7p8kfpTOr4GboCH6vCWuqozM8/edit#heading=h.jni8qp7n1lyr

**Comment by jfunez** [comment]
@jamilatta já fiz a listagem dinâmica com dados obtidos pelo feed nos 3 idiomas. amanhã (hoje) mando PR mas gostaria de discutir alguns pontos. Ou seja ainda temos ajustes pendentes.

#### screenshots do resultado parcial (localmente)

home do opac:
![screen shot 2016-05-21 at 02 22 13](https://cloud.githubusercontent.com/assets/805749/15446554/f6bb187a-1efa-11e6-83c3-b80786af5789.png)

home do blog (em pt):
![screen shot 2016-05-21 at 02 22 57](https://cloud.githubusercontent.com/assets/805749/15446557/0324b986-1efb-11e6-9f31-9e96691c7d74.png)
