### ISSUE TITLE
[BUG] Corrigir publicação de Retratação

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1243]
Problema com o aparecimento da caixinha amarela de retratação, a interface nova está suprimindo este dado.

NEW.BR
https://new.scielo.br/scielo.php?script=sci_arttext&pid=S2359-39972016000200186&lng=en&nrm=iso&tlng=pt

![image](https://user-images.githubusercontent.com/6084959/54684660-ace97480-4af3-11e9-9703-69082578ca2c.png)

BR ANTIGO
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2359-39972016000200186&lng=en&nrm=iso&tlng=pt

![image](https://user-images.githubusercontent.com/6084959/54684691-bd99ea80-4af3-11e9-8cc7-b7baa56ea803.png)

**Comment by alexxxmendonca** [comment]
Pessoal, por favor avaliem e se for necessário envolver a Parati para o design, me acionem.

**Comment by alexxxmendonca** [comment]
@RPostalli me parece que este problema foi solucionado. Confere?

Podemos fechar este ticket?

**Comment by RPostalli** [comment]
@alexxxmendonca Confere problema foi corrigido. 
OBS: O ideal é que a caixa exista no artigo também, já falamos sobre isso mas acho que nunca foi aberto ticket :(

**Comment by alexxxmendonca** [comment]
@RPostalli eu acho que tem um ticket aberto sobre isso.

Como a motivação original deste ticket foi resolvida, podemos tratar dessa outra questão no outro ticket, se houver, ou criar um novo.

Por este motivo, estou fechando-o.
