### ISSUE TITLE
Link para o SciELO.org está direcionando para uma URL inexistente

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1245]
Com o novo SciELO.org, as URLs antigas não respondem mais. Ex: http://www.scielo.org/php/index.php.

É necessário corrigir todos os links que redirecionam para o SciELO.org, para as páginas correspondentes.

**Comment by gustavofonseca** [comment]
@RPostalli, poderia colocar aqui um mapeamento de URLs que você espera que sejam tratadas pelo novo site? O email que enviou no final da tarde de ontem não deixou claro qual URL deve ser redirecionada para qual destino.

**Comment by gustavofonseca** [comment]
Fiz um comentário aqui que não competia a este projeto e removi logo em seguida.

**Comment by alexxxmendonca** [comment]
esse ticket não deveria estar no repositório do scielo.org?

**Comment by patymori** [comment]
@gustavofonseca e @alexxxmendonca,

A versão nova do site está disponível no ambiente de homologação, caso queiram verificar.

**Comment by alexxxmendonca** [comment]
Verifiquei e está ok! ;)

**Comment by patymori** [comment]
Disponível em produção.
