### ISSUE TITLE
Admin: filtro pelo campo Language nas model views: File e Images 

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#125]
#### Problema:

Atualmente o usuário não pode filtrar pelo campo ``language`` nas listagens de **Files** e **Images**

#### Objetivo:
Adicionar o filtro (custom filter) para permitir a filtragem pelo campo: Languages.

#### Obs:
O campo ``languages`` é um campo custom no modelos, to tipo [ChoiceType](https://sqlalchemy-utils.readthedocs.org/en/latest/data_types.html#module-sqlalchemy_utils.types.choice), então temos que investigar como construir o filtro nas model view.

**Comment by jfunez** [comment]
@swarzesherz para comenzar a trabajar en este issue, es necesario ajustar la base de datos SQL (sqlite), para esto puede utilizar el comando: ``python manager.py reset_dbsql --force``
que remueve las tablas y los datos y creará las nuevas tablas (``Image`` e ``File``) además de la ya conocida ``User``. 
Como el usuario también es removido, debes crearlo nuevamente con:
``python manager.py create_superuser``

Los archivo que son subidos por las nuevas views del admin, deben quedar alojados en ``webapp/media/files/`` o ``webapp/media/images/`` dependiendo del tipo de archivos.
Por último es necesario instalar 2 dependencias que fueron agregadas al requirements: **SQLAlchemy-Utils** y **Pillow**, 
``pip install -r requirements.txt``

Y si trabajas en Ubuntu, tal vez necesites ajustar algunas cosas en tu pc para que Pillow tenga soporte para diferentes formatos de imagenes (PNG, JPG, JPEG, etc), hay varias respuestas en StackOverflow para resolver esto, pero basicamente necesitas instalar algunas bibliotecas de desarrollo, y crear unos links simbólicos para algunos .so, finalmente reinstalar pillow. 

Cualquier consulta estamos a las ordenes!

**Comment by swarzesherz** [comment]
@jfunez de acuerdo revisare la tarea :thumbsup:

**Comment by jfunez** [comment]
resolvido em #172
