### ISSUE TITLE
Menu flutuante truncado

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1254]
Em artigos antigos, onde o texto completo não está disponível, somente o PDF, o menu flutuante aparece truncado com o rodapé.

Exemplo: https://new.scielo.br/article/mioc/1909.v1n1/33-43/pt/#

Isso precisa ser tratado.

**Comment by paratiuid** [comment]
@alexxxmendonca 
Faz sentido ter o menu flutuante quando não houver o artigo?

**Comment by alexxxmendonca** [comment]
@paratiuid faz, pois há botões que aplicam-se de qualquer forma, como: métricas, versões e traduções, como citar este artigo e artigos relacionados.

**Comment by joffilyfe** [comment]
@alexxxmendonca por gentileza você pode conferir se esta entrega satisfaz os critérios de aceitação? A modificação pode ser conferida no ambiente de homologação.

**Comment by alexxxmendonca** [comment]
@joffilyfe atende sim.

**Comment by joffilyfe** [comment]
Muito obrigado @alexxxmendonca, em breve será incorporado em produção.
