### ISSUE TITLE
Botões do menu suspenso com cursor incorreto

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1255]
Os botões de baixar os PDFs e métricas estão com o cursor padrão do mouse, ou seja, a "seta", ao invés de mostrar o cursor estilo "mãozinha".

Exemplo: https://drive.google.com/file/d/1EzZEQ2oTrSka6Cdw0GvoOsg_9DRGJtM8/view

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , essa modificação esta no ambiente de homologação https://homolog.opac.scielo.br/, vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em https://homolog.opac.scielo.br/
