### ISSUE TITLE
Adicionar um visualizador de PDF para mobile.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1257]
Atualmente a solução de visualização de PDFs no site está como responsabilidade do cliente. 

Dessa maneira, não temos um único padrão de exibição, para o mobile isso é um problema, pois, quase todos os browser mobile não tem clientes para isso, portanto, é necessário a instalação de um pacote js que tome a responsabilidade por renderizar este tipo de arquivo na tela do desktop e mobile. 

Uma opção é a instalação e configuração do [pdf.js](https://mozilla.github.io/pdf.js/ ) (Mozilla), essa solução também atende aos requisitos do mobile.

**Comment by paratiuid** [comment]
pessoal, 
o @gustavofonseca solicitou um parecer na nossa visão de designer sobre como deve ser o comportamento do botão PDF no artigo. Segue o texto:

Justificativa do uso de PDF no mobile.

Segundo Jakob Nielsen, 
os arquivos em formato PDF servem apenas para impressão, não sendo ideais para leitura em tela.

Vejam alguns trechos importantes dos artigos citado:

"Forçar os usuários a procurar arquivos PDF torna a usabilidade aproximadamente 300% pior em comparação com as páginas HTML. Use apenas PDF para documentos que os usuários possam imprimir."

"O PDF é ótimo para distribuir documentos que precisam ser impressos. Mas isso é tudo para que é bom. Não importa o quão tentador possa ser, você nunca deve usar PDF para conteúdo que espera que os usuários leiam on-line. Forçar os usuários a procurar documentos em PDF torna a usabilidade do seu site cerca de 300% pior em relação às páginas HTML."

"... muitas vezes vêem os usuários se perdendo em PDF porque o visualizador orientado para impressão dá a eles apenas um pequeno olho mágico em um layout grande e complicado e eles não podem riscá-lo da maneira simples e linear à qual estão acostumados na Web. Em vez disso, os arquivos PDF geralmente usam layouts gráficos elaborados e dividem o conteúdo em unidades separadas para cada folha de impressão. Embora isso seja altamente apropriado para documentos impressos, causa graves problemas de usabilidade on-line."

"Você deve usar PDF apenas para documentos que os usuários precisam baixar e imprimir. Quais documentos se enquadram nessa categoria? Qualquer coisa com cinco páginas ou mais é um bom candidato, já que os usuários não querem ler muito texto na tela."

"Como o PDF não é o formato de página da Web padrão, ele coloca os usuários em uma interface de usuário não padrão. Desviar-se da norma prejudica a usabilidade porque, por exemplo, a rolagem funciona de maneira diferente, assim como certos comandos, como o de tornar o texto maior (ou menor). Além disso, depois de terminar com um documento PDF, os usuários às vezes fecham a janela em vez de clicar no botão Voltar, perdendo assim seu histórico de navegação."

"Normalmente, arquivos PDF atormentam usuários em sites e intranets. Publicar um folheto de vendas, um relatório anual dos acionistas ou o manual de RH on-line como um único arquivo PDF irregular é uma receita certa para problemas de usabilidade. É muito melhor converter o conteúdo em um espaço de informações navegáveis e reescrevê-lo de acordo com as diretrizes para escrever para a Web."

Fonte:
https://www.nngroup.com/articles/avoid-pdf-for-on-screen-reading/
https://www.nngroup.com/articles/making-hated-design-elements-work/


Os trechos acima foram retirados de artigos referentes a telas de computador. Acredito que ao transferirmos as impressões para o mobile, as impressões com relação a manipulação de conteúdo em PDF sejam ainda piores.

Tendo em vista esses artigos de um dos magos da usabilidade, Jakob Nielsen, compreendo que ao oferecer uma opção intitulada "PDF" em um sistema, esta, deve conter:
- tamanho do arquivo em bytes
- tamanho do arquivo em páginas
- informação clara de que se trata de um arquivo em formato (tamanho do papel) e se destina para impressão.

Entendo também que, após ter acesso a uma interface amigável, de fácil leitura, otimizada para o tamanho de tela em questão (interface responsiva), ao acessar a opção PDF de um artigo, entendo que os objetivos do usuário sejam um dos citados a seguir:
- imprimir
- guardar
- compartilhar

Penso que a manipulação de arquivos deva se dar a nível de sistema operacional.
Alguém que utiliza o sistema iOS está habituado a manipular arquivos em suas interfaces. O mesmo ocorre para o usuário assíduo de Android.

Inserir uma interface intermediária de manipulação de PDF em um dispositivo mobile, a meu ver, apenas acrescenta esforço de aprendizagem, piorando a usabilidade.

Quanto menos interação com conteúdos não adaptados (responsivos), melhor.

Em outro momento, em conversa com o @gustavofonseca , foi dito que a opção de incluir essa interface de exibição do PDF na página era para poder contar os acessos ao documento PDF. Caso seja esse o problema, penso que podemos elaborar algum script dentro do analytics, junto com google tag manager, que obtenha os dados necessários de maneira transparente ao usuário. Mantendo a contagem desejada de maneira não invasiva.

**Comment by gustavofonseca** [comment]
@paratiuid, grato pela informação!

@alexxxmendonca, dados os pontos apresentados pela @paratiuid estou inclinado a remover a interface web para leitura do PDF em favor de um download direto. Está de acordo?

**Comment by alexxxmendonca** [comment]
@gustavofonseca estou de acordo.

**Comment by cesarbruschetta** [comment]
Devido a nova abordagem proposta, de que agora ao solicitar a visualização do PDF o site entregara o PDF diretamente e ficara a cargo do browser do cliente fazer a renderização do pdf assim proporcionando uma melhor experiencia ao usuario, essa issue sera fechada.
