### ISSUE TITLE
Alterar modo de apresentação dos links de acesso ao documento

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1263]
Alterar modo de apresentação dos links de acesso ao documento de modo que a referência passe a ser o tipo de documento e não o idioma:

![image](https://user-images.githubusercontent.com/4059679/55476301-9dd2ee00-55ec-11e9-80e5-10557171087f.png)

Exemplo:

**Resumo:** Português | Inglês | Espanhol **Texto:** Português | Inglês | Espanhol **PDF:** Português | Inglês | Espanhol **ePDF:** Português | Inglês | Espanhol

Lembrando que o Resumo deve-se manter o mesmo comportamento atual, ou seja, colapsar e expandir na mesma página.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , essa modificação esta no ambiente de homologação https://homolog.opac.scielo.br/, vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em https://homolog.opac.scielo.br/
