### ISSUE TITLE
Ícone e link para RSS dos press releases dos periódicos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1264]
Incluir um ícone e link para feed RSS dos press releases dos periódicos, junto ao feed que aparece na homepage do periódico:

![image](https://user-images.githubusercontent.com/4059679/55476646-85af9e80-55ed-11e9-8782-bc82e29f9d33.png)

O link é sempre a URL abaixo:

https://pressreleases.scielo.org/blog/category/press-releases/XX/feed/

Onde "XX" deve ser alterado pelo acrônimo do periódico no SciELO.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , o ambiente de homologação ja esta atualizado com esse ticket, vc pode validar? https://homolog.opac.scielo.br/journal/csc/

**Comment by alexxxmendonca** [comment]
@paratiuid a questão dos 3 idiomas não está sendo tratada.

Os feeds possuem URLs distintas para os 3 idiomas.

https://pressreleases.scielo.org/blog/category/press-releases/XX/feed/
https://pressreleases.scielo.org/en/blog/category/press-releases/XX/feed/
https://pressreleases.scielo.org/es/blog/category/press-releases/XX/feed/

**Comment by paratiuid** [comment]
@alexxxmendonca 
Ok, vou verificar.

**Comment by joffilyfe** [comment]
@alexxxmendonca por gentileza você pode conferir se esta entrega satisfaz os critérios de aceitação? A modificação pode ser conferida no ambiente de homologação.

**Comment by alexxxmendonca** [comment]
@joffilyfe a estrega satisfaz sim.

**Comment by joffilyfe** [comment]
Muito obrigado @alexxxmendonca, em breve será incorporado em produção.
