### ISSUE TITLE
Arquivo para impressão não renderiza corretamente

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1266]
Em new.scielo.br tentei visualizar o texto para impressão, clicando com o botão direito do mouse e clicando em imprimir.

![image](https://user-images.githubusercontent.com/6084959/55561171-15298000-56c8-11e9-8c78-e7045589fa71.png)

O conteúdo do texto para impressão fica todo desconfigurado.

![image](https://user-images.githubusercontent.com/6084959/55561237-2ffbf480-56c8-11e9-8c87-ffe740bf6cee.png)

![image](https://user-images.githubusercontent.com/6084959/55561261-3b4f2000-56c8-11e9-903a-57ac65cbaa03.png)

![image](https://user-images.githubusercontent.com/6084959/55561314-51f57700-56c8-11e9-926d-df64960a3f13.png)

![image](https://user-images.githubusercontent.com/6084959/55561381-6c2f5500-56c8-11e9-994a-23846ec3dfba.png)

![image](https://user-images.githubusercontent.com/6084959/55561398-75202680-56c8-11e9-9810-a088c8d8d70c.png)

Teste foi realizado no artigo disponível em: https://new.scielo.br/article/jvatitd/2019.v25/e147418/en/

PDF gerado anexo:
[SCIELO~1.PDF](https://github.com/scieloorg/opac/files/3043788/SCIELO.1.PDF)

**Comment by cesarbruschetta** [comment]
@RPostalli @alexxxmendonca , o ambiente de homologação ja esta atualizado com essa correção, vcs podem verificar? https://homolog.opac.scielo.br/article/jvatitd/2019.v25/e147418/en/

**Comment by alexxxmendonca** [comment]
@paratiuid O retângulo do lado esquerdo ainda está aparecendo:

![image](https://user-images.githubusercontent.com/4059679/58260179-5e9f5e80-7d4c-11e9-8c69-67836d99dafc.png)

Poderiam verificar?

**Comment by RPostalli** [comment]
No modo impressão as figuras não vão mesmo aparecer no PDF gerado?

PDF gerado para impressão
![image](https://user-images.githubusercontent.com/6084959/58260285-90182a00-7d4c-11e9-8569-3e6e20d1384b.png)

Artigo no site
![image](https://user-images.githubusercontent.com/6084959/58260333-a1f9cd00-7d4c-11e9-8001-872a151907a2.png)


Recomendo também que seja gerado os dados de fascículo na impressão (volume/número) ao qual pertence o artigo. São dados úteis para citação.

**Comment by paratiuid** [comment]
@alexxxmendonca 

Ok. Vou verificar.

**Comment by paratiuid** [comment]
@alexxxmendonca 
encontrei a causa do problema.

segue o print:

![Screen Shot 2019-05-23 at 3 10 35 PM](https://user-images.githubusercontent.com/22373640/58276156-193f5900-7d6d-11e9-82a0-815d16f55889.png)

**Comment by alexxxmendonca** [comment]
@paratiuid agora sim! Tudo certo. Pode enviar a correção do PR?

**Comment by joffilyfe** [comment]
> @paratiuid agora sim! Tudo certo. Pode enviar a correção do PR?

@alexxxmendonca este quadrado é resultado de uma ferramenta que nós utilizamos para `debug` na instância de homologação e/ou desenvolvimento. Asseguro que o quadrado não será exibido na instância de produção. Não vejo a necessidade de incorporarmos o #1316, o que você acha?

**Comment by alexxxmendonca** [comment]
@joffilyfe se for assim, confio na sua segurança. Não precisamos desse PR então.
