### ISSUE TITLE
Problemas ao abrir PDF de artigo do site [e sugestão para nome do arquivo]

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1267]
Quando gerado arquivo para impressão para salvar:
![image](https://user-images.githubusercontent.com/6084959/55561661-f081d800-56c8-11e9-95ee-e048d852633e.png)

O arquivo salvo fica com o nome enorme, utilizando como padrão: SciELO - Brasil - título completo do texto:

![image](https://user-images.githubusercontent.com/6084959/55561751-1b6c2c00-56c9-11e9-9ad6-e375a1ebc1aa.png)

Sugiro que a nomeação seja simplificada. Talvez usar o PID do documento, ou elocation-id, ou outro ID interno do site que seja único. Exemplo:

SciELO_Brasil_e156728

Ao salvar o texto do artigo em .pdf o arquivo não abre com Adobe Reader (leitor usual de PDF). Este PDF só abre nos programas (abrir com): PDF Architect 5 e no Google Chrome. 
*Não realizei teste em outros programas.

Arquivo testado: https://homolog.opac.scielo.br/article/sa/2019.v76n2/139-147/en/#

PDF anexo: 
[SCIELO~1.PDF](https://github.com/scieloorg/opac/files/3043836/SCIELO.1.PDF)

**Comment by amandasramalho** [comment]
Sobre a nomenclatura do arquivo, concordo que o título muito grande não seja o melhor caminho (talvez limite de caracteres?) mas minha observação é que o uso de um nome com códigos não me parece ser a melhor escolha. No SciELO Livros usamos o padrão "Sobrenome do autor - ISBN". E quando é download de capítulos, "Sobrenome do autor - ISBN - número do capítulo". Mas vale a reflexão de quais são as regras de Gestão de documentos vigentes (ISO?). Pelo menos essa definição seria respaldada por alguma prática internacional.

**Comment by RPostalli** [comment]
@amandasramalho ótima ideia. Qual norma ISO vc se refere? A 690 mesmo?

Agora percebi também que o PDF baixado não apaga. Eu e a Jennifer testamos e não é possível apagar o .pdf e tão pouco mudar sua nomeação. 😱

**Comment by alexxxmendonca** [comment]
@RPostalli eu estou com o mesmo problema do PDF que agarrou na minha área de trabalho e não exclui por nada nesse mundo.

**Comment by patymori** [comment]
Olá, todos.

Essa forma utilizada para salvar o texto do artigo como PDF é do navegador, que utiliza o título da página como nome padrão para o arquivo a ser salvo. Como essa funcionalidade é do navegador, é dele também a forma como gera este PDF, que não diz respeito ao site do SciELO (se vocês tentarem salvar de outros sites o efeito deve ser o mesmo).
Por fim, quanto à alterar/excluir o arquivo do computador de vocês, deve ser alguma permissão que vocês não tem.

Estou encerrando o ticket.
