### ISSUE TITLE
Resolver URL das páginas secundárias do site antigo para o novo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1268]
As URLs das páginas secundárias estão espalhadas em diversos pontos da web, como por exemplo a página do periódico, sistemas de submissão de artigos, PDFs e impressos diversos, inclusive diretórios como o DOAJ.

Essas URLs são tão antigas quanto o site SciELO e desde então a estrutura nunca foi alterada, portanto certamente elas estão espalhadas por incontáveis páginas e serviços na web.

É importante que após a migração essas URLs possam ser resolvidas para o endereço correspondente no novo site.

Abaixo, fiz uma correlação dos links atuais e novos, usando como base a interface em Inglês de um dado periódico (RBSMI).

http://www.scielo.br/revistas/rbsmi/iaboutj.htm
https://new.scielo.br/journal/rbsmi/about/#about

http://www.scielo.br/revistas/rbsmi/iedboard.htm
https://new.scielo.br/journal/rbsmi/about/#editors

http://www.scielo.br/revistas/rbsmi/iinstruc.htm
https://new.scielo.br/journal/rbsmi/about/#instructions

http://www.scielo.br/revistas/rbsmi/isubscrp.htm (essa página não tem uma página correspondente no site novo e, portanto, deve apontar para o About)
https://new.scielo.br/journal/rbsmi/about/#about

As URLs devem ser resolvidas nos 3 idiomas.

**Comment by gustavofonseca** [comment]
No momento em que escrevo o novo site resolve corretamente as URLs mencionadas, entretanto o conteúdo não é exibido em razão de outro erro (ainda não identificado) que impacta também no acesso às páginas _Sobre o periódico, Corpo editorial e Instruções aos autores_, no canto superior direito do novo site.
