### ISSUE TITLE
Página Informativa OPAC: Atualização de imagens/logos não é permanente

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1271]
Sempre que a unidade de produção trabalha com atualização de logos e imagens das revistas em OPAC é necessário também avisar a equipe de infra. Exemplo de email:
--------------------------
Prezados, bom dia

Foi atualizado o logotipo da JPED em homolog:

Nomes das imagens: plogo.gif e glogo.gif
--------------------------

Este procedimento passou a ocorrer quando detectamos que as imagens atualizadas, voltavam a ficar antigas após um tempo.

Diversas causas foram lançadas, mas a solução final foi informar pontualmente sobre cada atualização para a unidade de infra.

Segue algumas discussões por email:

---------------------
De: Anderson
Renata, 
os dados atualizados foram apenas das revistas listadas abaixo.

/var/www/scielo_br/htdocs/revistas/eagri/*.htm
/var/www/scielo_br/htdocs/revistas/bn/*.htm
/var/www/scielo_br/htdocs/revistas/zool/*.htm

Esta demanda foi para atender ao email enviado pela Roberta:

[URGENTE] Recuperar arquivos do antigo homolog.scielo.br (homolog-metodologia.scielo.org)

As páginas abaixo estão desatualizadas:
http://www.scielo.br/scielo.php?script=sci_serial&pid=0100-6916&lng=en&nrm=iso
http://www.scielo.br/scielo.php?script=sci_serial&pid=1676-0603&lng=en&nrm=iso
http://www.scielo.br/scielo.php?script=sci_serial&pid=1984-4670&lng=en&nrm=iso

Para atualizá-las, por favor, pegar os arquivos atualizados do antigo homolog.scielo.br e colocá-los no homolog-metodologia.scielo.org.

(isso está relacionado também com o conteúdo do novo SciELO BR)

/var/www/scielo_br/htdocs/revistas/eagri/*.htm
/var/www/scielo_br/htdocs/revistas/bn/*.htm
/var/www/scielo_br/htdocs/revistas/zool/*.htm

Por favor, conferir o resultado com Jennifer.

---------------------
De: Anderson
Bom dia Isabela,
como conversamos pessoalmente, no dia da atualização do logo, ajustamos o file glogo.gif, agora ajustamos o file plogo.gif, já apliquei o ajuste em produção, peço que aguarde a renovação do cache do site em produção.

Obs: Testamos uma solução para não ter mais este tipo de problema com os logos das revistas.

Obrigado.

**Comment by patymori** [comment]
@RPostalli,

Descrevendo o que faremos para resolver este problema:
- Vamos retirar o logo do periódico no processamento do novo site. Com isso, o novo periódico ficará disponível no novo site sem o logo
- Será necessário incluir o logo do periódico como Asset via interface de Admin do site novo.
- Ainda na interface Admin, no Catálogo de Periódicos, o campo de URL do logo será apresentado para edição e, caso necessária atualização ou configuração de um novo, deverá ser colocado a URL do Asset cadastrado conforme descrito anteriormente.

**Comment by RPostalli** [comment]
@patymori não entendi "Vamos retirar o logo do periódico no processamento do novo site. Com isso, o novo periódico ficará disponível no novo site sem o logo". 

Primeiro vamos atualizar a página que vai subir em produção sem logo e depois vamos atualiza-la novamente utilizando o link do logo? Desculpa não entendi.

**Comment by patymori** [comment]
@RPostalli, sim. Hoje este logo é vinculado ao periódico somente no momento do processamento do novo site e não é permitido configurá-lo via interface Admin do site.

**Comment by patymori** [comment]
@RPostalli, a nova versão está disponível no ambiente de homologação da coleção BR. Poderia verificar?

**Comment by patymori** [comment]
@RPostalli, aguardando validação

**Comment by RPostalli** [comment]
@cinthia pode testar por favor.

**Comment by cinthia-vieira** [comment]
@patymori Testado, a funcionalidade se comporta como esperado

Como já dito que aconteceria, alguns periódicos estão sem seus respectivos logos em homolog.opac.
