### ISSUE TITLE
Página Informativa: Desvincular criação de novas páginas com a existência de números publicados

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1272]
Na gestão de revistas novas, antes da revista publicar números as páginas informativas dela já são criadas.

No OPAC não é possível vincular uma página de revista nova quando a mesma não tem números publicados.

Este problema acarreta que as páginas da nova revista ficam nas páginas iniciais do SciELO até que a revista envie os primeiro números para publicação.

É necessário abrir a possibilidade da criação de páginas sem vinculo com números publicados/registrados.

É necessário também criar um botão onde as novas páginas só apareçam em produção quando todos os processos que envolvem a criação da revista nova estiverem completos.

**Comment by patymori** [comment]
@RPostalli,

Atualização disponível no ambiente de homologação. Poderia verificar?

**Comment by cinthia-vieira** [comment]
@patymori estou sem acesso ao homolog opac. poderias criar uma conta pra mim?

**Comment by cinthia-vieira** [comment]
@patymori a página criada ainda aparece no Sobre o SciELO. Onde, exatamente, indicaríamos que a página criada não é pública? Na lista de páginas?

**Comment by patymori** [comment]
> @patymori a página criada ainda aparece no Sobre o SciELO. Onde, exatamente, indicaríamos que a página criada não é pública? Na lista de páginas?

É necessário vincular a um periódico. O que foi feita como uma solução intermediária ao problema foi liberar a entrada de periódicos no site sem a existência de fascículos publicados. Com isso, quando o periódico for cadastrado na *Title Manager*, mesmo sem fascículos, estará disponível no admin do site e, assim, disponível para vincular as páginas secundárias.

Peço desculpas por não ter anotado o que exatamente foi feito. Havia discutido a solução somente com a Renata.

**Comment by RPostalli** [comment]
@patymori por favor informe para a Cinthia detalhadamente as novas funcionalidades que devem ser testadas e como utiliza-las. Como ela usa de fato a ferramenta no dia a dia o teste vai ser mais assertivo.
Obrigada.

**Comment by cinthia-vieira** [comment]
@patymori Mas ainda assim, não existe a possibilidade de mudar a visibilidade das páginas, estando elas vinculadas ou não a um periódico. Onde fica(ria) esse botão/campo? Eu realmente não consegui encontrar as modificações implementadas...

**Comment by patymori** [comment]
@cinthia-vieira, o que foi feito:

* Acessando o Admin do site,
  *Catálogo* > *Periódico*
  editando um periódico, foi adicionado um campo novo __Is Public__, que aceita `True` ou `False`. Ele determina se esse periódico vai ou não aparecer na navegação do site.

![Screen Shot 2019-05-17 at 18 38 37](https://user-images.githubusercontent.com/18053487/57957555-0f33db00-78d3-11e9-8682-84d6e00fdcbc.png)

* Havia um problema no processamento do novo site que não permitia a inclusão de periódicos sem fascículos. Esse problema foi solucionado e agora não será mais necessário esperar que haja um fascículo no periódico para cadastrar as páginas secundárias. Inicialmente o periódico sem fascículos será incluído com o status __Is Public__, descrito anteriormente, como `False`. Assim, ele aparecerá na lista de periódicos do cadastro de páginas secundárias, conforme a tela a seguir, mas não aparecerá publicada no site.

![Screen Shot 2019-05-17 at 18 40 24](https://user-images.githubusercontent.com/18053487/57957761-c892b080-78d3-11e9-86ad-9033275347ea.png)

* A partir de agora, com os periódicos disponíveis no site, torná-los acessíveis no site dependerá da alteração do campo __Is Public__ no cadastro do periódico.

Espero ter conseguido explicar melhor mas qualquer dúvida pode informar.

Obrigada

**Comment by cinthia-vieira** [comment]
@patymori Agora eu entendi como faz, obrigada!

Infelizmente, esse procedimento tem um problema porque não é intuitivo. Se vc não tivesse explicado, eu não conseguiria saber onde a visibilidade das páginas/periódicos é configurada (principalmente porque majoritariamente eu mexo somente nas abas Páginas e Ativos, assim como meus colegas da Produção, que são os responsáveis por criar e atualizar as páginas informativas atualmente). 

Não existe alguma maneira de incorporar esse campo também na edição das páginas informativas? Dessa forma facilita muito pra quem estiver criando/editando páginas fazer essa operação por conta própria.

**Comment by patymori** [comment]
@cinthia-vieira, entendo a dificuldade mas talvez eu não tenha conseguido explicar uma coisa: o status `is Public` diz respeito ao periódico, não tendo vínculo com as páginas informativas. Ou seja, independente se há ou não páginas informativas vinculadas ao periódico, é possível alterar o status de publicado/despublicado do periódico através da interface de admin. Portanto, por ser uma característica do periódico, faz mais sentido o status `is Public` ficar com as informações do periódico.
Quanto a disponibilizá-lo também na interface das páginas informativas, há uma complexidade maior que precisamos analisar a possibilidade pois foge da estrutura existente hoje. Poderíamos tratar dessa sugestão de melhoria em um outro ticket?
Obrigada pelas sua sugestão.

**Comment by cinthia-vieira** [comment]
@patymori entendi, realmente faz mais sentido nesse contexto. Criarei um novo ticket sim :)!!

Obrigada.

**Comment by patymori** [comment]
@cinthia-vieira e @RPostalli , as alterações estão em produção. Estou encerrando este ticket.
