### ISSUE TITLE
Considerar apenas datas do tipo collection para legenda bibliográfica do artigo

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1274]
Relação com https://github.com/scieloorg/opac/issues/1180#issuecomment-480798010

Na primeira [linha do artigo](https://new.scielo.br/scielo.php?script=sci_arttext&pid=S1414-32832019000100212&lng=pt&nrm=iso&tlng=pt) deve ser considerado apenas a data de citação do documento

![image](https://user-images.githubusercontent.com/6084959/55739115-cef15b00-59fe-11e9-84fa-cd796fc9a7bc.png)

Com os novos insumos de datas (SPS 1.9 pub + collection e SPS 1.8.1 epub + collection) deve ser considerado para a legenda bibliográfica apenas as datas do tipo collection.

Artigos ahead of Print (AOP) não possuem esta data (apenas quando migram para um fascículo).

Sugiro também que seja inserido alguma separador (vírgula, ponto e vírgula, hífen etc) entre o número do volume/número e a data. A leitura fica prejudicada sem um separador.

![image](https://user-images.githubusercontent.com/6084959/55739387-50e18400-59ff-11e9-877b-9058ec108691.png)

**Comment by robertatakenaka** [comment]
Este exemplo, é um PC e não possui a data collection pois é anterior a definição de data collection para todos os documentos.

[1807-5762-icse-23-e170521.zip](https://github.com/scieloorg/opac/files/3154278/1807-5762-icse-23-e170521.zip)

Todos os documentos, exceto os AOP, tem a data collection.

**Comment by RPostalli** [comment]
Segue exemplo de um artigo com as datas duas datas, o problema ainda ocorre.

https://new.scielo.br/article/bjmbr/2019.v52n4/e8409/en/

**Comment by robertatakenaka** [comment]
Bloqueado porque nem todos os XML tem a data **pub-date (collection)**.
Precisamos primeiro garantir por os XML serão adaptados para a versão SPS 1.9
