### ISSUE TITLE
Interface responsiva para Artigo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1275]
Adaptar a interface do texto completo (Artigo) de modo a torná-la responsiva para qualquer dispositivo.

**Comment by joffilyfe** [comment]
Critério de aceitação: 
https://projects.invisionapp.com/share/ZNN9Y0TJ9X3#/screens/366776414_Scielo_-_Artigo_-_Mobile_-_06-2019

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , esse ticket ja esta no ambiente de homologação (https://homolog.opac.scielo.br/), vc pode validar?

**Comment by alexxxmendonca** [comment]
Os financiadores não aparecem por completo.

Apenas FAPESP e CAPES estão aparecendo:

![IMG_3616](https://user-images.githubusercontent.com/4059679/59213992-87b55100-8b8c-11e9-9cbb-de766ea8bbaa.PNG)

**Comment by paratiuid** [comment]
> Os financiadores não aparecem por completo.
> 
> Apenas FAPESP e CAPES estão aparecendo:
> 
> ![IMG_3616](https://user-images.githubusercontent.com/4059679/59213992-87b55100-8b8c-11e9-9cbb-de766ea8bbaa.PNG)

@alexxxmendonca 

não consegui reproduzir este erro dos patrocinadores.

Podes me dar mais detalhes de como você efetuou os testes?

Tentei também acessar a homolog no link https://homolog.opac.scielo.br/ mas acabo caindo em um blog. Mesmo com VPN.

Aqui para mim, tanto no chrome, quanto safari ou firefox, o erro não ocorre.

**Comment by alexxxmendonca** [comment]
_não consegui reproduzir este erro dos patrocinadores.

Podes me dar mais detalhes de como você efetuou os testes?_

Eu só acessei pelo Safari do iPhone. Fiz um vídeo mas o github não permite subir MP4.

Mas está exatamente ao print do comentário anterior.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Cria um arquivo .zip com o vídeo assim o github permiti.

**Comment by alexxxmendonca** [comment]
Obrigado, Jamil!

@paratiuid segue vídeo anexo.
[RPReplay_Final1560253477.zip](https://github.com/scieloorg/opac/files/3276329/RPReplay_Final1560253477.zip)

**Comment by alexxxmendonca** [comment]
Aparentemente era cache do meu navegador. Atualizei a tela e os logos apareceram.

@cesarbruschetta pode dar seguimento à esse ticket então?

**Comment by paratiuid** [comment]
@alexxxmendonca e @cesarbruschetta 

Realmente acredito que seja cache sim Alex.
Conforme conversamos, retestei em vários ambientes e não consegui reproduzir o problema citado.

Segue abaixo imagem do navegador Safari, acessando a homologação.

![Screen Shot 2019-06-11 at 1 47 07 PM](https://user-images.githubusercontent.com/22373640/59291327-fa880000-8c50-11e9-9839-6a9a634a33f9.png)

**Comment by cesarbruschetta** [comment]
@alexxxmendonca e @paratiuid , verdade a gente verificou que havia uma divergencia de dados salvos na base de `homologação` e `produção` , os dados da coleção que podem ser editados pelo ´/admin´ do OPAC, assim vimos que na base de homologação estava faltando o cadastro de alguns patrocinadores e os dados de endereço da coleção. 

mas acho que podemos dizer que foi so cache mesmo :stuck_out_tongue_winking_eye:
