### ISSUE TITLE
Em como citar, apresentar o autor collab que deveria estar aparecendo antes de "et al".

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1278]
No artigo https://new.scielo.br/scielo.php?script=sci_arttext&pid=S2175-78602018000401513&lng=en&nrm=iso&tlng=en# no como citar o et al aparece na frente. 

![image](https://user-images.githubusercontent.com/6084959/56214146-b652f780-6033-11e9-981c-30e10ca06116.png)

Este dado usualmente vai depois do nome do autor.

Qual norma o como citar SciELO está usando?

**Comment by jamilatta** [comment]
@RPostalli @solange-scielo

Qual seria as condições para adicionar o **et al** devemos aplicar para todos ou existe um regra?

**Comment by RPostalli** [comment]
@jamilatta pra eu te responder isso preciso que você me responda a pergunta feita no ticket antes.

Qual norma o como citar SciELO está usando?

**Comment by jamilatta** [comment]
@RPostalli 

Boa pergunta?

**Comment by jamilatta** [comment]
A @solange-scielo consegui nos ajudar nessa resposta?

**Comment by RPostalli** [comment]
No site velho tínhamos 4 normas
![image](https://user-images.githubusercontent.com/6084959/64346461-8bf4dd00-cfc8-11e9-987e-58a70bd6887b.png)

Me parece por comparação que a norma é a ISO

![image](https://user-images.githubusercontent.com/6084959/64346678-ea21c000-cfc8-11e9-9776-7f297ff877b4.png)

Mas aqui o et al está correto.

O bug é só quando existe `<collab>`

**Comment by jamilatta** [comment]
Hum entendi.

**Comment by RPostalli** [comment]
@jamilatta, mais algumas considerações

- O et al na imagem esta grudado com o sobrenome do autor, tem que corrigir isso também. Tem que ter uma vírgula. Exemplo: Zhou, Xindie, et al.

- E está redundante ter o mesmo link DOI do artigo duas vezes. No site antigo havia a informação da URL do artigo e depois do link DOI. Como nossos links URL não são permanentes, recomendo que exclua o último link.

- trocar o termo: "Accessed" para "Cited" conforme dita a ISO

- trocar o termo "v" para "vol" conforme dita a ISO

- A formatação da ISO prevê que o `<source>` seja itálico (como era no site antigo), por favor corrigir isso também.

**Comment by amandasramalho** [comment]
Me permitam um comentário: A URL final da referência segue as recomendações de Boas Práticas do CrossRef. Acredito que o errado esteja na URL de DOI em "Available from".
![image](https://user-images.githubusercontent.com/5446933/64363574-6aefb480-cfe7-11e9-8713-6cbc92461428.png)

**Comment by amandasramalho** [comment]
Renata,
A ISO não orienta usar [Cited... e sim [Accessed....
![image](https://user-images.githubusercontent.com/5446933/64364426-35e46180-cfe9-11e9-83da-bfcc9f91a46c.png)
(Página 36 da ISO 690:2010)

**Comment by RPostalli** [comment]
@amandasramalho eu tenho pouquíssimo conhecimento de ISO, meu forte é ABNT. Pode por favor desenhar um modelo perfeito de journal na ISO para o @jamilatta reproduzir como ref no site novo? 

Os exemplos que eu vi na própria ISO estavam com Cited 😕

**Comment by RPostalli** [comment]
Ah mas o accessed é usado para [software] e [program]. Olha os exemplo de [online] na página 4 e 5. estão com Cited.

**Comment by RPostalli** [comment]
Ixe minha ISO é de 1997 😣. Você consegue criar um modelo padrão pra gente?

**Comment by amandasramalho** [comment]
@RPostalli 
Vou montar um modelo seguindo a ISO para revisão de vocês. Aliás, relendo a ISO, encontrei outra indicação para a data de acesso (ver imagem abaixo). Porém, cabe uma observação: se o "Available from" for retirado da referência, não há necessidade de inserir o "viewed", uma vez que a filosofia do DOI sugere que a URL esteja sempre atualizada e ativa.
![image](https://user-images.githubusercontent.com/5446933/64366776-531b2f00-cfed-11e9-8df5-b0f6d37a643f.png)

**Comment by RPostalli** [comment]
Obrigada @amandasramalho fico no aguardo para revisar.

Não podemos tirar o "Available from" por se tratar se um documento online e sermos uma base de dados digital, acho que é recomendado que esse dado exista. Minha sugestão era retirar o link DOI do final do documento e manter o link DOI como "Available from". Não pode será?

No seu comentário do CrossRef o link DOI do exemplo é um "Available from" mas sem o texto "Available from" não?

**Comment by amandasramalho** [comment]
@RPostalli
Vou montar um modelo seguindo a ISO para revisão de vocês. Aliás, relendo a ISO, encontrei outra indicação para a data de acesso (ver imagem abaixo). Porém, cabe uma observação: se o "Available from" for retirado da referência, não há necessidade de inserir o "viewed", uma vez que a filosofia do DOI sugere que a URL esteja sempre atualizada e ativa.
![image](https://user-images.githubusercontent.com/5446933/64367460-6a0e5100-cfee-11e9-9fc5-c271430ac6c3.png)

**Comment by amandasramalho** [comment]
@RPostalli 
Renata, o "Available from" é usado para URLs específicas de um site, no nosso caso, seria a URL própria do SciELO. Usar "Available from" para um DOI estaria errado, uma vez que o DOI tem outra finalidade.
Inclusive, a página 20 da ISO 690:2010 informa que é preferível o uso do DOI.
![image](https://user-images.githubusercontent.com/5446933/64368100-f8370700-cfef-11e9-8e6f-d99c6c7fd209.png)
Isso complementa inclusive o que você mencionou em sua mensagem anterior, as URLs do SciELO podem não ser permanentes. Mas o DOI deve sempre ser.

**Comment by RPostalli** [comment]
hummm entendi. Vixe eu acho que o Abel não gostará de tirar o Cited, se o Cited e o Available from são dependentes, acho que precisaremos da autorização dele para uma proposta de novo layout de referência no como citar.

Esse ticket na verdade já se transformou em outra coisa.

@jamilatta siga com a correção do et al para `<collab>` por favor.
@amandasramalho vou abrir outro ticket para apresentarmos uma nova proposta de como citar SciELO para o site novo com base da ISO e o exemplo que você nos enviar. 
@alexxxmendonca você poderia por favor apresentar ao Abel e nos informar?

**Comment by amandasramalho** [comment]
@RPostalli 
Não são "dependentes", é apenas uma sugestão. O caso do "cited" não há o que fazer, consequência de atualização da norma. Mas o caso do Available from, se não for usar as URLs do SciELO, então não faria sentido ter o DOI 2x na referência. E tendo como parâmetro as indicações de boas práticas do Crossref, acho que deveríamos seguir as instruções deles. Mas concordo que pode ser assunto para outro tópico.

**Comment by RPostalli** [comment]
Criei https://github.com/scieloorg/opac/issues/1412

**Comment by gustavofonseca** [comment]
A alteração já foi realizada no packtools [https://github.com/scieloorg/packtools/commit/1b1621efcb1678507644998c3fd5890190af5a22], portanto esta atividade pode seguir. Para tal, o projeto deve utilizar `packtools==2.5.6`.

**Comment by jamilatta** [comment]
@gustavofonseca 

Criei um tíquete no OPAC para atualizarmos o packtools: https://github.com/scieloorg/opac/issues/1458

**Comment by gustavofonseca** [comment]
> @gustavofonseca
> 
> Criei um tíquete no OPAC para atualizarmos o packtools: #1458

Ok. Se vc estiver vendo isso agora, acho que já poderia enviar o PR com a nova versão, assim a gente já resolve isso.
