### ISSUE TITLE
Site retorna metatag *citation_title* diferente do título do documento quando este é uma tradução

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1279]
**Nota: Já foi feito para SciELO Brasil, falta fazer para o SciELO Salud Pública** (modificar pontualmente no branch do scielosp)

A captura de tela a seguir mostra um documento de título _Instrumento de medición: conocimientos, actitudes y prácticas en personas con tuberculosis pulmonar_, mas o valor da metatag é: `<meta name="citation_title" content="Measuring instrument: knowledge, attitudes and practices of people with pulmonary tuberculosis">`

![Screen Shot 2019-04-18 at 14 28 43](https://user-images.githubusercontent.com/161335/56379791-14ccd100-6200-11e9-9a64-03f08c099200.png)

https://new.scielo.br/article/rlae/2019.v27/e3086/es/

Este problema foi reportado pela equipe de indexação do Google, que deverá ser avisada quando o problema tiver sido solucionado para que os conteúdos sejam reindexados.

ps.: No contato do Google não foi mencionada a instância new.scielo.br, mas sim www.scielo.sa.cr.

**Comment by jamilatta** [comment]
Essa atividade deve ser realizada na instância de SciELO Saúde Pública.

**Comment by cesarbruschetta** [comment]
PR #1282 fechado, mas sera incorporado pelo #1339
