### ISSUE TITLE
Compatibilizar língua de citação e título de citação

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac#1283]
### Descrição do problema
As *meta tags* `citation_title` e `citation_language` pertencem a página de exibição dos artigos no sistema OPAC. Com a solução de #1279 estas tags passarão a divergir e consequentemente entregarão dados inconsistentes.

### Passos para reproduzir o problema
1. Acesse a página https://new.scielo.br/article/rlae/2019.v27/e3086/es/
2. Inspecione o conteúdo HTML da página
3. Navegue até o nó `HEAD`
4. Observe o conteúdo divergente das tags

### Comportamento esperado
Por principio as duas tags possuem uma correlação **forte** de tal maneira que quando a *meta tag* `citation_title` possuir um conteúdo em espanhol a tag `citation_language` deve exibir o conteúdo **es**.

### Screenshots ou vídeos
N/A

### Anexos
N/A

### Ambiente utilizado
- Ambiente de produção e homologação do OPAC
- Qualquer sistema operacional

**Comment by cesarbruschetta** [comment]
@joffilyfe @robertatakenaka o ambiente de homologação ja esta atualizado, vcs podem verificar?

**Comment by joffilyfe** [comment]
> @joffilyfe @robertatakenaka o ambiente de homologação ja esta atualizado, vcs podem verificar?

Verifiquei @cesarbruschetta, funciona como o esperado.

**Comment by patymori** [comment]
Reaberto para aplicar correção na branch de SciELO Saúde Pública.
