### ISSUE TITLE
Troca de idioma no site.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#129]
### Problema: 

As bandeiras de troca de idiomas no site por hora são "fake". 

### Objetivo: 
Garantir que as bandeiras de troca de idioma no site funcionem.

**Comment by jamilatta** [comment]
Seguir a mesmo abordagem de troca de idioma adotado no admin do OPAC.

**Comment by jfunez** [comment]
resolvido em 4681d7f6963bd3a6f900c7d5d707f9ef008bc13c
