### ISSUE TITLE
URL do PDF no padrão do site antigo não é resolvido pelo novo site (CSP v28n5)

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1291]
O link do site antigo http://www.scielosp.org/pdf/csp/v28n5/03.pdf não está redirecionando para o site novo.

**Comment by robertatakenaka** [comment]
Analisando a questão, descobertas feitas:
1. Em **opac**, o comando abaixo retornou `issue == None`:

``issue = controllers.get_issue_by_journal_and_assets_code(assets_code=issue_info, journal=journal)``

https://github.com/scieloorg/opac/blob/e027ec34e2fc597e5e4bf79868abf72ce6498222/opac/webapp/main/views.py#L1118

2. Na base (homolog) ,``assets_code`` deste fascículo está com valor **None**, que é diferente de `issue_info` (que seria **v28n5**)

<img width="744" alt="Captura de Tela 2019-05-08 às 10 24 54" src="https://user-images.githubusercontent.com/505143/57378635-95397e80-717b-11e9-9d3a-ca56ab283752.png">

3. Em **opac_proc**, ``assets_code`` é preenchido com `xylose.assets_code`

https://github.com/scieloorg/opac_proc/blob/a3ee441dac0223023f6fb8991a2b1c2ab002a237/opac_proc/transformers/tr_issues.py#L137


4. Em **xylose**, ``assets_code`` é preenchido com o campo `v4`

https://github.com/scieloorg/xylose/blob/848daab2d7a01d3ed75b549aad243aff7c6a3be8/xylose/scielodocument.py#L250

```
        return self.data['issue'].get('v4', [{'_': None}])[0]['_']
```

6. Dado existe no articlemeta:

http://articlemeta.scielo.org/api/v1/articles/?collection=spa&code=S0102-311X2012000500003

<img width="790" alt="Captura de Tela 2019-05-08 às 11 12 16" src="https://user-images.githubusercontent.com/505143/57381892-3aefec00-7182-11e9-8e4b-54382e0a8f92.png">

**Comment by alexxxmendonca** [comment]
Outra URL com problema: https://www.scielosp.org/scielo.php?pid=S0213%2091112004000800004&script=sci_arttext&tlng=pt

mesma questão ou é um caso diferente?

**Comment by robertatakenaka** [comment]
@gustavofonseca @patymori @jamilatta @cesarbruschetta @joffilyfe por favor leiam e analisem o comentário acima, propondo soluções.

**Comment by gustavofonseca** [comment]
@robertatakenaka, me parece que nós deveríamos alterar a implementação de `assets_code`, no xylose, para que passe a obter o dado de *article*, ao invés de *issue*, conforme seu exemplo: 

> ```python
> >>> r['article']['v4']
> [{'_': 'v27n5'}]
> >>> j['article']['v4']
> [{'_': 'v28n5'}]
> ```

Faz sentido?

**Comment by robertatakenaka** [comment]
@gustavofonseca eu acredito que depende do caso. 
No caso de estar acessando o endpoint do artigo, "tanto faz" pegar o data['article']['v4'] ou data['issue']['issue']['v4']. 
No entanto, quando o endpoint é para o issue (que é o caso), não há data['article'], e por consequencia,o v4 estará ausente.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , esse ticket ja esta no ambiente de homologação (https://homolog.opac.scielo.br/), vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta como validar? Qual é a URL de homologação que faz o redirecionamento?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca esse seria um exemplo, citado no topo do ticket https://homolog.opac.scielo.br/pdf/csp/v28n5/03.pdf 

mas vc pode tentar pegar outras url de pdf do site classico e so colocar o endereço "https://homolog.opac.scielo.br/" na url

**Comment by alexxxmendonca** [comment]
@cesarbruschetta o problema foi reportado no SciELO SP. 

É correto eu testar no OPAC SciELO BR?

**Comment by cesarbruschetta** [comment]
> @cesarbruschetta o problema foi reportado no SciELO SP.
> 
> É correto eu testar no OPAC SciELO BR?

@alexxxmendonca , acredito que sim pois o "Opac Br" é hoje nosso branch de desenvolvimento master, então também devia ter problema aqui também, mas eu vou deixar registrado que esse ticket deve ser implantado também no ambiente de produção do "OPAC SP"

**Comment by gustavofonseca** [comment]
> @cesarbruschetta o problema foi reportado no SciELO SP.
> 
> É correto eu testar no OPAC SciELO BR?

Excelente ponto.

**Comment by gustavofonseca** [comment]
Ops, fechei sem querer.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , @robertatakenaka, @gustavofonseca 

Nos fizemos alteração, vcs podem validar novamente no ambiente de homologação de SP (https://homolog.opac.scielo.org/)

**Comment by alexxxmendonca** [comment]
@cesarbruschetta por mim está ok!

aguardo validação dos demais.
