### ISSUE TITLE
Definições para utilização de logging

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#13]
## Problema:

No OPAC não temos suporte a logging.

## Objetivo:

Definir e estudar a melhor forma de adicionar as capacidades de logging no OPAC.

**Comment by jfunez** [comment]
@jamilatta @fabiobatalha @gustavofonseca 
temos que definir a configuração do logger para o OPAC, então gerei este gist (como base) para discutirmos como pode ser melhorado, e o vocês acham.

https://gist.github.com/jfunez/2751977510955badc952

Escuto comentários!!

**Comment by jamilatta** [comment]
Devemos utilizar as definição de utilização de log mencionadas na documentação official do python, ver: https://docs.python.org/2/howto/logging.html#logging-basic-tutorial

Definimos o arquivo de configuração de log conforme abaixo: 

```ini
[loggers]
keys=root, admin, main

[handlers]
keys=consoleHandler, timedRotatingFileHandlerMain, timedRotatingFileHandlerAdmin

[formatters]
keys=simpleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_main]
level=DEBUG
handlers=timedRotatingFileHandlerMain
qualname=app.main

[logger_admin]
level=DEBUG
handlers=timedRotatingFileHandlerAdmin
qualname=app.admin

[handler_timedRotatingFileHandlerMain]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=simpleFormatter
args=('log/main.log', 'D', 1, 5, None, False, False)
propagate=0

[handler_timedRotatingFileHandlerAdmin]
class=handlers.TimedRotatingFileHandler
level=DEBUG
formatter=simpleFormatter
args=('log/admin.log', 'D', 1, 5, None, False, False)
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
```

Adicionamos um manipulador para o admin e para a app main. Em outro momento pretendemos reconfigurar esse arquivo.

**Comment by gustavofonseca** [comment]
Essas configurações variam de acordo com o ambiente de implantação. Se vocês olharem no wiki do scielo, na seção que fala sobre o modelo de implantação das apps, vocês verão que no nosso modelo o circusd é responsável pelo manuseio e rotação dos logs.
