### ISSUE TITLE
Duplicação de autores no cabeçalho da página de artigo

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1311]
### Descrição do problema
Ao acessar o artigo:
https://new.scielo.br/article/abc/2018.v111n3/436-539/
A linha de cabeçalho dos autores aparece duplicada. Ao expandir os autores, os nomes de autores aparecem duplicados e o botão `SOBRE OS AUTORES` multiplica-se (ver screenshots). Também multiplicam-se o número de autores do tooltip.
Importante notar que o erro não ocorre em todos os artigos, como neste exemplo:
https://new.scielo.br/article/abc/2018.v111n3/364-372/

### Passos para reproduzir o problema
1. Acessar a página https://new.scielo.br/article/abc/2018.v111n3/436-539/
2. Posicionar o mouse em `[...]` e verificar o número de autores
3. Clicar em `[...]`para expandir os autores
4. Observe a duplicação
5. Clicar em `X` para colapsar os autores
6. Observe o surgimento de um novo cabeçalho
7. Posicionar o mouse em `[...]` e verificar que o número de autores aumentou

### Comportamento esperado
- O cabeçalho não deveria aparecer duplicado no acesso
- O expandir e colapsar dos autores não deveria criar uma nova de autores
- O número de autores deve ser exibido corretamente

### Screenshots ou vídeos

<img width="768" alt="Screen Shot 2019-05-21 at 10 23 40" src="https://user-images.githubusercontent.com/18053487/58100239-a048d180-7bb3-11e9-91df-a39088b4b143.png">

<img width="770" alt="Screen Shot 2019-05-21 at 10 23 24" src="https://user-images.githubusercontent.com/18053487/58100250-a63eb280-7bb3-11e9-9a5f-7822d9213225.png">

<img width="911" alt="Screen Shot 2019-05-21 at 10 37 27" src="https://user-images.githubusercontent.com/18053487/58100803-c1f68880-7bb4-11e9-8f97-2d067295109f.png">

### Anexos
N/A.

### Ambiente utilizado
- Chrome 74.0.3729.157 (Official Build) (64-bit)
- Firefox 66.0.5 (64-bit)

**Comment by paratiuid** [comment]
@patymori 

consegui identificar o problema.

Este artigo foge do padrão dos demais por incluir mais de um div com a classe "contribGroup". No caso existem 2.

Onde o primeiro contém a denominação do grupo de autores = Comitê Coordenador da Diretriz de Insuficiência Cardíaca.

E o segundo, contém o grupo de autores em sí.

O script que esconde e mostra os autores dependendo de sua quantidade, espera apenas um desses elementos em tela. Como temos mais de um, ele se perde.

Sugiro que criemos uma nova classe css que identifique o nome do grupo de autores em sí, e mantenhamos a classe existente para o comportamento de mostrar e esconder.

Abaixo colo alguns prints que ilustram melhor o problema:

Código exibindo dois divs contendo a classe "contribGroup"
![Screen Shot 2019-07-03 at 6 10 05 PM](https://user-images.githubusercontent.com/22373640/60625631-bf479f80-9dbe-11e9-9db1-90e1153a4da6.png)

Sugestão de variação de nome de classe para diferenciar os dois tipos de dados:
![Screen Shot 2019-07-03 at 6 09 31 PM](https://user-images.githubusercontent.com/22373640/60625685-e7cf9980-9dbe-11e9-87ad-3ca1553e292d.png)

Exemplo em tela, de como pode ficar o artigo com a solução aplicada.
Vale lembrar que como teremos essa nova classe para identificar o nome do grupo de autores, esse dado pode sofrer alteração de cores, tamanho, fonte, etc..
<img width="1173" alt="Screen Shot 2019-07-03 at 6 09 16 PM" src="https://user-images.githubusercontent.com/22373640/60625741-13eb1a80-9dbf-11e9-9c38-1edc3250fa7b.png">

**Comment by paratiuid** [comment]
Talvez seja interessante validar o visual do texto "Comitê Coordenador da Diretriz de Insuficiência Cardiaca" com o @alexxxmendonca .

**Comment by alexxxmendonca** [comment]
@paratiuid acho que está bom da forma como está. Eu talvez colocaria um separador de dois pontos ":" após o "Comitê..." para vincular os nomes ao Comitê.

Da forma como está, está um pouco "solto".

**Comment by paratiuid** [comment]
@patymori 

Aguardo um posicionamento seu.

**Comment by robertatakenaka** [comment]
Me parece que o problema tem que ser corrigido no packtools na geração do html, deixando apenas 1 contribGroup, conforme mencionado: https://github.com/scieloorg/opac/issues/1311#issuecomment-508259339

**Comment by cesarbruschetta** [comment]
Vou implementar no `packtools` a correção dita pela @robertatakenaka

**Comment by gustavofonseca** [comment]
packtools == 2.5.2 contém a correção.

**Comment by cesarbruschetta** [comment]
@carolinatanigushi, vc consegue validar esse TK no ambiente de homolog do opac? https://homolog.opac.scielo.br/

**Comment by carolinatanigushi** [comment]
@cesarbruschetta Parece-me que a questão do Comitê apontada pelo @alexxxmendonca não foi resolvida? Vocês tiveram alguma discussão nesse sentido que fez com que isso não fosse levado para frente?

> @paratiuid acho que está bom da forma como está. Eu talvez colocaria um separador de dois pontos ":" após o "Comitê..." para vincular os nomes ao Comitê.
> 
> Da forma como está, está um pouco "solto".
