### ISSUE TITLE
Melhorar tooltips dos botões RSS na homepage do periódico

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1319]
### Descrição da nova funcionalidade
Eu, como **usuário do site**, gostaria que **os botões de RSS presentes na homepage (https://new.scielo.br/journal/mioc/) do periódico trouxessem mais informações sobre o tipo de conteúdo que ele traz.**, então **gostaria que fossem incluídos tooltips mais descritivos sobre o conteúdo que aquele RSS trará ao usuário interessado em utilizá-lo**.

Atualmente há 3 botões de RSS na mesma página, o que pode confundir o usuário. A descrição de 2 deles ("Atom") também não é clara para usuários leigos.

### Critérios de aceitação

Para que esta tarefa seja considerada concluída deve conter os seguintes pontos:
- O tooltip deve ser claro em sua descrição do conteúdo presente no RSS.
- Possuir tradução nos 3 idiomas da interface da aplicação.

Sugiro, para os botões de RSS superior e inferior:
"RSS do número mais recente do periódico" / "RSS of this journal's latest issue" / "RSS del número más reciente de la revista"

Sugiro, para o botão de RSS do feed de Press Release:
"RSS dos Press Releases mais recentes desse periódico" / "RSS of this journal's latests Press Releases" / "RSS de los últimos informes de prensa de esta revista"

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , esse ticket ja esta no ambiente de homologação (https://homolog.opac.scielo.br/), vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em homologação.
