### ISSUE TITLE
Saída HTML do sumário (TOC)

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/opac#1321]
### Descrição da nova funcionalidade
Eu, como **a pessoa que envia os alertas de novos fascículos/artigos**, gostaria que **houvesse a possibilidade de exportar o sumário (TOC) em HTML para o envio de alertas de novos artigos e fascículos organizados por seção**.

Atualmente nós enviamos esses emails de alerta para os periódicos cujo fluxo editorial é feito no SciELO copiando e colando o conteúdo do sumário do site (antigo) num editor de HTML e fazendo a limpeza do código (entre outras adaptações, como a adição de linhas de separação). Esse processo é bastante manual e um tanto trabalhoso, então, em resumo, o que precisamos aqui é uma forma de automatizar essa atividade.

### Critérios de aceitação
Lista de critérios a serem observados pela equipe de engenharia durante a elaboração e construção da tarefa. Seja claro(a), descreva os pontos que são importantes para você:
- Os artigos devem vir organizados por seção;
- O nome dos autores deverá vir em texto puro, sem o link de busca na base;
- A saída deve ser mais próxima possível dos HTMLs anexos;
- Seria interessante ter a possibilidade de selecionar quais artigos constarão na lista, no caso de periódicos que fazem publicação contínua (ver os Anexos).

### Anexos
Exemplos de alertas enviados pelo SciELO:

[JVATITD](https://new.scielo.br/toc/jvatitd/2019.v25/): enviado alerta para artigos novos. Nesse caso não são listados todos os artigos do fascículo, apenas alguns pré-selecionados:
- HTML: [jvatitd.txt](https://github.com/scieloorg/opac/files/3228883/jvatitd.txt);
- Alerta enviado: http://eepurl.com/gpWD49

[RBEF](https://new.scielo.br/toc/rbef/2019.v41n4/): enviado um alerta com todos os artigos do fascículo:
- HTML: [rbef.txt](https://github.com/scieloorg/opac/files/3228880/rbef.txt);
- Alerta enviado: http://eepurl.com/gsC9Sn

**Comment by alexxxmendonca** [comment]
Com o [programa em Python](https://github.com/scieloorg/scielo_exports) desenvolvido pelo @ednilson, esta demanda não é mais relevante.
