### ISSUE TITLE
Apresentar a lista de periódicos de acordo com recomendações do Google Scholar

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1323]
(Produção da listagem dos periódicos no servidor, em HTML puro.)

A listagem dos periódicos (https://new.scielo.br/journals/) implementada na versão atual do site é montada dinamicamente no navegador do cliente, em resposta a rolagem da página. Esta implementação prejudica a capacidade de indexação do Google Scholar.

Este ticket decorre de uma solicitação explícita feita pela equipe do Google Scholar.

### Descrição da nova funcionalidade
Eu, como **o crawler do Google Scholar**, gostaria que **visualizar a lista completa dos periódicos em HTML**, para que **eu possa coletar os links para as páginas dos periódicos e seguir com a indexação dos conteúdos**.

### Critérios de aceitação
A listagem dos periódicos deverá ser produzida no servidor, com links _HTML GET_.

### Referências
- https://scholar.google.com/intl/en/scholar/inclusion.html#crawl

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , como definido em plan semana, a @paratiuid ira verificar essa demanda.

**Comment by cesarbruschetta** [comment]
Ticket duplicado #1346 criado pela @paratiuid 

> ### Descrição do problema
> Tornar a lista de periódicos do Opac estática a fim de melhorar o SEO
> 
> ### Passos para reproduzir o problema
> Acesse a lista de periódicos do Opac
> 
> ### Comportamento esperado
> HTML estático e / ou amigável com SEO

**Comment by paratiuid** [comment]
Pessoal, @robertatakenaka  

conforme conversado hoje cedo em nossa reunião, 

ontem, @jamilatta  e eu trabalhamos na resolução deste problema.

Entendemos que uma boa abordagem seria identificar via user-agent, o googlebot, responsável pela indexação da lista.

Após identificar se o acesso foi dado pelo googlebot, a lista é exibida sem a necessidade de javascript e nem paginação.
Com isso, todo o conteúdo da lista é exibido e indexado.

O comportamento não foi alterado para usuários convencionais. Apenas sofreu alteração quando identificado que se trata do googlebot.


Assim que finalizados os últimos detalhes, será criado um pull-request.

Pedimos para que esta versão seja disponibilizada em ambiente de homologação para que a equipe do Google Scholar avalie se a solução atende a solicitação.

**Comment by alexxxmendonca** [comment]
O pessoal do Google Scholar conseguirá validar em homolog?

**Comment by gustavofonseca** [comment]
É improvável. Mas de qualquer forma será possível consultá-los para avaliar se a solução é suficiente.

-Gustavo

Em Qua 26 jun. 2019, às 14:42, alexxxmendonca escreveu:

**Comment by cesarbruschetta** [comment]
Devemos implementar uma nova solução onde mostra todos os periódicos sem paginação 

> Conforme conversamos em reunião de `daily` achamos melhor que seja feito uma implementação onde independentemente do cliente (Browser ou Bot) seja mostrado sempre a mesma lista com todos os periódico, sem a paginação via `JS`

_Originally posted by @cesarbruschetta in https://github.com/scieloorg/opac/pull/1351#issuecomment-510471470_

**Comment by cesarbruschetta** [comment]
@carolinatanigushi, vc consegue validar esse TK no ambiente de homolog do opac? https://homolog.opac.scielo.br/

**Comment by gustavofonseca** [comment]
Ao acessar a lista alfabética e alternar entre periódicos descontinuados e ativos, a lista passou a ser produzida por javascript e scroll infinito. É para ser assim mesmo?

**Comment by gustavofonseca** [comment]
A equipe de Google Scholar me informou que mesmo depois das alterações a lista continua inacessível para o crawler. Eles nos indicaram o uso da ferramenta "fetch as Google" em webmaster tools (URL inspection tool: https://support.google.com/webmasters/answer/9012289) para que a gente "veja o que o crawler vê".

**Comment by gustavofonseca** [comment]
De acordo com a ferramenta do Google, o impedimento se dá por causa da configuração expressa no arquivo `robots.txt`.

**Comment by jamilatta** [comment]
@gustavofonseca 

Realizei uma verificação ferramenta de inspeção do Google e veja: 


![Screenshot 2019-10-04 14 29 47](https://user-images.githubusercontent.com/373745/66227477-9d0e3800-e6b3-11e9-80f0-dc9feb12dd41.png)


Verifique que no http://www.scielosp.org o arquivo de robots.txt está bloqueando tudo, veja: https://www.scielosp.org/robots.txt (Esta quase tudo comentado)

Irei colocar a mesma configuração do SciELO BR: http://www.scielo.br/robots.txt e na ferramenta do google irei solicitar a reindexação.

**Comment by jamilatta** [comment]
Redefinimos essa atividade, segue: 

Conforme conversa no slack iremos criar uma rota no NGINX para um arquivo na instância que estará com as configuração de **allow**. 

Dessa forma iremos manter o arquivo **robots.txt** no repositório como **disallow** e para a instância do SciELO Saúde Pública iremos criar uma rota para um arquivo no **volume** com **allow**. 

Veja conversa no Slack: 

![Screenshot 2019-10-14 08 25 52](https://user-images.githubusercontent.com/373745/66748179-eb15ff00-ee5c-11e9-95f1-750a375c9853.png)

**Comment by jamilatta** [comment]
@gustavofonseca @paratiuid @robertatakenaka @joffilyfe 

Não sei se @patymori verificou previamente como está sendo entregue o arquivo **robots.txt**. Me refiro ao questionamento: 

É o NGINX ou a aplicação que está configurada para responder por  https://scielosp.org/robots.txt?

Solicitei para a infra estrutura o arquivo do NGINX e verifiquei que no arquivo não consta qualquer rota para robots.txt. 

Pesquisando no github da aplicação encontrei a seguinte rota: https://github.com/scieloorg/opac/blob/55bf5a97846aa6415fdd41d26472110c91fde753/opac/webapp/main/views.py#L1248

Portanto é possível termos uma variável do arquivo de configuração(com a opção de uma variável de ambiente) da aplicação que defini o caminho do arquivo **robots.txt**, deixando esse arquivo configurável. 

🚀

**Comment by gustavofonseca** [comment]
> Portanto é possível termos uma variável do arquivo de configuração(com a opção de uma variável de ambiente) da aplicação que defini o caminho do arquivo **robots.txt**, deixando esse arquivo configurável.

Mas então a aplicação contaria com alguma variedade de *robots.txt* para que o operador possa escolher? Se sim, essa opção torna a aplicação mais complexa, com mais código, e não mais flexível pois estaria limitada às variações de *robots.txt* disponíveis. 

Penso que a solução mais simples é usar mesmo uma regra no próprio NGINX para sobrescrever o *robots.txt* padrão.

**Comment by jamilatta** [comment]
@gustavofonseca 

Ok irei coordenar isso junto com a infra.
