### ISSUE TITLE
[Documentos] Fazer download do PDF diretamente

### ISSUE THREAD

**Issue by cesarbruschetta** [scieloorg/opac#1325]
### Descrição da nova funcionalidade
Eu, como **usuário do site**, gostaria que ao **clicar no botão** de PDF fosse realizado o download direto do arquivo PDF (*relacionado com a versão em exibição*), assim eu terei uma melhor experiência ao utilizar esta funcionalidade em dispositivos móveis.

### Critérios de aceitação

Os seguintes critérios serão observados durante a análise da implementação:
- Ao clicar no botão de PDF deve-se abrir uma nova janela (`target='_blank'`)
- A janela aberta deve exibir o conteúdo de acordo com o exemplo: a url `https://opac.scielo.org/pdf/csc/2019.v24n5/1973-1973/pt` o conteúdo da url `https://opac.scielo.org/article/ssm/content/raw/?resource_ssm_path=/media/assets/csc/v24n5/1413-8123-csc-24-05-1973.pdf`
- A página atual deve ser removida da aplicação

### Anexos
https://github.com/scieloorg/opac/issues/1257#issuecomment-482242312
<img width="1212" alt="Captura de Tela 2019-06-03 às 11 17 00" src="https://user-images.githubusercontent.com/1105583/58808888-48698c00-85f1-11e9-8ba2-068dc9ba5bfa.png">

### Referências
#1257

**Comment by cesarbruschetta** [comment]
@alexxxmendonca @gustavofonseca @RPostalli, 

Essa funcionalidade esta em Homologação, vcs podem validar https://homolog.opac.scielo.br/article/rbti/2016.v28n3/213-214/pt/

**Comment by alexxxmendonca** [comment]
Tudo certo! Testei no mobile também.
