### ISSUE TITLE
Conteúdo da página das listagens.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#133]
### Problema: 

Em nossa primeira versão do site não fomos tão rigorosos com o conteúdo dinâmico para as páginas de listagens, considerando essa fato, existe diferenças entre o mockup e a versão atual do site.

### Objetivo: 

Observar e resolver todas as diferenças entre o mockup do design e a versão atual para todas as  listagens.

Imagens das páginas dessa tarefa: 

![alpha](https://cloud.githubusercontent.com/assets/373745/14251490/b2b47218-fa59-11e5-82b6-bc099b02b399.png)

![inst](https://cloud.githubusercontent.com/assets/373745/14251508/c4a68bf0-fa59-11e5-9a32-b7eafd353461.png)

![tematic](https://cloud.githubusercontent.com/assets/373745/14251515/d2c92e54-fa59-11e5-8b5d-ced1bf75c048.png)

**Comment by jamilatta** [comment]
Para hacer esa tarea es necesario la base de datos, entonces @jfunez te vá a enviar mañana los archivos por FTP.

**Comment by swarzesherz** [comment]
Enterado, estaré a la espera del la base de datos

**Comment by jamilatta** [comment]
Ok

Atenciosamente, 

Jamil Atta Junior

**Comment by jfunez** [comment]
@jamilatta conversando com @swarzesherz vimos que este issue esta muito relacionado com o #134 que estou fazendo, então fica complicado para mexer ao mesmo tempo sem ter resolvido o ajax e o JS das listagens. vamos deixar este issue em pausa, e voltamos depois de ter resolvido a lógica para mostrar as listagens.
