### ISSUE TITLE
Página inicial mostrando 0 periódicos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1331]
### Descrição
A página inicial do site está exibindo um total de 0 periódicos ativos.

### Passos para reproduzir o problema
1. Acesse a página new.scielo.br

### Comportamento esperado
Exibir o número correto de periódicos ativos, que em 11/06/2019 é de **296**.

### Screenshots ou vídeos
![image](https://user-images.githubusercontent.com/4059679/59275570-f2b96300-8c32-11e9-8644-7ce7e29c9dad.png)

**Comment by patymori** [comment]
@alexxxmendonca, vamos alterar o site para exibir o número de periódicos, fascículos e artigos disponível no site, OK?

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , esse ticket ja esta no ambiente de homologação (https://homolog.opac.scielo.br/), vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta está ok, apesar do número real ser 296, mas creio que isso é um outro problema.

**Comment by patymori** [comment]
> @cesarbruschetta está ok, apesar do número real ser 296, mas creio que isso é um outro problema.
@alexxxmendonca, a versão da aplicação não tinha sido atualizada corretamente. Poderia validar novamente?

**Comment by alexxxmendonca** [comment]
@patymori agora sim! Testado e aprovado em homologação.
