### ISSUE TITLE
[HOMOLOGAÇÃO] Links para acesso aos documentos em caixa baixa

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1333]
### Descrição do problema
A atualização do ambiente de homologação ocorrida em 10/06/2019 deixou os links para acesso aos documentos em caixa baixa. 

### Passos para reproduzir o problema
1. Acessar qualquer sumário, de qualquer número, de qualquer periódico, em ambiente de **homologação**.

### Comportamento esperado
Os links devem estar em caixa alta.

### Screenshots ou vídeos
![image](https://user-images.githubusercontent.com/4059679/59276147-20eb7280-8c34-11e9-8112-b8f1b6c7471b.png)

**Comment by paratiuid** [comment]
@cesarbruschetta , @alexxxmendonca 

verifiquei os arquivos .less que correspondem a renderização desta página e não encontrei erro algum.

Fiz um teste de apenas regerar os bundles css e atualizar a página direto no navegador.

Após regerar os bundles, o texto mencionado aparece em caixa alta.

Acredito que tenha faltado fazer o upload dos bundles css na homologação.

Vejam os prints abaixo:

![img-uppercase](https://user-images.githubusercontent.com/22373640/60619482-2eb59300-9daf-11e9-9210-fc5000a808fd.jpg)

<img width="516" alt="Screen Shot 2019-07-03 at 4 23 07 PM" src="https://user-images.githubusercontent.com/22373640/60619494-36753780-9daf-11e9-92d9-cd7eaa4b62c5.png">

**Comment by cesarbruschetta** [comment]
A incorporação do PR #1356 e do TK #881 resolvera esse problema
