### ISSUE TITLE
Busca nas páginas de listagens 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#134]
### Problema: 

Nas listagens existe uma área para realizar pesquisa e atualmente é fake não funciona.

### Objetivo: 

Devemos pensar que tecnologia iremos aplicar para resolver essa pesquisa e essa solução deve ser aplicada para todas as listagem se for possível.

**Comment by jfunez** [comment]
Como conversamos, nesta primeira fase, vamos manter o código js do frontend e respeitar o formato de retorno (json) para que a lógica no frontend continue resolvendo as mudanças no DOM.
Então nesta tarefa, vamos fazer uma view que retorna json no mesmo formato e faz as mesmas filtragens que a solução do mockup

**Comment by jamilatta** [comment]
:+1:
