### ISSUE TITLE
Fascículo na coleção BR está inacessível

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1342]
### Descrição do problema
Não é possível acessar o conteúdo do fascículo volume `jubilee` de 2001 de periódico na URL: https://new.scielo.br/grid/babt/

### Passos para reproduzir o problema
1. Acesse o link: https://new.scielo.br/grid/babt/
2. Role a página até encontrar o volume `jubilee` de 2001.
3. Clique no número e veja o erro, como no screenshot em anexo

### Comportamento esperado
O conteúdo do fascículo deveria estar acessível, assim como no site clássico: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1516-891320010005&lng=en&nrm=iso

### Screenshots ou vídeos
![Screen Shot 2019-06-17 at 18 44 04](https://user-images.githubusercontent.com/18053487/59638897-fca9fd00-912f-11e9-97ac-3321aa1eeacd.png)

![Screen Shot 2019-06-17 at 18 44 20](https://user-images.githubusercontent.com/18053487/59638903-ff0c5700-912f-11e9-9b42-6aa169e66ff0.png)

### Anexos
N/A.

### Ambiente utilizado
https://new.scielo.br

**Comment by patymori** [comment]
Outro caso: https://new.scielo.br/toc/mioc/1955.v53n2-3-4/

**Comment by patymori** [comment]
O problema do volume alphanumérico ocorre por conta de um problema no Legendarium. Ticket para correção: scieloorg/legendarium/issues/170

**Comment by cesarbruschetta** [comment]
@alexxxmendonca Essa funcionalidade ja esta no ambiente de [homologação](https://homolog.opac.scielo.br/), vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta eu testei isso em produção, inclusive, e não identifiquei o problema. Deveria estar em produção, se estamos falando de homologação?

Talvez a @patymori possa testar melhor?
