### ISSUE TITLE
Desacoplar bootstrap do Opac

### ISSUE THREAD

**Issue by paratiuid** [scieloorg/opac#1343]
### Descrição da tarefa
Devem ser verificados arquivos js e css que sobrescrevem arquivos nativos do bootstrap a fim de mante-los distintos. Dessa maneira será possível atualização da biblioteca de maneira independente do sistema.

### Subtarefas

- [x] Verificação de css
- [x] Verificação de js

**Comment by cesarbruschetta** [comment]
@carolinatanigushi, vc consegue validar esse TK no ambiente de homolog do opac? https://homolog.opac.scielo.br/

**Comment by carolinatanigushi** [comment]
@cesarbruschetta existe uma forma de testar isso pela interface do usuário?

**Comment by cesarbruschetta** [comment]
@carolinatanigushi , Essa é uma alteração mais tecnica, mas gostaria que se foce possível voce desse uma olhada se houve alguma reverso no ponto de vista de layout, a nossa equipe ja vez essa avaliação e não entrou nenhum problema, mas sempre é melhor uma segunda opinião 😃

**Comment by carolinatanigushi** [comment]
@cesarbruschetta dei uma olhada e aparentemente está tudo no lugar :)
