### ISSUE TITLE
Analisar, planejar e desacoplar o Bootstrap 3.x

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac#1344]
### Descrição da tarefa
A aplicação atualmente possui um acoplamento muito forte com uma versão específica do Bootstrap onde até mesmo alterações em seu código fonte foram feitas. Esta atividade objetiva remover o versionamento do código fonte da biblioteca.

### Subtarefas

- [ ] Analisar possibilidade de desacoplamento
- [ ] Planejar método de migração
- [ ] Desacoplar código

## Considerações e notas
N/A

**Comment by paratiuid** [comment]
Este ticket está duplicado.
Já havia sido criado um ticket para este fim.

Ticket correspondente:
https://github.com/scieloorg/opac/issues/1343
