### ISSUE TITLE
Lista de periódicos amigável para SEO (html estático)

### ISSUE THREAD

**Issue by paratiuid** [scieloorg/opac#1346]
### Descrição do problema
Tornar a lista de periódicos do Opac estática a fim de melhorar o SEO

### Passos para reproduzir o problema
Acesse a lista de periódicos do Opac

### Comportamento esperado
HTML estático e / ou amigável com SEO

**Comment by cesarbruschetta** [comment]
Ticket duplicado, sera resolvido pelo tk #1323
