### ISSUE TITLE
Perguntas sobre o desenvolvimento do projeto

### ISSUE THREAD

**Issue by glauberm** [scieloorg/opac#1347]
Olá,

Como trabalho de conclusão de curso estou desenvolvendo um classificador de periódicos aberto. Ainda estamos na fase inicial do [projeto](https://github.com/glauberm/open_journals_classifier), que por enquanto só coleta informações do DOAJ, e a próxima etapa é justamente buscar mais fontes de dados.

Uma ótima fonte de dados é, claro, a SciELO. Por isso gostaria de fazer duas perguntas em relação ao desenvolvimento deste projeto: existem planos para a criação de uma API pública? E PRs meus que estendam a funcionalidade do aplicativo web (por exemplo, adicionando os campos `print_issn` e `electronic_issn` ao .CSV exportado) seriam aceitos?

**Comment by gustavofonseca** [comment]
Olá @glauberm, você gostaria de obter quais dados exatamente a partir desta API pública? Qual aplicativo web você se refere em relação ao `print_issn` e `electronic_issn`?

Abraço!

**Comment by glauberm** [comment]
Olá, @gustavofonseca. O aplicativo web ao qual me refiro é o [scielo.org](https://scielo.org/en/journals/list-by-alphabetical-order), que foi o único onde encontrei alguma funcionalidade de [exportar](https://scielo.org/en/journals/list-by-alphabetical-order/?export=csv) os periódicos da SciELO.

De uma API pública, idealmente, eu gostaria de obter todos os dados declarados [neste modelo](https://github.com/scieloorg/opac_schema/blob/master/opac_schema/v1/models.py#L313), mas os campos [desta versão descrita neste script](https://github.com/scieloorg/journals-list/blob/master/journals-list.py#L70) também seriam suficientes. No mínimo, o `print_issn` e o `electronic_issn`, para que eu possa buscar os periódicos da SciELO em outras bases (DOAJ, Scopus) e agrupar informações. Pelo CSV exportado através do scielo.org eu só posso realizar essa busca pelo título, o que não é confiável.

Qualquer ajuda que você possa me oferecer para obter esses dados (inclusive outros métodos de exportá-los além de através do scielo.org) é bem-vinda. Obrigado desde já!

**Comment by gustavofonseca** [comment]
@glauberm, entendi. Você poderia verificar se os conteúdos de https://static.scielo.org/tabs/tabs_network.zip possuem o que você deseja?

**Comment by glauberm** [comment]
Isso é perfeito, @gustavofonseca, muito obrigado! Gostaria de extrair esses dados de maneira programática, você saberia me informar alguma estimativa do intervalo de atualização desses arquivos?

**Comment by gustavofonseca** [comment]
Os arquivos são atualizados mensalmente, por volta do dia 10.

-Gustavo

Em Seg 1 jul. 2019, às 07:51, Glauber Mota escreveu:

**Comment by glauberm** [comment]
Muitíssimo obrigado, @gustavofonseca!
