### ISSUE TITLE
Avaliar e discutir o endereço no rodapé da página inicial do periódico. 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#135]
### Problema: 

Atualmente não sabemos de onde será retirado o conteúdo do endereço da revista na página inicial do periódico.

### Objetivo: 

Discutir e definir de onde e como será resgatado esse endereço ficará no manager no opac??? necessário conversamos e definirmos.

Imagem da página para essa atividade: 

![home_journal](https://cloud.githubusercontent.com/assets/373745/14251926/817af8fa-fa5b-11e5-8708-bf39d4af4c81.png)

**Comment by scielo** [comment]
Acho que esse dado fica no Manager. Esse dado já existe.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-04-04 11:50 GMT-03:00 Jamil Atta Junior <notifications@github.com>:

**Comment by jamilatta** [comment]
Reparemos no SciELO manager que estes dados são os dados da seção **Editor** no formulário de cadastro.

Exemplo Revista de Salud Pública: 

No manager: http://manager.scielo.org/journal/42/edit/
No site: http://www.scielosp.org/scielo.php?script=sci_serial&pid=0124-0064&lng=en&nrm=iso
