### ISSUE TITLE
"Revista da Sociedade Brasileira de Medicina Tropical" sem área cadastrada

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1354]
### Descrição do problema
O periódico "Revista da Sociedade Brasileira de Medicina Tropical" está sem área do conhecimento. Na lista de áreas (https://new.scielo.br/journals/#theme) o periódico sequer aparece.

### Passos para reproduzir o problema
1. Acesse a página https://new.scielo.br/journal/rsbmt/
2. Veja no cabeçalho "Área: None"

### Comportamento esperado
Exibir a(s) área(s) do periódico.

### Screenshots ou vídeos
![image](https://user-images.githubusercontent.com/4059679/60587948-20925300-9d6c-11e9-9113-36b696221966.png)

**Comment by jamilatta** [comment]
@joffilyfe @robertatakenaka @paratiuid @gustavofonseca 

Essa problema é consequência do seguinte erro no processamento: https://github.com/scieloorg/opac_proc/issues/523

**Comment by alexxxmendonca** [comment]
ticket relacionado: #1246

**Comment by alexxxmendonca** [comment]
Resolvido: 
![image](https://user-images.githubusercontent.com/4059679/116887956-46efd680-ac01-11eb-83e0-b199a4947c26.png)
