### ISSUE TITLE
Rede sociais no página inicial do periódico.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#136]
### Problema: 

Na versão atual do site os links para as rede sociais são estáticos. 

### Objetivo: 

Deixar esse conteúdo dinâmico considerando que os dados para esse item seja retirado do campo redes sociais contidas no modelo do periódico provindas do S.M. 

### Importante: 

As imagens das redes sociais precisam ser atualizadas com o mockup, ver: 

![home_journal](https://cloud.githubusercontent.com/assets/373745/14252068/1be55296-fa5c-11e5-9648-479dec7715e0.png)

**Comment by jamilatta** [comment]
Iremos remover temporariamente da interface, até que tenhamos como recuperar os dados do manager

Ver issue: https://github.com/scieloorg/scielo-manager/issues/1299

**Comment by jfunez** [comment]
segue em #254
