### ISSUE TITLE
Interface responsiva para Artigo (versão 2)

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1361]
### Descrição da nova funcionalidade
Eu, como **leitor de artigo em dispositivos móveis**, gostaria que **a experiência de leitura de artigos fosse a mais agradável possível**, então **alguns pontos da interface responsiva precisam ser melhorados**.

### Critérios de aceitação

Resolver os pontos levantados pelo @joffilyfe no PR de aceitação da interface responsiva. (https://github.com/scieloorg/opac/pull/1252#pullrequestreview-247232192)

**Comment by alexxxmendonca** [comment]
Uma outra questão: o título do artigo está muito grande. Diminuir um pouco o tamanho da fonte, de modo a mostrar um pouco mais dos outros elementos do artigo sem a necessidade de rolar a tela.

**Comment by cesarbruschetta** [comment]
@carolinatanigushi, vc consegue validar esse TK no ambiente de homolog do opac? https://homolog.opac.scielo.br/

**Comment by carolinatanigushi** [comment]
@cesarbruschetta todas as questões que o @joffilyfe levantou parecem estar resolvidas, mas reparei um problema na exibição de equações no iphone, abro um ticket novo para isso?

**Comment by joffilyfe** [comment]
> @cesarbruschetta todas as questões que o @joffilyfe levantou parecem estar resolvidas, mas reparei um problema na exibição de equações no iphone, abro um ticket novo para isso?

Esses problemas existem em produção?

**Comment by carolinatanigushi** [comment]
@joffilyfe dei uma olhada agora e só está acontecendo no homolog.
