### ISSUE TITLE
Exibir o Visual Abstract na página do artigo

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1363]
### Descrição da nova funcionalidade
Eu, como **Editor**, gostaria que **o visual abstract, presente no artigo, seja exibido na página do artigo**, então **teremos o visual abstract publicado**.
Esta é parte da implementação referente ao ticket #1005.

### Critérios de aceitação
* Não deve ser exibido como tumbnail, como o restante das imagens

### Anexos
N/A.

**Comment by cesarbruschetta** [comment]
### Relacioados
#1398 
#1399

**Comment by cesarbruschetta** [comment]
> PID S0101-28002019000100014

@alexxxmendonca  essa funcionalidade ja esta em homologação, vc pode validar?
https://homolog.opac.scielo.br/article/jbn/2019.v41n1/14-21/

**Comment by alexxxmendonca** [comment]
@cesarbruschetta remover o título que aparece antes do visual abstract:

![image](https://user-images.githubusercontent.com/4059679/63175124-ba127d00-c019-11e9-8c5a-231e6f83565c.png)

**Comment by jamilatta** [comment]
@alexxxmendonca 

Em conversa com a equipe entendemos que esse texto é conteúdo e que não podemos remover! 

Reparem que esse texto é proveniente do XML no seguinte trecho: 

```xml
        <abstract abstract-type="graphical">
            <title>qualquer coisa</title>
            <p>
                <fig id="vf01">
                    <caption>
                        <title>Texto em inglês<italic>propensity-score
                            matching</italic></title>
                    </caption>
                    <graphic xlink:href="2175-8239-jbn-2018-0058-vf01.jpg"/>
                </fig>
            </p>
        </abstract>
```

Imaginamos que se é um conteúdo que não deva ser exibido, sugerimos e concordamos que deve ser removido do XML.

@solange-scielo @RPostalli o que acham?

**Comment by RPostalli** [comment]
Para mim o title de fig deve ser opcional (assim como é na JATS) se tiver mostrar caso contrário ignorar.

Como estávamos discutindo no email, não sei como a equipe de tecnologia vai trabalhar para este tipo de documento ser pesquisável.

**Comment by jamilatta** [comment]
Conversando com a equipe iremos seguir com a seguinte estratégia para essa atividade: 

* Iremos, por hora, apresentar somente a imagem do visual abstract
* Iremos manter tanto o caption quando o title da imagem no XML
* Sobre a indexação irei abrir um ticket no http://search.scielo.org

**Comment by patymori** [comment]
Em reunião de GT, foi decidido que o título deve ser mantido no conteúdo da página do artigo.
