### ISSUE TITLE
Banner da política de cookies

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1365]
Um banner geralmente exibido no cabeçalho ou rodapé de todas as páginas do site, que contém um texto informativo e um botão para que o aceite do usuário.

### Descrição da nova funcionalidade

* Eu, como administrador, quero habilitar a exibição do banner da política de cookies para que meu site se torne conforme às leis de proteção de dados dos usuários (GDPR e LGDP).
* Eu, como adminsitrador, quero desabilitar a exibição do banner da política de cookies para que meu site apresente um interface mais limpa caso as leis vigentes em meu país não exijam o banner e o consentimento dos usuários para a coleta dos seus dados pessoais.
* Eu, como administrador, quero definir o texto informativo do banner para comunicar ao usuário o consentimento que está sendo solicitado.
* Eu, como administrador, quero redefinir o texto informativo do banner para comunicar ao usuário o consentimento que está sendo solicitado.
* Eu, como administrador, quero inserir links no texto informativo do banner para que seja possível direcionar o usuário para páginas que possuam mais detalhamento acerca dos consentimentos solicitados.
* Eu, como administrador, quero alterar os links no texto informativo do banner para que seja possível corrigir links quebrados ou direcionar o usuário para páginas atualizadas que possuam mais detalhamento acerca dos consentimentos solicitados.
* Eu, como administrador, quero remover os links no texto informativo do banner para que seja possível ter uma mensagem mais enxuta caso seja permitido dentro da legislação vigente no país.
* Eu, como visitante, quero aceitar a política de cookies do site para que se torne explícito o meu consentimento acerca dos dados que estão sendo coletados durante a minha navegação no site.
* Eu, como visitante, quero clicar no link do banner para saber mais sobre a política de cookies do site antes de dar meu consentimento explícito.

### Critérios de aceitação

* Uma vez que o usuário aceitou a política, o banner não deverá mais aparecer em nenhuma página do site para aquele usuário.

### Anexos
*

### Referências
*

**Comment by jamilatta** [comment]
@paratiuid 

Poderia gerar um desenho para essa demanda, segue exemplos: https://www.cookielawinfo.com/gdpr-cookie-consent-website-examples/

**Comment by joffilyfe** [comment]
Como a abordagem inicial para o desenvolvimento desta atividade enveredou para a utilização de JS durante a inclusão do banner eu gostaria de sugerir um meio agnóstico ao tipo de aplicação que executará o script:

```html
<script src="//static.scielo.br/cookies/index.js?language=pt-br&version=1.0"></script>
```

```javascript
if (document.getElementById && document.getElementsByTagName && document.createElement) {
    if (!window.SciELOCookies) {
        window.SciELOCookies = {}
    }

    (function init(container) {
        const language = /language=([^&]+)/.exec(document.currentScript.src) ? 
            /language=([^&]+)/.exec(document.currentScript.src)[1] : navigator.language;

        
        // exporta idioma
        window.SciELOCookies.language = language;

        // exibe banner de acordo com o idioma
    })("SciELOCookies");
}
```

O script acima seleciona o idioma a partir de duas fontes:
1. A partir do parâmetro `language` na inserção do script no HTML
2. A partir do idioma do browser SE o idioma não for parametrizado a partir do `src` do `script`

follow @jamilatta @paratiuid @gustavofonseca @robertatakenaka @patymori

**Comment by jamilatta** [comment]
@paratiuid 

Conforme conversado segue os itens discutidos: 

* Permitir que o script faça a leitura de ```lang``` e ```language```
* Remover alguns console.log 
* Minificar 
* Permitir que a aplicação possa customizar a msg (melhoria futura )
* Prever o idioma portugues como pt ou pt_BR ou pt-BR (case insensitive)

Para avaliação do script verificar em: http://scielohomolog.parati.ag/cookiePolicy.js

**Comment by jamilatta** [comment]
@joffilyfe 

Se entendi, esse trecho garante que seja obtido o idioma do navegador, correto?

**Comment by jamilatta** [comment]
@jamilatta @paratiuid @gustavofonseca @robertatakenaka @patymori

Em reunião com o @joffilyfe e @paratiuid, entendemos que a abordagem sugerida pelo @joffilyfe é menos acoplada e consideramos que as duas são passíveis de implementação, portanto vamos manter as duas abordagem no **script** desenvolvido pela @paratiuid. 

Link para o script em fase de desenvolvimento: http://scielohomolog.parati.ag/cookiePolicy.js

**Comment by paratiuid** [comment]
Pessoal, 
segue o script para avaliação:

http://scielohomolog.parati.ag/cookiePolicy.js
http://scielohomolog.parati.ag/cookiePolicy.min.js

Alinhei agora com o Alex.
Ele solicitou incluir também a verificação do idioma no caso do site scielo.br, onde o parâmetro de idioma é o "lng". Foi adicionado.

Além disso, ele solicitou que em último caso, caso o script não encontre o idioma no itens abaixo:
- idioma na url
- idioma no parametro da chamada do script
- cookie language
- cookie lang
- idioma do navegador

O idioma deve se setado para inglês (en).

O ajuste já foi feito.

Efetuei os testes nos seguintes sistemas:
- org
- search
- opac

Aguardo comentários de vcs.


Outra coisa, se possível, mesclar esse ticket com o seguinte:
https://github.com/scieloorg/scielo.org/issues/136

Aguardo.

**Comment by joffilyfe** [comment]
@paratiuid @jamilatta  ainda não revisei todo o script mas ao utiliza-lo no OPAC sem o parâmetro de `language` eu obtive um comportamento não esperado, veja a screenshot [1], isso aconteceu porque a língua definida pelo meu browser é `en-us` (https://developer.chrome.com/webstore/i18n table ou https://tools.ietf.org/html/rfc5646).

Pra solucionar o problema apresentado pela screenshot [1] eu refatorei a função `createElementCookieBar`, vejam:

```javascript

    createElementCookieBar: function (lang) {
        var lang = (/^[\w_-]{2,5}$/.exec(lang) ? /[\w_-]{2,5}/.exec(lang)[0].toLowerCase().replace("_", "-") : undefined);
        
        if (lang == undefined) {
            console.group("SciELO Cookie Banner")
            console.error("Cannot detect the correct language to show the cookie banner. The selected code language does not exists, please verify https://developer.chrome.com/webstore/i18n table or https://tools.ietf.org/html/rfc5646 RFC.")
            console.log("Using English as fallback language.")
            console.groupEnd()
            lang = "en";
        }
        
        // Create container element
        var div = document.createElement('div');
        div.setAttribute('class', 'alert-cookie-notification');

        // Choose content by language
        if (lang.indexOf("pt") > -1) {
            div.innerHTML = cookiePolicy.msgPt;
        } else if (lang.indexOf("es") > -1) {
            div.innerHTML = cookiePolicy.msgEs;
        } else {
            div.innerHTML = cookiePolicy.msgEn;
        }
```
Dessa forma se a língua não for detectada de maneira alguma nós teremos sempre o banner em inglês. Um outro ganho dessa abordagem é que nós não precisamos nos preocupar com as inúmeras variações de localização (`en-gb`, `en-us`, `en-au`, `pt-pt`, `pt-br`, etc).

### Screenshot
![Screen Shot 2019-10-08 at 14 37 12](https://user-images.githubusercontent.com/4604104/66422567-4882f980-e9e0-11e9-9740-cc31942cbe81.png)

**Comment by paratiuid** [comment]
@joffilyfe @jamilatta 

Efetuei os ajustes e publiquei o script atualizado na mesma url.

Testei novamente nos seguintes sistemas:
- Org
- Opac
- Search-journals

Obtive sucesso em todos os testes.

**Comment by jamilatta** [comment]
@paratiuid @robertatakenaka @gustavofonseca @joffilyfe @patymori 

Os arquivos estão disponíveis nos seguintes endereços: 

https://static.scielo.org/js/cookiePolicy.js
https://static.scielo.org/js/cookiePolicy.min.js

**Comment by jamilatta** [comment]
Acredito que podemos fechar esse ticket e criarmos tickets de integração desse script para cada aplicação que irá utiliza-lo.

**Comment by jamilatta** [comment]
@gustavofonseca 

Não está versionado!, alias suspeito que todos os arquivo que estão no http://static.scielo.org não estão versionados

**Comment by jamilatta** [comment]
@gustavofonseca @joffilyfe @robertatakenaka @patymori 

Vou criar um repositório para armazenar os arquivos que estão contido no http://static.scielo.org. 

**Obs.:** Somente arquivo passíveis de serem exibidos em um repositório.

**Comment by jamilatta** [comment]
@gustavofonseca @joffilyfe @robertatakenaka @paratiuid 

Podemos fechar esse ticket?

**Comment by gustavofonseca** [comment]
> @gustavofonseca @joffilyfe @robertatakenaka @paratiuid
> 
> Podemos fechar esse ticket?

A solução ainda não foi homologada e finalizada, então não.

**Comment by gustavofonseca** [comment]
> @gustavofonseca @joffilyfe @robertatakenaka @patymori
> 
> Vou criar um repositório para armazenar os arquivos que estão contido no http://static.scielo.org.
> 
> **Obs.:** Somente arquivo passíveis de serem exibidos em um repositório.

Eu não consegui encontrar o repositório que você criou, @jamilatta. Poderia me passar o link, por gentileza?
