### ISSUE TITLE
Link RSS na página inicial do periódico.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#137]
### Problema: 

Definir e avaliar o que será o link de RSS na página inicial do periódico.

### Objetivo: 

No site atual o RSS na página do periódico é os últimos artigos, no novo site iremos manter isso se sim, realizar a tarefa de termos um RSS para os artigos.

Página referente a essa tarefa: 

![home_journal](https://cloud.githubusercontent.com/assets/373745/14252241/c35a4c48-fa5c-11e5-8927-886f35ff7493.png)

**Comment by jamilatta** [comment]
Nosotros podríamos hacer una reunión sobre la tarea antes de empezar. Te contactaremos por el chat(IRC).

**Comment by jfunez** [comment]
@swarzesherz ya incorporamos el código que resuelve las listas de periódicos, que es necesário para proseguir con la tarea. Fijate en las funciones nuevas funciones que hicimos en el controlers.py para obtener las listas de periódicos, tal vez te puedan auxiliar.

**Comment by swarzesherz** [comment]
@jamilatta @jfunez de acuerdo lo tomare muy en cuenta para comenzar con la tarea, gracias...

**Comment by jamilatta** [comment]
Tarea hecha [6b0cb18bea32cd9037b6a04bf5b6468ae6011e74].
