### ISSUE TITLE
Melhoria na legenda bibliográfica

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#138]
### Problema: 

A legenda bibliográfica não esta de acordo com os mockups do design

### Objetivo: 

Deixar a legenda bibliográfica de acordo com o desenho, ver: 

![home_journal](https://cloud.githubusercontent.com/assets/373745/14252320/215ca6f6-fa5d-11e5-90d3-de9a556efeeb.png)

**Comment by jamilatta** [comment]
Adicionar no modelo um Func/Prop que resolve todos os casos, este será o formato canônico para todo o site.

**Comment by jfunez** [comment]
impedido até definir uma legenda bibliográfica universal para os produtos SciELO (ver: https://github.com/scieloorg/search-journals/issues/203)

**Comment by jamilatta** [comment]
Feito!
