### ISSUE TITLE
[homolog - QA] <history> em <front-stub> não aparece

### ISSUE THREAD

**Issue by marinachagas** [scieloorg/opac#1393]
Temos um caso onde as datas de publicação online dos PDFs em português são diferentes das em inglês.

Quando é inserido ```<history>``` em ```<front-stub>``` as datas da tradução somem conforme a imagem abaixo. Entretanto na versão original são mantidas.

![image](https://user-images.githubusercontent.com/53793690/62573283-16340f00-b86c-11e9-8d6a-45ef5911519a.png)

Envio XML anexo para análise, e o link do artigo no site de Homologação QA.

[0034-7094-rba-69-03-0227.txt](https://github.com/scieloorg/opac/files/3473960/0034-7094-rba-69-03-0227.txt)

Link de homologação: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0034-70942019000300227&lng=en&nrm=iso&tlng=pt

**Comment by joffilyfe** [comment]
Pessoal eu estou com uma dúvida sobre este ticket. As informações são referentes ao site clássico mas o ticket foi aberto no repositório do OPAC.

Detectei que no conversão do XML para HTML os marcadores das datas de histórico somem [1]. Vocês acham que se trata de um outro problema e este ticket deveria ser movido para o repositório https://github.com/scieloorg/Web?

### Imagens

HTML gerado a partir do packtools `2.5.2rc20190820` [1]
<img width="782" alt="Screen Shot 2019-08-20 at 14 27 05" src="https://user-images.githubusercontent.com/4604104/63369644-ba32b580-c356-11e9-885c-ca12998b597f.png">

**Comment by cesarbruschetta** [comment]
@joffilyfe entao, existe o tk no repositorio WEB scieloorg/Web#691

mas esse é um bug do site velho tambem ou sera que é um bug so para o site novo?

**Comment by joffilyfe** [comment]
> mas esse é um bug do site velho tambem ou sera que é um bug so para o site novo?

Na tradução é possível detectar que os marcadores não são exibidos mas as datas são:
<img width="782" alt="Screen Shot 2019-08-20 at 14 27 05" src="https://user-images.githubusercontent.com/4604104/63371980-86a65a00-c35b-11e9-9006-6eab78f89730.png">


No artigo principal as datas e os marcadores são exibidos como deveria:
<img width="793" alt="Screen Shot 2019-08-20 at 15 00 55" src="https://user-images.githubusercontent.com/4604104/63371982-86a65a00-c35b-11e9-9f61-74e9f0c327d4.png">

@cesarbruschetta pelo que eu entendi no site clássico não é exibido nada para a tradução, nem data nem marcadores.

**Comment by patymori** [comment]
@Rpostalli e @marinachagas, vocês podem confirmar se no OPAC o que precisa é somente colocar os marcadores?
Obrigada

**Comment by joffilyfe** [comment]
Oi @marinachagas tudo bem? Eu fui designado a resolver o problema apontado por você, infelizmente eu não tenho um vasto conhecimento sobre os dados dos XML e nem sobre o que deve aparecer onde e quando no OPAC por isso eu preciso reunir o máximo de informações para corrigir os problemas e entregar valor aos nossos usuários.

As imagens anexadas ao ticket são referentes ao site clássico e o link também é direcionado ao site. Por gentileza você poderia atualizar a issue com capturas de tela do https://new.scielo.br/ apontando os locais em que os dados deveriam aparecer?

Desde já agradeço pela disponibilidade e  o empenho.

**Comment by marinachagas** [comment]
@Joffily, bom dia!

Estávamos nos baseando no site clássico, portanto houve divergência de informações. 
O new de fato considerou a data de publicação diferente, informação que o old não exibe. 
O que precisamos no OPAC agora são apenas os marcadores, conforme apontado pela @patymori.

Desculpe pela confusão.

**Comment by RPostalli** [comment]
@marinachagas por favor solicito que teste a correção do bug.

**Comment by marinachagas** [comment]
@RPostalli Teste feito. O bug foi corrigido.
