### ISSUE TITLE
Caixa amarela não aparece para Retratação

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1400]
Relação com ticket https://github.com/scieloorg/opac/issues/528

Foi corrigido a caixa amarela para Errata (ver ticket #528 para mais informações), mas não para retratação.

Deveria estar assim:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2236-89062018000300540&lang=pt
![image](https://user-images.githubusercontent.com/6084959/63095293-49982d00-bf41-11e9-8763-8a75c59ac23e.png)

Mas está desta forma:
https://new.scielo.br/scielo.php?script=sci_arttext&pid=S2236-89062018000300540&lang=pt
![image](https://user-images.githubusercontent.com/6084959/63095265-39804d80-bf41-11e9-8845-89a2c93dc4d1.png)

Por favor aplicar a mesma regra de interface de Errata para Retratação ([Total e Parcial](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/retratacao.html))

**Comment by RPostalli** [comment]
@joffilyfe o texto aplicado não confere com o definido no ticket: https://github.com/scieloorg/opac/issues/1406 por favor solicito verificar

**Comment by robertatakenaka** [comment]
@RPostalli : Eu que tinha pedido para ele mudar, porque ficou cacafônico:

- "retratação retrata"

@joffilyfe: o que ficou acordado entre Renata e Alex foi:
https://github.com/scieloorg/opac/issues/1406#issuecomment-524839144

**Comment by RPostalli** [comment]
@robertatakenaka neste caso mesmo cacafônico tem que constar o texto. Porque a retratação retrata mesmo, ela nao corrige (quem faz isso é a errata), não existe outro termo. Por favor peço que sigam os textos pré-definidos.

**Comment by joffilyfe** [comment]
@RPostalli uma atualização para esta issue foi implantada em homologação, você poderia por gentileza conferir o resultado?

**Comment by RPostalli** [comment]
@joffilyfe testado idiomas inglês e português OK.

Fui pesquisar uma Retratação em espanhol mas parece que achei outro bug. Nest retratação que tem os 3 idiomas:
http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1983-804220170050&lng=en&nrm=iso

No new.br só consta um:
https://homolog.opac.scielo.br/toc/bioet/2017.nahead/

**Comment by joffilyfe** [comment]
> @joffilyfe testado idiomas inglês e português OK.
> 
> Fui pesquisar uma Retratação em espanhol mas parece que achei outro bug. Nest retratação que tem os 3 idiomas:
> http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1983-804220170050&lng=en&nrm=iso
> 
> No new.br só consta um:
> https://homolog.opac.scielo.br/toc/bioet/2017.nahead/

Oi @RPostalli, na verdade não é um bug em si porque no ambiente de homologação nós não temos todos os dados mesmo, se você acessar o de produção (https://new.scielo.br/scielo.php?script=sci_issuetoc&pid=1983-804220170050&lng=en&nrm=iso) vai poder ver os três idiomas normalmente.

**Comment by RPostalli** [comment]
@joffilyfe então beleza, aplica em produção que eu testo a caixinha na versão espanhol, se tiver tudo ok, o ticket foi finalizado. Obrigada.

**Comment by joffilyfe** [comment]
@RPostalli tentei uma solução alternativa e atualizei o registro do artigo `S1983-80422017005001000` em homologação para exibir os idiomas.

**Comment by RPostalli** [comment]
@joffilyfe testado nos 3 idiomas. Tudo OK.

**Comment by joffilyfe** [comment]
Agradecido @RPostalli e desculpe qualquer inconveniente.
