### ISSUE TITLE
Legenda Bibliográfica de artigos de 2013 para baixo não aparecem na página do artigo e o como citar não funciona

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1401]
Legenda Bibliográfica de artigos dos anos de 2013 para baixo não aparecem no cabeçalho na página dos artigos, tanto do scielosp quando do new.br. Possivelmente tratam-se de artigos HTML (legado)

Exemplo em [new br](https://new.scielo.br/article/csc/2013.v18n1/17-23/es/) 
![image](https://user-images.githubusercontent.com/6084959/63288194-81310d00-c292-11e9-8b15-da4bbe0b4908.png)

Exemplo [em SciELOSP](https://www.scielosp.org/article/csc/2013.v18n3/585-593/pt/)
![image](https://user-images.githubusercontent.com/6084959/63288286-b0477e80-c292-11e9-915e-59e9594727c0.png)

[Deveria ser](https://www.scielosp.org/article/csc/2019.v24n1/7-16/pt/): 
![image](https://user-images.githubusercontent.com/6084959/63288380-eab11b80-c292-11e9-92ab-2b8ea9dd5b5a.png)

Assim como ocorre na[ interface vintage](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-21002019000200147&lng=pt&nrm=iso&tlng=pt)
![image](https://user-images.githubusercontent.com/6084959/63288440-192ef680-c293-11e9-95dd-b4033ae78da7.png)

Reunião 23/08/2019

A legenda bibliográfica tem que aparecer visualmente na página do artigo (parte superior)
O como citar do artigo deve estar funcional (não funciona hoje)

**Comment by patymori** [comment]
@RPostalli e @alexxxmendonca
Acham que uma dessas opções atende? Segue exemplo:

`Revista Mal-Estar Subjetivo, 2011, Volume: 67, Number: 9, Supplement: 3`
ou
`2011, Volume: 67, Number: 9, Supplement: 3`

**Comment by alexxxmendonca** [comment]
@patymori a primeira opção é mais completa, leva o título do periódico.

**Comment by RPostalli** [comment]
@alexxxmendonca lembro que no site antigo essa legenda foi tópico de bastante discussão, tanto que é usado o título abreviado da revista não o título completo. No final foi o Abel que aprovou senão me falhe a memória.

@patymori Eu também prefiro a versão mais completa.

**Comment by alexxxmendonca** [comment]
Deve ser o mais próximo possível -- na verdade deveria ser IGUAL -- à legenda dos artigos posteriores a 2013.

**Comment by RPostalli** [comment]
Se for igual, então a legende deve conter:
1. Título abreviado do periódico
2. Volume
3. Número / Número especial
4. Suplemento
5. Cidade de publicação
6. Data do fascículo
7. Data completa de publicação

![image](https://user-images.githubusercontent.com/6084959/64129106-71382380-cd90-11e9-8fae-43cee9e9b6f5.png)

O item 7 no novo layout do artigo, já encontra-se no [rodapé da página](https://new.scielo.br/scielo.php?script=sci_arttext&pid=S0100-879X2019000200603&lng=en&nrm=iso&tlng=en)

![image](https://user-images.githubusercontent.com/6084959/64129152-c1af8100-cd90-11e9-9d3d-3ee0ae8330da.png)

Ai fica a critério de vocês repetir ou não a informação na legenda bibliográfica.

**Comment by alexxxmendonca** [comment]
@RPostalli refiro-me igual à legenda bibliográfica do novo site.

Se for reformular, isso deve ser tratado em outro ticket.

**Comment by RPostalli** [comment]
Entendi, são basicamente os mesmos itens também, com algumas diferenças.

![image](https://user-images.githubusercontent.com/6084959/64129252-819cce00-cd91-11e9-8094-bad789adef31.png)

1. Seção do documento
2. Título abreviado
3. Volume
4. Número / Número Especial
5. Data de publicação (repete mesmo aqui e no rodapé)
6. data do fascículo
7. DOI

Fica tudo na mesma linha.

**Comment by patymori** [comment]
@alexxxmendonca,

Conversando com @robertatakenaka, o "Como Citar" do site novo foi todo baseado no XML. Sei que o site deveria oferecer as mesmas funcionalidades do site antigo mas a plataforma nova fará a portabilidade dos artigos estáticos para XML e tudo funcionaria. É possível segurar esse ticket para que ele seja resolvido com a nova plataforma?

**Comment by RPostalli** [comment]
@patymori como citar ou legenda bibliográfica? O como citar estamos discutindo neste ticket https://github.com/scieloorg/opac/issues/1412

**Comment by patymori** [comment]
> @patymori como citar ou legenda bibliográfica? O como citar estamos discutindo neste ticket #1412

@RPostalli era específicamente sobre o "Como Citar" mas resolve ambos. Claro que poderíamos trabalhar somente com a legenda bibliográfica, caso não possa esperar.

**Comment by joffilyfe** [comment]
Issue #999 relacionado.

**Comment by gustavofonseca** [comment]
Pessoal, 

Entendemos que trata-se de um problema sério mas que não compromete a operação e disponibilização dos conteúdos. Desta forma, depois de uma breve análise, @patymori  e eu pensamos que a melhor opção é resolvermos ambos os problemas por meio da migração dos dados ao invés de partir para uma solução paliativa.

A migração dos dados ocorrerá dentro de pouco tempo -- estimamos até dezembro para a coleção Brasil, algo perto disso para SP.
