### ISSUE TITLE
Criar caixa amarela de errata/retratação no(s) artigo(s) com erro/retratado

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1406]
Atualmente a caixa amarela (gerada pelo related-article) da Errata/Retratação só aparecem na página da própria errata/retratação (relação com ticket https://github.com/scieloorg/opac/issues/528), mas não aparecem nos artigos corrigidos/retratados.

A informação da correão/retratação nestes documentos só aparecem como nota ao final dos dos documentos, o que faz com que os leitores só saibam que o artigo foi corrigido/retratado quando finaliza a leitura do documento.

Em reunião GT-Sites 23/08 foi decidido que seria importante ter a mesma funcionalidade da caixa amarela nos artigos que estão sendo corrigidos/retratados.

Exemplo (site clássico) da caixa na [errata](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572016000100106&lng=en&nrm=iso&tlng=en).
![image](https://user-images.githubusercontent.com/6084959/63619033-ffa7ea80-c5c3-11e9-9e72-7518a82c5281.png)

Exemplo (site new) da caixa na [errata](https://new.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572016000100106&lng=en&nrm=iso&tlng=en)
![image](https://user-images.githubusercontent.com/6084959/63619109-27974e00-c5c4-11e9-89fa-37cd02b3843b.png)

Exemplo da informação (site clássico) no [artigo corrigido](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572014000500434&lng=en&nrm=iso&tlng=en).
![image](https://user-images.githubusercontent.com/6084959/63619203-5ad9dd00-c5c4-11e9-8b10-15c29fa37047.png)

Exemplo da informação (site new) no [artigo corrigido](https://new.scielo.br/scielo.php?script=sci_arttext&pid=S1413-24782019000100217&tlng=pt).
![image](https://user-images.githubusercontent.com/6084959/63619588-72659580-c5c5-11e9-9f34-5b30e048e17c.png)

OBSERVAÇÃO: Em retratação a caixa não aparece devido um [bug] relato no ticket: https://github.com/scieloorg/opac/issues/1400 Para criar a caixa no artigo retratado será necessário primeiro corrigir o ticket 1400

**Informações Extras**

- A caixa amarela da errata/retratação é gerada pela marcação da tag related-article. Mais informações consultar SPS [`<related-article>`](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-related-article.html)

- Recomendo consulta no SPS na seção Tipos Especiais de Documentos: [Errata](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/errata.html) e [Retratação](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/retratacao.html)

- Uma errata pode ter mais de uma tag de `<related-article>`. Exemplo [site clássico](https://new.scielo.br/scielo.php?script=sci_arttext&pid=S0103-50532017005000100&lng=en&nrm=iso&tlng=en) e [site new](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-50532017005000100&lng=en&nrm=iso&tlng=en)

MAIS EXEMPLOS:

- Exemplos de erratas

Publicação Regular

JBCHS 1 errata para 4 artigos: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-50532017005000100&lng=en&nrm=iso&tlng=en

ABC 1 errata para 2 artigos: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2019000700182&lng=en&nrm=iso&tlng=en

RAMB 1 errata para um artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-42302019000701032&lng=en&nrm=iso&tlng=en

Publicação Contínua PC

JAOS 1 errata para 1 artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572016000100106&lng=en&nrm=iso&tlng=en

RLAE 1 errata para 6 artigos: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692016000100900&lng=en&nrm=iso&tlng=en

RBEDU 1 errata para um artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1413-24782019000101001&lng=en&nrm=iso&tlng=pt

EDUR 1 errata para um artigo:: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-46982019000100901&lng=en&nrm=iso&tlng=pt

-Exemplos Retratação Total

HOEHNEA: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2236-89062018000300540&lang=pt

ABCD: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-67202018000301000&lang=pt

RLPF:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47142017000400776&lang=pt

CM: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2236-99962018000200599&lang=pt

- Exemplos Retratação Parcial

AEM: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2359-39972016000200186&lng=en&nrm=iso&tlng=pt

AG: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0004-28032019000100110&lng=en&nrm=iso&tlng=pt

**Comment by alexxxmendonca** [comment]
Necessário definir qual seria o texto que deve aparecer na caixa, nos 3 idiomas.

Exemplo: "Esse documento possui uma errata: [link da errata]" (sugestão)

**Comment by RPostalli** [comment]
Gostei da sua sugestão. Só mudaria documento para artigo para seguir o texto que já está na errata. Exemplo: This corrects the **article**: 10.1590/1806-9282.65.4.568

Ficaria:

PT:
"Este artigo possui uma errata: [link da errata]"
EN:
"This article has an erratum: [link da errata]"
ES:
"Este artículo tiene una errata: [link da errata]"

**Comment by alexxxmendonca** [comment]
@RPostalli eu pensei em "artigo" inicialmente, mas daí lembrei que nem tudo que é publicado no SciELO é um artigo.

Existe a possibilidade de uma Errata corrigir algum documento que não seja um artigo?

**Comment by RPostalli** [comment]
@alexxxmendonca existe sim, uma errata pode corrigir qualquer tipo de documento, inclusive a própria errata. Estamos com um caso desse agora onde será publicado a errata da errata 🙈.

Mas eu acho que neste caso o artigo fica como um termo meio genérico. Não vejo muito problema em mantermos o termo artigo, mas se preferir alteramos para documento. Neste caso teria que corrigir o texto da caixinha da errata também. O que acha?

**Comment by alexxxmendonca** [comment]
@RPostalli acho que faz mais sentido usarmos "documento", então.

**Comment by RPostalli** [comment]
Combinado então. Ficaria

PARA ARTIGO CORRIGIDO:
PT:
Este documento possui uma errata: [link DOI da errata]
EN:
This document has an erratum: [link DOI da errata]
ES:
Este documento tiene una errata: [link DOI da errata]

PARA A ERRATA:
PT:
Esta errata corrige o documento: [link DOI do artigo]
EN:
This erratum corrects the document: [link DOI do artigo]
ES:
Esta errata corrige el documento: [link DOI do artigo]

PARA ARTIGO RETRATADO
PT:
Este documento possui uma retratação: [link DOI da retratação]
EN:
This document has a retraction: [link DOI da retratação]
ES:
Este documento tiene una retractación: [link DOI da retratação]

PARA RETRATAÇÃO ???????
PT:
Esta retratação retrata o documento: [link DOI do artigo]
EN:

ES:

Seria isso?

**Comment by alexxxmendonca** [comment]
@RPostalli acho que seria isso sim.

PARA RETRATAÇÃO
PT:
Esta retratação retrata o documento: [link DOI do artigo]
EN:
This retraction retracts the following document: [link DOI do artigo]
ES:
Esta retracción retrata el documento: [link DOI do artigo]

**Comment by RPostalli** [comment]
👏

**Comment by RPostalli** [comment]
Para documentar. 
Textos para documento do tipo Adendo (xml-type="addendum" + related-article-type="addendum")

ADENDO

PT:
Este adendo adiciona informação ao documento: [link DOI do artigo]
EN:
This addendum adds information to the following document: [link DOI do artigo]
ES:
Esta addenda agrega información al documento: [link DOI do artigo]

ARTIGO COM ADENDO

PT:
Este documento possui um adendo: [link DOI do adendo]
EN:
This document has an addendum: [link DOI do adendo]
ES:
Este documento tiene una addenda: [link DOI do adendo]

Guia de adendo publicado em scielo.org em 09/06/2021

**Comment by gitnnolabs** [comment]
@RPostalli 

Teria, por gentileza, um XML de exemplo que seja um **Adendo**?

**Comment by RPostalli** [comment]
> @RPostalli
> 
> Teria, por gentileza, um XML de exemplo que seja um **Adendo**? Ou um link para um artigo no site do SciELO.

Não, ainda não temos nenhum com o modelo novo. O guia de Adendo e as definições de publicação deste tipo de documento foram divulgadas em maio deste ano: [Guia para a publicação de Adendo](https://wp.scielo.org/wp-content/uploads/guia_adendo.pdf). Por favor veja neste Guia o item: 3.2. XML do Adendo e o item 3.4. XML do artigo. Qualquer dúvida fico à disposição.

**Comment by jamilatta** [comment]
@RPostalli @robertatakenaka 

Em reunião com a @RPostalli entendemos que esse tíquete se divide em 4 outras: 


1. Para um artigo que contém uma errata não existe o link no artigo para a errata.

> JBCHS 1 errata para 4 artigos: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-50532017005000100&lng=en&nrm=iso&tlng=en
> 
> ABC 1 errata para 2 artigos: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2019000700182&lng=en&nrm=iso&tlng=en
> 
> RAMB 1 errata para um artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-42302019000701032&lng=en&nrm=iso&tlng=en
> 
> Publicação Contínua PC
> 
> JAOS 1 errata para 1 artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572016000100106&lng=en&nrm=iso&tlng=en
> 
> RLAE 1 errata para 6 artigos: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692016000100900&lng=en&nrm=iso&tlng=en
> 
> RBEDU 1 errata para um artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1413-24782019000101001&lng=en&nrm=iso&tlng=pt
> 
> EDUR 1 errata para um artigo:: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-46982019000100901&lng=en&nrm=iso&tlng=pt

2. O mesmo problema acontece para retratação: 

> HOEHNEA: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2236-89062018000300540&lang=pt
> 
> ABCD: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-67202018000301000&lang=pt
> 
> RLPF:
> http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47142017000400776&lang=pt
> 
> CM: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2236-99962018000200599&lang=pt 

3. Aplicação a mesma solução para adendo: 

> Veja o comentário: https://github.com/scieloorg/opac/issues/1406#issuecomment-880746814

4. Considerar os seguintes textos para o adendo: 

ADENDO

PT:
Este adendo adiciona informação ao documento: [link DOI do artigo]
EN:
This addendum adds information to the following document: [link DOI do artigo]
ES:
Esta addenda agrega información al documento: [link DOI do artigo]

ARTIGO COM ADENDO

PT:
Este documento possui um adendo: [link DOI do adendo]
EN:
This document has an addendum: [link DOI do adendo]
ES:
Este documento tiene una addenda: [link DOI do adendo]


Vou criar um tíquete para cada atividade para ficar mais simples a execução e validação.

**Comment by gitnnolabs** [comment]
Adicionar um novo categoria de related, ver na documentação: https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/narr/artigo-comentado.html

**Comment by gitnnolabs** [comment]
Essa atividade já foi realizada.
