### ISSUE TITLE
Adicionar a última seção na página inicial do periódico.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#141]
### Problema: 

Na página inicial do periódico tem as seções do último fascículo, atualmente não esta em nenhuma ordem ou seguindo como esta no mockup.

### Objetivo: 

Adicionar a lista de seções em ordem na página do periódico conforme o mockup.

Ver imagens para realizar essa atividade: 

![home_journal](https://cloud.githubusercontent.com/assets/373745/14257824/e77265e8-fa75-11e5-9d97-7c8680492320.png)

**Comment by jfunez** [comment]
issue relacionado: #143

**Comment by jamilatta** [comment]
Realizando.
