### ISSUE TITLE
Remodelar como citar dos artigos no site SciELO novo

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1412]
Relação com https://github.com/scieloorg/opac/issues/1278

Remodelar como citar dos artigos no site SciELO novo.

**Comment by amandasramalho** [comment]
- Uso do et al.
A norma ISO 690:2010, tópico "5.4.2 More than three creators", diz que em um trabalho com 4 ou mais autores, todos os nomes devem ser informados, se possível. Mas, permite abreviar os nomes com o uso de "et al". (a mesma coisa acontece também na ABNT 6023:2018 onde o tópico "8.1.1.2" diz que "Quando houver quatro ou mais autores, convém indicar todos. Permite-se que se indique apenas o primeiro, seguido da expressão et al.). Entretanto, cabe uma reflexão sobre identificação da autoria em citações, onde os autores omitidos pelo "et al" não são facilmente identificáveis. O próprio currículo Lattes passou a exibir todos os autores de uma publicação. 
Sendo assim, o SciELO adotará o uso de et al para os modelos de "como citar" ou também passaremos a exibir todos os autores?
Modelo no Lattes:
![image](https://user-images.githubusercontent.com/5446933/64370345-a644b000-cff4-11e9-987d-fc77be7fa0b9.png)

**Comment by RPostalli** [comment]
Eu votaria em exibir todos os autores, concordo com você, mas temos casos como este http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2175-78602018000401513&lng=en&nrm=iso&tlng=en, não são comuns mas existem.

**Comment by amandasramalho** [comment]
@RPostalli 
Neste caso o paper indica a forma correta de citar:
![image](https://user-images.githubusercontent.com/5446933/64371003-f53f1500-cff5-11e9-84eb-ae4321bcb0a0.png)

**Comment by RPostalli** [comment]
Sim, verdade. Eu só comento isso, porque o tamanho da caixa de como citar teria que ser flexível, não sei como funciona hoje esse caixinha.
![image](https://user-images.githubusercontent.com/6084959/64371268-8a420e00-cff6-11e9-8403-c32846dab854.png)

**Comment by amandasramalho** [comment]
@RPostalli Ah, sim. A preocupação é válida! Mas acredito que isso teria que ser uma questão à ser discutida entre as equipes de WebMaster, Desenvolvimento e Paraty (@alexxxmendonca @jamilatta). Uma ideia seria incluir uma barra de rolagem e manter a tela do mesmo tamanho.

**Comment by alexxxmendonca** [comment]
Pessoal, toquemos para frente. O design e tecnologia deverão se adequar e comportar as nossas necessidades.

Precisamos definir o modelo do que deve ser exibido e como. Design e tecnologia apresentarão soluções.

**Comment by gustavofonseca** [comment]
Relacionado com #1703.

**Comment by gustavofonseca** [comment]
O ticket #1703 substitui este que portanto será fechado.
