### ISSUE TITLE
Adicionar Visual Abstract no sumário (TOC)

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1431]
### Descrição da nova funcionalidade
Eu, como **leitor e usuário do site SciELO**, gostaria que **fosse possível acessar o Visual Abstract de um determinado artigo no sumário do número ao qual ele faz parte**, então **é necessário incluir uma opção para visualizar o Visual Abstract pelo sumário, da mesma forma que existe opções para verificar o resumo em formato texto**.

### Critérios de aceitação

O link para o Visual Abstract deve aparecer ao lado direito dos links para os resumos em formato texto.

Label: Visual Abstract.

Não foi acertado nada sobre tradução do termo para outros idiomas, mas seria importante considerar que esse termo pode vir a ser traduzido para o Português e Espanhol no futuro.

**Comment by alexxxmendonca** [comment]
@paratiuid será necessário uma proposta de layout do sumário (toc) para essa demanda.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Acho que esse ticket é duplicado, veja: https://github.com/scieloorg/opac/issues/1364

**Comment by alexxxmendonca** [comment]
Fechando o ticket devido a duplicidade.
