### ISSUE TITLE
Manter a ordenação de artigos do site atual e do new (até que o atual seja desligado)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1435]
A sequência de artigos entre os sites br atual e new estão divergentes.

É correto que o site new trate a ordenação dos artigos sem considerar o other uma vez que o other é uma "gambiarra" para ordenar os artigos no site atual. Relação com ticket https://github.com/scieloorg/opac/issues/987

Porém, é um enorme trabalho entre SciELO/Prestadores/Editores para manter a ordem atual que é controlada pelas planilhas de other.

Até que o site atual seja desligado, a ordem considerada no site new deve ser exatamente a mesma desenhada no site atual. Não pode haver divergências entre a ordenação enquanto a publicação ocorrer nos dois sites ao mesmo tempo.

Quando o site atual for desligado, comunicaremos formalmente a todos os envolvidos externos a nova forma de ordenação automática. Mas até lá não pode haver divergência.

Exemplo: Ordem diferente dos artigos bjmbr v52n3:
new: https://new.scielo.br/toc/bjmbr/2019.v52n3/
atual: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0100-879X20190003&lng=en&nrm=iso

Artigo: Visual and automatic classification of the cyclic alternating pattern in electroencephalography during sleep

Em new: É o último da seção
Em atual: É o segundo da seção

**Comment by robertatakenaka** [comment]
@RPostalli pensando que em breve teremos o site novo, qual é a regra de apresentação dos documentos no sumário?

**Comment by RPostalli** [comment]
Other para quem tem elocation e paginação para quem tem lpage e fpage. E other para quem tem lpage e fpage com qualquer número que não seja arábico (ex. número romano).

Antes da Paty sair ela pediu pra eu testar e me parece que o new já está seguindo a ordenação original do site vintage. ;)

Os exemplos de ordenação errada que coloquei aqui no ticket já foram corrigidos.

Tendo em vista que o site novo não corrige o problema de other, esta regra de ordenação deve continuar a ser aplicada para o new mesmo para arquivos que passarem a ser publicados diretamente neste site.

**Comment by robertatakenaka** [comment]
@RPostalli então podemos fechar este issue?

**Comment by RPostalli** [comment]
Acredito que sim Robs, quando virar a chave para o site novo e tiver problemas de ordenação nos reportaremos pontualmente.
