### ISSUE TITLE
Melhorar a exibição dos resumos na Tabela de Conteúdo (TOC)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1450]
### Descrição do problema

A exibição dos resumos na tabela de conteúdo adiciona um texto indesejável no resumo, vejam: 

<img width="1095" alt="Screenshot 2019-10-21 20 56 40" src="https://user-images.githubusercontent.com/373745/67287811-298d6880-f4b2-11e9-84a0-cdba5602f012.png">
<img width="1062" alt="Screenshot 2019-10-21 20 20 27" src="https://user-images.githubusercontent.com/373745/67287817-2b572c00-f4b2-11e9-99e3-b4c1676e3498.png">
<img width="793" alt="Screenshot 2019-10-21 20 20 02" src="https://user-images.githubusercontent.com/373745/67287823-2db98600-f4b2-11e9-8442-8ede61f17136.png">

### Passos para reproduzir o problema
1. Acessar o link do TOC exemplo: https://new.scielo.br/toc/aa/2017.v47n3/ 
2. Clicar em qualquer link para o reumo.

### Comportamento esperado

Não exibir o texto "Resumo" ou "Summary" no conteúdo do resumo.

### Ambiente utilizado

Ambiente de produção: https://new.scielo.br/toc/aa/2017.v47n3/

**Comment by alexxxmendonca** [comment]
Com a nova forma de exibição dos resumos para melhor atender a indexação no Google Scholar, este ticket deixa de fazer sentido.

Testei alguns links apontados pelo Jamil e não consegui reproduzir o problema, de modo que acredito que o problema tenha sido resolvido.
