### ISSUE TITLE
Área do periódico não é exibida na Grade de fascículos.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1452]
### Descrição do problema

Após realizarmos um processamento completo na nossa máquina de laboratório, identificamos que não é apresentado a **Área do Periódico na página da Grade de Fascículos**.

### Passos para reproduzir o problema

Para visualizar o problema acesse o seguinte exemplo: http://dsteste.scielo.br/grid/aa/

### Comportamento esperado

Deve ser possível apresentar a área do periódico na **Grade de Fascículos**

### Screenshots ou vídeos

![Screenshot 2019-10-23 14 15 00](https://user-images.githubusercontent.com/373745/67417591-8286fa80-f59f-11e9-957d-f95f24024fba.png)

### Ambiente utilizado

http://dsteste.scielo.br

**Comment by robertatakenaka** [comment]
duplicado
