### ISSUE TITLE
Publicador não é exibida no cabeçalho do periódico

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1453]
### Descrição do problema

Após realizarmos um processamento completo na nossa máquina de laboratório, identificamos que não é apresentado o Publicador não é exibida no cabeçalho do periódico.

### Passos para reproduzir o problema

Para visualizar o problema acesse o seguinte exemplo: http://dsteste.scielo.br/toc/aval/2019.v24n1/

### Comportamento esperado

Deve ser possível exibir o publicador no cabeçalho do periódico

### Screenshots ou vídeos

![Screenshot 2019-10-23 14 18 21](https://user-images.githubusercontent.com/373745/67417975-4f913680-f5a0-11e9-9703-c9c378f6a203.png)

### Ambiente utilizado

http://dsteste.scielo.br

**Comment by jamilatta** [comment]
Essa atividade é dependende das definição do ticket: https://github.com/scieloorg/kernel/issues/147

**Comment by jamilatta** [comment]
@robertatakenaka 

Conforme conversamos essa difinição está clara para você e portanto estou transferindo essa atividade para ti.

**Comment by robertatakenaka** [comment]
@gustavofonseca @patymori @joffilyfe @jamilatta 
Vamos ver se estamos pensando na mesma coisa:

1. Title manager:
http://docs.scielo.org/projects/scielo-pc-programs/en/latest/titlemanager_title.html#journal-form
http://docs.scielo.org/projects/scielo-pc-programs/en/latest/titlemanager_title.html#publisher
Nesta época não havia distinção de quem era a instituição responsável pela publicação, no sentido periódico, e da instituição que publica, imprime.

2. Recentemente "Publishers" estrangeiros, como Elsevier, passaram a oferecer o serviço de "publicação", então sugiu mais um papel que estamos chamando de "publisher" no sentido de quem publica, faz o serviço de publicação, mas sem tirar a responsabilidade de gestão dos periódicos. Ou seja, o papel de publisher se dividiu em dois: "responsáveis pelo periódico" e  "casa publicadora/editora".

3. Observação: Em nenhum lugar em _Title Manager_ existe o campo **Editor**.  Não confundir o papel da pessoa "editor", com "casa publicadora" ou com "responsável pelo periódico". Que também não são "sponsors" que são instituições que financiam. Outro detalhe é que no papel de cada um: instituição responsável pelo periódico, casa publicadora, financiadores, todos poderiam ser mais de uma instituição.

4. Sabendo disso, minha proposta é que como até o site novo tampouco há a distinção do "novo papel" que é o de "publisher"/casa publicadora, é de preencher os dados no kernel como sendo de "instituição responsável pelo periódico" e, com este dado preencher o opac_schema o campo "publisher_name". Alguém tem alguma proposta diferente?

**Comment by jamilatta** [comment]
@robertatakenaka 

Como nossa estratégia é somente de integração e não de correção/ajustes, **concordo**!

Mas isso não tira a necessidade de alinharmos as aplicações no futuro, talvez devessímos criar tiquetes de caracter de discussão sobre a necessidade desse campos e de obtenção desses dados.

**Comment by robertatakenaka** [comment]
> Hoje o [`kernel`](https://github.com/scieloorg/kernel/blob/master/documentstore/domain.py#L1032) possui um campo que representa as instituições responsáveis pelo periódico, nós podemos preenche-lo? Em caso de positivo, quais campos da `title` serão utilizados?

conforme mencionei acima, acho que seria o "publisher" da title manager, campo 480.

**Comment by robertatakenaka** [comment]
> De toda maneira o `website` espera um `"publisher"` que hoje nós atendemos a partir dos dados relativos a publisher capturados do `xylose` (ex : [cidade](https://github.com/scieloorg/xylose/blob/master/xylose/scielodocument.py#L1183)).

acho que é o mesmo publisher da title manager, pois quando o site foi concebido não existia a distinção de entre o responsável pelo periódico e responsável pelo processo editorial

**Comment by robertatakenaka** [comment]
Obs.: "Material Research" tem mais de um responsável pelo periódico: "ABM, ABC, ABPol"
