### ISSUE TITLE
Endereço não é exibida no rodapé do periódico

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1454]
### Descrição do problema

Após realizarmos um processamento completo na nossa máquina de laboratório, identificamos que não é apresentado o endereço no rodapé do periódico.

### Passos para reproduzir o problema

Para visualizar o problema acesse o seguinte exemplo: http://dsteste.scielo.br/toc/aval/2019.v24n1/

### Comportamento esperado

Deve ser possível exibir o endereço no rodapé do periódico.

### Screenshots ou vídeos

![Screenshot 2019-10-23 14 26 46](https://user-images.githubusercontent.com/373745/67418441-27ee9e00-f5a1-11e9-811c-a49093017feb.png)

### Ambiente utilizado

http://dsteste.scielo.br

**Comment by robertatakenaka** [comment]
Analisando o caso:
opac:

```html
<div class="col-md-10 col-sm-9">
        <strong>{{ journal.publisher_name }}</strong>
        {% if journal.publisher_address %}
          {{ journal.publisher_address }} -
        {% endif %}
        {% if journal.publisher_city %}
          {{ journal.publisher_city }} -
        {% endif %}
        {% if journal.publisher_state %}
           {{ journal.publisher_state }} -
        {% endif %}
        {% if journal.publisher_country %}
           {{ journal.publisher_country }} <br/>
        {% endif %}
        {% if journal.publisher_telephone %}
          Tel/Fax: {{ journal.publisher_telephone }}
        {% endif %}
        {% if journal.editor_email %}
          <b>E-mail:</b> {{ journal.editor_email }}
        {% endif %}
      </div>
```

**Comment by jamilatta** [comment]
🚀
