### ISSUE TITLE
As imagens não são exibidas na página do artigo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1456]
### Descrição do problema

Após realizarmos um processamento completo na nossa máquina de laboratório, identificamos que as imagens não são exibidas na página do artigo.

### Passos para reproduzir o problema

Para visualizar o problema acesse o seguinte exemplo: http://dsteste.scielo.br/article/rgo/2019.v67/10.1590/1981-86372019000283566/en/#

### Comportamento esperado

Deve ser possível exibir as imagens não são exibidas na página do artigo.

### Screenshots ou vídeos

![Screenshot 2019-10-23 15 01 20](https://user-images.githubusercontent.com/373745/67421632-4a83b580-f5a7-11e9-8350-7fb1088af70b.png)

### Ambiente utilizado

http://dsteste.scielo.br

**Comment by robertatakenaka** [comment]
@patymori @gustavofonseca @jamilatta @joffilyfe 
Tínhamos feito um brainstorm e chegamos à conclusão se não me engano de:

1. Miniaturizar as imagens
2. Deixar registrado no XML por meio da tag `<alternatives/>` ambas imagens: original e miniatura

Isso deveria ter sido anotado em uma ADR
Foram tiradas fotos da opção escolhida

**Comment by robertatakenaka** [comment]
Levantamos a possibilidade de fazer esta modificação no XML dentro do packtools.

As mudanças que fizemos no XML para inserir dados como article-id (v3) entre outros foi feita no XC porque estes dados deveriam ser inseridos na base artigo. 

Esta mudança relacionadas com as imagens como não seriam registradas na base não necessariamente precisaria ser feita na fase do XC. Chegamos a levantar a questão de Visual Abstract que poderia entrar na base. Mas não temos muita definição sobre o assunto.

Concluimos que o melhor local para resolver a geração deste XML com alternatives e gerar as imagens seria no **packtools** e que seria executado no opac-airflow. Mas se futuramente decidirmos por executar isso no XC a mudança não seria difícil.

Identificamos também que em alguns casos os XML já possuem a tag alternatives para distinguir em tabelas e equações as alternativas gráficas e codificadas.

Também identificamos que há os atributos specific-use, mimetype e mime-subtype em graphic:
https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/graphic.html

Sobre alternatives: https://jats.nlm.nih.gov/publishing/tag-library/1.2/element/alternatives.html

Quanto ao HTML, existe a nova tag picture para lidar com imagens.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

**Comment by gustavofonseca** [comment]
É importante considerarmos as recomendações da JATS4R para _display objects_: https://jats4r.org/display-objects

**Comment by joffilyfe** [comment]
> ...
> Quanto ao HTML, existe a nova tag picture para lidar com imagens.
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

É possível implementar o suporte ao `picture` em browsers mais antigos utilizando um polyfill https://scottjehl.github.io/picturefill/.

**Comment by robertatakenaka** [comment]
Pessoal comentem em: https://github.com/scieloorg/packtools/issues/216

**Comment by jamilatta** [comment]
Fechado, por que identificamos a necessidade de tramento nas imagems, isso será feito em outro repositório: scieloorg/packtools#216
