### ISSUE TITLE
Erro na visualização dos botões no rodapé do artigo quando exibi a barra de CookiePolicy. 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1466]
### Descrição do problema

Ao acessar a página do artigo com a mensagem de Política de Cookie, identificamos que os botões no footer ficam escondidos.

### Passos para reproduzir o problema

Acesse a página https://new.scielo.br/article/agora/2019.v22n3/280-289/pt/, sem ter concordado com a política de cookies.

### Comportamento esperado

De alguma forma deve ser possível exibir os dois tanto os botões quando a mensagem de politíca de cookies

### Screenshots ou vídeos

<img width="1368" alt="Screenshot 2019-11-08 13 55 04" src="https://user-images.githubusercontent.com/373745/68495865-d47e8000-022f-11ea-94d3-92454f3f9b45.png">

**Comment by paratiuid** [comment]
Oi @jamilatta 
Verifiquei aqui e vi que o Z-index da barra está menor do que o do botão do menu.

Acredito que o ajuste deva ser feito no script do cookie para que a barra fique sobre o botão, correto?

**Comment by alexxxmendonca** [comment]
@paratiuid acho que a barra não deveria impedir que os botões do menu flutuante fossem clicáveis.

Haveria como mover para cima o menu flutuante enquanto a barra estiver ativa?

**Comment by gustavofonseca** [comment]
O erro está resolvido.
