### ISSUE TITLE
Links de resumos com múltiplos idiomas: expandir somente um por vez

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1471]
### Descrição do problema
Atualmente, os links para resumo expandem de maneira simultânea/acumulativa (por ex: quando o artigo possui 2 ou mais resumos, é possível expandir todos simultaneamente).

### Passos para reproduzir o problema
1. Acesse a página https://search.scielo.org/
2. Faça uma busca
3. Encontre um resultado de artigo com resumo em mais de um idioma
4. Expanda todos os resumos ao mesmo tempo

### Comportamento esperado
Ao expandir um resumo, os demais que por ventura estiverem expandidos devem ser colapsados. Exibir somente um idioma por vez.

### Screenshots ou vídeos
https://drive.google.com/file/d/1iXr4NUy-v-7tpNYKkZmRyq6xhWKzPvZi/view

**Comment by jamilatta** [comment]
@alexxxmendonca 

Por gentileza, assim que possível verifique esse ajuste no ambiente de homologação: https://homolog.opac.scielo.br/

**Comment by alexxxmendonca** [comment]
@jamilatta Testado e aprovado em homologação.
