### ISSUE TITLE
Aumentar z-index dos botões flutuantes na tela do artigo

### ISSUE THREAD

**Issue by paratiuid** [scieloorg/opac#1472]
### Descrição do problema
Com a inserção da barra de cookiePolicy na tela de artigo, vimos que os botões flutuantes ficam abaixo da barra.
O ajuste solicitado serve para trazer os botões para cima da barra, para que os botões possam ser usados mesmo com a barra sendo exibida.
Este ajuste foi mencionado no pr:
https://github.com/scieloorg/static/pull/2

### Passos para reproduzir o problema
1. Acesse a página do artigo e verifique que os botões flutuantes ficam abaixo da barra.

### Comportamento esperado
Ao setar o z-index dos botões para 2, eles já ficam sobre a barra e podem ser utilizados normalmente.

### Screenshots ou vídeos
<img width="325" alt="Screen Shot 2019-11-14 at 4 02 52 PM" src="https://user-images.githubusercontent.com/22373640/68892464-dea5f000-0701-11ea-9337-acc573d15ac6.png">
O primeiro botão que aparece acima da barra, recebeu o z-index = 2. O mesmo deve ser feito com todos os outros.

### Ambiente utilizado

Quando aplicável, forneça detalhes sobre o ambiente utilizado, ex:

O problema pode ser observado acessando a homolog com qualquer navegador.

**Comment by paratiuid** [comment]
@alexxxmendonca @joffilyfe @jamilatta @gustavofonseca 

Pessoal, 
acredito ter havido uma falha de comunicação então quando foi solicitado que os botões flutuantes da tela de artigo ficassem acima da barra de cookies.

Com base na nossa conversa de hoje na daily, entendo que este ajuste é desnecessário aqui no projeto Opac.
A correção deve ser feita no projeto satatic, direto no script de cookiePolicy.

**Comment by jamilatta** [comment]
Ok.
