### ISSUE TITLE
Adiciona a classe isCookiebarActive aos botões flutuantes da tela de Artigo.

### ISSUE THREAD

**Issue by paratiuid** [scieloorg/opac#1475]
### Descrição do problema
Adiciona a classe isCookiebarActive aos botões flutuantes da tela de Artigo.
Essa classe é inserida nos botões se a barra de notificação de cookies estiver aparecendo na tela.
Com ela, os botões ganham um espaço a mais na parte inferior, fazendo com que os botões não estejam sobre a barra.

Este ajuste funciona junto com o ticket:
https://github.com/scieloorg/static/pull/2

Este ticket gerencia a adição e remoção dessa classe nos botões flutuantes da tela de artigo.

### Passos para reproduzir o problema
Aqui no Opac, apenas será inserida a classe css que adiciona a propriedade "bottom: 50px" aos botões.
A adição e remoção da classe está no ticket:
https://github.com/scieloorg/static/pull/2

### Comportamento esperado
Com essa classe, os botões ficam + 50px afastados da parte inferior, dando respiro visual entre os botões e a barra de notificação de cookies.

### Screenshots ou vídeos
Sem a classe os botões fica abaixo da barra, escondidos.
<img width="1257" alt="Screen Shot 2019-11-18 at 4 53 53 PM" src="https://user-images.githubusercontent.com/22373640/69085124-520e7100-0a24-11ea-829d-c3a2c0c8d05d.png">

Com a classe, os botões sobem e aparecem na tela.
<img width="806" alt="Screen Shot 2019-11-18 at 4 52 04 PM" src="https://user-images.githubusercontent.com/22373640/69085204-6d797c00-0a24-11ea-988d-60cfa516c81e.png">

### Anexos
--

### Ambiente utilizado
Homologação

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia testar essa atividade em ambiente de homologação; https://homolog.opac.scielo.br/

**Comment by alexxxmendonca** [comment]
@jamilatta testado e aprovado em https://homolog.opac.scielo.br/

**Comment by jamilatta** [comment]
@alexxxmendonca 

Ok.
