### ISSUE TITLE
Formatação dos títulos dos documentos é perdida na tabela de conteúdos

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1484]
Periódicos de biológicas comumente apresentam formatação nos títulos dos seus artigos ao mencionar nomes científicos de espécies, por exemplo. Estas formatações não estão sendo exibidas na tabela de conteúdos dos fascículos ou listagem de documentos _ahead of print_.

Exemplo: https://new.scielo.br/toc/bjb/2019.nahead/ 

### Comportamento esperado
A formatação deve ser preservada, conforme consta no PDF ou na versão HTML do documento.

### Screenshots ou vídeos
![Screen Shot 2019-11-29 at 17 29 23](https://user-images.githubusercontent.com/161335/69889098-008c9e80-12ce-11ea-90be-31524d2c787d.png)

Este problema é percebido tanto com instâncias que operam com o _proc_ quanto com _airflow_.

**Comment by jamilatta** [comment]
@gustavofonseca 

Talvez devessimos ter um campo para exibição.

Atualmente quem faz a extração desse dado no XML é o **scielo-clea==0.4.0** e é extraído sem as tags de formação, importante lembrar, que para indexação devemos considerar somente os termos os termos sem formação(HTML).

**Comment by alexxxmendonca** [comment]
O problema foi corrigido:

![image](https://user-images.githubusercontent.com/4059679/122764846-44f7da80-d276-11eb-9942-f22c4a45efc8.png)
