### ISSUE TITLE
URL do site versão 1 não apresenta artigo

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1485]
### Descrição do problema
URL legada com path `/cgi-bin/fbpe/fbtext?got=last&pid=<pid versão 1>&usr=fbpe&lng=en&seq=<seq>&nrm=iso&sss=<sss>&aut=<aut>` anterior do site atual não é atendida.

Exemplo de URL publicada/referenciada com o PID antigo: http://www.scielo.br/cgi-bin/fbpe/fbtext?got=last&pid=S0103-9016(98)05500124&usr=fbpe&lng=en&seq=0103-9016-005&nrm=iso&sss=1&aut=71981947

URL funcionando no site atual: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-90161998000100024&tlng=en&lng=en&nrm=iso

### Passos para reproduzir o problema
1. Acesse o link https://new.scielo.br/cgi-bin/fbpe/fbtext?got=last&pid=S0103-9016(98)05500124&usr=fbpe&lng=en&seq=0103-9016-005&nrm=iso&sss=1&aut=71981947
2. É apresentado o erro

### Comportamento esperado
O site novo deveria direcionar para este artigo: https://new.scielo.br/article/sa/1998.v55n1/149-152/

### Screenshots ou vídeos
![Screen Shot 2019-12-03 at 13 23 43](https://user-images.githubusercontent.com/18053487/70069268-4304f280-15d0-11ea-92ed-5281de28e106.png)

**Comment by jamilatta** [comment]
:-()

**Comment by joffilyfe** [comment]
Alguns locais que achamos com links para a primeira versão do PID:
- http://cev.org.br/biblioteca/apresentacao-1/
- https://repositorio.usp.br/item/001010715
- https://repositorio.usp.br/item/001003027
- http://www.polbr.med.br/ano01/wal0301.php
- http://uniesp.edu.br/sites/_biblioteca/cursos/arquivos/20180412121521.pdf

Resultados achados a partir da [busca no google](https://www.google.com/search?q=allintext:+cgi-bin/fbpe/fbtext%3Fgot%3Dlast%26pid%3D&lr=&hl=pt-BR&as_qdr=all&ei=bn8YXrT_D6m85OUP7tqVyAk&start=0&sa=N&ved=2ahUKEwi07sDzlPnmAhUpHrkGHW5tBZk4FBDy0wN6BAgLEC8&biw=1680&bih=873).

**Comment by patymori** [comment]
Além da implementação da funcionalidade nas aplicações, é necessário que o campo criado para armazenar as diferentes versões do PID seja indexado na base do site novo. Para isso, é preciso fazer alteração no https://github.com/scieloorg/opac_schema.
