### ISSUE TITLE
Busca de PDFs pelo nome de arquivo nos PDFs do artigo vindos do opac-airflow

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1495]
### Descrição da nova funcionalidade
Eu, como **administrador do site de publicação**, gostaria que **o site novo buscasse o PDF pelo nome de arquivo nos PDFs do artigo além da URL legada**, então **as URLs legadas dos PDFs continuarão acessíveis após a migração do site atual para o site novo**.

### Critérios de aceitação
- O site deve ser capaz de acessar qualquer PDF de artigos vindos do processamento do opac-airflow
- O site deve ser capaz de acessar qualquer PDF de artigos vindos do processamneto do opac_proc

**Importante:** O nome original dos PDFs não são preservados no **minio**, portanto, no PR: https://github.com/scieloorg/opac-airflow/pull/149 foi adicionado o nome do PDF em um campo chave **filename** do campo **pdfs**.

Exemplo da estrutura armazenado no site novo quando processada pelo opac-airflow que armazena os PDFs no **minio**: 

<img width="1050" alt="Screenshot 2020-01-22 10 26 14" src="https://user-images.githubusercontent.com/373745/72897859-a8887c00-3d01-11ea-9414-cb6e5e3c3def.png">

Note que o nome do **PDF** é alterada e foi criado um campo **filename** com o nome original

### Anexos
N/A

### Referências
Detalhes da implementação para o ticket scieloorg/opac-airflow/issues/115 em: scieloorg/opac-airflow/pull/149/files#diff-aa9d05ef5ed7936289f4e9ef5a492dc7R341

**Comment by jamilatta** [comment]
Diante de uma análise mais profunda nessa atividade verificamos que é necessário termos o caminho completo do PDF na chave ``filenanme``.

Para isso redefinimos o fluxo de obtenção e armazenamento desse caminho no PDF.

**Comment by jamilatta** [comment]
Para finalizar essa atividade é necessário atender previamente o seguinte ticket: https://github.com/scieloorg/opac/issues/1512

**Comment by jamilatta** [comment]
Retornando para essa atividade, diante na nova definição do modelo do OPAC. 

PR que redefine o modelo: https://github.com/scieloorg/opac/pull/1514
