### ISSUE TITLE
[changes] Alimentar o site com as URLs legadas de manifestações dos documentos

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1505]
### Descrição da nova funcionalidade
Eu, como **usuário do site atual**, gostaria que **as urls atuais das manifestações dos artigos (PDFs) continuem funcionando**, então **as referências e acessos ao conteúdo original funcione sem problemas**.

### Critérios de aceitação

- As URLs dos PDFs do site atual devem continuar abrindo os PDFs no site novo. Ex: http://www.scielo.br/pdf/brjp/v1n1/1806-0013-brjp-01-01-0002-pt.pdf
- Mesmo os PDFs em diferentes idiomas devem permanecer acessíveis. Ex: http://www.scielo.br/pdf/mioc/v12n1/fr_tomo12(f1)_05-20.pdf

### Referências
- Implementação do document-store-migração para o armazenamento das URLs legadas das manifestações: https://github.com/scieloorg/document-store-migracao/pull/190/files
- Minio client para recuperar `metadata` de objetos: https://docs.min.io/docs/python-client-api-reference.html#stat_object

**Comment by joffilyfe** [comment]
Este ticket está duplicado, a requisição de funcionalidade já está descrita no issue #1495.
