### ISSUE TITLE
Título dos artigos no contexto do idioma.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#151]
### Problema: 

Na versão atual o título dos artigos estão com sendo exibidos com o primeiro idioma.

### Objetivo: 

Precisamos considerar o idioma corrente na a exibição dos artigo.

**Comment by jamilatta** [comment]
Acho que faltou adicionar na descrição da tarefa que em caso de não existir o título no idioma corrente da interface será exibido o idioma do título original.

**Comment by jfunez** [comment]
:+1:
