### ISSUE TITLE
Alimentar a fixture com os caminhos dos PDFs quando o artigo for proviniente de um XML nativo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1522]
### Descrição da tarefa
É necessário coletar o caminho dos PDFs dos artigos que são XML nativo. 

Recentemente foi gerado um arquivo de fixture onde armazenamos os caminhos do PDFs para a versão HTML.

Link para a fixture: https://drive.google.com/file/d/1nkquGDLWVeWxfIfnxQ2AGojS8lHgYmWB/view?usp=sharing

### Subtarefas

- [ ] Enriquecer o arquivo de fixture
- [ ] Rodar o comando que realizar a atualização na base de dados, ```python manager.py populate_pdfs_path_html_version```

**Comment by gustavofonseca** [comment]
Considero que este ticket não seja mais relevante.
