### ISSUE TITLE
Atender URL no padrão www.scielo.br/<acron do periódico>

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1523]
### Descrição da nova funcionalidade
Eu, como **usuário do sistema**, gostaria que **pedir URL no padrão `www.scielo.br/<acron do periódico>`**, então **ter acesso à home do periódico e não a mensagem de `The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`**.

Exemplo:
https://new.scielo.br/bjmbr
<img width="527" alt="Captura de Tela 2020-02-03 às 11 08 16" src="https://user-images.githubusercontent.com/505143/73659923-f5f7d800-4675-11ea-9dfb-a9171e4a708d.png">

### Critérios de aceitação
 - Acessar: https://new.scielo.br/bjmbr
 - Ver: https://new.scielo.br/journal/bjmbr

### Anexos
N/A

### Referências
N/A

**Comment by jamilatta** [comment]
Ambiente de homologação do OPAC BR atualizado: https://homolog.opac.scielo.br/
