### ISSUE TITLE
Avaliar e analisar as atividades para a migração das páginas informativas.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1534]
### Descrição da tarefa
Atualmente as páginas informativas contidas no site: https://new.scielo.br está atualizada. 

Precisamos avaliar e analisar uma estratégia de como migrar esses dados para uma instância que será populada com o kernel e minio.

### Subtarefas

- [x] Avaliar as atividades necessárias.
- [x] Descrição dos passos

## Considerações e notas

Verificar se é possível nessa atividade fazer uso da base de dados do admin do OPAC.

**Comment by joffilyfe** [comment]
O banco de dados `sqlite` guarda informações sobre upload de arquivos  e usuários do `admin` do site. Já  a base `mongodb` contém toda informações sobre os periódicos e suas páginas secundárias.

As atividades necessárias para migrar os dados são:

- Copiar a base `sqlite`;
- Copiar os dados da coleção `pages`;
- Atualizar o endereço dos logos na coleção `journal`;
