### ISSUE TITLE
Adicionar suporte as URLs das páginas informativas

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1535]
### Descrição da nova funcionalidade

Eu, como usuário, gostaria que o site tivesse a capacidade de resolver/responder as URLs antigas das páginas informativa.

### Critérios de aceitação

Considero aceitável que o site consiga responder com as páginas informativas de cada periódico quando solicitado as seguintes URLs: 

- http://www.scielo.br/revistas/rpc/iaboutj.htm
- http://www.scielo.br/revistas/rpc/iedboard.htm
- http://www.scielo.br/revistas/rpc/iinstruc.htm
- http://www.scielo.br/revistas/rpc/isubscrp.htm

Obs.: Necessário analisar se todos os periódico seguem com o mesmo padrão de URLs.

**Comment by jamilatta** [comment]
Avaliando o sistema de arquivo da instância de homologação para verificar se o padrão é o mesmo para todos os periodicos.

**Comment by jamilatta** [comment]
Trecho no site clássico que gera os links para as páginas informativas: https://github.com/scieloorg/Web/blob/1e377a701543fdade1669383cdb5d7a68750bf80/htdocs/xsl/sci_serial.xsl#L359

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia validar esse tíquete!

**Comment by jamilatta** [comment]
Está atualizado o ambiente de homologação: https://homolog.opac.scielo.br/

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
