### ISSUE TITLE
[dsteste] Ausência de título na página do artigo (XML gerado do HTML a partir do dsm)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1538]
### Descrição do problema
Ausência de dados na página do artigo (XML gerado do HTML a partir do dsm)
http://dsteste.scielo.br/article/abb/2009.v23n1/10.1590/S0102-33062009000100001/en/

### Passos para reproduzir o problema
1. Acesse a página http://dsteste.scielo.br/article/abb/2009.v23n1/10.1590/S0102-33062009000100001/en/
2. Observe que não há título da seção e não há título
3. Compare com o documento em outro idioma http://dsteste.scielo.br/article/abb/2009.v23n1/10.1590/S0102-33062009000100001/pt/

### Comportamento esperado
Apresentação similar a http://dsteste.scielo.br/article/abb/2009.v23n1/10.1590/S0102-33062009000100001/en/

### Screenshots ou vídeos
n/a

**Comment by patymori** [comment]
Os casos apontados não apresentam o título nos textos traduzidos pois não foram marcados. O título consta no HTML somente, não na base e, consequentemente, já são extraídos do Article Meta sem o título e ele é exibido como um parágrafo no body, não no título do artigo e nem o TOC.

**Comment by robertatakenaka** [comment]
Isso vai acontecer especialmente em editoriais ou em documentos que o título da seção é considerado o título do documento. 
Editoriais tem uma característica de que o título é igual em todos os idiomas (pt, en, es) e por isso, há "erro" de marcação ao identificar o título em apenas 1 idioma. 
Minha sugestão é: se há tradução mas apenas 1 título, na conversão criamos o título para o idioma correspondente igual ao único marcado.

**Comment by jamilatta** [comment]
@paratiuid 

Verifiquei esse artigo no sistema de pesquisa integra e ele está com o título veja: 

<img width="852" alt="Screenshot 2020-03-04 14 27 33" src="https://user-images.githubusercontent.com/373745/75906199-0fcb3d00-5e25-11ea-84f4-5685c9400998.png">

Suspeito que a abordagem utilizada no sistema de pesquisa seja o mesmo que a @robertatakenaka menciona.

**Comment by gustavofonseca** [comment]
> Isso vai acontecer especialmente em editoriais ou em documentos que o título da seção é considerado o título do documento.
> Editoriais tem uma característica de que o título é igual em todos os idiomas (pt, en, es) e por isso, há "erro" de marcação ao identificar o título em apenas 1 idioma.
> Minha sugestão é: se há tradução mas apenas 1 título, na conversão criamos o título para o idioma correspondente igual ao único marcado.

Eu receio que esta abordagem poderá suprimir erros. Além dos editoriais, há mais algum caso conhecido?

**Comment by jamilatta** [comment]
@gustavofonseca 

Acredito que essa estratégia de pesquisa possa ajudar a descobrir mais alguns casos: https://search.scielo.org/?q=&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1&q=-ti%3A*&lang=pt&page=1

**Comment by jamilatta** [comment]
@gustavofonseca @joffilyfe @robertatakenaka @patymori 

Como podemos resolver essa atividade?

**Comment by robertatakenaka** [comment]
@gustavofonseca @joffilyfe @jamilatta  @patymori

Há dois casos:
1) Há título, identificado em apenas 1 idioma, mas que por ser igual as pessoas não marcaram para os demais idiomas.

2) Há casos sem títulos porque de fato os documentos não os tem. Eram documentos baixo uma seção, como cartas.

Para o primeiro caso sugiro usar o título marcado em um idioma e replicá-lo para os demais textos / body.
No caso 2, deixar sem título, só que a DTD não permite isso.

**Comment by robertatakenaka** [comment]
> > Isso vai acontecer especialmente em editoriais ou em documentos que o título da seção é considerado o título do documento.
> > Editoriais tem uma característica de que o título é igual em todos os idiomas (pt, en, es) e por isso, há "erro" de marcação ao identificar o título em apenas 1 idioma.
> > Minha sugestão é: se há tradução mas apenas 1 título, na conversão criamos o título para o idioma correspondente igual ao único marcado.
> 
> Eu receio que esta abordagem poderá suprimir erros. Além dos editoriais, há mais algum caso conhecido?

O que significa "suprimir erros". Por que você acha que seria supressão de erros. O caso 1, é claramente erro de marcação. O segundo é assim porque era assim.

**Comment by gustavofonseca** [comment]
Para mim está claro que o caso 1 trata-se de erro de marcação. O que não está claro é se o mesmo motivo se aplica para todos os documentos. Será que de o título do documento traduzido não está presente pq é idêntico ao original ou pq alguém simplesmente deixou de marcar? Se for a segunda hipótese, ao copiar o primeiro título nós estaríamos invisibilizando o erro.

**Comment by gustavofonseca** [comment]
Segue o resultado da análise que fiz em 32444 documentos armazenados no _minio_ do _dsteste.

As ocorrências abaixo atendem às condições: _possui tradução_ e o _título da tradução não está definido_.

|    | PID                     | subject                           | sub-article_subject        | article-title                                                                     | sub-article_article-title   |
|---:|:-----------------------------------------------------------------------------------------------------------------------------------|:----------------------------------|:---------------------------|:----------------------------------------------------------------------------------|:----------------------------|
|  0 | H4PgQTtDpL5P9KB6cSFRq7g | []                                | []                         | ['Editorial']                                                                     | []                          |
|  1 | JgSfSdWQ63LFJjVWFTXJxyJ | []                                | []                         | ['Editorial']                                                                     | []                          |
|  2 | 6xLsNWGW5wGK9zLfK3jsKfc | []                                | []                         | ['Editorial']                                                                     | []                          |
|  3 | 9xJyLKnt8G6zrqXydCgxxPx | ['Editorial']                     | []                         | ['Anatomia microcirúrgica da artéria carótida externa: um estudo estereoscópico'] | []                          |
|  4 | QjtjGdmwdRqGf3WJQsnKWhJ | ['Editorial']                     | []                         | ['Novo sistema de submissões do Jornal Vascular Brasileiro']                      | []                          |
|  5 | tmcZMvQRQS3X9BKyw7qdNvG | ['Editorial']                     | []                         | ['Novidades do Jornal Vascular Brasileiro']                                       | []                          |
|  6 | NdkHGjCLFsqTrzV47zCZSsM | ['Editorial']                     | []                         | ['Intentos do Jornal Vascular Brasileiro']                                        | []                          |
|  7 | d63BkqGqs5BLrgwsbNdh9nN | []                                | []                         | ['A potência do pensamento']                                                      | []                          |
|  8 | V5bCY76jcxJt9bpLSLcv6kR | ['Resenhas']                      | ['Book Reviews']           | ['Manual de psicofarmacologia clínica']                                           | []                          |
|  9 | nMDNdwLXFLGy5qyBvh5V7Lm | ['Editorial']                     | ['Editorial']              | [None]                                                                            | []                          |
| 10 | SjYgMfZD9BDfmkVyDnjHWwj | ['Editorial']                     | ['Editorial']              | [None]                                                                            | []                          |
| 11 | v7zZpN5fRkjJK44PprFqTZt | ['Editorial']                     | ['Editorial']              | ['Desigualdades sociais no acesso a serviços odontológicos']                      | []                          |
| 12 | rwsDSggybtTvptLPF3hmq4s | ['Editorial']                     | ['Editorial']              | ['Editorial']                                                                     | []                          |
| 13 | QYYgGPkbb6xqcwQtYwyFmxb | []                                | ['Editorial']              | ['Research and spirituality']                                                     | []                          |
| 14 | nCsWmGf4zvZghGpB8JTKg8c | ['Editorial']                     | ['Editorial', 'Editorial'] | ['Notes on nursing: nurses making a difference in global health']                 | []                          |
| 15 | ZmjkGjTjQdY8qCnXX65qtWM | ['Editorial']                     | ['Editorial', 'Editorial'] | ['Preparing nurses for global health care']                                       | []                          |
| 16 | KCPVkyjLJBK7fGJKQ67crtx | ['Editorial']                     | ['Editorial']              | ['Criação, divulgação e ação: o saber em movimento']                              | []                          |
| 17 | 7MddYcR6gWnL4JfRFSjyQcf | []                                | []                         | ['Erratum Volume 18 Issue 1']                                                     | []                          |
| 18 | MGMWsMRGdmGwTTG6rcYKZYn | []                                | []                         | ['Erratum Volume 18 Issue 2']                                                     | []                          |
| 19 | VjDbnVM8zDb8Ytsw8sgTxQQ | ['Editorial']                     | ['Editorial', 'Editorial'] | ['O papel emergente do líder']                                                    | []                          |
| 20 | 8JJhRcrFwbvjZ5CbrqKPH4J | ['Artigos Originais de Pesquisa'] | ['Research Papers']        | ['Achados espectrais das vogais [a] e [ã] em diferentes aberturas velofaríngeas'] | []                          |
| 21 | nx54PcZcd9Qt9n47k9KMRwH | ['Editorial']                     | ['Editorial']              | ['Editorial']                                                                     | []                          |
| 22 | pPNG4HdjVWv3QDV4RF3hxHn | ['Editorial']                     | ['Editorial']              | ['Editorial']                                                                     | []                          |
| 23 | DF7xvnTTT35Pxz7NFtRQr8c | ['Editorial']                     | ['Editorial']              | [None]                                                                            | []                          |
| 24 | MYJY5Rgw5gc7mBpqYzBCVJR | ['Editorial']                     | ['Editorial']              | [None]                                                                            | []                          |
| 25 | 577Ms6wH6XNGkfVfqZStnrM | []                                | []                         | ['A Variedade de materiais em discussão']                                         | []                          |
| 26 | k3mKdH6RDK54Lw6kPkb6ZSt | []                                | []                         | ['COTEQ: um ponto de encontro sobre tecnologias de equipamentos industriais']     | []                          |

**Comment by jamilatta** [comment]
@gustavofonseca 

Muito bom isso demonstra que as nossas decisões de desenvolvimento precisam ser com base nos dados!

**Comment by gustavofonseca** [comment]
Estou inclinado a dizer que talvez o melhor seja não aplicar nenhuma correção automática e produzir um relatório para eventual correção manual. O que pensam sobre isso?

**Comment by jamilatta** [comment]
@gustavofonseca 

Concordo!

**Comment by joffilyfe** [comment]
@jamilatta, você ainda precisa de alguma ajuda neste ticket?

**Comment by jamilatta** [comment]
Diante da inlicnação do @gustavofonseca acho que podemos fechar esse tíquete e abrir um outro tíquete descrevendo que devemos criar **insumos** para as correções dos diversos casos que devemos mapear.

**Comment by gustavofonseca** [comment]
O problema foi registrado em https://docs.google.com/document/d/1zhZBePSnDcu99IUQThOcDNpEyi-vgthcpGTPJIdpLCs/edit?usp=sharing para tratamento manual.
