### ISSUE TITLE
Remover a dependência de obter os Logos de Periódicos do OPAC-SSM

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1539]
### Descrição da tarefa
Existe uma view do site que obtém os logos dos periódicos do SSM: `/media/assets/`. É necessário removê-la pois o SSM não será mais utilizado e os logos deverão ser carregados diretamente pelo Admin do site.

### Subtarefas

- [ ] Remover a view
- [ ] Sugestão: comando para obter as imagens do SSM e cadastrá-las no site.

## Considerações e notas
.

**Comment by gustavofonseca** [comment]
Aparentemente este ticket foi resolvido.
