### ISSUE TITLE
Analisar e criar nova rota (URL) de artigo

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1547]
### Descrição da tarefa
Analisar o impacto em adicionar uma nova rota de acesso para a view function que retorna a página do artigo e redirecionar a atual rota para esta. Esta rota seria no seguinte formato:

`/article/:acron/:id_doc[/:lang]`

Onde:
- `acron`: acrônimo do periódico onde o artigo está publicado
- `id_doc`: SciELO PID
- `lang`: idioma do texto (opcional)

## Considerações e notas
É importante ter em mente que as rotas atuais do projeto devem continuar funcionando.

**Comment by gustavofonseca** [comment]
O GitHub fechou este ticket automaticamente após a integração do PR #1554. Estou reabrindo o ticket até que ele seja homologado.

**Comment by gustavofonseca** [comment]
A atividade foi realizada mas o código poderá ser integrado apenas quando estivermos em vias de migrar as coleções de plataforma sob pena de causarmos efeitos colaterais indesejados na coleção Saúde Pública. Os códigos estão no branch https://github.com/scieloorg/opac/tree/pidv3-url-pattern.

**Comment by gustavofonseca** [comment]
O ticket #1580 altera o padrão da URL, invalidando este.
