### ISSUE TITLE
Analisar e criar novas rotas com o acrônimo do periódico

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1548]
### Descrição da tarefa
Analisar o impacto para adicionar novas rotas de acesso para view functions do site novo para representar melhor o conteúdo do site de acordo com a organização real, onde os artigos necessariamente não estão em um fascículo regular, mas que estão sempre publicados em um periódico. Estas rotas seriam:

`/j/:acron/` - home do periódico
`/j/:acron/grid` - grade de fascículos
`/j/:acron/ahead` - documentos Ahead of Print
~~`/j/:acron/:id_issue` - issue TOC~~
`/j/:acron/i/:id_issue` - issue TOC
~~`/j/:acron/:id_doc[/:lang]` - página do artigo~~
`/j/:acron/a/:id_doc?format=pdf&lang=es` - página do artigo

Onde:

`acron`: acrônimo do periódico onde o artigo está publicado
`id_issue`: identificador do fascículo
`id_doc`: SciELO PID
`lang`: idioma do texto (opcional)

## Considerações e notas
- [ ] avaliar o impacto na contagem de acessos

**Comment by robertatakenaka** [comment]
@gustavofonseca @joffilyfe @jamilatta @patymori e como seria o do pdf?

**Comment by gustavofonseca** [comment]
> @gustavofonseca @joffilyfe @jamilatta @patymori e como seria o do pdf?

Boa pergunta, acho que erramos ao definir a URL do artigo sem considerar isso. Uma abordagem é:

* PDF: `/j/:acron/pdf/:id_doc[/:lang]`
* HTML: `/j/:acron/html/:id_doc[/:lang]` ou `/j/:acron/article/:id_doc[/:lang]`

e futuramente..
* XML: * PDF: `/j/:acron/xml/:id_doc[/:lang]`

O que acham, @scieloorg/scielo-brazil-developers?

**Comment by robertatakenaka** [comment]
@gustavofonseca gosto

**Comment by gustavofonseca** [comment]
> @gustavofonseca gosto de ter o formato na url, mas estou achando meio estranho a ordem. Talvez o id devesse vir antes do formato, não sei.

E como ficaria o segmento opcional que indica o idioma?

**Comment by robertatakenaka** [comment]
Olha, há outra questão:

`/j/:acron/:id_issue` - issue TOC
`/j/:acron/:id_doc[/:lang]` - página do artigo

Percebem que o padrão está igual? Então, acho que a sua proposta faz mais sentido @gustavofonseca , de colocar o formato antes.

**Comment by gustavofonseca** [comment]
> Olha, há outra questão:
> 
> `/j/:acron/:id_issue` - issue TOC
> `/j/:acron/:id_doc[/:lang]` - página do artigo
> 
> Percebem que o padrão está igual? Então, acho que a sua proposta faz mais sentido @gustavofonseca , de colocar o formato antes.

De fato, deixamos passar vários problemas nessa definição =O

@robertatakenaka, [sua proposta](https://github.com/scieloorg/opac/issues/1548#issuecomment-607465192) é boa mas ainda assim eu fico ligeiramente incomodado com o fato de que o segmento da URL que terá o `:id_issue` (valor dinâmico) também poderá ter valores estáticos como `html`, `xml`, `pdf` etc. É extremamente improvável e esdrúxulo mas, hipotéticamente, se o id `pdf` for atribuído a um _issue_ a aplicação vai quebrar. 

Uma solução para isso seria criar um segmento estático, a exemplo do que fizemos com o `j`. Poderia ser algo como:
* `/j/:acron/i/:id_issue`
* `/j/:acron/pdf/:id_doc[/:lang]`

**Comment by robertatakenaka** [comment]
acho que sim para `/j/:acron/i/:id_issue`. @scieloorg/scielo-brazil-developers podemos considerar assim? é o PR que vou trabalhar agora!

**Comment by joffilyfe** [comment]
> @gustavofonseca gosto de ter o formato na url, mas estou achando meio estranho a ordem. Talvez o id devesse vir antes do formato, não sei.



> > @gustavofonseca gosto de ter o formato na url, mas estou achando meio estranho a ordem. Talvez o id devesse vir antes do formato, não sei.
> 
> E como ficaria o segmento opcional que indica o idioma?

Posso estar enganado mas nós discutimos a possibilidade do seguinte formato?

- `/j/:acron/a/:id_doc[/l/:lang]`
- `/j/:acron/a/:id_doc/pdf[/l/:lang]`

Acho que esse formato facilitaria o intercâmbio no output do formato do artigo como o @gustavofonseca mencionou mais acima (html, xml, pdf, epub, etc). 



> acho que sim para `/j/:acron/i/:id_issue`. @scieloorg/scielo-brazil-developers podemos considerar assim? é o PR que vou trabalhar agora!

@robertatakenaka eu acho uma boa estratégia prefixarmos os caminhos com o recurso que estamos acessando (`i` de issue 👍 ).

**Comment by gustavofonseca** [comment]
@joffilyfe, não está claro como o formato proposto em https://github.com/scieloorg/opac/issues/1548#issuecomment-607488976 _facilitaria o intercâmbio no output do formato do artigo_. Poderia elaborar, por gentileza?

**Comment by gustavofonseca** [comment]
> @joffilyfe, não está claro como o formato proposto em [#1548 (comment)](https://github.com/scieloorg/opac/issues/1548#issuecomment-607488976) _facilitaria o intercâmbio no output do formato do artigo_. Poderia elaborar, por gentileza?

Obs.: estou considerando que facilitaria em relação ao que foi proposto em https://github.com/scieloorg/opac/issues/1548#issuecomment-607469257.

**Comment by joffilyfe** [comment]
> Obs.: estou considerando que facilitaria em relação ao que foi proposto em [#1548 (comment)](https://github.com/scieloorg/opac/issues/1548#issuecomment-607469257).

@gustavofonseca do meu ponto de vista fica mais claro qual recurso nós estamos acessando (por causa do namespace). Como proposto mais acima acho até que poderíamos utilizar o formato do recurso e o idioma por meio de query strings, por exemplo:

- `/j/:acron/a/:id_doc` (artigo)
- `/j/:acron/a/:id_doc?format=pdf`
- `/j/:acron/a/:id_doc?lang=en`
- `/j/:acron/a/:id_doc?format=pdf&lang=es`

O que vocês acham?

**Comment by robertatakenaka** [comment]
@joffilyfe gosto

**Comment by patymori** [comment]
@joffilyfe gosto dessa última sugestão.

**Comment by gustavofonseca** [comment]
Excelente, @joffilyfe. Vou alterar na descrição deste ticket.

**Comment by robertatakenaka** [comment]
@scieloorg/scielo-brazil-developers outra questão: qual seria o valor de `:id_issue`?

**Comment by gustavofonseca** [comment]
E se continuarmos usando algo como `2019.v34n3`? Creio que `issue.iid` seja um _uuid4_, o que vai tornar a URL bizarra, e usar uma substring do PID-v2 (`issue.pid`) eu não penso que seja uma opção boa também haja vista que queremos ir adiante.

**Comment by robertatakenaka** [comment]
> E se continuarmos usando algo como `2019.v34n3`? Creio que `issue.iid` seja um _uuid4_, o que vai tornar a URL bizarra, e usar uma substring do PID-v2 (`issue.pid`) eu não penso que seja uma opção boa também haja vista que queremos ir adiante.

pode ser uma possibilidade

**Comment by patymori** [comment]
> 
> a. issue.id (acho que não existe este)
> b. issue.pid
> c. issue.iid

Na migração:
`issue.id` e `issue.iid` está com formato `ISSN-acron`, enquanto o `issue.pid` não está sendo preenchido no Kernel e, consequentemente, no site novo.

No processamento antigo:
`issue.id` e `issue.iid`, estão com um código derivado de um _uuid4_, enquanto o `issue.pid` está com o PID v2 de Issue.

Não sei o que seria melhor: usar o valor de um `.id` ou de `.pid`, mesmo passando a armazenar este campo na nova plataforma.
