### ISSUE TITLE
Discutir como iremos resgatar as informações de corpo editorial no TOC

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#155]
### Problema: 

No menu latereal esquerdo existe uma lista com o corpo editorial, hoje é "fake". 

### Objetivo:

Discutir e definir como iremos obter esses dados será em S.M.

Imagem para essa tarefa:

![Uploading issue_toc.png…]()

**Comment by jamilatta** [comment]
Em conversa com o @fabiobatalha definimos que os dados do corpo editorial estará disponível na interface thrift do SciELO Manager.

**Comment by jamilatta** [comment]
Este ticket esta impedido aguardando aprovação do tk: https://github.com/scieloorg/scielo-manager/pull/1288

**Comment by jamilatta** [comment]
O ticket para termos o corpo editorial foi aprovado, tk: scieloorg/scielo-manager#1288, porém o SciELO Manager não foi atualizado para que possamos realizar a coleta.

**Comment by jfunez** [comment]
por enquanto não vamos importar o corpo editorial...
