### ISSUE TITLE
Garantir estrutura inicial para o funcionamento pleno do site em container

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1550]
### Descrição da tarefa
Adicionar no Dockerfile, tanto de desenvolvimento quanto de produção, os comandos para garantir que toda a estrutura para o funcionamento pleno do site.

### Subtarefas

- [ ] Incluir comando para criar a base de dados SQL e as tabelas utilizadas pelo site, caso não exista
- [ ] Atualizar e compilar os arquivos de tradução do site

## Considerações e notas
.

**Comment by jamilatta** [comment]
@patymori 

Sobre a adicionar um comando para criar a base de dados SQL, verifiquei no Makefile e realmente não temos, mas para o item: 

- [ ] Atualizar e compilar os arquivos de tradução do site

Não seria o comando: **make_messages** que se encontra na linha: https://github.com/scieloorg/opac/blob/master/Makefile#L130

**Comment by gustavofonseca** [comment]
Particularmente não gosto da idéia de executar automaticamente comandos que causam efeitos no banco de dados, por considerar extremamente perigoso. Penso que o ideal é que criações de bases de dados, tabelas, migrações de bases e dados sejam executadas manualmente por um operador que sabe o que está fazendo.

**Comment by patymori** [comment]
> Não seria o comando: **make_messages** que se encontra na linha: https://github.com/scieloorg/opac/blob/master/Makefile#L130

Somente o comando de compilação está sendo executado no Dockerfile. Não é sobre a criação do comando mas sobre executá-los na criação do container.

**Comment by patymori** [comment]
> Particularmente não gosto da idéia de executar automaticamente comandos que causam efeitos no banco de dados, por considerar extremamente perigoso. Penso que o ideal é que criações de bases de dados, tabelas, migrações de bases e dados sejam executadas manualmente por um operador que sabe o que está fazendo.

Acho que é possível redefinir o que precisa ser feito então. Acha que a inclusão dos comandos no Makefile já seriam suficientes? Como seriam as execuções desses comandos?

**Comment by gustavofonseca** [comment]
> Acho que é possível redefinir o que precisa ser feito então. Acha que a inclusão dos comandos no Makefile já seriam suficientes? Como seriam as execuções desses comandos?

A priori a execução seria por vias normais, por exemplo `docker run` ou `docker exec` seguido do comando a ser executado dentro do contêiner, que poderia ser algo abstraído pelo Makefile.

Em resumo minhas sugestões são:

* Construção da imagem: compilação dos catálogos de tradução.
* Intervenção manual: comando para a criação de estruturas no banco de dados, carregamento de fixtures, migração de dados etc.

O que acham?

**Comment by patymori** [comment]
Concordo

**Comment by jamilatta** [comment]
Concordo.

**Comment by gustavofonseca** [comment]
As mensagens de tradução estão sendo compiladas durante a construção da imagem Docker, desta forma considero que não há nenhuma atividade a ser realizada no contexto deste ticket.
