### ISSUE TITLE
Adicionar a informação que o fascículo não tem número na grade.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1551]
### Descrição do problema

No site novo não temos a informação de fascículo sem número.

### Passos para reproduzir o problema

Acesso o site novo: http://dsteste.scielo.br/grid/alm/

Acesse o site antigo: http://www.scielo.br/scielo.php?script=sci_issues&pid=2236-4633&lng=en&nrm=iso

### Comportamento esperado

Devemos ter a informação de que o fascículo não tem volume.

**Comment by jamilatta** [comment]
Segue link no ambiente de produção do site novo: https://new.scielo.br/scielo.php?script=sci_issues&pid=2236-4633&lng=en&nrm=iso

**Comment by robertatakenaka** [comment]
duplicado #1327 / já resolvido
