### ISSUE TITLE
Ajuste no acesso de URLs legadas do site clássico

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1568]
### Descrição da tarefa
A view function `main.views.router_legacy()` deve redirecionar para as URLs do site novo. Seguem URLs de exemplo:
- Home do periódico:
  * `/scielo.php?script=sci_serial&pid=0066-782X&lng=en&nrm=iso`
- Issue TOC:
  * `/scielo.php?script=sci_issuetoc&pid=0066-782X20200002&lng=en&nrm=iso`
- PDF de artigo:
  * `/pdf/abc/v114n2/0066-782X-abc-114-02-0232.pdf`
- Grade de fascículos:
  * `/scielo.php?script=sci_issues&pid=0066-782X&lng=en&nrm=iso`

## Considerações e notas
.

**Comment by jamilatta** [comment]
@joffilyfe @patymori @gustavofonseca @robertatakenaka 

Está implantando em homologação do SciELO SP e SciELO BR, poderiam validar.

**Comment by gustavofonseca** [comment]
O problema já foi resolvido.
