### ISSUE TITLE
HTTP2

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#157]
### Melhoria:

Utilizar HTTP2 no OPAC, vários benefícios para a performance.
### Objetivo:
- Coletar métricas de performance com HTTP1.1;
- Conversar com infra sobre os certificados (geração e armazenamento);
- Configurar e instalar o nginx com os certificados 
- Testar e coletar as métricas com h2.

**Comment by jamilatta** [comment]
De alguma forma testar se realmente esta funcionando em HTTP2

**Comment by jfunez** [comment]
com curl: `curl -I --http2 https://homolog.opac.scielo.org`

obs: precisa instalar o curl com suporte para http2:
👉  https://simonecarletti.com/blog/2016/01/http2-curl-macosx/

**Comment by jfunez** [comment]
Jamil encontrou este post que fala que a causa é a deprecação do NPM:
https://www.nginx.com/blog/supporting-http2-google-chrome-users/

Já foi repassada a informação para a equipe de infra, e assim realizar os ajustes no nginx

**Comment by jamilatta** [comment]
Aberto chamado para a infra: https://suporte.scielo.org/front/ticket.form.php?id=1450

**Comment by jamilatta** [comment]
Item realizado.
