### ISSUE TITLE
Alternar a visibilidade do texto completo em HTML dos artigos

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1579]
Esta funcionalidade será importante após a migração de dados para a nova plataforma onde inúmeros XMLs produzidos automaticamente necessitarão de algum tipo de ajuste manual, e a possibilidade de publicá-los temporariamente com texto completo apenas em PDF será bastante explorada.

### Descrição da nova funcionalidade
* Eu, como **bibliotecário**, gostaria de **omitir a exibição do texto completo em HTML de determinado artigo**, para que **eventuais erros de marcação possam ser corrigidos sem que o artigo fique indisponível**.
* Eu, como **bibliotecário**, gostaria de **voltar a exibir o texto completo em HTML de determinado artigo**, para que **a visibilidade padrão seja restaurada**.
* Eu, como **bibliotecário**, gostaria de **visualizar a lista dos artigos que estão com seus textos completos em HTML omitidos**, para que **eu possa conferir a lista ou restaurar a visibilidade padrão**.

### Critérios de aceitação

- Deve ser possível realizar as operações em múltiplos artigos de uma única vez.

**Comment by joffilyfe** [comment]
### Proposta de solução

Para atender esta nova funcionalidade proponho adicionar uma nova ação no painel administrativo de artigos para que o operador do Website possa decidir exibir ou não o conteúdo completo do documento. Também será possível realizar filtros pelo _status_ de exibição do texto completo.

### Modificações necessárias

1. Adição de ações ao painel administrativo;
2. Adição de filtro ao painel administrativo;
3. Adição de um novo template demonstrando que o conteúdo está indisponível (anexo [1]);
4. Adição de propriedade ao _OPAC Schema_ para determinar a exibição ou não (_display_full_text = True | False_);

### Anexos

<img width="1043" alt="Screen Shot 2020-05-12 at 16 34 56" src="https://user-images.githubusercontent.com/4604104/81737493-8eb8a380-946e-11ea-9ee5-f21930ea67d9.png">

/cc @robertatakenaka, @patymori, @gustavofonseca, @jamilatta, o que acham?

**Comment by alexxxmendonca** [comment]
Caso seja aprovada, @joffilyfe por favor, remover o acento em "temporariamente"

**Comment by joffilyfe** [comment]
> Caso seja aprovada, @joffilyfe por favor, remover o acento em "temporariamente"

Perdão pelo erro @alexxxmendonca. Esqueci de te citar mas você também é muito bem-vindo a opinar sobre a proposta.

**Comment by alexxxmendonca** [comment]
@joffilyfe sem problemas!

Talvez algo como _Texto completo temporariamente indisponível neste formato_. 

Afinal de contas, o texto completo está disponível em PDF e outros formatos, só não em HTML.

Do jeito que está, pode dar a entender que está indisponível e o usuário pode desistir de procurar por alternativas.

**Comment by joffilyfe** [comment]
> @joffilyfe sem problemas!
> 
> Talvez algo como _Texto completo temporariamente indisponível neste formato_.
> 
> Afinal de contas, o texto completo está disponível em PDF e outros formatos, só não em HTML.
> 
> Do jeito que está, pode dar a entender que está indisponível e o usuário pode desistir de procurar por alternativas.

Concordo em especificar o formato indisponível. Uma dúvida, @alexxxmendonca; Você sabe dizer se os usuários nomeiam o texto completo em HTML de alguma maneira?

Faria sentido para o usuário se ele lesse algo como: `Texto completo em HTML temporariamente indisponível` ou `Texto completo temporariamente indisponível no formato HTML`?

**Comment by jamilatta** [comment]
@joffilyfe não sei se é possível mas sugiro que tenhamos o **título do artigo** no lugar do texto "Texto temporariamento indisponível", logo a baixo a lista de **autores**, o **abstract** e **palavras** chaves e depois o links diretos para os **pdfs** nos diversos idiomas. 

Claro é preciso verificar se isso é possível. 

Sugiro esse formato, pois o leitor já terá algumas dados relevates para o artigo e depois se caso seja esse atigo seja mesmo que ele procura acessa o "**inteiro teor**" do artigo no idioma que mais lhe convém.

**Comment by jamilatta** [comment]
Algo desse tipo, porém com links para os PDFs: 

![Captura de Tela 2020-05-13 às 09 16 34](https://user-images.githubusercontent.com/373745/81811125-83ab5500-94fa-11ea-9527-c3bd456eabd3.png)

**Comment by joffilyfe** [comment]
> @joffilyfe não sei se é possível, mas sugiro que tenhamos o **título do artigo** no lugar do texto "Texto temporariamento indisponível", logo a baixo a lista de **autores**, o **abstract** e **palavras** chaves e depois o links diretos para os **pdfs** nos diversos idiomas.
> 
> Claro é preciso verificar se isso é possível.
> 
> Sugiro esse formato, pois o leitor já terá algumas dados relevates para o artigo e depois se caso seja esse atigo seja mesmo que ele procura acessa o "**inteiro teor**" do artigo no idioma que mais lhe convém.

É posssível sim @jamilatta mas temos que ter ciência que esses dados também podem estar comprometidos por problemas na sintetização do XML. Acho que a ideia inicial da issue é justamente evitar expor esses problemas.

Faz sentido pra você, @jamilatta?

**Comment by jamilatta** [comment]
@joffilyfe sim faz, vou verificar se esse dados já não ficam na base de dados do OPAC, assim podemos avaliar e exibir o que é possível ser exibido.

**Comment by jamilatta** [comment]
Olhei no **opac_schema** e temos esses dados na base de dados, como são dados elementares de um artigo, não sei se vale a pena tentarmos ter uma interface mais rica de informações!

**Comment by alexxxmendonca** [comment]
@joffilyfe em resposta ao seu comentário, penso que devemo evitar o uso de termos técnicos, então sugiro algo como: 

_Este conteúdo está temporariamente indisponível neste formato.
Este conteúdo está temporariamente indisponível no formato de texto para web._

**Comment by robertatakenaka** [comment]
@joffilyfe Preferível usar o texto mais positivo:

_Este conteúdo está temporariamente disponível apenas em PDF_

**Comment by robertatakenaka** [comment]
> > @joffilyfe não sei se é possível, mas sugiro que tenhamos o **título do artigo** no lugar do texto "Texto temporariamento indisponível", logo a baixo a lista de **autores**, o **abstract** e **palavras** chaves e depois o links diretos para os **pdfs** nos diversos idiomas.
> > Claro é preciso verificar se isso é possível.
> > Sugiro esse formato, pois o leitor já terá algumas dados relevates para o artigo e depois se caso seja esse atigo seja mesmo que ele procura acessa o "**inteiro teor**" do artigo no idioma que mais lhe convém.
> 
> É posssível sim @jamilatta mas temos que ter ciência que esses dados também podem estar comprometidos por problemas na sintetização do XML. Acho que a ideia inicial da issue é justamente evitar expor esses problemas.
> 
> Faz sentido pra você, @jamilatta?

@joffilyfe todos os abstracts vem da base e não do body do HTML, tanto é que fica duplicado. 
Digamos que se os metadados estiverem comprometidos então isso está em tudo pois vem dos registros da base e não do XML. Então seria possível aproveitar os metadados.

**Comment by patymori** [comment]
@joffilyfe,

Gostei da ideia da apresentação. Vou adicionar algumas coisas.

> É posssível sim @jamilatta mas temos que ter ciência que esses dados também podem estar comprometidos por problemas na sintetização do XML. Acho que a ideia inicial da issue é justamente evitar expor esses problemas.
> 
> Faz sentido pra você, @jamilatta?

Concordo com seu apontamento mas talvez o título original do artigo a gente já poderia colocar, pois o dado estaria disponível na base. Vi aqui que também deveriam estar disponíveis as traduções do título mas acho que a nova plataforma não está preenchendo.

**Comment by joffilyfe** [comment]
> @joffilyfe Preferível usar o texto mais positivo:
> 
> _Este conteúdo está temporariamente disponível apenas em PDF_

Acho que dada a situação o texto proposto pelo Alex faz mais sentido porque hoje nós termos apenas um formato disponibilizado no site mas no futuro nós podemos ter outros.

> @joffilyfe todos os abstracts vem da base e não do body do HTML, tanto é que fica duplicado.
> Digamos que se os metadados estiverem comprometidos então isso está em tudo pois vem dos registros da base e não do XML. Então seria possível aproveitar os metadados.

> Concordo com seu apontamento mas talvez o título original do artigo a gente já poderia colocar, pois o dado estaria disponível na base. Vi aqui que também deveriam estar disponíveis as traduções do título mas acho que a nova plataforma não está preenchendo.

Ficou claro que os dados podem ser utilizados, mas então o time concorda que eles **devem** ser utilizados? Notem que esse layout está sendo feito no OPAC então nós não utilizamos a XSLT do packtools.

/cc @alexxxmendonca @robertatakenaka @jamilatta @patymori @gustavofonseca

**Comment by robertatakenaka** [comment]
> Acho que dada a situação o texto proposto pelo Alex faz mais sentido porque hoje nós termos apenas um formato disponibilizado no site mas no futuro nós podemos ter outros.

sim, eu vi... mas acho que fica meio vago "indisponível neste formato"... mas ok... Outro ponto, se isso for aceito, acho que não deveria ser em tamanho grande, pode ser mais reduzido para não causar um ocultamento de que há a disponibilidade do pdf. Ou seja, dar mais destaque ao que existe do que ao que não existe. Talvez colocar o link para o PDF antes da mensagem.

**Comment by alexxxmendonca** [comment]
Concordo com o que a @robertatakenaka sobre dar menos destaque à informação de indisponível e mais destaque à informação do que tem disponível.

**Comment by jamilatta** [comment]
Concordo com a @robertatakenaka também! 

Sobre dá mais destaques a informação disponível ao  invés da indisponível.

**Comment by jamilatta** [comment]
Outro ponto que acrescento é que a repetição de compomentes na interface não é uma boa prática. 

Repare que no desenho proposto repetimos o botão de PDF, sugiro o link para o PDF, ou algo como é colocado no search, vejam: 

![Captura de Tela 2020-05-13 às 12 57 56](https://user-images.githubusercontent.com/373745/81836081-646ff000-9519-11ea-9081-10daecc97623.png)

**Comment by joffilyfe** [comment]
/all precisamos então organizar o que será ou não mostrado nesta página. O time acha que devemos exibir:
- Título do artigo
- Resumo do artigo
- Texto explicativo (ex: `O conteúdo deste documento está disponível em PDF: ..`)
    - Link para as versões disponíveis naquele idioma
    - Botão/ícone para as versões disponíveis naquele idioma

Quais devem ser as prioridades de exibição se tivermos os elementos do artigo em concorrência com a mensagem de alerta?

**Comment by jamilatta** [comment]
@joffilyfe 

Concordo em exibir: 

- Título 
- Autores 
- Resumos
- Mensagem "**Texto completo disponível em PDF**." com os links, se possível, nos diverso idiomas. 

Acredito que "**Texto completo**" seria mais adequado, mas isso é opinião minha.

Não entendi a pergunta: "Quais devem ser as prioridades de exibição se tivermos os elementos do artigo em concorrência com a mensagem de alerta?"

**Comment by patymori** [comment]
> @joffilyfe em resposta ao seu comentário, penso que devemo evitar o uso de termos técnicos, então sugiro algo como:
> 
> _Este conteúdo está temporariamente indisponível neste formato._

Prefiro assim para o cabeçalho e as informações complementares que você sugeriu adicionado a isso, com os formatos disponíveis. Seria bom se fosse possível um tamanho menor do cabeçalho, mas se for possível.

**Comment by joffilyfe** [comment]
Pessoal é mandatório que tenhamos uma definição sobre o que será exibido e como será exibido nesta tela. No meu [comentário](https://github.com/scieloorg/opac/issues/1579#issuecomment-628087061) eu disponibilizo uma nova tela com parte da sugestão do @jamilatta.

Preciso de feedbacks a respeito dos pontos elencados no comentário e sugestões de melhoria.

----

> Prefiro assim para o cabeçalho e as informações complementares que você sugeriu adicionado a isso, com os formatos disponíveis. Seria bom se fosse possível um tamanho menor do cabeçalho, mas se for possível.

@patymori a sugestão é manter o layout mais próximo do que é exibido na página de artigo, incluindo título, _abstract_ e a informação de que o texto não está disponível?

**Comment by joffilyfe** [comment]
Em reunião com a equipe de projetos em 18/05/2020, ficou decidido que a tela apresentada no [comentário](https://github.com/scieloorg/opac/issues/1579#issuecomment-628087061) é suficientemente boa para o momento.
