### ISSUE TITLE
Compactação das imagens utilizadas no site

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#158]
### Problema: 

As imagens entregue pelo design tem tamanho absurdos.

### Objetivo: 

Utilizar ferramentas que realizem a compactação das imagens, estou bastante inclinado a utilizar uma ferramenta on-line: https://tinypng.com/

**Comment by jfunez** [comment]
@jamilatta seria bom deixar registrado de quanto foi a otimização.

**Comment by jamilatta** [comment]
@jfunez considerando a pasta de img que temos a aplicação o ganho foi significativo de 131 KB para 47 KB. 

Um ganho de 278% no total.

**Comment by jamilatta** [comment]
Item realizado no commit:  8d037859f3cae30f8b7305ed69b3284fa60f1911
