### ISSUE TITLE
[SPF] Migração de usuários da base atual para nova instância

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1583]
### Descrição da tarefa
Hoje existem usuários cadastrados e sendo usados em new.scielo.br. É necessário mantê-los funcionando na migração para a nova plataforma do Publishing Framework. Para isso, é necessário migrar os dados da base `User` do SQLite atual para a nova instância.

## Considerações e notas
.

**Comment by joffilyfe** [comment]
Não será necessário realizar programação para efetivar essa migração. A tabela de usuários será incorporada por completo quando a base for copiada.

Os detalhes e passos para a migração podem ser vistos em https://docs.google.com/document/d/1bC3ryHkBxAjmyUJ5Acj7XoceTOj6ezdgLWbLwtA3Nc0/edit?usp=sharing
