### ISSUE TITLE
Acesso aos conteúdos AOP a partir da barra de navegação 

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1595]
(Avaliar se é um issue válido) Remover os "issues aop" da navegação "anterior", "atual" e "próximo". Isto é, garantir que apenas os "issues" cujo type!='ahead' esteja nestas listas. AOP quando houver é o último da lista.

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Preferem discutir via um reunião remota e/ou preferem definir isso aqui mesmo nos comentários do github.

**Comment by patymori** [comment]
@jamilatta, acho que dá para seguir pelo ticket. Antes de começar a fazer, seria legal colocar a proposta de solução aqui.

**Comment by gustavofonseca** [comment]
Atualmente os issues AOP são ignorados da barra de navegação, conforme descrito no ticket. Estou fechando este ticket.
