### ISSUE TITLE
Estudar contexto transacional.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#16]
Visando adicionar contexto transacional em operações criticas, devemos estudar sobre o pacote ``transaction`` disponível em: https://pypi.python.org/pypi/transaction

**Comment by jfunez** [comment]
acrescento informação:
- http://blog.labix.org/2012/08/22/multi-doc-transactions-for-mongodb
- https://docs.mongodb.org/manual/tutorial/perform-two-phase-commits/
- https://github.com/rystsov/mongodb-transaction-example

**Comment by jamilatta** [comment]
Iniciado os estudos :-)

**Comment by jamilatta** [comment]
Estudando sobre o pacote de transação proposto e pensando melhor sobre esse tipo de abordagem, acreditamos que é desnecessário um contexto transacional para a maioria das operações realizado no OPAC Admin, a consistência eventual é suficiente para essa app.

Contudo segue um pouco do estudo e impressões sobre o pacote ``transaction`` do ZODB:

Considerando que o pacote ``transaction`` é uma biblioteca genérica de contexto transacional...não encontrei exemplos e documentações de uso da biblioteca sem que esteja utilizando o SQLAchemy, também verifique que desde de 19/05/2015 não há atualização no **pypi**.

Particularmente fiquei desapontado com o pacote **transaction**, pois além de não encontrar exemplos de uso, não há qualquer ajuda para uso da  biblioteca no repositório official: https://github.com/zopefoundation/transaction.
