### ISSUE TITLE
A aplicação possui inúmeras mensagens não traduzidas para inglês e espanhol

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac#1604]
### Descrição do problema
[Os comentários](https://github.com/scieloorg/opac/pull/1603#pullrequestreview-415352112) feitos em um pull request apontam para as mensagens que não foram traduzidas quando criadas. É necessário que sejam traduzidas antes do lançamento oficial.

### Passos para reproduzir o problema
1. Ver o [comentário](https://github.com/scieloorg/opac/pull/1603#pullrequestreview-415352112)

### Comportamento esperado
Espera-se que, em sua maioria, as mensagens estejam traduzidas e disponíveis.

### Screenshots ou vídeos
N/A

### Anexos
N/A

### Ambiente utilizado

N/A

**Comment by gustavofonseca** [comment]
O escopo deste ticket está muito abrangente. Vou fechá-lo na perspectiva que sejam abertos tickets específicos para cada uma das traduções faltantes.
