### ISSUE TITLE
Títulos que possuem equações em MathML são exibidos incorretamente no sumário do número

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1641]
O artigo _Uma Reflexão de Professores sobre Demonstrações Relativas à Irracionalidade de √2_ ([link](https://doi.org/10.1590/1980-4415v34n67a18)) apresenta dado codificado em MathML em seu título, como é possível verificar neste fragmento extraído de seu XML:

```xml
<article-title>Uma Reflexão de Professores sobre Demonstrações Relativas à Irracionalidade de <inline-formula>
        <mml:math display="inline" id="m1">
            <mml:mrow>
                <mml:msqrt>
                    <mml:mn>2</mml:mn>
                </mml:msqrt>
	    </mml:mrow>
        </mml:math>
    </inline-formula>
</article-title>
```

O dado codificado é exibido corretamente na página do texto completo do documento[1], entretanto não é exibido corretamente no sumário do número[2].

[1]
![Screen Shot 2020-08-17 at 14 46 00](https://user-images.githubusercontent.com/161335/90427116-8046dd00-e098-11ea-9b91-8043d32a969c.png)

 [2]
![Screen Shot 2020-08-17 at 13 51 05](https://user-images.githubusercontent.com/161335/90428164-f566e200-e099-11ea-8f24-d3df55a7d088.png)

## Informações adicionais e pré-análise
* Com exceção da página do texto completo[1], observei que o dado codificado em MathML é exibido de forma incorreta em todos os outros pontos:
    * Cabeçalho do HTML da página do texto completo (`/html/head/title`)
    * Função _Como citar_ do documento
    * Resultado de busca no SciELO Search
    * Registro depositado no Crossref https://api.crossref.org/works/10.1590/1980-4415v34n67a18

* O _endpoint_ `/documents/:doc_id/front`, do https://github.com/scieloorg/kernel, não está tratando adequadamente este caso o que está resultando na perda do dado codificado.

**Comment by alexxxmendonca** [comment]
Problema resolvido:

![image](https://user-images.githubusercontent.com/4059679/123149155-5b00c900-d437-11eb-8e49-810f39a6dd38.png)
