### ISSUE TITLE
[FASE 4] Ausência de ativos digitais em alguns documentos

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1643]
### Descrição do problema
Apresenta imagens: https://new.scielo.br/article/rbef/2020.v42/10.1590/1806-9126-RBEF-2020-0121/pt/
Não apresenta imagens: https://new.scielo.br/article/esa/9999.nahead/10.1590/S1413-41522020182506/

Diferença no XML:
```xml
<fig id="f1">
          <label>Figura 1</label>
          <caption>
            <title>Força de atrito em função do escorregamento <mml:math><mml:mrow><mml:mover><mml:mi>δ</mml:mi><mml:mo>˙</mml:mo></mml:mover></mml:mrow></mml:math>.</title>
          </caption>
          <attrib>Fonte: Ruina e Pratap <xref ref-type="bibr" rid="B13">[13]</xref> </attrib>
          <alternatives>
            <graphic xlink:href="https://minio.scielo.br/documentstore/1806-9126/zPwW7c4LmdpDq58tQMQ4vvb/3ad9261e9760f9f670238e6188349f8d1262ae0b.tif"/>
            <graphic xlink:href="https://minio.scielo.br/documentstore/1806-9126/zPwW7c4LmdpDq58tQMQ4vvb/7a5c8823b01795301948305eb08b7b045c9631e3.png" specific-use="scielo-web"/>
            <graphic xlink:href="https://minio.scielo.br/documentstore/1806-9126/zPwW7c4LmdpDq58tQMQ4vvb/85ff21ed9427b9d8e5cdc79c3d7e6bc10d5bf44d.jpg" specific-use="scielo-web" content-type="scielo-267x140"/>
          </alternatives>
        </fig>
```

```xml
<fig id="f1">
          <label>Figura 1 -</label>
          <caption>
            <title>(A) Altura média das plantas, (B) matéria seca da parte aérea (MSPA) e (C) matéria seca radicular (MSR) do consórcio aveia preta, ervilhaca e azevém cultivados em solo degradado pela mineração de carvão com adição de biossólido. Barras verticais representam o erro padrão da média (n = 5). Médias seguidas da mesma letra não diferem entre si pelo teste de Scott-Knott (p &lt; 0,05).</title>
          </caption>
          <alternatives>
            <graphic xlink:href="https://minio.scielo.br/documentstore/1809-4457/BrT6FWNFFR3KBKHZVPN8Y9N/8972aaa0916382b6f2d51a6d22732bb083851913.png"/>
            <graphic xlink:href="https://minio.scielo.br/documentstore/1809-4457/BrT6FWNFFR3KBKHZVPN8Y9N/3c30f9fec6947d47f404043fe08aaca8bc51b1fb.jpg" specific-use="scielo-web" content-type="scielo-267x140"/>
          </alternatives>
        </fig>
```

### Passos para reproduzir o problema
1. Acesse as páginas mencionadas acima do new.scielo.br acessível internamente
2. Role a página até da figura 1 de cada documenot
3. Observe a presença e ausência das imagens
4. Observe os XML em anexo que seriam os usados pelo htmlgenerator (packtools) para montar o html:

```
htmlgenerator --nochecks <path do xml>
```
resultado do documento que não contém as figuras apresentadas
[a.pt.html.zip](https://github.com/scieloorg/opac/files/5105003/a.pt.html.zip)

### Comportamento esperado
Apresentação da imagem

### Screenshots ou vídeos
<img width="600" alt="Captura de Tela 2020-08-20 às 15 46 53" src="https://user-images.githubusercontent.com/505143/90812423-7a513600-e2fc-11ea-9229-0fa212fbd7d2.png">
<img width="872" alt="Captura de Tela 2020-08-20 às 15 47 08" src="https://user-images.githubusercontent.com/505143/90812428-7cb39000-e2fc-11ea-9211-139287bde414.png">

### Anexos
[opac-tk.zip](https://github.com/scieloorg/opac/files/5104876/opac-tk.zip)

### Ambiente utilizado
new.scielo.br, release v3.1.1
packtools 2.6.4

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Olhando os .xml(s) verifiquei que não é obtido a url da figura por falta do atributo ``specific-use="scielo-web"`` no elemento ``<graphic>`` . 

Veja:


Conversando com a equipe

**Comment by jamilatta** [comment]
Em conversa com a equipe decidimos que iremos fazer uma ordem de precedência, iremos sempre tentar pegar a tag do XML ``graphic`` com atributo  ``specific-use="scielo-web"``, caso não tenha o atributo ``specific-use="scielo-web"`` utilizamos a primeira tag ``graphic``.
