### ISSUE TITLE
A visualização de imagem em um artigo específico não funciona

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac#1654]
### Descrição do problema

O [artigo](https://new.scielo.br/j/rae/a/7s4JJxZBVjfDJRnJkJXt5cd/) em sua versão do dia 16/09/2020 até às 16:00:00-03Z não possibilitava a exibição de uma imagem posicionada como primeiro elemento do copo do artigo.

Também é possível ver o mesmo comportamento para um [segundo artigo](https://new.scielo.br/j/rae/a/qvqzQMnYWqqfHCmN8gYDrpC), com versão do dia 16/09/2020 até às 16:00:00-03Z.

### Passos para reproduzir o problema
1. Acesse a [página](https://kernel.scielo.br/documents/7s4JJxZBVjfDJRnJkJXt5cd);
2. Clique para ampliar a primeira e única imagem do artigo;
3. Confirme que a imagem não foi aberta como é esperado.

### Comportamento esperado

Espera-se que as imagens que aparecem como _thumbnail_ sejam passíveis de ampliação quando o usuário clicar no quadro que exibe a modal da imagem.

### Screenshots ou vídeos

1. Trecho do XML com o elemento `fig`
<img width="1565" alt="Screen Shot 2020-09-16 at 20 19 21" src="https://user-images.githubusercontent.com/4604104/93402003-ef5f4f00-f859-11ea-9b97-2fc1251c2dd0.png">

### Anexos
N/A

### Ambiente utilizado
- Nova plataforma do site BR

**Comment by robertatakenaka** [comment]
@patymori A correção deve ser feita no arquivo

https://github.com/scieloorg/packtools/blob/fb799332c70071a3b13694d1a0cd2a2753c79c0b/packtools/catalogs/htmlgenerator/v2.0/html-modals.xsl#L93

Pois está criando `Modal` apenas para `fig[@id]` e no caso esta `fig` não tem `@id`.
