### ISSUE TITLE
Erro no data da legenda bibliografica do artigo 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1655]
### Descrição do problema
 
Para alguns artigos é apresentado o ano de publicação **duplicado**. 

### Passos para reproduzir o problema

1. Acesse a página: https://new.scielo.br/j/abcd/a/P56Jy5HBp5pwBt4ZQKMsS7n/
2. Veja a duplicidade do ano na legenda bibliográfica em cima do título do artigo

![Screen Shot 2020-09-17 at 16 20 44](https://user-images.githubusercontent.com/373745/93518045-ad3e1800-f902-11ea-93d6-b34faf1be6d9.png)

### Comportamento esperado

É esperado que o ano não seja duplicado.

### Ambiente utilizado

Ambiente de produção do site novo testado com **chrome** versão: 85.0.4183.102 (Official Build) (64-bit)

**Comment by robertatakenaka** [comment]
Possivelmente relacionado com https://github.com/scieloorg/packtools/pull/195

**Comment by gustavofonseca** [comment]
Ao acessar agora o link informado na descrição notei que o erro foi corrigido. Estou fechando o ticket.
