### ISSUE TITLE
Grade de fascículos apresenta fascículos em "Revisão". 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1656]
### Descrição do problema

Na revista BJMB(Brazilian Journal of Medical and Biological Research), existe fascículo com o label de "review" no site novo e ao acessar esse fascículo não é apresentado qualquer artigo.

### Passos para reproduzir o problema
1. Acesse a página https://new.scielo.br/j/bjmbr/grid
2. Veja que é apresentado nos anos de 2011 e 2009 um fascículo único com o label "review"
3. Clique no fascículo e veja que não há artigos.

### Comportamento esperado

No site clássico isso não acontence, desejamos que seja da mesma forma já que é um fascículo sem artigos.

### Screenshots ou vídeos

No site clássico: 
![Captura de Tela 2020-09-18 às 09 39 46](https://user-images.githubusercontent.com/373745/93598771-8b40a600-f993-11ea-9f8d-5392407ae133.png)

No site novo: 
![Captura de Tela 2020-09-18 às 09 44 49](https://user-images.githubusercontent.com/373745/93598810-9dbadf80-f993-11ea-9bc5-b0257e47d12c.png)

### Ambiente utilizado

Ambiente de produção do site novo e site clássico, testado com chrome versão: 85.0.4183.102 (Official Build) (64-bit)

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Pessoal realizando o ajuste para que esses fascículo de ``review`` não seja apresentado na grade do site, percebi que o kernel contém esses fascículos, vejam: 

https://kernel.scielo.br/bundles/0100-879X-2011-nreview

Está correto esses ``bundles`` existirem no “kernel”? e outra pergunta se alguém poder me ajudar por que esse fascículos existem?

**Comment by jamilatta** [comment]
A realização desse tíquete depende da definição do tíquete: https://github.com/scieloorg/kernel/issues/226

**Comment by gustavofonseca** [comment]
> Está correto esses `bundles` existirem no “kernel”? e outra pergunta se alguém poder me ajudar, por que esses fascículos existem?

Está correto no sentido de que existem os registros correspondentes na base _issue_. Esses fascículos foram criados para experimentar com um modelo de publicação (ou algo assim) para a BJMBR, mas que nunca foi em frente. Como o site clássico não exibe fascículos vazios, o lixo foi mantido na base até agora.

> A realização desse tíquete depende da definição do tíquete: scieloorg/kernel#226

Não vejo essa dependência. Podemos remover aqui no site e depois resolvemos no Kernel.

**Comment by jamilatta** [comment]
@gustavofonseca 

Para removermos da exibição do site será necessário verificar se o fascículo tem ou não artigo, não vejo outra opção. 

Como eu gostaria de evitar mais consultas na base de dados do **opac** e dessa forma evitar de deixar a página da grade com o payload maior, suspeito que por enquanto temos essa dependência.

@scieloorg/scielo-ps-developers 

Alguém teria uma sugestão melhor? Para não exibirmos um fascículo vazio na grade, segue os dados em base de dados: 

![Captura de Tela 2020-12-11 às 16 04 49](https://user-images.githubusercontent.com/373745/101943891-ab66b680-3bca-11eb-8dfb-bbbb40a9f2f2.png)

**Comment by gustavofonseca** [comment]
@jamilatta, basta remover 3 registros da base de dados do site, ou estou subestimando a atividade?

**Comment by jamilatta** [comment]
@gustavofonseca 

Pelo que conversarmos na daily, me parece que não está subestimando, irei realizar o ajuste!

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Pessoal olhando a base de dados do site, reparei que temos mais do que 3 fascículos nas mesmas condições, vejam: 

![Captura de Tela 2020-12-14 às 10 13 50](https://user-images.githubusercontent.com/373745/102085366-4a6ef680-3df5-11eb-9e22-59546d1d03d5.png)

**Comment by jamilatta** [comment]
Em anexo deixo um arquivo .jsonl contendo o conteúdo dos registros removidos.

[delete_nreview_issues.jsonl.zip](https://github.com/scieloorg/opac/files/5691091/delete_nreview_issues.jsonl.zip)
