### ISSUE TITLE
O endereço do artigo em PDF está incorreto para resoluções de telas iguais a de tablets

### ISSUE THREAD

**Issue by joffilyfe** [scieloorg/opac#1661]
### Descrição do problema

Ao acessar artigos publicados na plataforma SPF, é possível observar que ao alterar a resolução de tela entre `1024` e `1184`, os links para PDF estão utilizando o `pid v2` em vez de `pid v3`.

### Passos para reproduzir o problema
1. Acesse a página https://new.scielo.br/j/ensaio/a/wR4TH35MmLLvJhb43pkCXYc/
2. Altere a solução de sua janela para 1024;
3. Clique no botão de PDF;
4. Observe que o endereço é igual a https://new.scielo.br/j/ensaio/a/S0104-40362020000300672/?lang=en&format=pdf em vez de https://new.scielo.br/j/ensaio/a/wR4TH35MmLLvJhb43pkCXYc/?lang=en&format=pdf

### Comportamento esperado

Espera-se que exista consistência entre os links dos ativos/manifestações independente da resolução de tela do cliente.

### Screenshots ou vídeos

<img width="1121" alt="Screen Shot 2020-09-23 at 15 30 48" src="https://user-images.githubusercontent.com/4604104/94054298-ddc5fc00-fdb1-11ea-82fb-5fe1297b240c.png">

### Anexos
N/A

### Ambiente utilizado
N/A

**Comment by robertatakenaka** [comment]
@jamilatta este issue não faz mais sentido, o issue que estou resolvendo acabou resolvendo isso
