### ISSUE TITLE
Verificar o formato da data de publicação armazenada pelo SPF 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1665]
### Descrição do problema

Olhando o DSTeste verificamos que o formato da data está com um formato estranho.

### Passos para reproduzir o problema
1. Olhando a base de dados do DSTeste
2. Olhe para os registros e repare no formato da data:
```json
"publication_date" : "06 07 2020",
	"scielo_pids" : {
		"v2" : "S0006-87052020005008202",
		"v3" : "4zX3XJHcW9JzNspPKrnK4qG"
	},
```
3. Olhando nos dados de SciELO SP, verifique que o formato da data segue o seguinte formato:

```json
    "publication_date" : "2002-06",
```

Outro exemplo: 

```json
"abstract_languages" : [],
    "original_language" : "pt",
    "publication_date" : "2004",
    "type" : "editorial",

```

Essa data esta sendo inserida no momento da sincronização dos dados pela linha: https://github.com/scieloorg/opac-airflow/blob/75cdb87ad5b96bfb065485d4e593cbc01cf32c36/airflow/dags/operations/sync_kernel_to_website_operations.py#L222

O formato que o site aguarda é: **YYYY-MM-DD**(string)

Necessário avaliarmos uma solução.

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Segue um arquivo de exemplo de como está o formato da data em ambiente de produção: 

https://gist.github.com/jamilatta/8630bd21641a03b650ce89d4db59ce84

**Comment by jamilatta** [comment]
Olhando o como o site reparei que existe bastantes pontos em que utilizamos esse dado vejam: 

https://github.com/scieloorg/opac/search?q=publication_date

**Comment by robertatakenaka** [comment]
@jamilatta pelo: opac/tests/test_controller.py, já se sabe o esperado que é YYYY-MM-DD

Há 2 tipos de datas que estão inseridas desde a versão SPS 1.8.
- data real da publicação no SciELO que pode ser atrasada, adiantada ou em dia em relação à data editorial (do "fascículo"). Esta data é completa, contém dia. Chamamos de "pub".
- data editorial é a data "prevista" ou "esperada" ou relacionada a um fascículo. Por exemplo, digamos que os números sejam publicados a cada 3 meses. (Jan-Mar, Abr-Jun, Jul-Set, Out-Dec). Esta data geralmente não tem dia. Há inclusive casos em que só há o ano. Chamamos de "collection".

https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-date.html#elemento-pub-date

Dada esta informação talvez devemos ter 2 datas no opac.

**Observe que se um documento de 2010 entra atualmente no SciELO, sua data "pub", terá ano 2020. NO entanto sua data collection, o ano será 2010.**

**Comment by jamilatta** [comment]
Existe duas abordagens possíveis que visualizo, segue: 

1. Passa a pegar não mais o atributo ``text`` do **kernel:clea**, mas os atributos **[day, month, year]**, vejam: 

https://github.com/scieloorg/opac-airflow/blob/75cdb87ad5b96bfb065485d4e593cbc01cf32c36/airflow/tests/fixtures/kernel-document-front-s1518-8787.2019053000621.json#L274

2. Passar a realizar uma transformação no dado no ArticleFactory(https://github.com/scieloorg/opac_proc/blob/master/opac_proc/transformers/tr_articles.py#L195) algo como: 

```python
date = '03 08 2020'.split(" ")
print("-".join(date.reverse()))
'2020-08-03'
```
**IMPORTANTE**: a segunda abordagem resolve para todos as combinações entre [dia, mês, ano]

**Comment by robertatakenaka** [comment]
>     1. Passa a pegar não mas o atributo `text` do **kernel:clea**, mas os atributos **[day, month, year]**, vejam:

Este é o caso de um documento de publicação contínua. Tente ver um que tenha duas datas...

**Comment by jamilatta** [comment]
> @jamilatta pelo: opac/tests/test_controller.py, já se sabe o esperado que é YYYY-MM-DD
> 
> Há 2 tipos de datas que estão inseridas desde a versão SPS 1.8.
> 
> * data real da publicação no SciELO que pode ser atrasada, adiantada ou em dia em relação à data editorial (do "fascículo"). Esta data é completa, contém dia. Chamamos de "pub".
> * data editorial é a data "prevista" ou "esperada" ou relacionada a um fascículo. Por exemplo, digamos que os números sejam publicados a cada 3 meses. (Jan-Mar, Abr-Jun, Jul-Set, Out-Dec). Esta data geralmente não tem dia. Há inclusive casos em que só há o ano. Chamamos de "collection".
> 
> https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-pub-date.html#elemento-pub-date
> 
> Dada esta informação talvez devemos ter 2 datas no opac.
> 
> **Observe que se um documento de 2010 entra atualmente no SciELO, sua data "pub", terá ano 2020. NO entanto sua data collection, o ano será 2010.**

@robertatakenaka grato pela explicação, vou verificar se no **clea** temos as duas datas ["pub", "collection"]

**Comment by jamilatta** [comment]
> > ```
> > 1. Passa a pegar não mas o atributo `text` do **kernel:clea**, mas os atributos **[day, month, year]**, vejam:
> > ```
> 
> Este é o caso de um documento de publicação contínua. Tente ver um que tenha duas datas...

**Comment by robertatakenaka** [comment]
@jamilatta A Renata está me passando alguns fascículos de retrospectiva para confirmar as datas:

AIB v77n2
RBEM v21 n2-3
RAM-v6-n1
REP v22n3

**Comment by jamilatta** [comment]
@robertatakenaka 

Olhando o ``/front`` do kernel temos o atributo data tipo ``collection``, veja: https://kernel.scielo.br/documents/jhx5X7LJkJH7cKCZCkXBScg/front

![Captura de Tela 2020-11-24 às 08 26 49](https://user-images.githubusercontent.com/373745/100088422-d4e3bc00-2e2e-11eb-9853-3d22459bd391.png)


Como você havia comentado que seria interessante, termos às duas [`collection`, `pub`] datas no site novo... e olhando o  formato da data fique com algumas dúvidas e gostaria da sua ajuda para realizarmos isso da melhor forma, segue: 

- É suficiente termos apenas mais um campo ``text`` para armazenar essa data? 
- Olhando o ``clea`` o formato segue da seguinte forma: ``Jan-Fev 2015``, armazenamos nesse formato ou é necessária alguma conversão por conta de algum cálculo aritmético com datas?

Estou com a correção da data concluída, seria interessante definirmos esses pontos para que eu possa abrir o PR com esse ajuste também!

**Comment by robertatakenaka** [comment]
@jamilatta EITA!!!!
É porque está assim no XML... 
Agora não sei como podemos resolver isso... Certamente não é deixando literal, com certeza!

**Comment by jamilatta** [comment]
@robertatakenaka 

Entendi, o que acha de eu abrir o PR somente com a correção do ``publication_date`` e abrimos um tíquete para essa necessidade?

**Comment by robertatakenaka** [comment]
@jamilatta há uma questão anterior... o opac aceita mais de uma data?
porque cada um destas data tem um significado.

Talvez nem seja necessário traduzir o conteúdo de collection pensando que se for só para exibição.... (não sei se é ou não o caso)

**Comment by patymori** [comment]
@robertatakenaka e @jamilatta,

> há uma questão anterior... o opac aceita mais de uma data?
> porque cada um destas data tem um significado.

Teria que alterar o OPAC-Schema para ter datas diferentes.

> Talvez nem seja necessário traduzir o conteúdo de collection pensando que se for só para exibição.... (não sei se é ou não o caso)

Pelo que olhei, esta data é utilizada para 2 funcionalidades que passam a não funcionar com o problema:
1. Na ordenação dos artigos por mais novos/mais antigos no TOC
2. Na montagem da busca por Artigos Relacionados, que tenta pegar os 4 primeiros dígitos como sendo o ano YYYY

Para exibição, o dado é lido diretamente do XML, na renderização feita pelo packtools.

**Comment by jamilatta** [comment]
> @jamilatta há uma questão anterior... o opac aceita mais de uma data?
> porque cada um destas data tem um significado.
> 
> Talvez nem seja necessário traduzir o conteúdo de collection pensando que se for só para exibição.... (não sei se é ou não o caso)

Entendi! Bom como não vejo utilidade para data ``collection`` agora!!! Não vou adicionar isso nesse PR. 

Vou criar um tíquete para nossa avaliação.

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Sobre a questão da inclusão de mais um campo de data na base de dado do site.... criei um tíquete: https://github.com/scieloorg/opac/issues/1718
