### ISSUE TITLE
Alterar valor da metatag *citation_pdf_url* para a URL canônica do PDF

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1666]
Com o ticket https://github.com/scieloorg/opac/issues/1580, as URLs para as versões HTML e PDF dos artigos foi modificada de forma a tornar possível selecionar entre elas com o parâmetro `format` da _querystring_. Entretanto, o valor da _metatag_ `citation_pdf_url` não foi alterada para refletir a mudança. 

Exemplo do valor atual do elemento:
```xml
<meta name="citation_pdf_url" content="https://new.scielo.br/article/ssm/content/raw/?resource_ssm_path=/documentstore/1809-4392/VcRDh6ZwcKydkYbnkF8tbJk/abace0f3ea3623965e8ee2ec95031f5e6bd4de33.pdf">
```

Exemplo do valor desejado após a modificação (ao visualizar o documento em inglês):
```xml
<meta name="citation_pdf_url" content="https://new.scielo.br/j/aa/a/VcRDh6ZwcKydkYbnkF8tbJk/?format=pdf&lang=en">
```

**Comment by gustavofonseca** [comment]
Se relaciona, de alguma forma, com https://github.com/scieloorg/opac/issues/1661

**Comment by robertatakenaka** [comment]
@gustavofonseca Deve conter só o pdf de 1 idioma ou de todos os idiomas disponíveis?

**Comment by gustavofonseca** [comment]
> @gustavofonseca Deve conter só o pdf de 1 idioma ou de todos os idiomas disponíveis?

@robertatakenaka, deve ser a URL para o PDF no mesmo idioma em que o texto completo em HTML está sendo exibido na tela.
