### ISSUE TITLE
Artigo duplicado na coleção de Saúde Pública

### ISSUE THREAD

**Issue by julianafurlani** [scieloorg/opac#1685]
O artigo "Mestrado Profissional em Saúde da Família (ProfSaúde): uma experiência de formação em rede" da ICSE v24s1 está duplicado em SP:  https://scielosp.org/j/icse/i/2020.v24suppl1/

![image](https://user-images.githubusercontent.com/41448861/96296370-9522ec80-0fc5-11eb-97bd-ac9353ba33e6.png)

A revista faz parte da coleção BR e SP, mas o erro ocorre apenas em SP.

Nos sites http://homolog.xml.scielosp.org/scielo.php?script=sci_issuetoc&pid=1414-328320200003&lng=en&nrm=iso e http://homolog.scielosp.org/scielo.php?script=sci_issuetoc&pid=1414-328320200003&lng=en&nrm=iso o artigo aparece apenas 1 vez. 

O erro ocorre apenas em produção.

Segue o caminho para o artigo V:\SciELO\serial\icse\v24s1\1807-5762-icse-rpass-0120-24-s1

Poderiam verificar, por gentileza?

**Comment by jamilatta** [comment]
Avaliando essa duplicidade, descobrimos algumas coisas interessantes sobre: 

Verificamos que realmente o artigo está duplicado na base de dados do site(opac), vejam: 

<img width="1738" alt="Screen Shot 2020-10-19 at 15 50 30" src="https://user-images.githubusercontent.com/373745/96500656-97838180-1225-11eb-8d35-a4401580f59a.png">

Identificamos que temos 22 artigos nesse fascículo: 

<img width="1704" alt="Screen Shot 2020-10-19 at 15 50 52" src="https://user-images.githubusercontent.com/373745/96500735-ae29d880-1225-11eb-9988-c2db03c6177e.png">

Reparamos também que as data dos artigo são diferente, vejam: 

Um artigo é do dia **31/08/2020**: 

<img width="1656" alt="Screen Shot 2020-10-19 at 16 12 41" src="https://user-images.githubusercontent.com/373745/96500906-f9dc8200-1225-11eb-9692-0856a51eb3cd.png">

E outro é do dia **16/10/2020**:

<img width="1660" alt="Screen Shot 2020-10-19 at 16 12 32" src="https://user-images.githubusercontent.com/373745/96500944-082a9e00-1226-11eb-8e45-b1cfe7c2a940.png">


Mesmo com essas informações não foi possível identificar a causa raiz que nos levou a termos dois arquivo idênticos no site!

**Comment by robertatakenaka** [comment]
Na base ISIS do fascículo icse v24s1, há 21 documentos.

```
CRIAÇÃO          ATUALIZAÇÃO      ORDEM         XML
20200824         20200824         00201         icse/v24s1/1807-5762-icse-24-s1-e190513.xml
20200824         20200824         00202         icse/v24s1/1807-5762-icse-24-s1-e190524.xml
20200824         20200824         00203         icse/v24s1/1807-5762-icse-24-s1-e190531.xml
20200824         20200824         00204         icse/v24s1/1807-5762-icse-24-s1-e190622.xml
20200911         20200911         00206         icse/v24s1/1807-5762-icse-24-s1-e190449.xml
20200911         20200911         00207         icse/v24s1/1807-5762-icse-24-s1-e190472.xml
20200911         20200911         00208         icse/v24s1/1807-5762-icse-24-s1-e190578.xml
20200911         20200911         00209         icse/v24s1/1807-5762-icse-24-s1-e190609.xml
20200911         20200911         00210         icse/v24s1/1807-5762-icse-24-s1-e190629.xml
20200911         20200911         00211         icse/v24s1/1807-5762-icse-24-s1-e190630.xml
20200911         20200911         00212         icse/v24s1/1807-5762-icse-24-s1-e190664.xml
20200911         20200911         00213         icse/v24s1/1807-5762-icse-24-s1-e190707.xml
20200911         20200911         00300         icse/v24s1/1807-5762-icse-24-s1-e190548.xml
20200911         20200911         00301         icse/v24s1/1807-5762-icse-24-s1-e190584.xml
20200930         20200930         00214         icse/v24s1/1807-5762-icse-24-s1-e190487.xml
20200930         20200930         00215         icse/v24s1/1807-5762-icse-24-s1-e190634.xml
20200930         20200930         00216         icse/v24s1/1807-5762-icse-24-s1-e190640.xml
20201001         20201001         00205         icse/v24s1/1807-5762-icse-24-s1-e190441.xml
20201001         20201001         00217         icse/v24s1/1807-5762-icse-24-s1-e190600.xml
20201009         20201009         00218         icse/v24s1/1807-5762-icse-24-s1-e190628.xml
20201013         20201013         00200         icse/v24s1/1807-5762-icse-24-s1-e200192.xml
```

ENTRADA = data de entrada, primeira vez, identificada pelo sistema (XC)

**20201013** 00200 icse/v24s1/1807-5762-icse-24-s1-e200192.xml

Aparentemente, 1807-5762-icse-24-s1-e200192.xml entrou como se fosse um novo documento no dia 13/10.
A primeira vez foi em agosto (sabemos disso pelo registro na base do opac).

Se um documento é processado no XC mais de uma vez, ele tem uma data de criação que é mantida e a data de atualização é a data atual. Não sabemos o motivo pelo qual não foi registrado como uma atualização.
Talvez pode ter tido o order modificado? Aconteceu algo em particular com este documento?

**Comment by robertatakenaka** [comment]
@jamilatta acredito que resolvemos o problema se apagarmos pontualmente a segunda entrada no banco do opac.

**Comment by joffilyfe** [comment]
> @jamilatta acredito que resolvemos o problema se apagarmos pontualmente a segunda entrada no banco do opac.

Se houve um novo registro, podemos ter dados atualizados na segunda versão do documento, recomendo verificar qual é a versão mais atualizada. De inicio eu vi que os dois registros possuem dois XMLs diferentes com a seguinte mudança:

```diff
< 			<article-id pub-id-type="other">00251</article-id>
---
> 			<article-id pub-id-type="other">00200</article-id>
```

Também existem diferenças de PID, já que o `other` é diferente.

**Comment by julianafurlani** [comment]
Conversei com o responsável pelo processamento do artigo que me informou que houve alteração de other para correção de seção, provavelmente por isso está constando essa modificação no other em duas datas distintas. A versão correta é a que possui o other <article-id pub-id-type="other">00200</article-id>.

**Comment by jamilatta** [comment]
@julianafurlani 

Estamos removendo essa inconsistência da base de dados! Irei remover o PID com ordem **00251**.

**Comment by jamilatta** [comment]
Pessoal artigo removido!
