### ISSUE TITLE
Links para resumos de documentos que não possuem resumo na página /j/acron/i/issue_url

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1730]
### Descrição do problema
Issue TOC com documentos que não possuem abstract (https://new.scielo.br/j/asoc/i/2020.v23/ e https://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1414-753X20200001) tem links incorretamente exibidos na página. Ao clicar nos links, nada é exibido. 

### Passos para reproduzir o problema
1. Acesse a página https://new.scielo.br/j/asoc/i/2020.v23/
2. Observe que os primeiros documentos tem links para os resumos
3. Clique em um dos links de idiomas de resumos
4. Observe que nada é exibido

### Comportamento esperado
Links para exibir os resumos deveriam estar presentes no Issue TOC somente para os documentos que possuem resumo.

#### Artigos sem abstract

![Screen Shot 2020-12-07 at 11 41 32](https://user-images.githubusercontent.com/18053487/101396778-988e7200-38aa-11eb-87e5-40029a326f42.png)

### Ambiente utilizado
O problema foi detectado na nova instância do opac alimentada pelo SPF (https://new.scielo.br).

**Comment by robertatakenaka** [comment]
```
"abstract":"","abstract_languages":["en","pt","es"],"abstracts":[{"language":"en","text":""},{"language":"pt","text":""},{"language":"es","text":""}]
```

**Comment by carolinatanigushi** [comment]
Não tenho certeza se é relevante, mas também acontece no Search: https://github.com/scieloorg/search-journals/issues/443
