### ISSUE TITLE
Resumos passíveis de extração pelo Google Scholar

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1762]
### Descrição da nova funcionalidade
O Google Scholar não está conseguindo extrair os resumos dos artigos nos sumários por conta de estarem sendo exibidos por meio de recurso de expandir/colapsar.

A sugestão do Google Scholar é que os resumos sejam exibidos em sua própria landing page.

Mensagem original do Google Scholar:

> 1. Would it be possible to add separate abstract pages, as for the current site? 
> 
> Details: The site has a TOC setup like: 
> https://new.scielo.br/j/aa/i/2020.v50n3/
> 
> These abstracts are just dropdowns to expand text on the TOC page, not separate pages. 
> 
> The crawler wouldn't be able to handle this. For abstracts to be crawled, the abstract links would point out to separate HTML landing pages as for the current abstract pages. 
> The current site has a TOC setup like:
> 
> https://www.scielo.br/cgi-bin/wxis.exe/iah/
> 
> where links point to abstract page like https://www.scielo.br/scielo.php?script=sci_abstract&pid=S0044-59672020000300204&lng=en&nrm=iso&tlng=en
> 
> and these pages have metatags and link to PDF
> 
> Would this be possible?

### Critérios de aceitação

Os resumos devem ser passíveis de indexação pelo Google Scholar.
Os resumos devem ser acessíveis também por serem humanos por meio de interface, seguindo as definições do Design System do SciELO.

### Anexos
N/A

### Referências
Depende de https://github.com/scieloorg/packtools/issues/246

**Comment by paratiuid** [comment]
@alexxxmendonca 

Segue o protótipo de como imaginamos essa interação:

https://www.figma.com/proto/nf3CmbAdOCYoxIb3akFjkB/Resumo-artigo-Opac?node-id=27%3A4373&viewport=-159%2C-613%2C0.5&scaling=min-zoom

Aguardo retorno.

**Comment by alexxxmendonca** [comment]
@paratiuid Tenho dúvidas se devemos exibir todos os títulos do artigo (traduções) e do tamanho dos títulos, mas isso pode ficar para outro momento.

Poderia confirmar se a proposta atende às necessidades do Google Scholar?

**Comment by paratiuid** [comment]
@alexxxmendonca 

sim, 

a idéia é que seja utilizado um parâmetro na url do mesmo modo como mencionado na descrição do ticket.

https://www.scielo.br/scielo.php?script=sci_abstract&pid=S0044-59672020000300204&lng=en&nrm=iso&tlng=en

O final EN identifica o idioma ingles, e exibe uma página exclusiva do resumo naquele idioma.

Cada link de resumo deve apontar para um idioma distinto e portanto, abrirá uma página exclusiva no idioma selecionado.

**Comment by alexxxmendonca** [comment]
@paratiuid perfeito.

Considerando que atende à necessidade original do ticket, está aprovado.

**Comment by gustavofonseca** [comment]
@alexxxmendonca e @paratiuid, a proposta ficou ótima. Não pude deixar de notar que alguns aspectos divergem do design atual, como por exemplo a fonte utilizada, o menu de navegação etc. Essas divergências serão ignoradas ou há algum outro plano?

**Comment by paratiuid** [comment]
@gustavofonseca 

conforme solicitado pelo @alexxxmendonca a proposta foi criada já baseada no projeto do design system que está em andamento.

Nesse primeiro momento vamos apenas incluir a funcionalidade para atender a demanda do Google Scholar. Todas as alterações de layout referente ao design system devem ocorrer com a atualização das folhas de estilo.

Portanto, o foco é na funcionalidade de exibição do resumo. As atualizações de estilos serão realizadas ao término do projeto design system.

**Comment by paratiuid** [comment]
Boa tarde @alexxxmendonca, @gustavofonseca 

conversei ontem com o @joffilyfe  para entender bem como funciona a construção de uma nova página no Opac utilizando templates existentes. Ele me explicou que existe um arquivo views.py que é responsável pela criação da url. Por se tratar de um arquivo python, ele citou que qualquer ajuste nestes arquivos devem ser feitos pela equipe SciELO, pois envolvem uma série de decisões técnicas.

Sendo assim, entendemos que a maneira mais rápida de eu entregar essa atividade é criando um template em html.
Esse template herdará todas as classes css já existentes no sistema e apenas exibirá as informações já decididas no mockup. Após a entrega desse template, a equipe da SciELO deverá editar no arquivo views.py citado acima, uma função que será responsável pela criação da url única para cada resumo em seu respectivo idioma. Além disso o template entregue por mim deverá receber as variáveis responsáveis pela exibição dos conteúdos como título, resumo, etc.

**Comment by gustavofonseca** [comment]
> Boa tarde @alexxxmendonca, @gustavofonseca
> 
> conversei ontem com o @joffilyfe para entender bem como funciona a construção de uma nova página no Opac utilizando templates existentes. Ele me explicou que existe um arquivo views.py que é responsável pela criação da url. Por se tratar de um arquivo python, ele citou que qualquer ajuste nestes arquivos devem ser feitos pela equipe SciELO, pois envolvem uma série de decisões técnicas.
> 
> Sendo assim, entendemos que a maneira mais rápida de eu entregar essa atividade é criando um template em html.
> Esse template herdará todas as classes css já existentes no sistema e apenas exibirá as informações já decididas no mockup. Após a entrega desse template, a equipe da SciELO deverá editar no arquivo views.py citado acima, uma função que será responsável pela criação da url única para cada resumo em seu respectivo idioma. Além disso o template entregue por mim deverá receber as variáveis responsáveis pela exibição dos conteúdos como título, resumo, etc.

Após análise, percebi que a abordagem mencionada acima apresenta alguns desafios técnicos, que são: (a) títulos que embutem MathML ou LaTeX serão apresentados de maneira incorreta, (b) paridade entre a implementação do _HTMLGenerator_ e a com templates JINJA, (c) reimplementação de diversos componentes, como a forma citada do documento e eventuais serviços agregados. 

Nesta perspectiva, estou avaliando a complexidade de tornar a XSLT do _HTMLGenerator_ capaz de omitir o texto completo de forma a produzir a página do artigo. Caso funcione, o resultado final ficará ligeiramente diferente do que foi apresentado pela @paratiuid e mais próximo da página atual do texto completo do documento. @alexxxmendonca, me diga  por gentileza se isso for um problema.

**Comment by alexxxmendonca** [comment]
@gustavofonseca não vejo problema nesta abordagem.

Aguardo seu parecer final.

**Comment by robertatakenaka** [comment]
@gustavofonseca @alexxxmendonca fiz um experimento de colocar os links para os textos completos e os resumos junto com o link do pdf. Vejam as imagens abaixo.

Então, sugerem quais opções?

1. Colocar Textos (similar ao que há para PDF), de todos os idiomas, na página de resumo
2. Colocar Textos (similar ao que há para PDF), de todos os idiomas, nas páginas de resumo e de texto completo
3. Colocar Texto (ao lado de "PDF"), com link para o texto só no idioma que corresponde ao resumo e só na página do resumo
4. Colocar Resumos (similar ao que há para PDF), de todos os idiomas, exceto aquele q já está aberto, só na página do resumo
5. Colocar Resumos (similar ao que há para PDF), de todos os idiomas, nas páginas de resumo e de texto completo
6. Não colocar nenhum link para resumo em nenhuma página
7.  Não colocar nenhum link para texto completo em nenhuma página

<img width="576" alt="Captura de Tela 2021-03-16 às 10 55 16" src="https://user-images.githubusercontent.com/505143/111322328-9412eb80-8647-11eb-9b66-bac7250123ae.png">
<img width="576" alt="Captura de Tela 2021-03-16 às 10 55 25" src="https://user-images.githubusercontent.com/505143/111322341-970ddc00-8647-11eb-81f6-6f90308ea5e9.png">

**Comment by alexxxmendonca** [comment]
Estou de acordo com a sugestão do @gustavofonseca (2 e 5). Concordo que é importante oferecermos acesso a todos os idiomas de texto, resumo e pdf a partir de qualquer ponto.

**Comment by robertatakenaka** [comment]
@alexxxmendonca minha dúvida é se estando no resumo português, por exemplo, se na lista mostro o resumo em português, ou mostro com um destaque (mas qual? de forma que o usuário saiba que já está nele), ou não mostro o resumo em português na lista. O mesmo vale para o texto completo

**Comment by alexxxmendonca** [comment]
@robertatakenaka eu sou a favor de mostrar com um destaque. 

Prefiro evitar não mostrar com a justificativa de que o usuário esteja naquela página.

@paratiuid, que tipo de destaque poderia ser dado aqui, levando em conta o trabalho que estamos fazendo de Design Systems?

**Comment by robertatakenaka** [comment]
@alexxxmendonca concordo. Também prefiro dar algum destaque. Só fica difícil de saber como.

**Comment by paratiuid** [comment]
Assim como @gustavofonseca e @alexxxmendonca , também concordo com as versões  2 e 5. 

Sobre o destaque a ser dado ao idioma selecionado, acredito que podemos seguir o seguinte modelo:

<img width="181" alt="Screen Shot 2021-03-24 at 2 41 59 PM" src="https://user-images.githubusercontent.com/22373640/112359751-5c8fe900-8cb0-11eb-859a-567c19f4e324.png">
 

<img width="175" alt="Screen Shot 2021-03-24 at 2 42 19 PM" src="https://user-images.githubusercontent.com/22373640/112359831-716c7c80-8cb0-11eb-8760-dd74683bed5a.png">


Precisamos ficar atentos em como serão mostrados estes botões nas versões para celular e tablet além do desktop.

**Comment by alexxxmendonca** [comment]
Eu gostei da solução. Me chamou a atenção somente o uso do termo "PT-BR". Acredito que estamos usando somente "PT" em outros lugares onde o idioma aparece.

Não sou particularmente a favor ou contra de um ou outro, mas sou a favor de sermos consistentes.

**Comment by paratiuid** [comment]
@alexxxmendonca 
concordo. O correto é utilizar somente PT.

**Comment by robertatakenaka** [comment]
@paratiuid é só mandar isso em html

**Comment by gustavofonseca** [comment]
Excelente @paratiuid.

**Comment by paratiuid** [comment]
Pessoal, 

mostrei hoje para o @alexxxmendonca  as telas com os botões de resumo, texto e pdf já ajustados no grid para as telas no modo responsivo. Ele pediu para que eu compartilhasse aqui no ticket para que todos possam opinar.

As telas foram atualizadas com os componentes do design system. Alguns componentes podem estar diferentes de como são exibidos hoje. Peço que vocês avaliem apenas a região que contém os botões de navegação. Onde foram incluídos os botões "Resumo", "Texto" e atualizado o botão de "PDF".

A proposta é que o idioma selecionado apareça somente no dropdown da página em questão. Exemplo:

Estou lendo o resumo em português.
O Dropdown do resumo exibe o label "Resumo (PT)".

Estou lendo o artigo completo em inglês
O Dropdown do texto exibe o label "Texto (EN)".


Outro item importante:
No mobile, penso que os botões de navegação acabam ocupando muito espaço útil. Desse modo, fiz uma sugestão onde os botões "anterior", "atual" e "seguinte" são ocultados.
Da mesma forma ocorre na versão tablet Vertical.

Seguem as imagens. Aguardo os comentários de vocês.

Mobile v1
![mobile-v1](https://user-images.githubusercontent.com/22373640/114244837-9b3aca00-9965-11eb-9662-f7c4465cef80.jpg)

Mobile v2
![mobile-v2](https://user-images.githubusercontent.com/22373640/114244860-a68df580-9965-11eb-9f2f-9e0b5e00f17d.jpg)

Tablet Vertical
![tablet-vertical](https://user-images.githubusercontent.com/22373640/114244880-b279b780-9965-11eb-9ab1-675b19afaf26.jpg)

Tablet Horizontal
![tablet-horizontal](https://user-images.githubusercontent.com/22373640/114244903-bdcce300-9965-11eb-8d0e-954d930528ff.jpg)

Desktop
![desktop](https://user-images.githubusercontent.com/22373640/114244933-cf15ef80-9965-11eb-92ff-e761dbe76d64.jpg)

**Comment by jamilatta** [comment]
@paratiuid 

Gostei bastante da versão onde os botões "anterior", "atual" e "seguinte" são ocultados, penso que em dispositivos móveis não teremos mesmos as mesmas funções em comparação a “interface” em desktop, **porém realizaria ajustes no tamanho da fonte do título**, repare que o título na versão em dispositivos móveis ocupa grande parte da tela e removeria no mobile o botão de "Copiar", outro componente que está com muito destaque.   

Nessa mesma linha o usuário conta com a opção de navegar pelo "sumário".

Portanto, voto na versão "**Mobile v2**".

**Comment by alexxxmendonca** [comment]
@paratiuid 

Eu já havia manifestado minha opinião a favor do Mobile v2 em nossa reunião, mas aproveito para deixar registrado aqui também.

O argumento a favor desta versão é que a leitura das funções é menos confusa para o usuário, além de ocupar menos área útil, como já dito.
O argumento contra esta versão é que ela difere das demais versões, quebrando-se a consistência entre as interfaces. Contudo, o usuário ainda consegue navegar entre os artigos ao acessar o sumário, portanto apesar de quebrar a consistência, ainda é possível obter o mesmo resultado com alguns passos a mais. 

Importante destacar que isso aplica-se somente na interface mobile. A consistência é preservada nas demais interfaces.

E concordo com o comentário do @jamilatta sobre o tamanho dos títulos. Embora aqui não seja o local ideal para conversarmos sobre isso, acredito que o tamanho dos títulos deverá ser revisado nas interfaces não-desktop.

**Comment by paratiuid** [comment]
@alexxxmendonca @jamilatta @gustavofonseca

Pessoal,  
atualizei meu comentário incluindo mais uma possibilidade para o mobile.

Na v3, o foco fica mais direcionado ao conteúdo. Mantendo na parte superior apenas  link para home,  sumário e share.
O menu que indica o conteúdo que está sendo exibido e as outras possibilidades de conteúdo está posicionado abaixo do conteúdo.

Ele  deve ficar flutuante, colado a margem inferior do dispositivo.

Peço que avaliem essa possibilidade também, por favor.

**Comment by alexxxmendonca** [comment]
@paratiuid ainda prefiro a v2

**Comment by gustavofonseca** [comment]
Sugiro que por hora a gente siga com a v2, conforme a preferência do @alexxxmendonca. Algo me diz que muito em breve nós teremos oportunidade de colocar mais energia no redesign deste site, inclusive com a  aplicação do _design system_.

**Comment by alexxxmendonca** [comment]
@paratiuid 

Vamos seguir com a v2 então, por favor.

**Comment by alexxxmendonca** [comment]
Melhoria já aplicada em produção.
