### ISSUE TITLE
Retirar o arquivo robots.txt da implementação do site

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1775]
### Descrição da tarefa
Retirar o arquivo robots.txt da implementação do site

## Considerações e notas
* Verificar com a infra se ok retira este arquivo robots.txt
* Foi inserido por caracter paliativo, mas agora precisa ser removido.

**Comment by patymori** [comment]
Este arquivo não está sendo usado. Na instância da coleção BR, por mais que o arquivo esteja lá, não há configuração no proxy apontando para ele, enquanto na instância de SP há a configuração que aponta para um arquivo configurado pela infraestrutura. É necessário lembrar de fazer a mesma configuração usada em SP na instância do novo site da coleção BR.

**Comment by gustavofonseca** [comment]
Eu não consegui entender a justificativa desta tarefa e constatei após o commit 69a8240e1b378f20e4379158b36855e214c3add5 que o arquivo é sim usado. Se eu tiver comido bola basta reabrir o ticket, mas por hora vou fechar.
