### ISSUE TITLE
A aplicação não especifica conexão com replicaset MongoDB

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1780]
### Descrição da tarefa
Permitir que, através de configuração, determine-se a conexão com replicaset MongoDB e preferência de leitura.

**Comment by patymori** [comment]
A variável `OPAC_MONGODB_HOST` é usada para configurar `MONGODB_SETTINGS["host"]`, que também suporta DSN, conforme [documentação de configuração do Flask Mongoengine](http://docs.mongoengine.org/projects/flask-mongoengine/en/latest/#configuration).

Para configurações de replicaset e preferência de leitura, é possível informar através da própria URI, conforme [documentação do MongoDB](https://docs.mongodb.com/manual/reference/connection-string/#read-preference-options).

Também sobre configurar preferência de leitura, a opção _nearest_ é a que conecta no node com menor latência, tratando primário e secundários igualmente.

**Comment by gustavofonseca** [comment]
O ticket #1770 reporta o mesmo problema que este.

**Comment by patymori** [comment]
Após realização de testes de performance, foi identificado que, mesmo com a configuração do DSN, as conexões foram direcionadas somente para o node primário.
