### ISSUE TITLE
R7. O sistema dever permitir associar um logotipo a instância.

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#18]
## Dependência:

- [R6]

## Problema:

O sistema deve permitir gerir um logo para a coleção.

## Objetivo:

1. Acrescentar a funcionalidade que permita que um usuário administrador possa associar um logo, no modelo da coleção, utilizando a interface de administração (*admin*).
2. Acrescentar a funcionalidade que permita que um usuário administrador possa remover o logo, no modelo da coleção, utilizando a interface de administração (*admin*).
3. Por padrão o logo da coleção será uma imagem genérica (logo SciELO).

## Caso de Uso:

*pendente*

[R6]: https://github.com/scieloorg/opac/issues/17

**Comment by jamilatta** [comment]
Esse ticket será resolvido no momento que o tk #17 for concluído.
