### ISSUE TITLE
Disponibilizar dicionário para aplicação de contagem de acessos

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/opac#1814]
### Descrição da nova funcionalidade
Eu, como **usuário da aplicação de contagem de acessos Matomo & COUNTER & SUSHI**, gostaria que **fosse disponibilizado, via URL, um JSON que mapeia PIDs no formato V3 a dados como ano de publicação, outras versões de PID e idioma padrão**, então **seria possível requisitar essa informação periodicamente**.

### Critérios de aceitação

- O JSON retornado deve conter, pelo menos: PID v3, PID v2, PID v1, PID ahead of print (se houver), ano de publicação e idioma padrão.
- Deve-se limitar a consulta a, no máximo, 31 dias de dados.
- Deve-se ser capaz de solicitar um mês qualquer, ainda que incompleto (por exemplo: ao solicitar março de 2021 serão retornados todos os dados entre 1º de março de 2021 e hoje (22 de março).
- Espera-se obter o JSON por meio de uma consulta como [new.scielo.br/api/v1/access-counter-dict/?dates=2020-03](new.scielo.br/api/v1/access-counter-dict)
- O parâmetro `dates` pode ser qualquer data do tipo YYYY-MM.  O comportamento padrão, caso `dates` não seja informado, é retornar dados desde o dia 1º do mês atual até o dia da requisição.
- É desejável também ser capaz de informar um parâmetro `start_date`, data a partir da qual os últimos 31 dias de dados serão obtidos.

### Anexos
Os insumos serão utilizados para:
- Contabilização de acessos no contexto de relatórios COUNTER R5;
- Contabilização de métricas relacionadas ao idioma dos insumos acessados;
- Estudo de métricas relacionadas a acessos a Preprints e respectivas versões finais.
- Segue um estrutura básica de retorno desejado:

```
{
    "creation_date": "2020-03-22 18:12:30.000",
    "platform": "SciELO Brasil",
    "documents": [
        {"j6wLCh97nFmTrK7V6wC7LdP": {
            "journal_acronym": "alb",
            "pid_v2": "", 
            "pid_v1": "", 
            "pid_ahead": "", 
            "year_of_publication": "2020", 
            "default_language": "en"},
        {"Rf9kdMRv4JVzRvR5wM8yPJf": { 
            "journal_acronym": "reben",
            ...,
            "default_language": "en"},
        ...
    ]
}
```

### Referências
- Para uma breve descrição das atividades Matomo & COUNTER & SUSHI, consulte [este documento](https://docs.google.com/document/d/1gbH-GC4nmLqNloiwxZ4lNR3aAG0nXcwsXcUbnhXSuCM).
- Esta tarefa faz parte da tarefa [Contabilizar acessos ao novo site](https://github.com/scieloorg/access-counter/issues/12)

**Comment by rafaelpezzuto** [comment]
@gustavofonseca Por favor, verifique se faltou algo.

**Comment by gustavofonseca** [comment]
@rafaelpezzuto, acho que não faltou nada. 

Só uma dúvida. Nos critérios está que "O parâmetro dates pode ser qualquer data do tipo YYYY-MM. Caso não seja informado, devem ser retornados os últimos 31 dias, a partir da data de requisição.". O comportamento padrão do parâmetro não deveria ser retornar desde o dia 1 do mês atual até o dia da requisição?

**Comment by rafaelpezzuto** [comment]
@gustavofonseca Sim, deveria. Descrição corrigida.
