### ISSUE TITLE
[SciELO SP] Acesso a documento aponta erro "pid: None"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#1863]
### Descrição do problema
Ao acessar o documento de URL https://scielosp.org/scielo.php?script=sci_arttext&amp;pid=S0864-34662009000300012, o site retorna o seguinte erro:

![image](https://user-images.githubusercontent.com/4059679/116882294-aa2a3a80-abfa-11eb-8d0b-5cde1290d518.png)

### Passos para reproduzir o problema
1. Acesse a página https://scielosp.org/scielo.php?script=sci_arttext&amp;pid=S0864-34662009000300012
2. Observe o erro apresentado

### Comportamento esperado
Exibir o documento solicitado.

OBS: a mensagem de erro em si apresenta um erro de digitação: "Requsição" (falta uma letra "i")

**Comment by jamilatta** [comment]
@alexxxmendonca 

Pelo que olhei aqui a URL está errada, veja na composição da URL que temos um **&amp;**.... o correto é somente o **&**. 

Teste remover o **&amp;** e acessar novamente, assim 

https://scielosp.org/scielo.php?script=sci_arttext&pid=S0864-34662009000300012

**Comment by alexxxmendonca** [comment]
@jamilatta Entendo!

Foi um e-mail que recebemos na conta webmaster. Eu perguntei ao usuário onde ele havia encontrado o link e a resposta dele foi:

> Foi feito um levantamento bibliográfico e registrado todo o resultado numa planilha de excell, logo na planilha aparece uma janelinha com o link desse material que direcionava ao erro que reportei a vcs.

Vou assumir então que foi um erro de digitação do responsável pelo preenchimento da planilha.

Vou fechar o ticket, de qualquer forma, fica o alerta para o erro de ortografia:
OBS: a mensagem de erro em si apresenta um erro de digitação: "Requsição" (falta uma letra "i")
