### ISSUE TITLE
Erro ao utilizar o "Reportar Erro" com Varnish.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1865]
### Descrição do problema

Ao utilizarmos o modal para notificar sobre um problema no site é possível notar que estamos com erro.

### Passos para reproduzir o problema
1. Acesse a página http://new.scielo.br
2. Clique em: 
![Captura de Tela 2021-05-03 às 10 58 06](https://user-images.githubusercontent.com/373745/116885681-89fc7a80-abfe-11eb-842d-d5fcdd7131d6.png)

3. Preencha os dados necessários 
4. Verifique a msg de erro: 
![Captura de Tela 2021-05-03 às 11 00 54](https://user-images.githubusercontent.com/373745/116885930-d9db4180-abfe-11eb-89a8-f707d4c4d12b.png)

O AJAX utilizado como solução retorna um 404, veja: 

![Captura de Tela 2021-05-03 às 11 02 26](https://user-images.githubusercontent.com/373745/116886183-2030a080-abff-11eb-8450-600ac8b74b9d.png)

### Comportamento esperado
É esperado pelo usuário uma msg de sucesso de envio. 

**Importante:** Ao desligarmos ou utilizarmos o ambiente de desenvolvimento esse erro não é apresentado.

**Comment by gustavofonseca** [comment]
O erro foi corrigido, mas não tenho mais detalhes.
