### ISSUE TITLE
Painel *Números mais recentes* exibem ahead-of-print

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#1866]
No painel _Números mais recentes_, presente na página inicial do site, são exibidos os números mais recentemente publicados dentro do conjunto de periódicos ativos da coleção. O problema é que a implementação atual não restringe a números propriamente ditos, mas também está exibindo números do tipo _ahead-of-print_, conforme o exemplo:

![Screen Shot 2021-05-03 at 11 09 52](https://user-images.githubusercontent.com/161335/116887192-69352480-ac00-11eb-86a0-b30d872b39a2.png)

Isso acontece pois, na modelagem de dados do site os documentos _ahead-of-print_ estão contidos em contêiners idênticos aos utilizados para representar os números, e a aplicação não está fazendo nenhuma diferenciação na hora de montar o painel, que segundo o título, deveria conter apenas números.

Minha sugestão é que o painel exiba exclusivamente links para números, excluindo _ahead-of-print_. @alexxxmendonca, está de acordo?

**Comment by alexxxmendonca** [comment]
@gustavofonseca considerando que o label diz "**números** mais recentes", sim, estou de acordo com esta filtragem.
