### ISSUE TITLE
R10. O sistema dever permitir definir uma licença padrão para o site.

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#19]
## Problema:

O sistema não tem e não permite definir uma licencia padrão(?) (do que?).

## Objetivo:

*pendente* (falta contexto)

## Caso de Uso:

*pendente*

**Comment by jfunez** [comment]
@jamilatta acho que ficou pendente dar uma melhorada na descrição deste issue.

**Comment by jamilatta** [comment]
Sim, precisamos pensar sobre esse ticket para definirmos a melhor forma de
fazermos isso... se quiser iniciar depois discutirmos sobre ele.

On Fri, Jan 22, 2016 at 1:54 PM, Juan Funez <notifications@github.com>
wrote:

> @jamilatta <https://github.com/jamilatta> acho que ficou pendente dar uma
> melhorada na descrição deste issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/opac/issues/19#issuecomment-173959801>.
>



-- 

Jamil Atta Junior

**Comment by jamilatta** [comment]
Esse ticket será resolvido no momento que o tk #17 for concluído.
