### ISSUE TITLE
Possibilitar exportação dos artigos em formato XML

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/opac#1917]
### Descrição da nova funcionalidade
Eu, como **usuária do site**, gostaria que **houvesse a possibilidade de exportar o artigo em formato XML**, como **era possível no site antigo**.

![image](https://user-images.githubusercontent.com/12699183/119710765-22200500-be35-11eb-920f-03caea557f34.png)

### Critérios de aceitação
Possibilidade de exportar artigos em formato XML.

### Anexos
Este ticket surgiu da [solicitação de um usuário pelo Twitter](https://twitter.com/ericbrasiln/status/1397603728560099328): 

> Parabéns pelo novo site, entretanto não há opção de baixar artigo em formato XML, como existia na versão antiga, mesmo o link constando no código-fonte dos artigos.  Essa opção é importante p pesquisas variadas, de humanidades digitais sobretudo. 
 Pretendem incluir?

**Comment by ericbrasiln** [comment]
Reforço a sugestão da @carolinatanigushi .
Fiz essa sugestão no twitter justamente pq tenho trabalhado com ferramentas digitais de pesquisa e os arquivos XML são muito importantes. 
Como o link para o XML já se encontra no código-fonte da página de cada artigo, imagino que a inclusão do botão para download não seja uma alteração muito grande.
Agradeço a atenção
![xml](https://user-images.githubusercontent.com/58128421/119715649-9b6e2680-be3a-11eb-9cf8-60ab8b4fe2bd.jpeg)

**Comment by gustavofonseca** [comment]
Relacionado com https://github.com/scieloorg/opac/issues/1667

**Comment by gustavofonseca** [comment]
Considero que há a possibilidade de exportação em formato XML com o uso do parâmetro `?format=xml`, portanto vou fechar este ticket.
