### ISSUE TITLE
Ao compartilhar um artigo o link apresentado nas "redes sociais" apresenta apenas www.scielo.br

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#1950]
### Descrição do problema
Ao compartilhar um artigo o link apresentado nas "redes sociais" apresenta apenas www.scielo.br e o esperado é o título do documento.

### Passos para reproduzir o problema
1. Acesse a página de um artigo
2. Copie o link e tente compartilhar em uma rede social
3. Observe a ausência de título apresentado
<img width="345" alt="Captura de Tela 2021-06-17 às 16 19 05" src="https://user-images.githubusercontent.com/505143/122459927-e554b300-cf87-11eb-81e4-03a07e7eb9f7.png">

### Comportamento esperado
Ao compartilhar o documento numa rede social, por exemplo, no FB, que o título do artigo seja apresentado.
Exemplo:
<img width="494" alt="Captura de Tela 2021-06-30 às 13 01 16" src="https://user-images.githubusercontent.com/505143/123994101-6dcd4d80-d9a3-11eb-823c-a0b6abf67e36.png">

### Screenshots ou vídeos
funciona
<img width="1433" alt="Captura de Tela 2021-06-30 às 13 09 04" src="https://user-images.githubusercontent.com/505143/123995187-74a89000-d9a4-11eb-90e1-593881124680.png">

não funciona
<img width="1165" alt="Captura de Tela 2021-06-30 às 13 10 43" src="https://user-images.githubusercontent.com/505143/123995418-b2a5b400-d9a4-11eb-8716-8eb7ca99cf6c.png">

### Anexos
n/a

### Ambiente utilizado
www.scielo.br

### IMPORTANTE
Aparentemente o problema é que `<title>` não é uma das primeiras
 tag dentro de `<head/>` e também o título está duplicado.

**Comment by jamilatta** [comment]
@robertatakenaka 

Avaliando essa atividade percebi que existe um "protocolo" para o compartilhamento que se chama "[Open Graph](https://ogp.me/)". 

A url: **http://old.scielo.br** está trazendo o título no momento do compartilhamento graças ao analisador de tags brutas do facebook, porém isso não ocorre de forma correta para todas as páginas. 

Utilizando o analisado do facebook em modo de depuração é possível verificar erros.

 Veja: 

![Captura de Tela 2021-07-04 às 12 40 16](https://user-images.githubusercontent.com/373745/124391051-0bd35780-dcc5-11eb-94ec-0335c78a67d1.png)

Em resumo o analisador do facebook através de IA utiliza algumas tags brutas e faz a correspondência para tags "Open Graph". 

Note que na imagem ele pegou como imagem o **scimago**(errado). 

Portanto, o correto é adicionarmos as tags do "Open Graph" que funcionará para qualquer rede social que realize uma introspecção nas nossas páginas. 

**Links relevantes para essa atividade:**

- Depurador de compartilhamento do facebook: https://developers.facebook.com/tools/debug/
- Open Graph Protocol: https://ogp.me/
- Guia de compartilhamento: https://developers.facebook.com/docs/sharing/webmasters/
- Tutorial: https://neilpatel.com/blog/open-graph-meta-tags/

**Comment by robertatakenaka** [comment]
@jamilatta Faltou um detalhe que o título aparece duas vezes. Há um template em que ele duplica o título. Mas eu vou aprovar este PR e vc ajeita numa próxima iteração.

<img width="1378" alt="Captura de Tela 2021-07-05 às 07 47 04" src="https://user-images.githubusercontent.com/505143/124460294-9370a300-dd65-11eb-99a4-989384cbaed6.png">

**Comment by jamilatta** [comment]
@robertatakenaka é interessante antes de atualizarmos o ambiente de produção, testarmos em ambiente de homologação para podermos verificar os resultados no depurador: https://developers.facebook.com/tools/debug/

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Importante ressaltar que essas tags adicionadas também contempla o whatsapp.

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Após atualização dessa atividade verificamos utilizando o depurador do facebook que temos um problema que impede de obter os dados das tags, para o facebook. 

https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fwww.scielo.br%2Fj%2Fep%2Fa%2FrZmk4fQgds6vjhfRQkPqTqz%2F%3Flang%3Dpt

Pesquisando sobre, achei os seguintes links sobre o erro:

- https://rameerez.com/facebook-sharing-not-scraping-url-correctly-with-https-links/
- https://victorlava.com/how-to-fix-curl-60-ssl_cacert-cant-validate-ssl-certificate/
- https://whatsmychaincert.com/?scielo.br

Olhando no https://www.opengraph.xyz/ tem validador para outras mídias: 

Facebook: https://developers.facebook.com/tools/debug/

Twitter: https://cards-dev.twitter.com/validator

LinkedIn: https://www.linkedin.com/post-inspector/

Pinterest: https://developers.pinterest.com/tools/url-debugger/

Note que tem validador que funciona, porém alguns retorno erro.

**Comment by jamilatta** [comment]
Veja o que o validador do twitter retorna: 

![Captura de Tela 2021-07-05 às 17 37 43](https://user-images.githubusercontent.com/373745/124516799-ec1d5b80-ddb8-11eb-862e-f81f1a72d6b2.png)

Para o LinkedIn: 

![Captura de Tela 2021-07-05 às 17 47 01](https://user-images.githubusercontent.com/373745/124516880-1242fb80-ddb9-11eb-8f9a-b3e2ae7418c6.png)

Pintrest: 

![Captura de Tela 2021-07-05 às 17 48 07](https://user-images.githubusercontent.com/373745/124516948-356dab00-ddb9-11eb-8765-a77b23f21de1.png)

![Captura de Tela 2021-07-05 às 17 48 13](https://user-images.githubusercontent.com/373745/124516953-369ed800-ddb9-11eb-8138-a48bb0fea7e9.png)

Site do open graph: 

![Captura de Tela 2021-07-05 às 17 49 06](https://user-images.githubusercontent.com/373745/124517034-5cc47800-ddb9-11eb-9b87-fd5d14eb9ca6.png)

**Comment by jamilatta** [comment]
@scieloorg/scielo-ps-developers 

Olhando no https://whatsmychaincert.com/?scielo.br é possível verificar que tem um **misconfigured**

**Comment by gitnnolabs** [comment]
@rondinelisaad poderia verificar esse erro de SSL?

**Comment by gitnnolabs** [comment]
Olhando no Site What`s My Chain Cert o search.scielo.org está correto: https://whatsmychaincert.com/?search.scielo.org🥇

**Comment by rondinelisaad** [comment]
O certificado no varnish estava com a cadeia do cert.pem e o privkey.pem do certificado assinado pelo let's encrypt. Eu coloquei o fullchain.pem gerado, combinado com o privkey.pem. O resultado foi positivo conforme visto em:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/505148/124978974-d4d4ad00-e008-11eb-8542-6c118ec411c4.png">

**Comment by gitnnolabs** [comment]
@rondinelisaad Grato!

**Comment by robertatakenaka** [comment]
@RPostalli @alexxxmendonca resolvido
