### ISSUE TITLE
Criar funcionalidade para revistas que mudaram de título/ISSN

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1972]
Revistas que mudaram de ISSN/título perderam os links para título novo/antigo que existia na página da grade de artigos. Na lista alfabética também não existem mais estas informações (consultar lista site old).  Exemplos de revistas com mudança de título/ISSN: REM/REMI, REFUEM/JPE, RAUSP/RMJ, PD/AWS, RBA/BJA, TEMA/TCAM, BJOCE/OCR, RDOR/BRJP…

https://old.scielo.br/scielo.php?script=sci_serial&pid=2179-8451&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/123856971-1a51f580-d8f8-11eb-8b71-5c3f7479ec44.png)

https://old.scielo.br/scielo.php?script=sci_issues&pid=2179-8451&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/123857027-2d64c580-d8f8-11eb-986a-1698db96a662.png)

https://old.scielo.br/scielo.php?script=sci_serial&pid=2676-0029&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/123857048-3786c400-d8f8-11eb-8c1e-20f6f72ef27a.png)

https://old.scielo.br/scielo.php?script=sci_issues&pid=2676-0029&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/123857091-4a999400-d8f8-11eb-8d7a-405e606a2a24.png)

Na lista de não correntes: Non-current titles - 84  serials listed
https://old.scielo.br/scielo.php?script=sci_alphabetic&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/123857237-6e5cda00-d8f8-11eb-8b48-28ad764f19d5.png)

**Comment by alexxxmendonca** [comment]
@RPostalli poderia validar este ticket?

Me parece que apenas uma metade da demanda foi atendida.

Não há links apontando para o título antigo, a partir do título novo (somente para o título novo, a partir do título antigo).

Notei falta também do link para título novo/antigo acima da grade de fascículos.

PSI @gitnnolabs

**Comment by gitnnolabs** [comment]
@alexxxmendonca irei reprocessar os periódicos para conter os títulos, ai solicito uma nova avaliação.

**Comment by gitnnolabs** [comment]
@alexxxmendonca agora é possível verificar com todos dos dados, veja: https://www.scielo.br/journals/alpha?status=no-current

**Comment by alexxxmendonca** [comment]
@gitnnolabs na verdade eu não tinha observado problemas nessa parte.

O que eu observei foi:
_Não há links apontando para o título antigo, a partir do título novo (somente para o título novo, a partir do título antigo).

Notei falta também do link para título novo/antigo acima da grade de fascículos._

**Comment by gitnnolabs** [comment]
@alexxxmendonca verdade! 

Vou verificar como resolver isso!

**Comment by gitnnolabs** [comment]
@alexxxmendonca poderia valiar esse tíquete novamente.

Não adicionei essa relação de títulos na grade já que temos essa informação presente sempre no cabeçalho do periódico.

**Comment by alexxxmendonca** [comment]
@gitnnolabs agora está ok!

_Não adicionei essa relação de títulos na grade já que temos essa informação presente sempre no cabeçalho do periódico._

Ok, faz sentido.

Estou fechando o ticket.
