### ISSUE TITLE
Manter dados de "desindexação" para revistas não correntes

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#1973]
As informações contidas na lista de revistas não correntes são muito importantes para histórico da revista na coleção e também é usada por pesquisadores/usuários e deve ser mantida:
Data de desindexação 
Status. sendo:
- Deceased Continued as xxxxxxxx (link para o título novo)
- Indexing interrupted

Em new: https://www.scielo.br/journals/alpha?status=no-current
![image](https://user-images.githubusercontent.com/6084959/123857711-0955b400-d8f9-11eb-8ec2-5584f097d5c7.png)

Em old: https://old.scielo.br/scielo.php?script=sci_alphabetic&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/123857835-31ddae00-d8f9-11eb-9a9d-c7223d412458.png)

**Comment by alexxxmendonca** [comment]
@RPostalli poderia validar este ticket?

**Comment by alexxxmendonca** [comment]
Ticket validado em produção.

Estou fechando esse ticket pois a demanda foi atendida!
