### ISSUE TITLE
R11.  O sistema dever permitir gerir código de google analytics.

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#20]
## Problema:

O sistema não permite cadastrar nem modificar o código de Google Analytics.

## Objetivo:

1. Definir se é necessário gerir 1 o mais de 1 código de G.A. para cada OPAC;
2. Definir como será armazenado, (novo modelo?);
3. Definir o que acontece se o código não esta disponível;
4. Acrescentar a funcionalidade que permita que um usuário administrador possa modificar o código de G.A. utilizando a interface de administração (admin);
5. Assim que for definido um código de G.A. (por padrão ou pela interface admin) o código ficar funcionando no site público.

## Caso de Uso:

A equipe responsável pela operação tem a necessidade de acompanhar os acessos realizado no OPAC.

**Comment by jfunez** [comment]
@jamilatta também este issue precisa de ser melhorias na descrição.

**Comment by jamilatta** [comment]
Idem a resposta do #10

On Fri, Jan 22, 2016 at 1:55 PM, Juan Funez <notifications@github.com>
wrote:

> @jamilatta <https://github.com/jamilatta> também este issue precisa de
> ser melhorias na descrição.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/opac/issues/20#issuecomment-173960229>.
>



-- 

Jamil Atta Junior

**Comment by jamilatta** [comment]
Repensando sobre essa atividade e considerando a maioria das configurações ainda não foram definidas. 

Definimos que essa configuração ficará por hora no arquivo de configuração da app.

**Comment by jamilatta** [comment]
Instalei um do google chamado "Google Tag Asssitant", um plugin do chrome para auxiliar em possíveis problemas com o Google Analytics e outros serviços do Google.

Ao adicionar o código do G.A na minha instância foi notificado e direcionado para o seguinte link: https://support.google.com/tagassistant/answer/3059154?ref_topic=2947092#move_head

Considerando as recomendações do Google movi o código do G.A para o cabeçalho das páginas. 

Estudando um pouco sobre o Google Analytics verifiq
