### ISSUE TITLE
Equações longas sobrepõem o rótulo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#2026]
### Descrição do problema
Equações longas sobrepõem o rótulo de equação.

### Passos para reproduzir o problema
1. Acesse a página https://www.scielo.br/j/rbf/a/9LzVjQrYQF7BvkYWnJw9sDy/?lang=en#
2. Ver a Equação 2
3. Observe que o rótulo é sobreposto pela equação

### Comportamento esperado
Equação não sobrepor o rótulo.

Nesse caso é preciso trocar a posição CSS do elemento para de **absolute** para **block** para que não haja essa sobreposição.

Antes:

![image](https://user-images.githubusercontent.com/4059679/129716752-96708c9d-d5bf-4206-beff-85571c3fdeaf.png)

Depois:

![image](https://user-images.githubusercontent.com/4059679/129716795-84036e3d-22b0-49ec-97d1-30488ab8e8aa.png)

**Comment by gitnnolabs** [comment]
Item revolcido.
