### ISSUE TITLE
Hora das notícias publicadas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#206]
A hora das notícias publicadas não corresponde a hora real de publicação.

**Comment by jamilatta** [comment]
@alexxxmendonca poderia verificar no ambiente de homologação: http://homolog.opac.scielo.org.

**Comment by alexxxmendonca** [comment]
Ficou legal! Mas teria como ocultar os segundos? Se não for dar muito trabalho. Penso que ficaria melhor.

**Comment by jamilatta** [comment]
OK.

**Comment by jamilatta** [comment]
Ajustado.
