### ISSUE TITLE
"Lista em arquivo para Excel" dos periódicos descodificada

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#208]
Ao executar o arquivo com os títulos dos periódicos ("Lista em arquivo para Excel"), aparece a seguinte mensagem, informando que o arquivo pode não ser seguro:

![image](https://cloud.githubusercontent.com/assets/4059679/15673629/54d42a76-270e-11e6-898c-6257bbed6938.png)

Ao abrir o arquivo, os caracteres acentuados aparecem descodificados:

![image](https://cloud.githubusercontent.com/assets/4059679/15673648/6e80e14e-270e-11e6-9cd7-bad0b139fba5.png)

Além disso, a formatação dos dados não é amigável pois traz valores que o usuário final pode não entender como:

Fractal : Revista de Psicologia,**25,28,1,2016,True**
Intercom: Revista Brasileira de CiÃªncias da ComunicaÃ§Ã£o,**11,39,1,2016,True**
Kriterion: Revista de Filosofia,**29,56,132,2015,True**
Lua Nova: Revista de Cultura e PolÃ­tica,**93,None,97,2016,True**
Motriz: Revista de EducaÃ§Ã£o FÃ­sica,**25,22,2,2016,True**
Physis: Revista de SaÃºde Coletiva,**66,None,ahead,2016,True**
PrÃ³-Fono Revista de AtualizaÃ§Ã£o CientÃ­fica,**21,22,4,2010,False**

**Comment by jfunez** [comment]
@alexxxmendonca por gentileza, pode testar de novo, e ver se continua o erro? Obg!

**Comment by alexxxmendonca** [comment]
Os erros persistem.

Testei em http://homolog.opac.scielo.org/journals/

**Comment by jfunez** [comment]
@alexxxmendonca Jamil já enviou as correções (testado no windows com Excel)... 
Amanhã vamos atualizar o ambiente de homologação, entre outras coisas você pode revisar se este issue esta resolvido

**Comment by jamilatta** [comment]
Ambiente atualizado, por favor, validar.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.opac.scielo.org/
