### ISSUE TITLE
"Como citar este artigo": disponibilizar opções de exportar para gerenciadores de referências

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#2098]
### Descrição da nova funcionalidade
Eu, como **pesquisador e usuário do site SciELO**, gostaria que **fosse possível facilmente gerenciar as referências dos artigos SciELO que estou consultando e pretendo usar em minha pesquisa**, então **gostaria que o site SciELO oferecesse uma maneira de exportar para gerenciadores de referências a forma de citar um determinado artigo que estou pesquisando**.

### Critérios de aceitação

Incluir opções de download na janela modal existente "Como citar este artigo":
![image](https://user-images.githubusercontent.com/4059679/138457609-6885b3c9-0b5a-4af6-b09d-a92721ba5d96.png)

![image](https://user-images.githubusercontent.com/4059679/138469553-1515a26d-b35a-4487-aae3-ba557ee1e0a4.png)

Permitir exportação da referência nos seguintes formatos:
- BibTex
- Reference Manager
- Pro Cite
- End Note*
- Refworks

*Priorizar o formato End Note.

**Comment by RPostalli** [comment]
@jamilatta a @robertatakenaka pediu pra eu incluir nesse milestone o bug do Como Citar reportado por um usuário.
1. Os artigos que tinham nota (xref) no título, estavam como o label e/ou nota inteira aparecendo junto ao título
2. O problema foi corrigido no título do artigo e sumário
3. O problema permaneceu no Como Citar.

Exemplo: https://www.scielo.br/j/rbce/a/R4Cmhq8WCYpL6RhkgkbQvqv/?lang=pt#

Como citar: Farias, Marcelo Sant’Ana de et al. A prática corporal na disciplina natação nos cursos de formação: saber ou não saber nadar?1 1 Este trabalho é um recorte de algumas fontes e categorias de análises da pesquisa de mestrado intitulada “Análise da prática corporal na disciplina Natação, nos cursos de Educação Física das universidades públicas da cidade do Recife-PE” que o pesquisador principal realizou através do Programa Associado de Pós-Graduação em Educação Física UPE/UFPB. . Revista Brasileira de Ciências do Esporte [online]. 2021, v. 43 [Acessado 3 Novembro 2021] , e013320. Disponível em: <https://doi.org/10.1590/rbce.43.e013320>. Epub 02 Ago 2021. ISSN 2179-3255. https://doi.org/10.1590/rbce.43.e013320.

**Comment by gitnnolabs** [comment]
@RPostalli depois poderia testar novamente essa questão do "Como citar", pelo que estou verificando a @robertatakenaka já corrigiu!
