### ISSUE TITLE
R12.  O sistema dever permitir gerir textos de termos de uso do site.

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#21]
## Problema:

O site público não disponibiliza os textos com os "Termos de Uso" do site. E tampouco permite gerir esses textos.

## Objetivos:

1. Definir como serão armazenados;
2. Definir se terá suporte a tradução desses textos;
3. Definir se existira um texto padrão ou qual será o resultado caso os termos de uso não estejam disponíveis;
4. Acrescentar a funcionalidade que permita que um usuário administrador possa modificar os textos de "Termos de Uso" (e suas traduções  caso seja necessário) utilizando a interface de administração (admin);

## Caso de Uso:

*pendente*

**Comment by jamilatta** [comment]
Acreditamos que falta bastante contexto e definições para iniciarmos essa atividade. 

No mínimo precisamos de um modelo desse texto e também de características mais particulares.

**Comment by jamilatta** [comment]
Acreditamos que os termo de uso pode ser mais um item na página sobre o SciELO. 

Ver: 
<img width="1231" alt="screenshot 2016-10-18 16 39 03" src="https://cloud.githubusercontent.com/assets/373745/19491354/66f43b72-9551-11e6-8353-859c2fb71f0e.png">
