### ISSUE TITLE
Revisão das instruções e variáveis de ambiente visando uma instalação do zero

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#2116]
### Descrição da tarefa
Revisão das instruções e variáveis de ambiente visando uma instalação do zero

### Subtarefas

- [x] Analisar as variáveis
- [x] Remover as variáveis desnecessárias 
- [x] Identificar as variáveis opcionais
- [x] Documentar no código e/ou no README

**Comment by gitnnolabs** [comment]
👍

**Comment by gitnnolabs** [comment]
Realizando....

**Comment by gitnnolabs** [comment]
Atividade realizada no PR: https://github.com/scieloorg/opac/pull/2144
