### ISSUE TITLE
Sugestão - Inclusão das opções "Continua como" e "Título anterior"

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/opac#214]
Notei que na nova versão do site não existe os links "Continua como" e "Título anterior" que fazem a ligação entre um título terminado e seu título atual e vice-versa.

Exemplo - Site atual:
[Revista do Hospital das Clínicas](http://www.scielo.br/scielo.php?script=sci_serial&pid=0041-8781&lng=pt&nrm=iso) continua como [Clinics](http://www.scielo.br/scielo.php?script=sci_serial&pid=1807-5932&lng=pt&nrm=iso)

Acho que seria importante manter esses links para fazer a relação entre os títulos. Por exemplo, se um periódico mudou o título recentemente e um usuário busca pelo título anterior por não saber que o título mudou, vai parecer que o periódico terminou e não que só mudou o título.

**Comment by jamilatta** [comment]
@francine-curivil 

sim concordo, iremos avaliar a melhor forma de colocarmos essa informação na interface juntamente com o designer.

**Comment by fabiobatalha** [comment]
A equipe considerou importante dizer que a revista mudou de nome e para qual nome foi.
Indicar também o motivo da revista ter sido encerrada ou esta inativa.

**Comment by jfunez** [comment]
#### Objetivo:
Adicionar em cada fila da listagem de periódicos, a informação indicando a mudança do nome, e se corresponde um motivo da revista de ter sido encerrada ou esta inativa.

**Comment by jamilatta** [comment]
Abri um ticket no Xylose para adicionar o título anterior: https://github.com/scieloorg/xylose/issues/133

**Comment by jamilatta** [comment]
Foi adicionado apenas o nome da revista nas listagens. Vou criar outro ticket para torna um link para o título anterior.

**Comment by javani** [comment]
@jamilatta não consigo avaliarcom dados de Saúde Pública

**Comment by jamilatta** [comment]
@javani

ok iremos disponibilizar os dados do SciELO Brasil.
