### ISSUE TITLE
Sugestão - Opção "Títulos-correntes" e "Títulos não-correntes"

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/opac#216]
Como todos os periódicos (correntes e não-correntes) estão listados juntos, acho que seria bacana ter   os filtros "Corrente" e "Não-corrente" para o caso do usuário querer visualizar a lista por esses parâmetros.

**Comment by fabiobatalha** [comment]
A equipe considerou isso relevante pois os usuários podem usar esse filtro corrente e não corrente para identificar revistas abertar para submissão de artigos.

Incluir filtro ao lado do search para periódicos ativos e inativos.

**Comment by javani** [comment]
@jfunez @jamilatta filtros presentes e funcionando, apenas precisaria testar links entre periódicos correntes e não correntes. Em Saúde Pública são todos correntes.
