### ISSUE TITLE
R13.  O sistema dever permitir gerir canais de RSS

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#22]
## Problemas:

O sistema não permite a gestão de Feeds de RSS.

## Objetivos:

1. Definir como seria armazenado;
2. Definir se serão definidos feeds por padrão ou o que acontece quando os feeds não estejam definidos;
3. Definir qual seria o comportamento caso exista alguma falha na integração (serviço não disponível por exemplo);
4. Acrescentar a funcionalidade que permita que um usuário administrador possa modificar os feeds de RSS utilizando a interface de administração (admin);
5. Assim que for definido um feed, as noticias do feed deve ficar disponível no site público.

## Casos de Uso:

*pendente*

**Comment by jamilatta** [comment]
Considerando as últimas reunião sobre as integrações que o OPAC terá o cenário está mais incerto do que nunca, portanto iremos realizar essa tarefa em outra interação.

**Comment by jamilatta** [comment]
Item realizado, iremos abrir ticket para melhorias, commit: d0e0703.
