### ISSUE TITLE
Campo de busca na home

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#220]
@amandasramalho

Não há campo de busca visível na home do site.

**Comment by amandasramalho** [comment]
Como usuária a primeira coisa que procuro ao entrar em um site de pesquisas é justamente o campo de busca. É importante estar visível na página principal.
Para simplificar, poderia ter o campo de busca simplificado na página inicial e um botão de "Busca avançada".

**Comment by fabiobatalha** [comment]
Verificar modelo de Portal Global para implementar a página inicial do site de coleção

http://scielohomolog.parati.ag/Portal/

**Comment by jamilatta** [comment]
Item adicionado nos últimos desenvolvimento, por favor, validar!
