### ISSUE TITLE
Barra de opções

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#221]
@amandasramalho

Rótulo de grupo de funções do periódico "Lista de Periódicos" na barra parece estar perdido.

Não parece algo que deveria estar presente.

![screen shot 2016-06-20 at 12 14 08 pm](https://cloud.githubusercontent.com/assets/504142/16199654/cdee461c-36e0-11e6-85da-139f9667cfe6.png)

**Comment by amandasramalho** [comment]
O ideal seria retirar este título, uma vez que uma "barra de opções" é algo auto-explicativa.

**Comment by fabiobatalha** [comment]
Implementando a página do portal global para as coleções, este ticket é resolvido.
