### ISSUE TITLE
Função de compartilhar na home não é clara.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#222]
@amandasramalho

Compartilhar o que? Todas as matérias? o compartilhamento não deveria ser por matéria?

![screen shot 2016-06-20 at 12 18 46 pm](https://cloud.githubusercontent.com/assets/504142/16199766/3249caaa-36e1-11e6-8c19-72facf880119.png)

**Comment by amandasramalho** [comment]
Como as matérias remetem ao Blog - e no Blog já existe botões específicos de compartilhamento - acho que esta opção acaba sendo inválida. Se a pessoa quiser compartilhar o site, ela vai enviar o link da página. E se a pessoa quiser compartilhar uma matéria específica, ela vai entrar no post do blog e usar os botões do próprio post. 
Nesta área acho que poderia ter somente o "imprimir" e o feed RSS.

**Comment by fabiobatalha** [comment]
* Incluir siga-nos em nossas redes sociais
* Incluir link de compartilhar.

**Comment by jamilatta** [comment]
Impedido aguardando a home nova do consultor.

**Comment by jfunez** [comment]
vou fechar este issue, porque a home mudou completamente
