### ISSUE TITLE
Link para PDF de material suplementar não aparece na interface

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/opac#2223]
O link que direciona para o PDF de um material suplementar não está sendo disponibilizado na interface do www.scielo.br.

Segue exemplo do erro apresentado:

1. Acesse a página https://www.scielo.br/j/hcsm/a/TwZZBvMMN6XQNWb7C5Rc4qr/?lang=pt#
2. Role a página até **Fontes**
3. Observe o erro apresentado

<img width="506" alt="hcsm" src="https://user-images.githubusercontent.com/23195801/155319466-a47e86b5-d5c1-4427-9931-3cc43fb4cd2d.png">

Segue também em anexo o xml do artigo:
[0104-5970-hcsm-27-01-0275.zip](https://github.com/scieloorg/Web/files/8124283/0104-5970-hcsm-27-01-0275.zip)

**Comment by robertatakenaka** [comment]
@JoyceRaphaela @RPostalli O motivo de não aparecer é porque a tag 
```xml
<app-group>
      <app id="app01">
        <label>FONTES</label>
        <supplementary-material id="s01" mime-subtype="pdf" mimetype="application" xlink:href="0104-5970-hcsm-27-01-0275-suppl01.pdf"/>
      </app>
    </app-group>
```

Não tem texto. Idealmente é melhor que seja informado um texto. Pode-se colocar o nome do arquivo no lugar, no entanto, no site novo o arquivo muda de nome:

```xml
<app-group>
      <app id="app01">
        <label>FONTES</label>
        <supplementary-material id="s01" 
mime-subtype="pdf" mimetype="application"
 xlink:href="https://minio.scielo.br/documentstore/1678-4758/TwZZBvMMN6XQNWb7C5Rc4qr/51c6856d1570190ab90aaa9b311a6ba1d762657a.pdf"/>
      </app>
    </app-group>

```

Aguardo uma sugestão

**Comment by RPostalli** [comment]
@robertatakenaka isso é bug, porque no [SPS](https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-supplementary-material.html) o exemplo está igual a marcação que foi feita e no site old aparece de fato a nomeação do arquivo. O site novo tem que se comportar da mesma forma para este tipo de material.

**Comment by gitnnolabs** [comment]
Pelo que estou olhando falta somente o nome do arquivo: 
![Captura de Tela 2022-04-11 às 14 51 23](https://user-images.githubusercontent.com/86991526/162799763-cb9fb151-7de0-407e-8dbe-1f49bbd94c1c.png)

**Comment by gitnnolabs** [comment]
@robertatakenaka 

Gostaria da sua opnião para resolver essa questão! 

Temos algumas opções: 

1. Criar um JavaScript para verificar esses links de material suplementar sem valor na tag ``<a>`` consultando a base de dados do site e colocando o nome do arquivo. 

Veja na base de dados tempos o nome do arquivo: 
![Captura de Tela 2022-04-11 às 14 55 03](https://user-images.githubusercontent.com/86991526/162800254-7f9d6624-2134-4811-a2d8-2454fdf0010f.png)

2. Realizar a exibição de material suplementar no final de cada artigo, com todos os materiais suplementar. Dessa forma garantirmos que seja exibido e com o nome correto sem muita "expertise" da aplicação. 

Algo como: 

**Matrial suplementar**

* [0104-5970-hcsm-27-01-0275-suppl01.pdf](https://old.scielo.br/pdf/hcsm/v27n1/0104-5970-hcsm-27-01-0275-suppl01.pdf)
* [0104-5970-hcsm-27-01-0275-suppl02.pdf](https://old.scielo.br/pdf/hcsm/v27n1/0104-5970-hcsm-27-01-0275-suppl01.pdf)
* [0104-5970-hcsm-27-01-0275-suppl03.pdf](https://old.scielo.br/pdf/hcsm/v27n1/0104-5970-hcsm-27-01-0275-suppl01.pdf)

**Comment by robertatakenaka** [comment]
opção 2
Roberta Takenaka (she/her)
Coordenadora de Desenvolvimentos de Sistemas
Coordinadora de Desarrollo de Sistemas
Systems Development Coordinator
SciELO - Scientific Electronic Library Online
FAPESP - CAPES - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Rua Dr. Diogo de Faria, 1087 – 9º andar – Vila Clementino 04037-003 São
Paulo/SP - Brasil
