### ISSUE TITLE
Links dos perfis do SciELO nas redes sociais.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#223]
@amandasramalho

Não foi localizado nenhum link dos perfis do SciELO nas redes sociais.

É importante que esses links sejam incluídos em algum lugar na interface.

**Comment by amandasramalho** [comment]
Ter os botões das Redes Sociais é muito recomendado, pois apresenta "Onde estamos" ou "Acompanhe o SciELO nas Redes Sociais".
Por exemplo:
O Blog SciELO em Perspectiva tem os botões na barra lateral: http://blog.scielo.org/
O site da Thomson Reuters apresenta no rodapé uma lista com o nome "Siga-nos": https://thomsonreuters.com.br/pt.html

**Comment by jfunez** [comment]
Sigue no issue #222

**Comment by javani** [comment]
@jfunez @jamilatta itens disponíveis.
