### ISSUE TITLE
DOI de tradução não está sendo usado para obter as métricas e na indexação da metatags do google

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#2236]
### Descrição do problema
DOI de tradução não está sendo usado para obter as métricas e na indexação da metatags do google

### Passos para reproduzir o problema
1. Acesse a página https://www.scielo.br/j/rae/a/mTSNspjDVVkVfz8k3RdPfmx/?lang=en
2. Note que o DOI é 10.1590/S0034-759020210302x
3. Abra o código fonte da página e verifique se está usando o DOI da versão em português 10.1590/S0034-759020210302 no lugar de 10.1590/S0034-759020210302x (versão inglês)

### Comportamento esperado
Onde está 10.1590/S0034-759020210302 deve apresentar 10.1590/S0034-759020210302x ao acessar https://www.scielo.br/j/rae/a/mTSNspjDVVkVfz8k3RdPfmx/?lang=en

### Screenshots ou vídeos
n/a

**Comment by gitnnolabs** [comment]
@scieloorg/scielo-ps-developers 

Realizando...
