### ISSUE TITLE
Rodapé com alinhamento diferente do resto do site.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#225]
@amandasramalho

Por que o rodapé com logo SciELO esta alinhado a esquerda e não centralizado como o restante?

![screen shot 2016-06-20 at 12 26 43 pm](https://cloud.githubusercontent.com/assets/504142/16200089/458e90ae-36e2-11e6-81c7-8d43728a8f20.png)

**Comment by fabiobatalha** [comment]
Deixar como esta e verifica o alinhamento com o resto do site.

**Comment by jfunez** [comment]
Aqui tem algumas indicações de porque o rodapé parece ter alinhamento diferente (tirando a seção de noticias que seria refeita).

**obs:** para ver estas imagens, utilizei as ferramentas de desenvolvimento do firefox, ou seja, botão direito na página e click em "Inspect Element".

![screenshot 2016-07-01 13 52 17](https://cloud.githubusercontent.com/assets/805749/16528675/b576d9a2-3f94-11e6-8191-b3d00ffd8525.png)
![screenshot 2016-07-01 13 52 48](https://cloud.githubusercontent.com/assets/805749/16528677/b57ab6da-3f94-11e6-9b83-2d9b20601688.png)
![screenshot 2016-07-01 13 53 16](https://cloud.githubusercontent.com/assets/805749/16528676/b578908a-3f94-11e6-8b76-f538342312f7.png)

**Comment by amandasramalho** [comment]
@jfunez @fabiobatalha 

Como a linha de licença vai sair, acho que a _sensação_ de desalinhamento vai ficar menor.

**Comment by jfunez** [comment]
Vou fechar este issue, podemos voltar na discussão numa próxima revisão.
