### ISSUE TITLE
O rótulo home na barra de navegação não esta claro.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#226]
@amandasramalho

A barra de navegação tem funções diferentes para o mesmo botão dependendo do contexto. Quanto esta nas páginas do periódico, remete a página inicial da revista, quanto esta nas páginas da coleção, remete a página inicial da coleção.

Esta comportamento não fica claro para o usuário, seria interessante indicar "página da revista", "página da coleção" para que o usuário saiba exatamente qual será o comportamento deste botão, o mesmo deve ocorrer para os demais idiomas.

![screen shot 2016-06-20 at 1 42 52 pm](https://cloud.githubusercontent.com/assets/504142/16202651/fc88a93e-36ec-11e6-9951-757c4c758b83.png)

**Comment by fabiobatalha** [comment]
Incluir "home da revista"

O link não aparece mais na home da coleção

**Comment by jfunez** [comment]
#### Problema
O botão para ir a home do periódico esta confusa, junto com o botão igual para acessar a home da coleção.

#### Objetivo:
Como o menu da coleção vai mudar, foi decido trocar  o label do botão "home" nas páginas da coleção, pela etiquita: "home da revista" (traduzível claro).
O botão "home" da coleção pode se manter igual, até ser atualizado pelo novo design.

**Comment by javani** [comment]
@jfunez @jamilatta verificado e ok
