### ISSUE TITLE
Seção material suplementar aparece 2x no new

### ISSUE THREAD

**Issue by luziakanashiro** [scieloorg/opac#2278]
Seção Supplementary Material no artigo da BN abaixo está aparecendo 2 vezes mas repete o nome da seção em português (BN só publica em inglês) e sem texto, só o nome de um dos arquivos. No old aparece correto.

No new: https://www.scielo.br/j/bn/a/GJq3kzJLQw876pxRdSrhmQG/?lang=en
![image new suppl BN](https://user-images.githubusercontent.com/101260804/165378079-296ce500-e2b7-43df-9579-e35c00acbfa5.png)

No old: https://old.scielo.br/scielo.php?script=sci_arttext&pid=S1676-06032022000100206&lng=en&nrm=iso&tlng=en
![image old suppl BN](https://user-images.githubusercontent.com/101260804/165378489-d10a8dd3-7392-4877-8075-99622a8b6b4b.png)

**Comment by gitnnolabs** [comment]
Link para o kernel desse registro: https://kernel.scielo.br/documents/GJq3kzJLQw876pxRdSrhmQG/manifest
