### ISSUE TITLE
Informação Institucional da coleção

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#228]
@javani

Não há nenhuma informação institucional sobre a coleção, o core business do SciELO e seu conteúdo na home do site.

Ex:
* Sobre o SciELO
* Sobre a coleção
* Lista dos útlimos artigos
* Lista dos últimos fascículos

**Comment by fabiobatalha** [comment]
Com a página da coleção implementando a página do portal Global haverá grupos com os últimos artigos e fascículos.

**Comment by jfunez** [comment]
Então resolve com a nova página da coleção.

**Comment by javani** [comment]
@jfunez @jamilatta verificado que há um menu para Sobre SciELO. ok
