### ISSUE TITLE
Menu Global ou Sanduiche.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#229]
@javani

Menu global "rede" não deixa claro que é um integrador de serviços SciELO e links de coleções da rede.

A mudança de contexto das páginas confunde o usuário pois a posição deste menu não condiz com o conteúdo (links) apresentados por ele.

![screen shot 2016-06-20 at 1 55 26 pm](https://cloud.githubusercontent.com/assets/504142/16203025/af7a77d8-36ee-11e6-8282-4dc77e7d4cdb.png)

**Comment by jfunez** [comment]
falta detalhar o que temos a fazer

**Comment by jamilatta** [comment]
Alguém consegui definir o que fazer com esse ticket!

**Comment by jfunez** [comment]
Resolvido!
