### ISSUE TITLE
Apresentar área temática da revista em outro local.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#230]
@javani

A área temática do WoS apresentada no topo não é um conteudo de destaque. Deveria estar em outro local da página.

![screen shot 2016-06-20 at 1 57 38 pm](https://cloud.githubusercontent.com/assets/504142/16203095/fb4b90ac-36ee-11e6-83f1-ad9dc8f982f7.png)

**Comment by fabiobatalha** [comment]
Colocar em baixo do título como:

Área temáticado: <área cnpq> <área wos>

**Comment by jfunez** [comment]
@jamilatta @fabiobatalha vocês podem me confirmar que:
- ``áreas cnpq`` corresponde com o atributo ``Journal.subject_areas`` do xylose?
- ``áreas wos`` corresponde com o atributo ``Journal.wos_subject_areas`` do xylose?

se for assim, como o processamento já [salva esses dados](https://github.com/scieloorg/opac_proc/blob/master/am2opac.py#L93) então só teríamos que ajustar nos templates 😄 , se não teríamos que ajustar desde o processamento que recupera os dados desde o ArticleMeta 😞 .

**Comment by fabiobatalha** [comment]
esta correto.

**Comment by jfunez** [comment]
@swarzesherz puedes ayudarnos con este ticket? 

Necesitamos:
1. cambiar en el cabezal (ver imagen arriba) el lugar donde aparece el área temática del periódico, de la parte superior (como esta actualmente) hacia la parte inferior (debajo del título del periódico).
2. además de mostrar el area WoS (internamente está almacenada en el campo: ``journal.study_areas``) como esta actualmente, debemos agregar el área cnpq (almacenada en el campo: ``journal.subject_categories``). 
3. el orden de estas áreas seria: primero la lista de áreas de CNPQ (``journal.subject_categories``) y debajo en otra linea la lista de áreas WoS (``journal.study_areas``).

##### Observaciones:
- los dos campos de áreas: ``journal.subject_categories`` y ``journal.study_areas`` son listas de strings que pueden ser extensas.

Cualquier duda nos consultas!!!

**Comment by swarzesherz** [comment]
Hola, enterado!
Reviso la tarea y les informo, saludos...

**Comment by javani** [comment]
@jfunez @jamilatta verificado e ok
