### ISSUE TITLE
Barra de navegação esta confusa no contexto do periódico.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#231]
@javani

* Na página com a grade de fascículo os botões **anterio** e **próximo** não tem sentido, o que deveria acontecer ao clicar em anterior?
* Na página do fascículo os botões **anterior** e **próximo** da barra de navegação têm a mesma função dos botões na lateral esquerda, o botão lateral a esquerda é melhor e mais intuitivo.

![screen shot 2016-06-20 at 2 06 15 pm](https://cloud.githubusercontent.com/assets/504142/16203345/318354f6-36f0-11e6-96d7-cf259009c5cd.png)

**Comment by javani** [comment]
@fabiobatalha isso mesmo. Tendo a possibilidade de navegação nos números não faz sentido manter a mesma funcionalidade no topo do sumário. Se já estou no contexto do número não faz sentido manter no cabeçalho essa mesma informação. Talvez incluir no meu lateral a possibilidade de voltar à grade com todos os números.

**Comment by fabiobatalha** [comment]
tirar menu lateral azul,
tirar label números,
escrever: número anterio, número atual, número seguinte.
escrever: artigo anterio, artigo atual, artigo seguinte.

**Comment by javani** [comment]
@jfunez @jamilatta verificado e ok.
