### ISSUE TITLE
"Como citar" mostra o texto da nota junto ao título do artigo

### ISSUE THREAD

**Issue by carolinatanigushi** [scieloorg/opac#2323]
### Descrição do problema
Para artigos que possuem uma nota no título, o "Como citar" está inserindo o texto da nota no campo de título do artigo:

![image](https://user-images.githubusercontent.com/12699183/170739443-b15f3de1-8616-45e3-82ff-557256db2fbd.png)

![image](https://user-images.githubusercontent.com/12699183/170739413-c4cb8c1d-4dc0-4cd4-968e-b10560ce34df.png)

### Passos para reproduzir o problema
1. Acesse o artigo [Design of a smart LED lamp to monitor insect populations in an integrated pest management approach](https://doi.org/10.1590/1807-1929/agriambi.v25n4p270-276) (ou qualquer outro artigo que possua uma nota no título).
2. Vá em "Como citar este artigo".

### Comportamento esperado
O "Como citar" não deve conter o texto da nota, apenas o título do artigo.

**Comment by alexxxmendonca** [comment]
Além do problema reportado, há ainda uma outra questão relacionada:

No template que gera a citação, está faltando um "ponto final" (separador) entre o nome do último autor e o título. Isso ocorre em todos os artigos.

**Comment by gitnnolabs** [comment]
Me parece correto não está colocando as notas no model de como citar, vejam como era: 

![Captura de Tela 2022-11-28 às 10 53 38](https://user-images.githubusercontent.com/86991526/204294941-141c487b-2acd-449f-bc2c-5ce40600c50d.png)

E agora sem as notas: 

![Captura de Tela 2022-11-28 às 10 53 24](https://user-images.githubusercontent.com/86991526/204295011-74bbddb1-01d0-4a3f-9fa6-5e364861f8f0.png)

**Comment by alexxxmendonca** [comment]
@gitnnolabs por favor, veja em: https://www.scielo.br/j/ensaio/a/p9TrN437Ggdbdt6HNpq5nYf/?lang=pt#ModalArticles

![image](https://user-images.githubusercontent.com/4059679/204304502-cc523323-92bf-43f0-ba63-836342addbfe.png)

**Comment by gitnnolabs** [comment]
@robertatakenaka https://github.com/scieloorg/opac/issues/2323#issuecomment-1329219149

**Comment by gitnnolabs** [comment]
@alexxxmendonca está correto, estou avaliando localmente essa alteração ainda não está em produção.

**Comment by alexxxmendonca** [comment]
@gitnnolabs o problema foi resolvido em partes.

O problema reportado [neste comentário](https://github.com/scieloorg/opac/issues/2323#issuecomment-1322415271) ainda persiste.

**Comment by robertatakenaka** [comment]
@

> @gitnnolabs o problema foi resolvido em partes.
> 
> O problema reportado [neste comentário](https://github.com/scieloorg/opac/issues/2323#issuecomment-1322415271) ainda persiste.

@alexxxmendonca melhor criar outro issue, pois não é o mesmo problema apesar de ocorrer na mesma tela. Este problema não foi tratado

**Comment by gitnnolabs** [comment]
@alexxxmendonca 

Foi criado um novo issue para esse problema?

**Comment by robertatakenaka** [comment]
@gitnnolabs sim e já foi resolvido
