### ISSUE TITLE
Títulos perdidos na barra de navegação

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#233]
@javani

Os titulo de grupos de botões na barra de navegação ficam perdidos. Não esta claro que o titulo se refere a um grupo de botões com comportamento específico. Parece um bug da interface.

![screen shot 2016-06-20 at 2 19 15 pm](https://cloud.githubusercontent.com/assets/504142/16203729/032853ca-36f2-11e6-9711-edfa568ab139.png)

**Comment by fabiobatalha** [comment]
Vai sair com novas definições.

**Comment by javani** [comment]
@jfunez ficou mais intuitivo, melhor do que estava antes no nível do número. No caso de Lista de periódicos na home, acredito que dê para ficar como está.

**Comment by jamilatta** [comment]
👍
