### ISSUE TITLE
Icones no texto completo poluem a leitura.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#235]
@javani

Os icones de links para figuras, tabelas e referências poluem a interface a a leitura do artigo.

![screen shot 2016-06-20 at 2 30 13 pm](https://cloud.githubusercontent.com/assets/504142/16204082/8b28aa26-36f3-11e6-84bb-2955429551c7.png)

**Comment by fabiobatalha** [comment]
* Tirar os icones de figuras e tabelas.
* Deixar o acesso padrão expandido
* Manter links de colpsar explandir
* Link não deve ir para a referência
* Abrir referência em tooltip no onclick

**Comment by caramez** [comment]
Analisem se este layout atende:
https://invis.io/VR75HH77T#/202757209_Artigo-Inicio

**Comment by jamilatta** [comment]
@caramez 

nossa parece que é outro site, o contexto parece ser outro.

**Comment by jamilatta** [comment]
Esse ticket já esta resolvido nos novos mockups enviado pelo designer.
