### ISSUE TITLE
Não há declaração sobre acesso aberto no SciELO.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#236]
@gustavofonseca 

Sites que publicam em acesso aberto costumam ter a declaração de acesso disponível e visível na home do site, ex: PeerJ, Plos, Redalyc.

**Comment by fabiobatalha** [comment]
Incluir cadeado aberto na home do SciELO com link para texto de políticas de acesso aberto do SciELO.

Solicitar sugestão de layout para designer.

**Comment by jfunez** [comment]
@fabiobatalha você pode nos indicar o link?

**Comment by jfunez** [comment]
@alexxxmendonca Pode nos ajudar? 

Precisamos do texto da declaração sobre acesso aberto em 3 idiomas (en, es, pt). Ou tal vez solicitando esse texto a Abel, caso esse texto não tenha sido escrito ainda.

com exemplo, aqui tem a [Declaración de Accesso Abierto da Redalyc](http://www.redalyc.org/redalyc/media/redalyc_n/estaticasredalyc/openacces.html) (só em espanhol)

**Comment by alexxxmendonca** [comment]
Não temos esse texto ainda. Por ora, poderíamos inserir essa declaração geral (sugerido pelo Abel):

SciELO é um programa de cooperação internacional em comunicação científica em acesso aberto que opera por meio de uma rede de coleções nacionais de periódicos revisados por pares.
 
SciELO es un programa de cooperación internacional en comunicación científica en acceso abierto que opera a través de una red de colecciones nacionales de revistas revisadas por pares.
 
SciELO is an international cooperation program on scientific communication in open access operating through a network of national collections of peer-reviewed journals.

**Comment by jfunez** [comment]
👍

**Comment by alexxxmendonca** [comment]
Outro ponto levantado pelo Abel:

"O SciELO é antes de tudo um programa de comunicação científica de periódicos de qualidade. Acesso aberto é um princípio de operação mas não o fim!"

**Comment by jfunez** [comment]
isso que você apontou agora, é para acrescentar no texto, certo? tem as tradução em outros idiomas?

**Comment by alexxxmendonca** [comment]
Não, é apenas uma justificativa para não termos um texto mais completo como o da Redalyc.

**Comment by jfunez** [comment]
👍

**Comment by jfunez** [comment]
Feito, com o texto indicado acima pelo Alex.
Ver PR: #264 issue: #238

**Comment by javani** [comment]
@jamilatta @jfunez verificado e ok
