### ISSUE TITLE
Imagem não atualizou no Site SciELO

### ISSUE THREAD

**Issue by felipeEsteves** [scieloorg/opac#2369]
No processamento do dia 06/07, Na revista AA v52n2, a figura 1809-4392-aa-52-02-149-gf5.png não atualizou no site, como pode ver no [Site ](https://www.scielo.br/j/aa/a/pqYTrRfP7b3J5fFp4c4HkdC/?lang=en#ModalFigf5)ela consta com o fundo Rosa, a imagem correta não contém o fundo Rosa. Em [homolog ](http://homolog.scielo.br/img/revistas/aa/v52n2//1809-4392-aa-52-02-149-gf5.png)está OK.  A imagem abaixo é a correta.
![1809-4392-aa-52-02-149-gf5](https://user-images.githubusercontent.com/17028766/178259547-c34705bc-9723-4988-ace9-4acaecfe6bd4.png)

**Comment by gitnnolabs** [comment]
@felipeEsteves 

Poderia, poderia por gentileza testar. 

<img width="1494" alt="Screen Shot 2022-07-11 at 16 34 18" src="https://user-images.githubusercontent.com/86991526/178344232-b2a27009-6708-446f-867d-d3a1e58380e2.png">

**Comment by felipeEsteves** [comment]
@robertatakenaka quando abre a img ela aparece correta(sem o Rosa), porém no texto ela esta aparecendo rosa ainda
![aa](https://user-images.githubusercontent.com/17028766/178345863-92765320-1284-46f6-9ccf-60aaf4f66d49.jpg)
.

**Comment by gitnnolabs** [comment]
Vou verificar
