### ISSUE TITLE
Links de mudança de idiomas devem ser escritos no idioma original.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#237]
Os links de mudança de idioma não devem ser traduzidos.

Ex:
português
english
español

![screen shot 2016-06-20 at 2 35 10 pm](https://cloud.githubusercontent.com/assets/504142/16204232/573df698-36f4-11e6-9e15-41ed86ed3032.png)

**Comment by javani** [comment]
@jamilatta @jfunez verificado e ok
