### ISSUE TITLE
URL da revista não esta boa.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#239]
Deve utilizar acronimo, ISSN ou outro identificador.

Atualmente esta apresentando: http://homolog.opac.scielo.org/journals/**86246dddf656493787261c2483266426**

**Comment by jamilatta** [comment]
Definimos que as URL do site deve funcionar com o mesmo formato da legenda bibliográfica implementada pela biblioteca https://github.com/scieloorg/legendarium e documentada em: https://docs.google.com/document/d/1GvM5tEmOo8BRzJuS6fKGs9Lsql0sCGNBEVjjLMZKmVw/edit.

**Comment by jamilatta** [comment]
Item resolvido nos últimos desenvolvimentos, por favor, validar!
