### ISSUE TITLE
R16. O sistema deve permitir filtrar todos os periódicos despublicados pelas justificativas.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#24]
## Dependência: 

#23 

## Problema:

O sistema não permite filtrar periódico pelas justificativas de "despublicação".

## Objetivos:

1. Dever ser possível filtrar periódico pelas justificativas de "despublicação" pelo usuário admin na interface de administração

## Casos de uso: 
pendente

**Comment by jfunez** [comment]
resolvido em https://github.com/scieloorg/opac/commit/91c3eb46f69b4f81090c8f58f8cfe55ff13ea94f
