### ISSUE TITLE
Apresentar telefone nos contatos do rodapé.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#240]
@RPostalli

![screen shot 2016-06-20 at 2 48 08 pm](https://cloud.githubusercontent.com/assets/504142/16204598/07f20ec4-36f6-11e6-8276-3827a147db75.png)

**Comment by RPostalli** [comment]
Falta inserir a informação. Tel.: +55 11 5083-3639/59
E email: <scielo@scielo.org>

Seguir informações disponíveis hoje em SciELO BR
http://www.scielo.br/?lng=pt

![rodape_br](https://cloud.githubusercontent.com/assets/6084959/16206125/436747ba-36fd-11e6-8150-8a6748ddc004.jpg)

**Comment by jfunez** [comment]
Os dados exibidos como endereços são editáveis pelo admin do OPAC. 
Vou fechar este issue, porque não corresponde com uma tarefa a ser realizada, nem erro a ser corrigido.

**Comment by javani** [comment]
@jfunez @jamilatta entendo então que não temos que analisar nada nesse caso. De qualquer forma, agora só aparece SciELO, sem outra informação disponível.

**Comment by jamilatta** [comment]
@javani 

esses dados podem ser inseridos via admin, irei adicionar e depois fechamos o ticket.
