### ISSUE TITLE
Notícias na página da revista

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#241]
@RPostalli

A página da revista não deve apresentar notícias (posts) quando não existir posts em seu canal RSS ou quando a revista não tiver um canal de RSS registrado no site.

Na ausência de notícias da revista também não devem ser apresentadas as notícias do site SciELO.

Na página da revista só devem ser apresentadas notícias da revista.

**Comment by RPostalli** [comment]
Na página da revista está aparecendo a mesma página de notícias da página principal; que são notícias gerais e não específicas de cada revista.

Como está hoje:
![pag_rev](https://cloud.githubusercontent.com/assets/6084959/16206498/0e8bcca8-36ff-11e6-969f-dde7022f5311.jpg)

O ideal é que apareçam notícias da própria revista vinculadas a suas próprias redes sociais como blog, site, twiter e etc. Sendo de responsabilidade do editor o conteúdo informativo.

Caso a revista não possua outros meios de comunicação não deve aparecer nenhum conteúdo no campo.

**Comment by jamilatta** [comment]
@RPostalli 

sim a idéia é essa mesmo porém ainda não contamos com as notícias contextualizados por revista, por hora adicionamos na página inicial e removemos da home da revista até que tenhamos um local para a coleta.

**Comment by jfunez** [comment]
Foi definido que importaremos as noticias desde o blog.
Será resolvido na importação das noticias.
