### ISSUE TITLE
Pressreleases na página da revista.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#242]
@RPostalli

A página da revista não deve apresentar pressreleases quando não existir pressreleases em seu canal RSS ou quando a revista não tiver um canal de RSS registrado no site.

Na ausência de pressreleases da revista também não devem ser apresentados os pressreleases do site SciELO.

Na página da revista só devem ser apresentados os pressreleases da revista.

**Comment by RPostalli** [comment]
Poucas revistas atualmente publicam PR, não passa de 10 revistas em toda a coleção SciELO Brasil. (Vou confirmar a informação de quantas)

Sendo assim, não é necessário inserir na página das revistas as informações de PR, somente das revistas que realmente publicam.

Atualmente está assim:

![pr](https://cloud.githubusercontent.com/assets/6084959/16208549/1bd197e4-3709-11e6-9873-127782d68eeb.jpg)

Além de tudo, polui a página da revista.

**Comment by jamilatta** [comment]
Nos últimos desenvolvimentos garantimos que o Press Release aparece somente para as revistas que tem Press Release.

**Comment by jamilatta** [comment]
@RPostalli 

pode validar e verificar se sua observações implementada no ambiente de homologação para podermos fechar esse ticket.

**Comment by jfunez** [comment]
agora é possível associar o Press Release ao Periódico. e quando não houver, não será mostrado
