### ISSUE TITLE
Volta para link de referência bibliográfica.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#244]
@RPostalli

Quando clicamos em links das referências bibliográficas no artigo o navegador desce até a referência no final do artigo, entretanto não existe a volta para o ponto de leitura em que o usuário estava.

**Comment by RPostalli** [comment]
Sugiro que todos os links tenham esta interação, inclusive de imagens.

Ou seja, no XML, todo o rid que tiver um id correspondente deveria ter na interface link que vai e volta.

**Comment by fabiobatalha** [comment]
Sugestões de ticket #235 resolvem este problema

**Comment by javani** [comment]
@jamilatta por favor, me passe o link onde está a interface de um artigo para eu testar. No opac não consigo ver artigos.

**Comment by jamilatta** [comment]
@javani
ainda estamos trabalhando na página do artigo.

@gustavofonseca 
atenção para esse ticket.

**Comment by gustavofonseca** [comment]
to de olho 👀

**Comment by jamilatta** [comment]
Rsrsrsr

Atenciosamente, 

Jamil Atta Junior
