### ISSUE TITLE
Lista de periódicos por instituição

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#245]
@solange-scielo

Não faz sentido apresentar a lista de periódicos por instituição, a maioria dos periódicos possuem instituição única gerando uma lista de 1 instituição para 1 periódico. Os poucos casos onde são apresentados mais de 1 periódico por instituição ocorrem quando um periódico mudou de nome.

**Comment by solange-scielo** [comment]
Essa informação não necessariamente precisa estar na interface do SciELO. Não é uma informação normalizada. Poderíamos disponibilizar essa informação para ser baixada em um arquivo CSV disponível com outros tipos de informação que o SciELO disponibiliza como ocorre com o Analytics.

**Comment by jfunez** [comment]
@fabiobatalha @solange-scielo lembrando que a decisão sobre este issue foi estruturar a listagem em 3 níveis, baseadas na normalização das instituições: Universidades > Faculdades > Departamentos. Também foi mencionada hierarquização para os outros casos, que pelo que eu lembro já estaria discutida e definida com Abel. 
Porém, atualmente não contamos com esta informação, nem hierarquizada nem estruturada, temos apenas o nome que mostramos no único nível da listagem de periódicos.   
E também a mudança para contar com a informação hierarquizada não vai ser imediata.
Se vocês concordarem, podemos fechar este issue, e reabrir quando for implementadas as mudanças e assim teremos a informação estruturada e hierarquizada.

**Comment by solange-scielo** [comment]
Lembro-me que na reunião o Abel comentou que essa informação deveria vir da unidade da Denise (Avaliação) que tem isse detalhadamente descrito e deverá ser incorporado em nossa title ou no Manager.

**Comment by jamilatta** [comment]
Sim, acredito que vocês podem conversar e obter esses dados para serem cadastrado no SciELO Manager no primeiro momento e depois na Title. Estou abrindo um issue para o SciELO Manager e para a Title Manager.

**Comment by jamilatta** [comment]
Ver também: https://github.com/scieloorg/scielo-manager/issues/1300

**Comment by jamilatta** [comment]
Por hora estamos mantendo o desenvolvimento dessa interface até que se tenha uma definição sobre.

**Comment by jfunez** [comment]
Por enquanto foi decidido que a listagem será removida, e voltara quando os dados estiverem enriquecidos adequadamente.
