### ISSUE TITLE
Apresentar o editor de seção (responsável pelo processo de peer-review) no menu lateral esquerdo da página do artigo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#2451]
### Descrição da tarefa
Apresentar o editor de seção (responsável pelo processo de peer-review) no menu lateral esquerdo da página do artigo

```xml
<fn fn-type="edited-by" id="fn1">
	<label>Edited by:</label>
	<p> Luís Fábio Silveira</p>
</fn>
```

```xml
<fn fn-type="edited-by" id="fn2">
	<label>Editors-in-chief:</label>
	<p>Wesley Mendes-da-Silva (Fundação Getulio Vargas, EAESP, Brazil)</p>
	<p>Marcelo de Souza Bispo (Universidade Federal da Paraíba, PPGA, Brazil)</p>
</fn>
```

**Comment by gitnnolabs** [comment]
Versão anterior a essa alteração:

 
![Captura de Tela 2022-11-28 às 09 23 28](https://user-images.githubusercontent.com/86991526/204277198-fbe7e1f6-e95a-45e0-832a-022d22585a16.png)

Após a alteração: 

![Captura de Tela 2022-11-28 às 09 22 40](https://user-images.githubusercontent.com/86991526/204277256-93e7b727-0579-471e-8699-b10b63368f3c.png)


Me parece correto, reparem que o menu lateral aumentou significativamente e que em alguns links ficou com o ":".

**Comment by gitnnolabs** [comment]
![Captura de Tela 2022-11-28 às 16 36 46](https://user-images.githubusercontent.com/86991526/204365652-86ca471d-0520-4d26-a80c-07b75f899e4f.png)
![Captura de Tela 2022-11-28 às 16 35 57](https://user-images.githubusercontent.com/86991526/204365664-31606bb4-c880-43a2-8bc4-aa83d5fbae4a.png)
![Captura de Tela 2022-11-28 às 16 35 29](https://user-images.githubusercontent.com/86991526/204365666-f68a3768-47fe-46d8-82c2-21abf1eb3b92.png)
![Captura de Tela 2022-11-28 às 16 34 47](https://user-images.githubusercontent.com/86991526/204365668-3eeef046-4ae1-4d88-8ba6-6256f9468327.png)
![Captura de Tela 2022-11-28 às 16 34 06](https://user-images.githubusercontent.com/86991526/204365675-9d73095c-73c8-41a0-a2bf-c016aef8f367.png)

**Comment by robertatakenaka** [comment]
Exemplos:
https://www.scielo.br/j/rac/a/zkkkfGsJ9bpX33JmjkcvzNc/?lang=pt
https://www.scielo.br/j/icse/a/3BkhLx6fyNx7rCB6dWgHyPJ/?format=html&lang=pt

**Comment by robertatakenaka** [comment]
Resolvido com v4.0.2
