### ISSUE TITLE
Rolling pass é apresentado incorretamente

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#246]
@solange-scielo

Verificar exemplo de Revista de Saúde Pública.
Verificar como Indicar que publicação é continuada na grade de fascículo.

**Comment by SolangeSantos** [comment]
Okay man
Em 20/06/2016 15:08, "Fabio Batalha" <notifications@github.com> escreveu:

**Comment by jfunez** [comment]
Resolvido segundo discutido na reunião do dia 30/9
