### ISSUE TITLE
Ajustar as opções de como citar. 

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#248]
@solange-scielo 

O serviço de como citar sempre entrega as referências de forma inconsistente pois os dados armazenados no SciELO não permitem a produção de multiplas normas.

Ex: Uma revista que fomenta o uso da norma VANCOUVER não pode ter suas referências apresentadas em outras normas pois as regras de nomeação dos autores e os conjuntos de metadados exigidos diferem das outras normas.

Recomendamos gerar apenas os formatos de exportação bibtext, reference manager, procites, endnotes, refworks, etc.

**Comment by fabiobatalha** [comment]
Ou apenas produzir o formato RIS que é utlizado pelos principais Reference Managers, tais como: ( EndNote, ProCite, Reference Manager, RefWorks, etc.

A PLOS atualmente exporta suas referências somente em RIS.

**Comment by SolangeSantos** [comment]
Fabio
Em 20/06/2016 15:20, "Fabio Batalha" <notifications@github.com> escreveu:

**Comment by solange-scielo** [comment]
A forma inconsistente do como citar tem relação direta com o dado fonte na revista.
Por exemplo: se os nomes do autores já estiverem abreviados no dado fonte, não conseguiremos reproduzir uma norma que indique que os nomes devem ser apresentados por extenso.

![image](https://cloud.githubusercontent.com/assets/13770419/16235415/2f5ec4b0-37ab-11e6-9385-cb3d1ab47f51.png)

**Comment by fabiobatalha** [comment]
Manter exportação para todos os Reference Managers.
Incluir uma versão texto para apresentar a exportação.

**Comment by patrickhilt** [comment]
ProCite há anos que não se vende, e o Reference Manager também foi abandonado o ano pasado, o soporte ao programa termina em desembro. 
Os formatos importantes são RIS, BibTeX e EndNote. 
O Citavi pode importar os três formatos, o RefWorks tem formato particular.

**Comment by jfunez** [comment]
relacionado com: #572

**Comment by jfunez** [comment]
resolvido em #572
