### ISSUE TITLE
Filtrar periódicos ativos e inativos.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#249]
Na lista de periódicos o icone vermelho/verde não indica claramente que se refere aos periódicos ativos e inativos do SciELO.

Permitir filtrar a lista entre periódicos ativos e inativos.

**Comment by francine-curivil** [comment]
Eu já havia criado um ticket para isso: [#216](https://github.com/scieloorg/opac/issues/216)

**Comment by javani** [comment]
@jamilatta @jfunez verificado filtro, contudo a coleção em teste não possui títulos descontinuados. Talvez fosse interessante o teste com uma base que tenha títulos descontinuados também para verificar mensagens e links entre título novo e antigo.
