### ISSUE TITLE
Adicionar na página do artigo o Logo para o SCImago 

### ISSUE THREAD

**Issue by gitnnolabs** [scieloorg/opac#2496]
### Descrição da nova funcionalidade

Eu, como usuário, gostaria que fosse apresentado o link para o ranking de instituição do SCImago na página do artigo, sendo que o link deve ser apresentado para afiliação de cada autor.

Link para o site do SCIMAGO dos rankings de instituições: https://www.scimagoir.com/rankings.php

### Critérios de aceitação

O logo da instituição deve está na lista de autores logo após o label de afiliação, veja a imagem: 

![image (2)](https://user-images.githubusercontent.com/86991526/201229279-73091302-5fa8-4ac9-8f7f-26ac5a6a22d4.png)

### Anexos

Em anexo para essa atividade segue o logo do SCImago. 

[logoSIR.zip](https://github.com/scieloorg/opac/files/9985355/logoSIR.zip)

### Referências
N/A

**Comment by gitnnolabs** [comment]
### Proposta de solução

Irei apresentar algumas propostas de solução ordenado do mais "_paliativo definitivo_" para o mais definitivo. 



**Proposta 1(Este é o que indico)**:

Olhando da na API do **SCImago**, descobri que é possível obter o link para a instituição, realizando uma pesquisa pelo nome da instituição, portanto é possível varremos a lista de autores obtendo sua respectiva instituição e mondando o link. 

**Vantagens**: 

- Não é necessário alterarmos a nossa estrutura de dados para acomodar esses dados
- Passamos a obter os dados do **trust source** o que nos garante que tenhamos as alterações nos dados
- Não precisamos nos preocupar com atualizações desses dados 
- Caso o **idp** que é o id para a instituição mude não precisamos fazer nada
- Estamos sempre "up to date" se uma instituição sair ou entra, tudo bem!!!


**Desvantagem**: 

- Caso a instituição não exista no SCImago não iremos apresentar(isso é verdade para todas as propostas)
- Caso tenha muita diferença de no nome da instituição não iremos apresentar(isso é verdade para todas as propostas)
- Se o **SCImago** estiver fora não iremos apresentar o link 

**Proposta 2(Este não indico)**:

Adicionar no nosso modelo um novo modelo para acomodar esses dados.

Essa proposta seria criamos no modelo do site um novo modelo, para acomodar os seguintes dados: 

```json
{"extraction_date": "2022-09-05", "study_unit": "document", "collection": "scl", "issn_scielo": "0074-0276", "issns": "0074-0276;1678-8060", "title_at_scielo": "Mem\u00f3rias do Instituto Oswaldo Cruz", "title_thematic_areas": "Biological Sciences;Health Sciences", "agricultural_sciences": "0", "applied_social_sciences": "0", "biological_sciences": "1", "engineering": "0", "exact_and_earth_sciences": "0", "health_sciences": "1", "human_sciences": "0", "linguistics_letters_and_arts": "0", "multidisciplinary": "0", "title_current_status": "current", "pid": "S0074-02761992000700005", "document_publishing_year": "1992", "document_type": "research-article", "document_is_citable": "1", "document_affiliation_instituition": "1Liverpool School of Tropical Medicine", "document_affiliation_country": "UKs.af", "document_affiliation_country_iso_3166": "", "document_affiliation_state": "", "document_affiliation_city": "Liverpool", "idp": "62746", "organizacion": "Liverpool School of Tropical Medicine", "country": "GB", "sir_link": "https://www.scimagoir.com/institution.php?idp=62746"}
```

**Vantagens**: 

- Caso o **SCImago** esteja fora iremos mostra o link, porém é possível que não seja possível acesso a página de ranking.

**Desvantagens**: 

- É necessário alterarmos a nossa estrutura de dados para acomodar esses dados
- Não passamos a obter os dados do **trust source** o que não garante a atualização desses dados
- Precisamos nos preocupar com atualizações desses dados 
- Caso o **idp** que é o id para a instituição precisamos atualizar os dados armazenados
- Não estamos sempre "up to date" se uma instituição sair ou entra, tudo bem!!!

**Proposta 3(Definitiva e genérica)**:

Adicionar no projeto [core](https://github.com/scieloorg/core), um modelo para acomodar dados adicionais dos artigos, esse modelo seria genérico e o site seria usuário desses dados assim como qualquer outro usuário e/ou aplicação. 

Penso que esse modelo deve conter compor de referência para o artigo e um campo para acomodar uma estrutura de dados genérica (json) onde seja possível indicar qualquer dado adiciona sobre o artigo. 

Seria necessário um campo para indicar o tipo de dado que está armazenado nessa estrutura e também seria necesário um endpoint (**REST**) que permita que seja obtido esses dados por tipo e com filtros pelo dado json de forma livre no endpoint, visando diminuir o payload para o cliente desses dados. 

Um exemplo de requisição para essa estrutura
http://core/article/data?category=scimago&key__name=USP&fields=link

Sendo que **category** é a categoria do dado adicional do artigo e **key__name** é o filtro. Nesse caso instituição **USP**  e **fields** seria uma lista com separação por "," nesse caso o link para instituição. 


Retorno: 

```json
{
      "filter": {
            "key__name": "USP",
            "category": "scimago"
      },
      "records": {
            "link": "https: //www.scimagoir.com/institution.php?idp=773"
      },
      "found": 1
}
```

Dessa forma podemos criar processamentos para preencher esse modelo e temos sempre esses dados disponíveis em um endpoint no core, sem "sujar" nossa estrutura de dados que não é de nossa responsabilidade, contando claro com tarefas agendadas de coleta e atualização desse modelo

**Comment by robertatakenaka** [comment]
@gitnnolabs independente da fonte de alimentação, o desafio é inserir no html.
É óbvio que a proposta 1 é melhor por pelo menos 2 motivos:
- é menos custosa - não há a necessidade de montarmos uma solução do lado de cá para armazenar e servir os dados
- garante ter os dados atualizados

No entanto, não vamos nos livrar de ter a solução 3, que proporcionar o agrupamento de vários indicadores para geração de relatórios.

Concluindo devemos ter a solução 1 (curto prazo) e 3 (longo prazo).

**Comment by robertatakenaka** [comment]
- https://www.scielo.br/j/abb/a/znMrbS7T6cwCbxr3qh96TZm/?lang=en#

**Comment by gitnnolabs** [comment]
OK vou olhar!

**Comment by gitnnolabs** [comment]
Segue alguns exemplos: 

- https://www.scielo.br/j/alb/a/jqHKZxnmmXcvjLgkzN3xqbL/?format=html&lang=en#
- https://www.scielo.br/j/abd/a/ZHBpFyYptKpKxVYL39pKJMK/?lang=en#ModalTutors
- https://www.scielo.br/j/abd/a/yrPpWjSrZjfX7MBpcd5VXMP/?format=html&lang=en#ModalTutors
- https://www.scielo.br/j/jbn/a/DJLbXktDD6Rxk3yGxq4rMyD/?lang=en#ModalTutors
- https://www.scielo.br/j/pusp/a/MBhvjJRTwC5RSsXwm9TkMMG/?lang=pt#ModalTutors
- https://www.scielo.br/j/pusp/a/c4QGj9hfTBqHcXPWgzmWGhQ/?format=html&lang=pt#ModalTutors

**Comment by robertatakenaka** [comment]
@gitnnolabs reavaliar o código, pois há instituições registradas no scimago e o link não aparece

**Comment by gitnnolabs** [comment]
Em conversa com a @robertatakenaka iremos realizar um ajuste para garantir que seja verificado dos os termos da afiliação  divididos por virgula.

Exemplo: **Pontifícia Universidade Católica de Minas Gerais, Belo Horizonte, MG, Brasil**
