### ISSUE TITLE
R17. Revisar as pesquisas por periódicos

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#25]
## Problema:

Os campos de pesquisa para os periódicos estão incompletos

## Objetivos:

1. Revisar as pesquisar disponíveis para os periódicos na interface de administração, pelo seguintes campos: 

* ID
* Título
* Título ISO
* Título abreviado
* Acrônimo
* Print ISSN
* Eletronic ISSN

#### Atores:
- usuário administrador (webmaster)

#### Fluxo de Eventos Primário (caminho básico):

1. O caso de uso começa quando o usuário administrador acessa a listagem de periódicos no admin. 
2. O usuário utiliza o campo de pesquisa, realizando buscas para cada um dos campos mencionados acima.
3. O Sistema mostra a listagem filtrada pelos critérios da busca.

#### Fluxo de Secundário (caminho alternativo):
*Não corresponde.*

#### Pré-condição:
- O usuário administrador tem acesso ao admin.
- Tem periódicos suficientes para aplicar as pesquisas.

##### Pós-condição:
Nenhum periódico deve ser modificado.

**Comment by jfunez** [comment]
Adicionei na descrição do issue, o caso de uso.
