### ISSUE TITLE
Página da Revista não indica o tipo de ISSN.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#250]

**Comment by francine-curivil** [comment]
O site novo não indica se o ISSN que aparece na página é da versão impressa ou online do periódico:
![exemplo 1](https://cloud.githubusercontent.com/assets/4871433/16265792/ad8fec68-3857-11e6-83ea-27406d7f6fa0.jpg)

Como ainda há periódicos que publicam ambas as versões e por isso possuem dois ISSNs, é importante informar qual ISSN é de qual versão/suporte. Atualmente isso é feito:

![exemplo 2](https://cloud.githubusercontent.com/assets/4871433/16265872/2d047838-3858-11e6-8884-d869991bd93e.jpg)

**Comment by jfunez** [comment]
#### Problema:
No cabeçalho das páginas do periódico, apresenta o ISSN, mas não fica explicito qual tipo de ISSN é exibido, se impreso ou eletrônico.

#### Objetivo:
Ajustar o cabeçalho para mostrar explicitamente o tipo de ISSN junto ao dado (ISSN) como esta no site atual (metodologia):

```
<Titulo do periódicos>
versão impressa ISSN <AAAA-BBBB>
versão On-line ISSN <CCCC-DDDD>
```
(o texto fora das "<" e ">" deve ser traduzível)

**Comment by javani** [comment]
@jamilatta @jfunez verificado. Está ok.
