### ISSUE TITLE
Botão "ACESSIBILIDADE/REPORTAR ERRO" não é lido por leitores de tela

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#2534]
### Descrição do problema
Recebemos o relato de usuários com deficiência visual e que utilizam leitores de tela que o botão "ACESSIBILIDADE/REPORTAR ERRO" não é facilmente encontrado.

### Passos para reproduzir o problema
1. Acesse a página www.scielo.br
2. Utilize um leitor de tela e tente acessar o botão "ACESSIBILIDADE/REPORTAR ERRO" 
3. Alternativamente, acesse a página www.scielo.br, use o botão "tab" do teclado e observe que nunca chega no botão "ACESSIBILIDADE/REPORTAR ERRO"

### Comportamento esperado
O botão "ACESSIBILIDADE/REPORTAR ERRO" deveria ser um dos primeiros links lidos pelos leitores de tela ou tecla tab.

**Comment by gitnnolabs** [comment]
@paratiuid
