### ISSUE TITLE
Mostrar somente PDF do artigo na página do artigo

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#256]
- Adicionar URL de pdf e html que estão disponíveis no AM.
- mostar somente o PDF do artigo na página do artigo
- ajustar a página do artigo, agora deve passar o idioma na url para saber qual PDF abrir
- ajustar os test

**Comment by jfunez** [comment]
As mudanças no processamento já foram realizadas. o salvo algumas inconsistências encontradas no article meta (ver issue: https://github.com/scieloorg/articles_meta/issues/87) faltaria ajustar os templates do OPAC para mostrar o PDF do artigo no idioma certo.
