### ISSUE TITLE
Revisar as filtragens por periódicos 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#26]
## Problema:

Os campos de filtragem para os periódicos estão incompletos

## Objetivo: 

1. Revisar os campos de filtragem disponíveis para os periódicos na interface de administração, pelo seguintes campos:

* Licença de uso
* National Code
* Ano inicial
* Ano Final
* Volume inicial
* Volume Final
* Número inicial
* Número Final
* Status corrente
* Indexadores
* Publico/Despublicado

#### Atores:
- usuário administrador (webmaster)

#### Fluxo de Eventos Primário (caminho básico):

1. O caso de uso começa quando o usuário administrador acessa a listagem de periódicos no admin. 
2. O usuário utiliza os filtros, aplicado para cada um dos campos mencionados acima.
3. O Sistema mostra a listagem filtrada pelos critérios da busca.

#### Fluxo de Secundário (caminho alternativo):
*Não corresponde.*

#### Pré-condição:
- O usuário administrador tem acesso ao admin.
- Tem periódicos suficientes para aplicar as pesquisas.

##### Pós-condição:

- Nenhum periódico deve ser modificado.

**Comment by jfunez** [comment]
Adicionei na descrição do issue, o caso de uso.
