### ISSUE TITLE
Caixa amarela de artigo comentado criou texto para adendo

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#2603]
No artigo: https://www.scielo.br/j/trans/a/SjTdb8jgPc7Lg6d4X8NNDTN/?lang=es

Que possui dois comentários:
1. https://www.scielo.br/j/trans/a/5fw5pdvcC8vZLQGYnMB4sjn/?lang=pt
2. https://www.scielo.br/j/trans/a/BdKCNDYdzFbxCMBXd7vL5Zf/

Foi gerado a caixa com o texto de Adendo:
![image](https://user-images.githubusercontent.com/6084959/217089061-e0f85f80-e053-4544-b983-1adf7b19c93c.png)

O texto da caixa tem que ser gerado com o texto para Artigo Comentado:
(@alexxxmendonca pode validar o texto por favor? PS: Tinha jurado que já tínhamos criado este texto mas não criamos :( )

ARTIGO COMENTADO

PT:
Este documento tem um comentário: [link DOI do comentário]
EN:
This document has a comment: [link DOI do comentário]
ES:
Este documento tiene un comentario: [link DOI do comentário]

COMENTÁRIO

PT:
Este documento comenta: [link DOI do artigo comentado]
EN:
This document comments: [link DOI do artigo comentado]
ES:
Este documento comenta: [link DOI do artigo comentado]

**Comment by robertatakenaka** [comment]
Em `opac/webapp/templates/article/includes/related-article.html` há um bug
<img width="775" alt="Captura de Tela 2023-02-07 às 08 55 21" src="https://user-images.githubusercontent.com/505143/217238326-80546863-8248-486c-804e-4f852a41fd22.png">
O texto deveria ser:
ARTIGO COMENTADO

PT:
Este documento tem um comentário: [link DOI do comentário]
EN:
Este documento tiene un comentario: [link DOI do comentário]
ES:
Esta addenda agrega información al documento: [link DOI do comentário]

**Comment by robertatakenaka** [comment]
@RPostalli os textos acima estão incorretos para inglês e espanhol

**Comment by RPostalli** [comment]
@robertatakenaka corrigi direto no issue para não ficar confuso.

**Comment by robertatakenaka** [comment]
@RPostalli atualizado no site

**Comment by RPostalli** [comment]
@robertatakenaka testado em produção. Tudo OK. Obrigada.
