### ISSUE TITLE
Como citar exibe `issue` incorretamente na parte `year;volume(issue)`

### ISSUE THREAD

**Issue by lpanebr** [scieloorg/opac#2650]
### Descrição do problema
A citação deveria exibir o número do `issue`, mas ao invés disso, está exibindo a `representação textual da edição`.

_Arrisco que usaram o método artigo.issue() ao invés da propriedade ou algo assim._

Não encontrei nada reportado na [lista de tickets abertos sobre como citar](https://github.com/scieloorg/opac/issues?q=is%3Aissue+citar+is%3Aopen).

### Passos para reproduzir o problema
1. Acesse a página [https://www.scielo.br/j/resr/a/dChQPqQMtVzkKjp6JVH9cRb/?lang=pt](https://www.scielo.br/j/resr/a/dChQPqQMtVzkKjp6JVH9cRb/abstract/?lang=pt#)
2. Paire o cursor no botão azul com 3 pontos e clique no ícone para **How to cite this article** 
3. Observe o erro apresentado (ver print)

### Comportamento esperado
- **Como está:** `2024;62(Rev. Econ. Sociol. Rural, 2024 62(1))`
- **Esperado:** `2024;62(1)`

### Screenshots ou vídeos
![image](https://user-images.githubusercontent.com/129185/224784605-3e7afe1d-bd7e-4b9d-9108-f587333933a2.png)

**Comment by gitnnolabs** [comment]
@lpanebr 

Irei fazer o ajuste grato pelo identificação!

**Comment by gitnnolabs** [comment]
PR: https://github.com/scieloorg/opac_schema/pull/104 corrige esse Bug. 

Será atualizado no novo release do projeto.

**Comment by gitnnolabs** [comment]
@lpanebr assim que estiver atualizado te aviso para realizamos novos testes.

**Comment by gitnnolabs** [comment]
@lpanebr o site foi atualizado com a correção!

**Comment by lpanebr** [comment]
Muito bom. Confirmo que a correção ficou boa.
Parabéns e obrigado!
PS: me assustei com a quantidade de testes automáticos na PR. Fala sério, nada como um bom e velho humano pra fazer um teste hein! ;-)

**Comment by gitnnolabs** [comment]
Verdade @lpanebr. 

Grato pelo contribuição!
