### ISSUE TITLE
Redes sociais do periódico na Home

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/opac#277]
Acho que daria mais visibilidade para as redes sociais do periódico se os ícones ficassem no cabeçalho da página do periódico:

![01](https://cloud.githubusercontent.com/assets/4871433/17565447/e6008210-5f0d-11e6-8ebd-3d7a02cff4bd.jpg)

Ou pelo menos em algum lugar da Home ao invés de ficar na página "[Sobre o periódico](http://homolog.opac.scielo.org/abcd/about)", pois acho que nessa página fica muito escondido.

**Comment by jfunez** [comment]
boa tarde @francine-curivil 

Na verdade temos que ocultar esses links (por enquanto), porque não temos como coletar os dados de contas de redes sociais de periódicos, somente pelo SciELO Manager, mas este sistema ainda não contem muitas coleções. 

em breve vamos a enviar um email com as ultimas atualizações do OPAC (homologação) para que vocês enviem mais feedback!

Grato!

**Comment by francine-curivil** [comment]
Boa tarde, @jfunez !

Ok, obrigada!
