### ISSUE TITLE
atualização de depenências

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#279]
Temos uma nova versão de **flask-mongoengine**
https://github.com/MongoEngine/flask-mongoengine/releases/tag/0.8
a lista de mudanças é grande, e a mais interessante é que tem suporte para MongoMock, o que tiraria a parte de Mongo nos tests.
#### Objetivo:

Temos que testar a nova versão, ver se não quebra nada, e trocar nos tests para usar mongomock como recomendado.

**Comment by jfunez** [comment]
@swarzesherz puedes darnos una mano con esto?

El problema que tenemos, es que al momento de ejecutar los tests, precisamos de una instancia de mongo corriendo, y de esta forma los tests demoran más.

Por esto, queríamos cambiar el enfoque, y al momento de ejecutar los tests, pasariamos a utilizar [mongomock](http://docs.mongoengine.org/guide/mongomock.html) como es recomendado por MongoEngine, pero la integración entre la dependencia **flask-mongoengine** no soportaba mongomock hasta su release más reciente: 
- https://github.com/MongoEngine/flask-mongoengine/releases/tag/0.8

Ahora con esta nueva versión, podríamos hacer el cambio y utilizar mongomock.
Entonces las tareas serian:

1. actualizar la versión de flask-mongoengine para 0.8 (ya tenemos un PR para aprobar: https://github.com/scieloorg/opac/pull/280)
2. cambiar la configuración de conexión a mongodb en testing: https://github.com/scieloorg/opac/blob/master/opac/webapp/config/templates/testing.template#L81 ó aqui: https://github.com/scieloorg/opac/blob/master/opac/tests/base.py#L87 para utilizar mongomock
3. remover código que retorna la conexión a la instancia a mongo: https://github.com/scieloorg/opac/blob/master/opac/tests/base.py#L85 y remover la clase: ``MongoInstance`` en ese mismo archivo.
4. ejecutar los tests sin tener una instancia de mongo corriendo, los tests deben pasar y no debe haber ninguna base de datos o dato almacenado resultado de los test.
5. mandar PR y fiesta 🎉 

**Obs:** Esta tarea no es urgente, cualquier cosa estamos en contacto.

**Comment by swarzesherz** [comment]
@jfunez de acuerdo reviso la actualización del PR y el uso de mongomock, estamos en contacto...

**Comment by jfunez** [comment]
feito em: https://github.com/scieloorg/opac/pull/349 sem a parte do mongomock
