### ISSUE TITLE
R20. O sistema deve permitir adicionar um motivo para a "despublicação" de um fascículo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#28]
## Problema: 

No OPAC não é possível adicionar um motivo para "despublicação" de um fascículo

## Objetivo: 

1. Definir como será armazenado
2. Esse motivo deve ser informado em caso de acesso ao recurso do fascículo
3. Esse motivo deve ser informado na ação de "despublicação" pelo usuário administrador

## Casos de uso:
pendente

**Comment by jfunez** [comment]
resolvido em https://github.com/scieloorg/opac/commit/91c3eb46f69b4f81090c8f58f8cfe55ff13ea94f
