### ISSUE TITLE
Corrigir rótulo sobre data de postagem de preprint

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#2832]
### Descrição do problema
Corrigir o rótulo que aparece na seção "Histórico" sobre data de postagem de preprint.

Ex: https://www.scielo.br/j/edur/a/zj7TGF9nnXVWJvnZymkLSvx/?lang=en

Como está:
PT:  Preprint **depositado** em
EN:  Preprint **uploaded** on

Como deve ser:
PT: Preprint **postado** em
EN:  Preprint **posted** on
ES: Preprint **disponible** en

### Screenshots ou vídeos
![image](https://github.com/scieloorg/opac/assets/4059679/7efd25fa-fdde-4536-a38b-6f9fa1d6d234)

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção.

**Comment by RPostalli** [comment]
@robertatakenaka o link continua cortado, só a frase atualizou.
