### ISSUE TITLE
Data availability duplicado no site

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/opac#2878]
Realizei a publicação de um artigo com a informação de disponibilidade de dados marcada incorretamente como `<fn>`, no entanto, quando realizei a correção para marcação em `<sec>` e reprocessei o artigo a informação foi apresentada duplicada no site.

1. Acesse a página: https://www.scielo.br/j/interc/a/BFWKjVtTxGR7qs3PqHYsz6x/?lang=pt
2. Role a página até Disponibilidade de dados
4. Observe o erro apresentado

<img width="105" alt="dados" src="https://github.com/scieloorg/opac/assets/23195801/88e6ab2f-3972-42b2-8f88-4184c70c8043">

<img width="461" alt="dados1" src="https://github.com/scieloorg/opac/assets/23195801/d0508bd7-8c39-4b40-8512-c46492a5feb8">
<img width="436" alt="dados2" src="https://github.com/scieloorg/opac/assets/23195801/7fde92fd-d1b6-4cb9-b201-f014e118f048">

Segue o xml do artigo: [1980-3508-interc-46-e2023122.zip](https://github.com/scieloorg/opac/files/13861360/1980-3508-interc-46-e2023122.zip)

**Comment by robertatakenaka** [comment]
@JoyceRaphaela o problema está no XML que tem 

```xml
<supplementary-material id="s01" content-type="data-supplement" mimetype="application/pdf"
mime-subtype="pdf" xlink:href="1980-3508-interc-46-e2023122-supll.pdf"/>
```
além de `sec[@sec-type='data-availability']`

Fiz um teste local, removendo o supplementary-material e funcionou
<img width="201" alt="Captura de Tela 2024-01-08 às 11 34 01" src="https://github.com/scieloorg/opac/assets/505143/89e73f40-353c-4f95-838c-e795123667c9">
<img width="223" alt="Captura de Tela 2024-01-08 às 11 34 12" src="https://github.com/scieloorg/opac/assets/505143/d1ad96e6-c7fa-4ab2-835b-088a5c5be709">
<img width="872" alt="Captura de Tela 2024-01-08 às 11 34 37" src="https://github.com/scieloorg/opac/assets/505143/775f4bfe-2b5b-4c46-bcbe-86883a725507">
