### ISSUE TITLE
Suporte de URL antigas (metodologia)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#290]
Discussão: poderia ser uma nova view:

```python
@main.route('/scielo.php', methods=["GET", ])
def scielo_php():
   ...
```
aonde se revisam os parámetros da querystring (script, PID, lang) e se faz um **redirect** para a página/view nova.

**Comment by jamilatta** [comment]
Optei por criar uma nova view que espera o fragmento da URL conhecida no site antigo.

Realizei um teste com ~8K de URL antigas e obtivemos apenas pouco menos de um centena de 404 que realmente são registros que não estão na base de dados (Estou verificando o processamento e a existência desses itens no backend).

**Comment by jamilatta** [comment]
Em breve sai um PR.
