### ISSUE TITLE
Link quebrado para a página do artigo na página do seu press-release.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#291]
Com a navegação partindo da página inicial, localize a região identificada como "Press-releases" e em seguida clique em "Knowledge industry: a powerful mechanism". Logo abaixo do título e do número DOI haverá o texto com o link quebrado "Press release relacionado ao artigo: Cad. saúde pública 2016;32(1):e00121114".

<img width="1081" alt="screen shot 2016-09-20 at 10 48 56" src="https://cloud.githubusercontent.com/assets/161335/18672918/50e672f6-7f20-11e6-979e-eb282eee3a84.png">

**Comment by amandasramalho** [comment]
@jamilatta O mesmo erro ocorre com os links dos e.mails do autor. Ao clicar não existe nenhuma ação.

**Comment by jfunez** [comment]
@jamilatta os press release serão visualizados no blog, certo? acho que podemos fechar este issue

**Comment by jamilatta** [comment]
Sim.
