### ISSUE TITLE
Botão de compartilhamento no press release?

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#295]
Seria interessante incluir opção de compartilhamento do press release direto desta visualização que existe?

**Comment by jfunez** [comment]
@jamilatta pode atualizar este issue? agora que a cada press release mostrado na home da coleção é um link pro blog de Press Release, é necessário os botões de compartilhar que menciona  @amandasramalho ?

**Comment by amandasramalho** [comment]
@jfunez @jamilatta 
Este issue ficou desatualizado com as novas atualizações. Antes havia um preview no site... agora quem clica nos links, é redirecionado pro blog ou pro twitter (na qual já possui os botões...). Mas vi que a coluna dos press releases não estão mais na home... normal?

**Comment by jfunez** [comment]
@amandasramalho não tem press releases aparecendo porque não tem nenhuma press release cadastrada... agora estamos trabalhando em importar os press releases de um blog SciELO e quando o usuário clicar vai ser direcionado ao post no blog (que teria os botões de compartilhar)...

Então vamos fechar este issue e quando fique pronto a importação de PRs pedimos para você avaliar/validar novamente ok?
