### ISSUE TITLE
Adicionar a funcionalidade de envio de e-mail em todas as páginas.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#297]
### Problema: 

Não funciona o envio de e-mail nos links para envio em todas as páginas. 

### Objetivo:

Garantir o model de envio de e-mail esteja funcionando em todas páginas.

O corpo do e-mail pode ser composto somente pela msg: 

```
O usuário ['email do remetente'] compartilha este link: ['link'], da SciELO
```

Por hora somente essa msg, depois podemos melhorar essa msg com a sugestão da equipe.

**Comment by jamilatta** [comment]
Arturo cualquer duda... estamos aqui!

**Comment by swarzesherz** [comment]
De acuerdo 👍

**Comment by almeida-fabio** [comment]
Não está prevista essa funcionalidade de envio por e-mail na página de pdf de um artigo? Ex.:

http://homolog.opac.scielo.org/aiss/2015.v51n4/267-269/en/
