### ISSUE TITLE
Revisar as filtragens por fascículos 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#30]
## Problema:

Os campos de filtragem para os fascículos estão incompletos

## Objetivo: 

1. Revisar os campos de filtragem disponíveis para os fascículos na interface de administração, pelo seguintes campos:

* Periódico
* Licença de uso
* Volume
* Número
* Tipo
* Mês de inicio
* Mês de final
* Ano
* Publicado/Despublicado

#### Atores:
- usuário administrador (webmaster)

#### Fluxo de Eventos Primário (caminho básico):

1. O caso de uso começa quando o usuário administrador acessa a listagem de fascículos no admin. 
2. O usuário utiliza os filtros, aplicado para cada um dos campos mencionados acima.
3. O Sistema mostra a listagem filtrada pelos critérios da busca.

#### Fluxo de Secundário (caminho alternativo):
*Não corresponde.*

#### Pré-condição:
- O usuário administrador tem acesso ao admin.
- Tem fascículos suficientes para aplicar as pesquisas.

##### Pós-condição:
- Nenhum fascículo deve ser modificado.

**Comment by jfunez** [comment]
Adicionei na descrição do issue, o caso de uso.
