### ISSUE TITLE
titulo "Declaração sobre acesso aberto" sem tradução

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#305]
#### Problema:

Na página: http://homolog.opac.scielo.org/open_access/
tem o título: "Declaração sobre acesso aberto" e assim aparece em todos os idiomas (pt,en, es)

#### Objetivo:
Traduzir o título para quando muda o título da interface (pt, en, es)

**Comment by jamilatta** [comment]
Este tk é dependente do #301

**Comment by jamilatta** [comment]
Adicionei esse item como sendo um item na página de about que resolve a questão do idioma. 

Em breve sai um PR.
