### ISSUE TITLE
imprimir a página das listagens ainda precisa de ajustes 

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#309]
resultado atual:
[Saúde Pública.pdf](https://github.com/scieloorg/opac/files/503413/Saude.Publica.pdf)
[Saúde Pública2.pdf](https://github.com/scieloorg/opac/files/503412/Saude.Publica2.pdf)

**Comment by jamilatta** [comment]
@jfunez 

por gentileza, quais são os ajustes que você acredita que são necessários?

**Comment by jfunez** [comment]
@jamilatta pode dar uma olhada nos pdfs que deixei como anexo no ticket, pode ver que aparecem algumas "linhas" no canto superior direito, isso teríamos que ser removido.
Outra coisa é que: quando escolher para imprimir as listagens temáticas ele imprimia a alfabética...
E no caso de imprimir as listagens colapsáveis deveria aparece tudo expandido para ver os periódicos em questão.

**Comment by jamilatta** [comment]
Dependente do ajuste do #308.

**Comment by jamilatta** [comment]
Verificamos melhor e não existe problemas.
