### ISSUE TITLE
R21. O sistema deve permitir filtrar todos os fascículos despublicados pelas justificativas.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#31]
## Dependência:

#28 

## Problema:

O sistema não permite filtrar fascículos pelas justificativas de "despublicação".

## Objetivo: 

1. Dever ser possível filtrar fascículos pelas justificativas de "despublicação" pelo usuário admin na interface de administração

## Casos de uso:
pendente

**Comment by jfunez** [comment]
resolvido em https://github.com/scieloorg/opac/commit/91c3eb46f69b4f81090c8f58f8cfe55ff13ea94f
