### ISSUE TITLE
Exibir imagem no feed do blog SciELO

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#318]
No feed do blog, exibir as imagens thumbnails de cada post.

**Comment by jamilatta** [comment]
@alexxxmendonca, por gentileza, verificar com o designer como será apresentando essas imagens para que possamos dar continuidade ao desenvolvimentos.

**Comment by alexxxmendonca** [comment]
Ok. 

Favor marcar com o label "Design" os tickets que necessitarem de trabalho do designer. Assim fica mais fácil de identificá-los.

**Comment by alexxxmendonca** [comment]
O designer foi informado e está trabalhando nisso.

**Comment by paratiuid** [comment]
@alexxxmendonca 
No arquivo Colecao/index.html foi adicionada a imagem como solicitado.
Estamos à disposição!

Atenciosamente.

**Comment by paratiuid** [comment]
@alexxxmendonca 
segue a sugestão de posicionamento da imagem:

![screen shot 2018-04-05 at 6 05 24 pm](https://user-images.githubusercontent.com/22373640/38391713-601c17a8-38fb-11e8-9ecc-27cdc60a16f0.png)

Aguardo aprovação.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Para adicionarmos esse novo recurso no site é necessário que a image das notícia estejam no RSS Feed do WordPress. 

Estive procurando como fazer isso no WordPress e achei essa opção: https://wordpress.org/plugins/add-featured-image-to-rss-feed/ é um plugins para adicionar a imagem no feed. 

Enquanto não tivermos essas imagens no feed do blog é impossível aprovar esse PR. 

Caso precise de alguma ajuda estou a disposição.

**Comment by alexxxmendonca** [comment]
Aberto chamado para a instalação do plugin.

**Comment by jamilatta** [comment]
@alexxxmendonca ok

**Comment by jamilatta** [comment]
@alexxxmendonca 

Algum retorno da equipe de infraestrutura?

**Comment by alexxxmendonca** [comment]
@jamilatta ainda não.

Quando houver, o ticket será atualizado por mim.

**Comment by jamilatta** [comment]
Ok, Alex Grato!

**Comment by alexxxmendonca** [comment]
@jamilatta conseguimos inserir as imagens no feed do blog, não por meio do plugin, mas sim por meio de alteração no código do Wordpress.

https://blog.scielo.org/feed/

Podemos retomar essa demanda?

**Comment by cesarbruschetta** [comment]
Branch #paratiuid-tk318

**Comment by patymori** [comment]
@alexxxmendonca , poderia verificar no ambiente de homologação?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação! 👍

**Comment by patymori** [comment]
@alexxxmendonca , disponível em produção.
