### ISSUE TITLE
Lista de periódicos - Novos números

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#320]
Realizar as seguintes alterações na lista de periódicos:
- Novos periódicos
- Eliminar Métricas
- Novos número: faixa horizontal com os número publicados recentemente, localizado antes dos press-releases.

**Comment by jfunez** [comment]
pendente:
> Novos número: faixa horizontal com os número publicados recentemente, localizado antes dos press-releases.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Realizamos esse desenvolvimento sem utilizar uma interface definida pelo designer, portanto se for preciso melhor esse desenvolvimento é necessário termo um mockup feito pelo designer. 

Verificar esse desenvolvimento no home page do site: http://homolog.opac.scielo.org

**Comment by alexxxmendonca** [comment]
👍
