### ISSUE TITLE
Importar e Exibir Press releases vindos do Blog

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#321]
Ficou definido em reunião que o conteúdo virá do blog, através de RSS.

#  Definição de testes de aceitação
### No site
1. Listar 20 últimos _Press Releases_ vindos do blog na _home_ da coleção
2. Na página do periódico, listar os últimos 20 _Press Releases_ relacionadas apenas a este periódico.

### No Admin
1. Acrescentar uma página para importação para _Press Releases_ , equivalente a página notícias.
2. Deve dispor de um link para importar todos
3. Listar todos _Press Releases_

**Comment by jamilatta** [comment]
E-mail enviado, ver: 

Boa tarde a todos, 

Em reunião com o Alex e Fabio Almeida e depois juntamente com o Juan, definimos como será realizado a coleta dos RSS dos Press Releases no Blog do SciELO. 

Inicialmente pensamos em adicionar novos campos no RSS, como por exemplo um campo (custom field) chamado "Acronym" para identificar a periódico, porém analisando melhor verificamos que isso iria quebrar a especificação do RSS (W3C). 

Analisando melhor descobrimos que é possível utilizar as categorias hierarquizadas. Atualmente existe uma categoria chamada press-release, adicionando mais uma categoria que será o acrônimo do periódico... sendo assim possível coletar os press-release por periódico e/ou todos os press-release. 

URL que serão disponibilizadas para a coleta: 

/category/press-release/feed (Coleta todos os press-release)
/category/press-release/rsp/feed (Coleta todos os press-release do periódico rsp)


Qualquer dúvida estamos a disposição, 

Jamil Atta Junior e Juan Funez

**Comment by jamilatta** [comment]
Utilizar o endereço: http://pressreleases.scielo.org/ para coletar os press-releases.

**Comment by jamilatta** [comment]
Link de exemplo para o Press Release do Blog: http://pressreleases.scielo.org/blog/category/cr/feed/

**Comment by jamilatta** [comment]
Garantir que os press-releases sejam ordenados pelos mais recentes.

**Comment by jamilatta** [comment]
@brunousml consegui realizar esse ajuste?

**Comment by brunousml** [comment]
@jamilatta Todo essa tarefa sim.

**Comment by jamilatta** [comment]
👍

**Comment by brunousml** [comment]
@alexxxmendonca solicitou que mantivéssemos a coesão em relação a forma de apresentar os press releases tanto na home da coleção, como na página do periódico. Tomando como referência a apresentação da home da coleção.

**Comment by brunousml** [comment]
@alexxxmendonca as alterações solicitadas foram aplicadas. Por gentileza, você poderia validar?

https://homolog.opac.scielo.org/

**Comment by alexxxmendonca** [comment]
Testado e aprovado.
