### ISSUE TITLE
Demarcar a área de leitura (Texto centralizado)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#330]
Considerar a interface do ReadCube como exemplo: 

<img width="1410" alt="screenshot 2016-10-18 13 45 27" src="https://cloud.githubusercontent.com/assets/373745/19485223/2884e89a-9539-11e6-888b-c23125d7810f.png">

**Comment by caramez** [comment]
Segue o layout com o texto centralizado:
https://invis.io/VR75HH77T#/202757209_Artigo-Inicio

**Comment by jamilatta** [comment]
@caramez 

Achei a área do texto muito pequena, na minha opinião deveríamos aumentar a área de leitura, repare que a rolagem vertical ficou muito grande!

**Comment by alexxxmendonca** [comment]
@jamilatta isso está relacionado com o #331, não?

**Comment by jamilatta** [comment]
SIm. 

Vou adicionar o comentário no #331.

**Comment by jfunez** [comment]
Feito pelo Designer
