### ISSUE TITLE
Melhorar a experiência de leitura na página do artigo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#331]
Avaliar uma quantidade em linha aceitável de caracteres para um leitura em tela(Desktop).

**Comment by caramez** [comment]
Como foi pedido, mantemos uma linha com aproximadamente 90 caracteres.
As recomendações são entre 80 e 120 por linha.

Segue o layout:
https://invis.io/VR75HH77T#/202757209_Artigo-Inicio

**Comment by jamilatta** [comment]
@caramez

Achei a área do texto muito pequena, na minha opinião deveríamos aumentar a área de leitura, repare que a rolagem vertical ficou muito grande!

**Comment by alexxxmendonca** [comment]
@jamilatta essa largura de 90 caracteres foi definido em reunião baseado em estudos que dizem que a experiência de leitura é melhor dessa forma.

**Comment by jfunez** [comment]
Feito!
