### ISSUE TITLE
Referência da citação deve abrir em um tooltip ao clicar.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#333]
Para removermos o comportamento de **top -> down** nas citações, decidimos que as citações terá um tooltip para monstrando o conteúdo da citação.

**Comment by caramez** [comment]
No layout apresentado, seguimos com uma linha semelhante ao PlosOne:
https://invis.io/VR75HH77T#/202757209_Artigo-Inicio

**Comment by jamilatta** [comment]
@caramez 

Gostei 👍

**Comment by alexxxmendonca** [comment]
@caramez não havíamos combinado de retirar o fundo azul dos indicadores das citações?

**Comment by caramez** [comment]
@alexxxmendonca eu não havia entendido isso. Vou trocar.

**Comment by jfunez** [comment]
Feito!
