### ISSUE TITLE
Criar um menu suspenso no canto direito. 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#334]
Para substituir o menu superior direito que contém os links da imagem abaixo, ver: 

<img width="525" alt="screenshot 2016-10-18 13 56 50" src="https://cloud.githubusercontent.com/assets/373745/19485756/ccb377d2-953a-11e6-8d95-c28c62b3d177.png">

Adicionar um menu lateral suspenso tipo ReadCube:
- Métricas
- Figuras e Tabelas
- Versões (PDF, ePDF, XML, ePUB, etc)
- Idiomas do artigo
- Exportar e como citar
- Tradução automática
- Artigos similares

Ver: 

<img width="472" alt="screenshot 2016-10-18 13 55 15" src="https://cloud.githubusercontent.com/assets/373745/19485789/e0bd499c-953a-11e6-992e-40c85764db66.png">

**Comment by caramez** [comment]
Criamos o menu, porém optamos por dar a mesma relevância a todos eles.
https://invis.io/VR75HH77T#/202757209_Artigo-Inicio

**Comment by jamilatta** [comment]
@caramez 

esse menu so não está suspenso por que é um desenho é isso?

**Comment by caramez** [comment]
@jamilatta é isto mesmo, ali não tem como simular isto lá.

**Comment by jamilatta** [comment]
👍

**Comment by jfunez** [comment]
Feito!
