### ISSUE TITLE
Desenhar um exemplo de tabela e imagem em uma janela modal.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#337]
Considerando os seguintes exemplo, bolar uma janela em modal para as imagens e tabelas, ver os links: 

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-14392015005006107&lng=en&nrm=iso&tlng=en#t05

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1413-35552016005008105&lng=en&nrm=iso#t03

http://www.scielo.br/article_plus.php?pid=S0080-21072016000200225&tlng=en&lng=en

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-14392016005019103&lng=en&nrm=iso&tlng=en

**Comment by caramez** [comment]
Pessoal, ainda uma prova de layout:
https://invis.io/VR75HH77T#/202757214_Artigo-Modal-Tabelas-Detalhe

A ideia neste caso foi manter a tabela sem muitas divisórias horizontal, deixando apenas com ação do mouse-over. 

Uma discussão que devemos ter é sobre a questão do rowspan. Vocês acham que colocamos divisórias (ficando mais sujo), ou conseguimos verificar se tiver rowspan e mudar o layout nestes casos?

**Comment by jamilatta** [comment]
@caramez 

Gostei 👍

**Comment by scielo** [comment]
É complicado isso, pois nem todas tabelas possuem esse formato canônico.

Existem tabelas com colunas e linhas com merge e coisas do tipo.

*Fabio Batalha C. Santos*
Lider de Tecnologia
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

On Sun, Nov 6, 2016 at 10:50 PM, Jamil Atta Junior <notifications@github.com

**Comment by jfunez** [comment]
Feito!
