### ISSUE TITLE
R25. Revisar as pesquisas por artigos

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#34]
## Problema:

Os campos de pesquisa para os artigos estão incompletos

## Objetivos:

1. Revisar as pesquisar disponíveis para os artigos na interface de administração, pelo seguintes campos: 

* ID
* Issue
* Journal
* Título
* Chave de domíno

## Casos de uso:
pendente

#### Atores:
- usuário administrador (webmaster)

#### Fluxo de Eventos Primário (caminho básico):

1. O caso de uso começa quando o usuário administrador acessa a listagem de artigos no admin. 
2. O usuário utiliza o campo de pesquisa, realizando buscas para cada um dos campos mencionados acima.
3. O Sistema mostra a listagem filtrada pelos critérios da busca.

#### Fluxo de Secundário (caminho alternativo):
*Não corresponde.*

#### Pré-condição:
- O usuário administrador tem acesso ao admin.
- Tem artigos suficientes para aplicar as pesquisas.

##### Pós-condição:
Nenhum artigo deve ser modificado.

**Comment by jfunez** [comment]
Adicionei na descrição do issue, o caso de uso.
