### ISSUE TITLE
Label "Home da Revista"

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/opac#340]
No texto na label "Home da revista", trocar o termo revista por periódico:

![image](https://cloud.githubusercontent.com/assets/8592848/19560662/19c7ac30-96b4-11e6-821d-8d2cb5742eef.png)

**Comment by jfunez** [comment]
@almeida-fabio a etiqueta: **"home da revista"** foi definido em reunião de revisão com Abel. 
Qual seria o motivo da mudança?

**Comment by alexxxmendonca** [comment]
Normalmente utilizamos "periódico". Foi acordado para utilizar especificamente o termo "revista"?

**Comment by jfunez** [comment]
@alexxxmendonca Sim. "home da revista" foi o que ficou registrado no [issue (226)](https://github.com/scieloorg/opac/issues/226#issuecomment-228834405) durante a reunião de revisão

**Comment by alexxxmendonca** [comment]
Não me lembro especificamente, mas tudo bem então, ignorem esse pedido.
