### ISSUE TITLE
Revisar as filtragens por artigo 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#35]
## Problema:

Os campos de filtragem para os artigos estão incompletos

## Objetivo: 

1. Revisar os campos de filtragem disponíveis para os artigos na interface de administração, pelo seguintes campos:

* Fascículo
* Periódico
* Ahead of Print
* Publicado/Despublicado

#### Atores:
- usuário administrador (webmaster)

#### Fluxo de Eventos Primário (caminho básico):

1. O caso de uso começa quando o usuário administrador acessa a listagem de artigos no admin. 
2. O usuário utiliza os filtros, aplicado para cada um dos campos mencionados acima.
3. O Sistema mostra a listagem filtrada pelos critérios da busca.

#### Fluxo de Secundário (caminho alternativo):
*Não corresponde.*

#### Pré-condição:
- O usuário administrador tem acesso ao admin.
- Tem artigos suficientes para aplicar as pesquisas.

##### Pós-condição:
- Nenhum artigo deve ser modificado.

**Comment by jfunez** [comment]
Adicionei na descrição do issue, o caso de uso.
