### ISSUE TITLE
Lista de Grandes Áreas do Conhecimento

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#352]
Na lista de periódicos por Grandes Áreas, as revistas devem estar separadas apenas pelas "grandes áreas" que são:  (http://homolog.opac.scielo.org/journals/#theme).

en
       AGRICULTURAL SCIENCES
       APPLIED SOCIAL SCIENCES
       BIOLOGICAL SCIENCES
       ENGINEERING
       EXACT AND EARTH SCIENCES
       HEALTH SCIENCES
       HUMAN SCIENCES
       LINGUISTICS, LITERATURE AND ARTS

pt  
       CIENCIAS AGRARIAS
       CIENCIAS BIOLOGICAS
       CIENCIAS DA SAUDE
       CIENCIAS EXATAS E DA TERRA
       CIENCIAS HUMANAS
       CIENCIAS SOCIAIS APLICADAS
       ENGENHARIAS
       LINGUISTICA, LETRAS E ARTES

Veja site SciELO atual: http://www.scielo.br/scielo.php?script=sci_subject&lng=en&nrm=iso

Não sei se é possível ou viável ou tem a ver, mas pelo menos internamente, as pessoas as vezes buscam a qual área um determinado periódico pertence, sendo assim é muito mais fácil dar um control F com o nome da revista. Da forma que esta disposto esta página, impossibilitaria a busca desta forma, sendo que a pessoa deveria abrir área por área para "achar" a revista.

**Comment by alexxxmendonca** [comment]
@RPostalli Eu também faço isso para descobrir a área de um periódico. Mas note que se você escrever o título do periódico no campo de busca dessa página, o site filtra apenas aquele periódico.

**Comment by RPostalli** [comment]
Olha que maravilha. \o
Então perfeito, o problema era da falta de conhecimento da usuária.
Fica então para este ticket apenas a situação das grandes áreas.
Obrigada Alex.

**Comment by jfunez** [comment]
@RPostalli 

**Sobre as Grande áreas:**
O dado que usamos para agrupar os periódicos é dado que vem no periódico... ou seja nós não fixamos nada... portanto se tem que se limitar a 8 grandes áreas deve ser ajustado no dado... 

Por este motivo coloquei a etiqueta de discutir neste issue

**Sobre a busca na s listagem**:
Como bem explicou @alexxxmendonca tem a função de busca na parte superior da listagem

HTH!

**Comment by RPostalli** [comment]
Juan me explique por favor esse "vem do periódico", onde vocês buscam está informação? Temos o dado das grandes áreas da title de cada periódico. Essa listagem se for mantida, não representa GRANDES áreas, são apenas áreas, sub-áreas (são quase infinitas, creio que impossível de mapear num website).

Ver mais em:  http://fisio.icb.usp.br:4882/posgraduacao/bolsas/capesproex_bolsas/tabela_areas.html

**Comment by jfunez** [comment]
@RPostalli 
> Juan me explique por favor esse "vem do periódico", onde vocês buscam está informação? Temos o dado das grandes áreas da title de cada periódico. 

A nossa fonte de dados é Article Meta, e sim, conferimos e também temos o dado de Grandes Áreas.

Discutimos aqui com a equipe e verificamos que vamos mudar a listagem para agrupar os periódicos pelas grandes áreas... Porem não temos como agrupar revistas de forma hierarquizada em grande área e sub área (são campos independentes)

Por exemplo a revista: **Revista de Economia e Sociologia Rural** tem 2 grandes áreas e 2 sub áreas.

E pelo consultado aqui com a equipe não temos uma definição oficial de correspondência entre Grandes áreas e suas Sub áreas (como você indicou no link)...
Caso tenha alguma dúvida ou comentários sobre esta decisão pedimos para você vir conversar com a equipe, que pode explicar melhor os argumentos e citar mais exemplos...

**Comment by RPostalli** [comment]
Sim concordo, fica inviável disponibilizar as subáreas. Existem como eu disse diversas (milhares mesmo) de subáreas e ainda estas subáreas podem ser mescladas, e ainda existem as "adaptações" o que complica ainda mais.  As Grandes Áreas são fixas e usadas de forma universal. De acordo com a decisão. Obrigada!

**Comment by jamilatta** [comment]
Ticket resolvido por favor verificar no ambiente de homologação.

http://homolog.opac.scielo.org/journals/

**Comment by RPostalli** [comment]
Verificado. OK
