### ISSUE TITLE
Abrir link de submissão online em nova janela

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#353]
O link de submissão online deve abrir em "_blank", tanto na lista de periódicos quanto na página do periódico:

![image](https://cloud.githubusercontent.com/assets/4059679/20139320/9314dba4-a66c-11e6-95fd-7c21fe239a47.png)

![image](https://cloud.githubusercontent.com/assets/4059679/20139308/865b02da-a66c-11e6-9079-f472ce92e724.png)

**Comment by jfunez** [comment]
@swarzesherz nos puedes dar una mano con esta tarea? gracias!!

**Comment by alexxxmendonca** [comment]
Também no menu suspenso:

![image](https://cloud.githubusercontent.com/assets/4059679/20139715/9868e616-a66e-11e6-894d-244adf971462.png)

**Comment by jamilatta** [comment]
👍

**Comment by swarzesherz** [comment]
👍

**Comment by jfunez** [comment]
Muchas gracias @swarzesherz !!

@alexxxmendonca este issue também já foi corrigido, por favor validar ele na próxima atualização do ambiente de homologação

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.opac.scielo.org/
