### ISSUE TITLE
Arquivo Excel exportado vem desconfigurado

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#354]
Ao exportar a lista de títulos, o arquivo não vem com codificação UTF-8 e não vem tabulado:

![image](https://cloud.githubusercontent.com/assets/4059679/20139361/d7e74e88-a66c-11e6-9d7a-f8f9c72a9160.png)

Como é um Excel, já deveria vir com as tabulações.

**Comment by jfunez** [comment]
@alexxxmendonca  este issue já foi registrado em #208 e @jamilatta esta trabalhando neste momento... 
Por favor verificar se o problema já foi reportado antes de abrir novos issues.

Por acompanhar o progresso da solicitação no issue #208
Grato!
