### ISSUE TITLE
[Verificar] Link de submissão online para periódicos (discutir comportamento dos "não-correntes")

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#355]
Discutir qual será o comportamento para os links de submissão online nos títulos não-correntes:

![image](https://cloud.githubusercontent.com/assets/4059679/20139462/62c9a4f6-a66d-11e6-8038-95133d0e74c4.png)

Sugestão: manter o ícone mas desativar o link.

**Comment by jamilatta** [comment]
Item realizado e implantado.

**Comment by alexxxmendonca** [comment]
Os links continuam ativos para os periódicos não correntes. Pensei que eles não iriam ficar clicáveis...

E por que os periódicos que possuem sistema online o link não está apontando para ele?

**Comment by jamilatta** [comment]
@alexxxmendonca 

poderia por gentileza apontar um exemplo dos periódicos que tem link para o sistema de submissão para que possamos analizar.

**Comment by alexxxmendonca** [comment]
Periódico ICSE (Interface) deveria ter, assim como: CSC, PHYSIS.

**Comment by jamilatta** [comment]
Grato @alexxxmendonca

**Comment by jfunez** [comment]
@jamilatta considerar o apontado pelo Alex no outro issue relacionado #577) 
```
Apenas para constar: as URLs dos sistemas estão cadastradas no SciELO Manager e estão Ok.
```

**Comment by jfunez** [comment]
resolvido em: https://github.com/scieloorg/opac/pull/659
