### ISSUE TITLE
Motivo aparecendo no "Histórico deste periódico na coleção"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#356]
O motivo da desindexação está aparecendo no Histórico:

![image](https://cloud.githubusercontent.com/assets/4059679/20139675/617987c8-a66e-11e6-9423-fdf48f6445fc.png)

Essa informação é de uso interno apenas, certo?

**Comment by jamilatta** [comment]
Precisamos discutir sobre, mas acredito que é de uso interno mesmo. 

Caso decidirmos que isso não deve ser apresentado a solução seria remover esse motivo na origem (SciELO Manager).

**Comment by jamilatta** [comment]
Adicionei a etiqueta de discutir.
