### ISSUE TITLE
Carrossel/Feed do SciELO em Perspectiva e do Twitter sem "trava"

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#359]
Quando clicamos na setinha do carrossel, aparece áreas em branco... o @alexxxmendonca disse que isso já foi reportado, mas eu não achei o ticket.

![image](https://cloud.githubusercontent.com/assets/5446933/20140213/2c308c12-a671-11e6-9f6c-361886977875.png)

**Comment by jfunez** [comment]
@caramez você pode dar uma ajuda aqui?

**Comment by caramez** [comment]
@jfunez alteramos o script que faz o scroll horizontal:
http://scielohomolog.parati.ag/Colecao/

Dá uma olhada no objeto Slider:
http://scielohomolog.parati.ag/static/js/main.js
