### ISSUE TITLE
Atualizar Página Equipe

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#360]
Faz algum tempo, com autorização do Abel e coordenação, a página da equipe SciELO foi atualizada.

Está:
http://homolog.opac.scielo.org/collection/about/?page_id=05be840f06d647078ba023f8a9405d36

Deveria ser:
http://www.scielo.br/equipe/equipe_p.htm

Por favor atualizar.

**Comment by jfunez** [comment]
@RPostalli esta página junto com outras são editáveis pela interface de administração do OPAC, o que chamamos de OPAC Admin.

Cadastrei seu email para ter acesso a esta área de administração, você deve receber um email para configurar sua senha e pode acessar...

Pode dar uma olhada, mas fique tranquila que estamos com a ideia de fazer uma reunião com as pessoas interessadas (semana que vem possivelmente) para mostrar, ensinar como operar e assim dar manutenção ao OPAC...

Qualquer duvida estamos a disposição

**Comment by RPostalli** [comment]
Juan o email não veio e não esta no spam!

**Comment by jfunez** [comment]
OK! vamos verificar! Obrigado!

**Comment by jfunez** [comment]
Resolvido e envio de email!

Agora pode editar a página da equipe pelo OPAC Admin
