### ISSUE TITLE
Falta email do rodapé da página

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#361]
Falta a divulgação de email do Rodapé da página. Está da seguinte forma:

SciELO - Scientific Electronic Library Online
Avenida Onze de Junho, 269 - Vila Clementino 04041-050 São Paulo SP - Brazil - Brasil Phone: +55 11 5083-3639/59 ***EMAIL?***

Acredito que deva constar o email de todas as equipes SciELO. Desta forma o usuário já direciona sua dúvida para a equipe específica, no caso de não saber ao certo, envia no padrão SciELO.

- produção: <producao@scielo.org>
- tecnologia: <tecnologia@scielo.org>
- submissão: <scielo.submission@scielo.org>
- avaliação: <scielo.avaliacao@scielo.org>
- administração: <administracao@scielo.org>

e por fim o <scielo@scielo.org>

**Comment by jfunez** [comment]
@RPostalli Essa informação com o endereço de SciELO e telefone, é um dado editável pela interface de administração (OPAC Admin), indicado em outro issue :)

**Respeito a disponibilizar os emails de cada área:**
Isso não foi contemplado nos mockups, talvez o @alexxxmendonca pode ver isso com o designer e escolher o melhor lugar para colocar tais informações.

Esses emails vão depender da coleção? ou vão atender todas as coleções da rede? Suspeito que podem receber emails por questões alheias ao escopo de atuação de cada área, por exemplo, problemas de usuário ou de conexão com o site, etc...  inclusive colocar todos esses emails em copia para uma demanda pontual... mesmo sendo uma demanda válida para uma área, vai gerar ruído para as outras, me explico?

O que você acha @alexxxmendonca ?

**Comment by RPostalli** [comment]
Juan eu vi o outro ticket, fico no aguardo do email para editar, vou realizar as alterações que dizem respeito a minha equipe OK.

Todo o site tem que ter o email de contato, o mockup tem que contar com este dado (não?), caso contrário todos vão usar o único meio de contato divulgado que é o telefone e acredito que teremos grandes problemas. 

Tanto o scielo.br quanto o org possuem o email de contato no rodapé (o geral scielo@scielo.org). Outras coleções tem os emails gerais de seus países.

Acho válido a divulgação do email das equipes em BR, mas entendo sua colocação, precisamos fazer uma reunião sobre e avaliar o que vale mais a pena.

**Comment by jfunez** [comment]
@RPostalli 
> Juan eu vi o outro ticket, fico no aguardo do email para editar, vou realizar as alterações que dizem respeito a minha equipe OK.

Já foi enviado (para seu email da SciELO), caso você não tenha recebido, por favor verifique no Spam e caso não esteja lá, vamos revisar se o tem algum problema. O seu login será email (da SciELO, e a senha definida por você com o link enviado por email).

> Todo o site tem que ter o email de contato, o mockup tem que contar com este dado (não?), caso contrário todos vão usar o único meio de contato divulgado que é o telefone e acredito que teremos grandes problemas. 

Entendo, entonces @alexxxmendonca tem que passar essa demanda para o designer, assim nós (desenvolvimento) sabermos aonde colocar tais informações.

> Tanto o scielo.br quanto o org possuem o email de contato no rodapé (o geral scielo@scielo.org). Outras coleções tem os emails gerais de seus países.

Essa informação é importantíssima, assim podemos ajustar o modelo de dados e assim inserir/ajustar tais emails.

> Acho válido a divulgação do email das equipes em BR, mas entendo sua colocação, precisamos fazer uma reunião sobre e avaliar o que vale mais a pena.

Então vou marcar este issue como a etiquete de discussão, para ser tratado na próxima revissão

**Comment by alexxxmendonca** [comment]
Caso seja definido que essa demanda será aplicada, será solicitado ao designer uma alteração no mockup.

**Comment by RPostalli** [comment]
SciELO.org
SciELO Brasil
SciELO Saúde Pública
scielo@scielo.org

SciELO África do Sul
scielo@assaf.org.za

SciELo Argentina
scielo@caicyt.gov.ar

SciELO Bolivia
infocyt@minedu.gob.bo

SciELO Chile
scielo@conicyt.cl

SciELO Colombia
scielo@unal.edu.co

SciELO Costa Rica
binas@ns.binasss.sa.cr

SciELO Cuba
scielo@infomed.sld.cu

SciELO Espanha
scielo@isciii.es

SciELO México
scielo@dgb.unam.mx

SciELO Peru
scielo@concytec.gob.pe

SciELO Portugal
dsectsi.scielo@dgeec.mec.pt

SciELO Uruguai
biname@fmed.edu.uy

SciELO Venezuela
scielo_venezuela@yahoo.es

**Comment by jamilatta** [comment]
@alexxxmendonca e @RPostalli 

por favor verifiquem no ambiente de homologação que este item já esta resolvido. 

Aguardo a confirmação de vocês para que possamos fechar esse ticket.

**Comment by RPostalli** [comment]
Esta OK, nas 3 interfaces.



Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[Atenção: A versão XPM 11/04/2016, será descontinuada em 9 de janeiro de
2017. Por gentileza, passem a usar a versão com relatório 21/11/2016
<http://docs.scielo.org/projects/scielo-pc-programs/en/latest/download.html>
]

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

Em 24 de novembro de 2016 10:06, Jamil Atta Junior <notifications@github.com

**Comment by jamilatta** [comment]
@RPostalli grato. 

Irei fechar esse ticket porém ele é importante para termos a lista de contato dos outros países.
