### ISSUE TITLE
Type: "Nenhum fascículo encontrado para esse perióico" (falta letra d em periódico)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#368]
No processo de tradução Thais encontro o seguinte erro:
> Nenhum fascículo encontrado para esse perióico

E apontou que falta a letra **"d"** na palavra **periódico**.

o string esta localizado em: 
``opac/webapp/templates/issue/grid.html:91``

Corrigir!

**Comment by jamilatta** [comment]
Corrigido e atualizado no ambiente de homologação.
