### ISSUE TITLE
Traduzir texto do menu da área "Thematic" em EN e ES

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#374]
![image](https://cloud.githubusercontent.com/assets/5446933/20396877/cbeed1b0-acce-11e6-9ac1-a28b8f69bb6f.png)

**Comment by jamilatta** [comment]
👍

**Comment by jamilatta** [comment]
Item realizado verificar em http://homolog.opac.scielo.org

**Comment by amandasramalho** [comment]
Ok, confirmado.
![image](https://cloud.githubusercontent.com/assets/5446933/20595119/de2afe0c-b21f-11e6-973e-4c8233e53ad7.png)
