### ISSUE TITLE
Traduzir as indicações de idioma do texto/resumo do sumário EN e ES

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#375]
![image](https://cloud.githubusercontent.com/assets/5446933/20397333/7c1e1f40-acd0-11e6-80b2-43bc4c2204bd.png)

**Comment by jamilatta** [comment]
Item realizado verificar em: http://homolog.opac.scielo.org

**Comment by amandasramalho** [comment]
Ok. Verificado.
![image](https://cloud.githubusercontent.com/assets/5446933/20599246/4005f1f4-b234-11e6-9266-9a360836d996.png)

![image](https://cloud.githubusercontent.com/assets/5446933/20599271/5e9e5c0a-b234-11e6-9a29-7a992fcbd4ae.png)
