### ISSUE TITLE
Alterar grafia "Último número" em EN

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#377]
![image](https://cloud.githubusercontent.com/assets/4059679/20398216/b328bc90-acd3-11e6-9334-ca8c9c866cf5.png)

Na interface em Inglês, sugiro que seja alterada a grafia de "Last" para "Latest".

"Latest" seria o mais correto e mais comumente utilizado. "Last" aplicaria-se apenas se não houvessem futuros números -- o que não é o caso.

**Comment by jamilatta** [comment]
👍

**Comment by jamilatta** [comment]
@alexxxmendonca 

verificar no ambiente de homologação: http://homolog.opac.scielo.org.

**Comment by alexxxmendonca** [comment]
Para mim ainda aparece "Last".

**Comment by jamilatta** [comment]
@alexxxmendonca 

verifica agora por gentileza.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.opac.scielo.org/
