### ISSUE TITLE
Atualizar a documentação da Wiki do projeto 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#378]
Diante das mudanças para instalação e operação do projeto é necessário revisarmos e atualizarmos a documentação da Wiki do projeto.

Ver: https://github.com/scieloorg/opac/wiki

**Comment by jfunez** [comment]
Atualizei as settings novas:
https://github.com/scieloorg/opac/wiki/Configura%C3%A7%C3%A3o-padr%C3%A3o-e-vari%C3%A1veis-de-ambiente
