### ISSUE TITLE
Adicionar CitedbyAPI para metricas dos artigos e periódicos.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#379]
O @fabiobatalha desenvolveu uma API em cima do citedby para retornar as citações dos artigos e dos periódicos 

Avaliar o uso para implementação desse recurso na página do artigo.

**Comment by jfunez** [comment]
acho que seria melhor deixar essa lógica no opac_proc 
ou precisa ser mostrado os dados atuais em cada requisição?

**Comment by jamilatta** [comment]
Os dados terão um delay de 3 meses... isso implica em não precisamos de modelo e a consulta é feita em um arquivo json caso não tenha é requisitado para o backend o que garante que precisamos somente importa e usar.

A idéia é que devemos como uma biblioteca.

**Comment by jfunez** [comment]
então se encaixa bem para ficar no processamento, eu acho

**Comment by jamilatta** [comment]
Encaixa e encaixaria mesmo que não fosse um lib que tivessimos que coleta, mas acredito que não precisamos armazenar algo que a biblioteca entrega sem problemas de intergração que é o que nos leva a estocar em nossas base de dados.

**Comment by jamilatta** [comment]
Esse ticket é inválido, pois, nas últimas reunião ficou decidido que não será apresentado métricas no site. Iremos sempre exibir métrica no http://analytics.scielo.org.
