### ISSUE TITLE
Criar na grade de fascículos a informação "Publicação Contínua"

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#380]
Em conversa com a Solange, foi definido que é importante que as revistas que publicam na modalidade continuada (PC) tenham uma sinalização da grade dos fascículos.

Temos 2 casos desta modalidade.
OBS: Ver figura 7 do Guia de PC para maiores informações: <http://www.scielo.org/local/Image/guiarpass.pdf>

**Volume**
exemplo rsp - passou a ser PC em 2015
<http://homolog.opac.scielo.org/rsp/issues/>

**Volume e número**
exemplo bjmbr - passou a ser PC em 2016
<http://homolog.opac.scielo.org/bjmbr/issues/>

No primeiro caso como existe uma mudança na periodicidade, fica mais claro que a revista mudou (mais ainda assim não fica claro que mudou a modalidade de publicação; parece apenas que mudou a periodicidade)

Já no segundo caso, onde a revista não altera a periodicidade, fica indetectável que a revista publica em outra modalidade.

Atualmente temos 35 revistas que publicam como PC, são elas:

ACR: volume.
AIB: volume.
BABT: volume.
BJMBR: volume e número.
BN: volume e número.
BOR: volume e número.
BPSR: volume e número
HIS: volume.
JVATITD: volume.
RGENF: volume e número.
RSP: volume.
CSP: volume e número 
NAU:  volume.
NI: volume e número.
RBCS: volume 
RBCSoc: volume e número.
RBEF: volume e número. 
RBSO: volume 
RLAE: volume.
RIMTSP: volume
TCE: volume e número
ZOOL: volume e número
RBPI: volume e número
PRC: volume 
RBF: volume e número (6 números ano)
JPE: volume 
ISZ: volume
BAR: volume e número
EAN: volume e número
PTP: volume e número 
ALB: volume
BJFT: volume.
RESP: volume
CR: volume e número (12 ano ano)
CPA: número (3 ao ano)

**Comment by fabiobatalha** [comment]
@RPostalli 

Entendemos a necessidade. Agora necessitamos que vocês definam junto com a direção como essa sinalização deverá ser implementada. O Resultado desta definição deve ser um ou mais mockups exemplificando o que deverá ser desenvolvido.

Vocês podem consultar o @alexxxmendonca sobre sugestões de implementação da solução na interface do novo site.

**Comment by RPostalli** [comment]
Outro caso bor (não convencional - único caso em SciELO)

http://www.scielo.br/scielo.php?script=sci_issues&pid=1806-8324&lng=en&nrm=iso

**Comment by jfunez** [comment]
Só para lembrar que esta discussão já foi levantada na primeira reunião de revisão, e segundo o registrado no issue #246 foi discutido e **definido** nessa reunião.

Vide issue: https://github.com/scieloorg/opac/issues/246

**Comment by alexxxmendonca** [comment]
@jfunez acessei o #246 mas não encontrei registrado o que ficou definido. 

Já temos então uma definição?

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

Infelizmente o que foi discutido não foi documento. Entretanto, como alguns já haviam mencionado na reunião, a implementação definida parece não resolver o problema.

Segue imagem do que foi implementado.

![screen shot 2016-11-18 at 15 14 57](https://cloud.githubusercontent.com/assets/504142/20439308/150919fe-ada2-11e6-9721-52e00b51c8c3.png)

**Comment by alexxxmendonca** [comment]
Entendo.

@caramez, você poderia propor uma solução?

Minha sugestão é um label ao lado de "Todos os números"/"All issues".

**Comment by RPostalli** [comment]
@fabiobatalha a forma como foi implementado resolve o problema para 1 dos dois casos que temos de revistas nessa modalidade (caso somente volume).
@alexxxmendonca não acho legal "dividir" os números em duas grade, acho que bastaria um label ao lado do ano na linha da grade dos fascículos com a informação "Publicação Contínua".

**Comment by jamilatta** [comment]
Item definido em reunião que irá ser apresentado conforma imagem enviado pelo @fabiobatalha. 

Implantado.
