### ISSUE TITLE
Configurar transifex para tradução colaborativa

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#39]
#### Problema:
Precisamos ter a capacidade de traduzir os textos. Temos a opção de utilizar (como foi estabelecido para outros projetos) a integração com [Transifex](https://www.transifex.com/)

#### Objetivo:
- configurar o transifex para poder traduzir os textos lá, sob a organização SciELO. 

#### Extra:
As traduções ficam em: [``opac/app/translations``](https://github.com/scieloorg/opac/tree/master/app/translations)

#### Dependências:
- ~~Para realizar esta tarefa, o issue #12 deve ser incorporado/resolvido previamente.~~ :white_check_mark: feito!

**Comment by jfunez** [comment]
@fabiobatalha acho que você tem permissões absolutas e insuperáveis no transifex da SciELO ;)
poderia dar uma olhada?

**Comment by jfunez** [comment]
@fabiobatalha já versionei o arquivo .POT, e esta disponível  em: 
[https://github.com/scieloorg/opac/blob/master/app/translations/messages.pot](https://github.com/scieloorg/opac/blob/master/app/translations/messages.pot)

mas não consigo adicionar Resources nessa interface bonita do transifex, que segundo a documentação deveria aparecer assim:
![transifex_add_resource_file](https://cloud.githubusercontent.com/assets/805749/12393019/302b91e8-bdda-11e5-9e31-60e7e91dd6c3.png)

mas o que eu vejo é:
![screenshot 2016-01-18 11 51 10](https://cloud.githubusercontent.com/assets/805749/12393027/3e2ff1b2-bdda-11e5-98ac-ee3a0a5f58f4.png)

**Comment by scielo** [comment]
Vou ver se consigo.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by jfunez** [comment]
Feito!

:beers:
