### ISSUE TITLE
Integrar com Sentry para  notifiação de erros

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#395]
#### Problema:
não temos logs nem reporte de erros quando acontece em runtime para o OPAC

#### Objetivo:
- Criar uma instância de Sentry (Docker Container)
- Integrar o OPAC com Sentry

#### Obs:
Com a nova infra (rancher) podemos configurar facilmente uma instância de Sentry, também é possível instalar localmente um container para trabalhar no desenvolvimento (docker-compose-dev.yml)

- container Sentry: https://hub.docker.com/_/sentry/
- manual de integração e doc oficial (Sentry + Flask): https://docs.sentry.io/clients/python/integrations/flask/#usage
- Para instalar na nova infra (rancher) é só acessar o Catálogo, buscar por Sentry e seguir os passos :)

**Comment by jamilatta** [comment]
@jfunez realizou essa atividade.
