### ISSUE TITLE
Mapear urls de páginas secundárias

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#421]
Em conversa com a Solange e equipe fomos informados que é necessário mapear as páginas secundárias do site.

É interessante observar como foram mapeadas as URLs do OPAC para Periódico, Fascículo e Artigo.

**Comment by gustavofonseca** [comment]
@jamilatta, o que significa _mapear as URLs do OPAC_? Seria algo como resolver as URLs do site clássico?

**Comment by jamilatta** [comment]
@gustavofonseca esse ticket já foi realizado veja: 

Link para o site clássico: 

https://www.scielo.br/revistas/alea/iedboard.htm

Se acessarmos no novo site novo, verificamos que está funcionando: 

https://new.scielo.br/revistas/alea/iedboard.htm
