### ISSUE TITLE
Permitir a ordenação dos Sponsor na área de administração 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#422]
Sugestão da equipe poder ordenar a lista de sponsors no Admin do OPAC.

**Comment by jfunez** [comment]
Acredito que este issue já foi resolvido por @patymori, adicionando o campo `order` no registro de sponsor. Essa funcionalidade esta em produção já.

concordam? @jamilatta @paratiuid @alexxxmendonca 
![screen shot 2018-11-09 at 09 59 17](https://user-images.githubusercontent.com/805749/48261419-2b2b6100-e406-11e8-9ba8-66d9c4cb9d90.png)

**Comment by jamilatta** [comment]
@jfunez 

Acho que é só fechar repare na data do ticket **Dec 13, 2016**  e data de implementação: **Nov 28, 2017.**
