### ISSUE TITLE
Filtros para recuperar as "páginas secundárias"

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#423]
Diante da quantidade de itens na lista de páginas secundárias, a equipe sugeri poder realizar uma ordenação. 

Para executar essa atividade verificar com a equipe responsável pela gestão do Admin quais ordenações são necessárias.

**Comment by alexxxmendonca** [comment]
Atualmente existem estes filtros disponíveis:

![image](https://user-images.githubusercontent.com/4059679/118029443-8d98ab80-b33a-11eb-9cb0-4206ccd1c03c.png)

É possível filtrar por periódico utilizando o acrônimo.

Estou fechando este ticket por ora, acreditando que os filtros atuais atendam à necessidade de localizar uma página secundária específica.
