### ISSUE TITLE
Trocar o editor de HTML das páginas secundárias para Redactor JS

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#424]
Para facilitar o upload das imagens é possível alterar o editor de HTML.

**Comment by jfunez** [comment]
Conversando com @alexxxmendonca escolhemos usar o TinyMCE pelas facilidades de editar o HTML:

- https://www.tinymce.com/

**Comment by jfunez** [comment]
O editor foi atualizado e já atende todas os requisitos. Portanto vou fechar este ticket
