### ISSUE TITLE
Adicionar templates das páginas secundárias no Admin do OPAC.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#426]
Diante da dificuldade e da quantidade de páginas secundárias ficou acertado que seria interessante termos um template com a "maioria" das seções utilizadas na páginas secundárias.

**Comment by jfunez** [comment]
Este issue trata sobre falta de conteúdo no site. A ferramenta de administração do site permite inserir tal conteúdo, que será feito pelo responsável de conteúdo.

Em reunião no dia 28/6/17 com Abel, foi definido que o responsável pelo conteúdo será @alexxxmendonca

Vamos agendar uma serie de reuniões para tratar a inserção de conteúdo como Alex e sua equipe.
