### ISSUE TITLE
integração com Travis-CI

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#43]
#### Problema:

Não é possível integrar este repo com travis, porque não sou admin do repo, ergo não tenho permissão para isso:
> Sorry, but we can't find any repositories you have admin access to. 
> You require admin rights to enable these repositories

#### Objetivo:

Integrar este repo com Travis-CI (já foi adicionado o [arquivo ``.travis.yml``](https://github.com/scieloorg/opac/pull/42/files#diff-354f30a63fb0907d4ad57269548329e3))

**Comment by jamilatta** [comment]
Realizado direto no master.
