### ISSUE TITLE
Erro ao tentar baixa a lista de periódicos. 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#436]
Ao tentar baixar os arquivo .csv e xls, encontramos o seguinte erro: 

<img width="1390" alt="screenshot 2016-12-22 10 53 42" src="https://cloud.githubusercontent.com/assets/373745/21426272/18e52920-c835-11e6-82c0-cd5d05aeb1db.png">

Acredito que esse erro deve ter sido provocado após a atualização para o PY3.5.

**Comment by jfunez** [comment]
Tentando baixar a lista alfabética (XLS ou CSV) quando tem um periódico sem last_issue, gera erro:
https://homolog.sentry.scielo.org/sentry/homologopacscieloorg/issues/126/

```
AttributeError

'NoneType' object has no attribute 'volume'
```

**Comment by jamilatta** [comment]
Este último erro esta relacionado com o tk: https://github.com/scieloorg/opac_proc/issues/56 (opac_proc)
