### ISSUE TITLE
Erro de carga na lista alfabética.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#459]
Em um dado momento a lista alfabética retorna o seguinte erro: 

![screenshot 2017-02-07 09 09 47](https://cloud.githubusercontent.com/assets/373745/22688924/806c1388-ed15-11e6-9aec-38f25729c033.png)

Se ententi alguma periódico não esta conseguindo retornar o segmento da URL.

**Comment by jfunez** [comment]
@jamilatta valida na homologação (após o deploy da última versão no rancher) e se estiver OK, pode fechar este issue.

**Comment by jamilatta** [comment]
Testado e aprovado.
