### ISSUE TITLE
Press Release da "MAN" não aparece

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#463]
O press release da MAN foi publicado em 01 de Fevereiro, somente no idioma Inglês:

http://pressreleases.scielo.org/en/category/press-releases/man/

Entretanto, esse press release não aparece na interface em Inglês da home do periódico:

https://homolog.opac.scielo.org/man/

**Comment by brunousml** [comment]
Bom dia @alexxxmendonca. Acabei de reprocessar a importação dos press releases e o registro apareceu. Você pode confirmar pra mim, por favor?

**Comment by alexxxmendonca** [comment]
Deu certo! 👍 
Fica só o alerta para que isso não tenha que ser feito sempre.

**Comment by jamilatta** [comment]
Ok, ciente.
