### ISSUE TITLE
Feed rss do blog com resultados duplicados e desconfigurado nas interfaces EN e ES

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#480]
O feed rss do blog está com resultados duplicados e nas interfaces EN e ES está aparecendo verticalmente.

**Comment by jfunez** [comment]
boa @alexxxmendonca !!!
a duplicidade já esta resolvida... não será mais necessário importar às noticias pelo admin do opac...
agora o problema do layout vamos investigar

**Comment by alexxxmendonca** [comment]
👍

**Comment by jfunez** [comment]
@alexxxmendonca já foi incoporado o fix... em breve vamos atualizar o ambiente de homologação para você validar

**Comment by alexxxmendonca** [comment]
👍

**Comment by jamilatta** [comment]
@alexxxmendonca poderia validar no ambiente de homologação: https://homolog.opac.scielo.org/

**Comment by alexxxmendonca** [comment]
Agora está ok, mas o feed está desatualizado, certo? Não está mostrando os press releases mais recentes.

**Comment by jamilatta** [comment]
@alexxxmendonca vou rodar o processamento para obter os press-release mais novos.

**Comment by jamilatta** [comment]
@alexxxmendonca poderia verificar agora?

**Comment by alexxxmendonca** [comment]
Entrou mais um, mas tem outros 5 já publicados.

É só vocês compararem: http://pressreleases.scielo.org/

**Comment by jamilatta** [comment]
@alexxxmendonca esta ambiente é o SciELO Saúde Pública então coletamos somente os press release para saúde pública.

**Comment by alexxxmendonca** [comment]
Ah... ok... é que tem horas que é Saúde Pública, horas que é Brasil...

Então está tudo ok.

**Comment by jamilatta** [comment]
👍
