### ISSUE TITLE
Modal da Tabela

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#492]
Ao abrir modal da tabela, apresentar além de rótulo (Tabela 1), apresentar também caption. Exemplo:
Table 5 (label): Electrical elements fitted values for the T0 sample up to 96 hours of immersion in a 0.05 mol.L–1 NaCl solution. The error percentage associated with each parameter value is given in parenthesis.  (caption)

<img width="884" alt="captura de tela 2017-04-19 as 13 02 31" src="https://cloud.githubusercontent.com/assets/505143/25189742/783e852e-2500-11e7-9c04-5da52b3563b9.png">

Atualmente, somente aparece o label Table 5
<img width="905" alt="captura de tela 2017-04-19 as 13 03 12" src="https://cloud.githubusercontent.com/assets/505143/25189787/995b345a-2500-11e7-9c17-438fc79841c2.png">

**Comment by caramez** [comment]
@robertatakenaka este item já havia sido finalizado.
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
resolvido
