### ISSUE TITLE
Apresentação de intervalo de citação

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#493]
Em um texto, pode apresentar um intervalo de citações numéricas, por exemplo 17-19.
Para não perder a fluidez da leitura, optamos pelo desenho de apresentar o texto da referência quando o usuário coloca o mouse sobre o número. Desta forma, quando há um intervalo, por exemplo, 17-19, a referência 18 fica omissa. Considerar que há casos em que o intervalo pode ser maior. Propor uma solução para que não se perca as referências ocultas.

<img width="761" alt="captura de tela 2017-04-07 as 11 19 31" src="https://cloud.githubusercontent.com/assets/505143/25189915/09ce38b8-2501-11e7-8720-cb60620e08d8.png">
<img width="881" alt="captura de tela 2017-04-07 as 11 19 43" src="https://cloud.githubusercontent.com/assets/505143/25189916/09d49654-2501-11e7-9905-b09bbe419c13.png">

**Comment by caramez** [comment]
@robertatakenaka na último forum que tivemos eu dei a sugestão de existir uma aba dentro da janela de citação. Você comentou que ia ver com o pessoal. 

Como vamos tocar isto, posso proceder com a ideia da aba?

**Comment by robertatakenaka** [comment]
@caramez : só registrei aqui, ainda não comentei com todos. Por favor, aguarde.

**Comment by robertatakenaka** [comment]
@caramez uma idéia que me ocorreu é cria um modal para cada referência (ou nota), de forma que se aparece mais de uma vez dentro do texto a menção à referência (ou nota), a ação é mostrar o modal. No caso dos intervalos, no modal da referência, apareceria um "botão/ícone/caracter" para visualizar o próximo e até mesmo o anterior.

**Comment by caramez** [comment]
@robertatakenaka então mudamos tudo para modal mesmo? Acho que é uma questão funcional sobre a função da referência e data nota também. Acho que interrompe muito a leitura.

Mas se optarem, vamos pra cima e mudamos tudo.

**Comment by robertatakenaka** [comment]
@caramez : acho que não sei html, js e css o suficiente para decidir isso... Quando dei a idéia esperava que você me dissesse se é válido ou não, se tem o resultado idêntico ou não, o que acha?

**Comment by caramez** [comment]
@robertatakenaka então comentei sobre a questão funcional, para ver uma referência você sai do mouseOver para 2 cliques para abrir e fechar. Acho que compromete o ritmo de leitura. Foi isso o que eu disse.

Agora a solução por modal resolve esta questão do intervalo. Talvez fosse o caso de tratar os intervalos de forma diferente por modal por exemplo. Não sei se pega a questão de consistência.

Acho que podemos experimentar 2 modelos em termos de protótipo. A ideia de aba dentro da nota e o modal para ver qual seria a melhor.

**Comment by robertatakenaka** [comment]
@caramez : Entendi. Ficou mais claro que modal só é possível visualizar clicando. Pensei que talvez pudesse ter o mesmo comportamento do mouseOver... (Disse que nunca fui especialista de CSS/JS/HTML hehehe)

Quando puder o ideal é apresentar modelos para o pessoal daqui decidir. Com algo mais concreto visível fica mais fácil de discutir.

**Comment by caramez** [comment]
@robertatakenaka pois até dá para abrir no mouseOver, mas imagina passar o mouse sem querer e travar a tela no modal.

O que vai pegar é questão das prioridades, precisamos ver o que vem na frente. Acho que seria uma boa hora para discutir isto, estamos nas últimas horas deste mês.

**Comment by robertatakenaka** [comment]
@caramez : por enquanto este é de menor prioridade na minha opinião, não que não seja importante, mas porque vai demorar mais tempo. Então, é melhor resolver o que é bug primeiro. Isso não considero bug, considero que é algo que não tínhamos pensado.

**Comment by robertatakenaka** [comment]
@jamilatta @jfunez @gustavofonseca @fabiobatalha @alexxxmendonca 
O que acham?

(0034-8910-rsp-48-01-0170)

<img width="661" alt="captura de tela 2017-06-29 as 14 57 56" src="https://user-images.githubusercontent.com/505143/27702776-885de6bc-5cdb-11e7-9d9c-2087144d8f30.png">
<img width="664" alt="captura de tela 2017-06-29 as 14 57 48" src="https://user-images.githubusercontent.com/505143/27702779-8ac90756-5cdb-11e7-8df0-b2f7092f00c8.png">
<img width="610" alt="captura de tela 2017-06-29 as 14 57 35" src="https://user-images.githubusercontent.com/505143/27702782-8cc4f22c-5cdb-11e7-8a08-536a013a1bf6.png">

**Comment by alexxxmendonca** [comment]
No caso, por que não aparece a última referência? Referência 48 no primeiro exemplo, e referência 65 no segundo exemplo.

**Comment by robertatakenaka** [comment]
porque para ver a 48 é só colocar o mouse na 48

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by alexxxmendonca** [comment]
Faz sentido, mas à princípio o comportamento que eu esperava era que aparecessem todas.

**Comment by robertatakenaka** [comment]
@alexxxmendonca : não tenho certeza...
Pensei de fazer isso tanto para a 46 como para a 48, ou seja, em ambas aparecer 46, 47, 48, mas o problema que vejo é que ao fazer isso, se o usuário entrar em 48, ela estaria lá no final, de qualquer forma... tampouco sei se seria "comportamento esperado", entende?

**Comment by alexxxmendonca** [comment]
Se pensarmos assim, a referência 46 deveria aparecer somente quando o mouse over ocorrer nela.

Eu vejo como sendo um conjunto: "46-48".

**Comment by robertatakenaka** [comment]
Entendo, mas eles não são identificados como um intervalo, são identificados individualmente... Vou tentar ver o que posso fazer.

**Comment by gustavofonseca** [comment]
@robertatakenaka, eu não entendi tua proposta do comentário https://github.com/scieloorg/opac/issues/493#issuecomment-312047364

**Comment by robertatakenaka** [comment]
no intervalo 51-53, ao mouserover 51, mostra 51 e 52, mouseover 53 mostra 53.

**Comment by gustavofonseca** [comment]
hm eu esperava que o intervalo 51-53 fosse tratado como unidade, indivisível, e apresentasse as referências 51, 52 e 53. Sua implementação segue alguma norma/convenção que eu desconheço?

**Comment by robertatakenaka** [comment]
@gustavofonseca @alexxxmendonca : na verdade, isso depende mais de como está representado o dado no XML e, em qualquer forma de representação, é complicado representar no HTML. 

Por exemplo, para representar 15-17. Vou ilustrar como poderia estar no XML e quais impactos para apresentar no HTML

```<xref rid="B15">15</xref>-<xref rid="B17">17</xref>```
De alguma forma posso identificar que há o caracter hífen e assumir que é um intervalo de b15 a b17. É possível. No entanto, não estou certa da melhor forma de apresentar isso.

```<xref rid="B15">15-17</xref>```
Nesta forma, para montar o "link" para o mouseover é bem melhor, no entanto, veja que se perde a explicidade de que é um intervalo de B15 a B17. Claro que se supor que se teria que assumir que B + o que tiver após o hífen. É possível, mas não é explícito. É B por convenção... e se não for B quebra a regra. E quem garante que estaria bonitinho assim numero-numero?

Não há nenhuma restrição ou recomendação no uso de xref para SciELO:
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-xref.html
Na documentação do PMC, está:
https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-xref

Concluindo há muitas questões que definições.

Acho que para uma primeira versão está aceitável, pois apesar de não ser o ideal (não sei qual é o ideal mas este não é), não deixa de apresentar as referências ao leitor.

<img width="401" alt="captura de tela 2017-06-30 as 10 26 34" src="https://user-images.githubusercontent.com/505143/27737482-acb3849c-5d7e-11e7-8c03-bee9e41d8152.png">
<img width="367" alt="captura de tela 2017-06-30 as 10 26 47" src="https://user-images.githubusercontent.com/505143/27737486-add72c2a-5d7e-11e7-8caf-f23c88f73307.png">

**Comment by alexxxmendonca** [comment]
Entendo.

_Acho que para uma primeira versão está aceitável, pois apesar de não ser o ideal (não sei qual é o ideal mas este não é), não deixa de apresentar as referências ao leitor._

Concordo, e talvez seja necessário rever as restrições e recomendações do xref para SciELO, pensando nessa questão.

**Comment by jfunez** [comment]
@robertatakenaka podemos fechar este issue?
