### ISSUE TITLE
Modelo: Carta e Resposta

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#495]
Apresentar um modelo para carta e resposta.

Exemplo: 

http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0102-311X2015000701571&lng=en&nrm=iso&tlng=en
http://www.scielosp.org/pdf/csp/v31n7/0102-311X-csp-31-7-1571.pdf

**Comment by caramez** [comment]
@alexxxmendonca @robertatakenaka 
Seguem a proposta: 
http://scielohomolog.parati.ag/Artigo/cartas.html

**Comment by robertatakenaka** [comment]
ok. (Vale a entrega do dia 2017-04-27)
