### ISSUE TITLE
Artigo com Biografia

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#496]
Biografia pode conter uma foto + texto biográfico

Exemplo:
http://www.scielosp.org/pdf/bwho/v91n8/0042-9686-bwho-91-08-551.pdf

**Comment by caramez** [comment]
@robertatakenaka @alexxxmendonca 
Segue a proposta: http://scielohomolog.parati.ag/Artigo/bibliografia.html

No conteúdo vão notar duas caixas de autor, representam o modelo com e sem foto.

**Comment by robertatakenaka** [comment]
Acho que ficou de acordo com o esperado

**Comment by robertatakenaka** [comment]
@caramez : uma correção não é bibliografia, mas sim biografia
```xml
<div class="articleBibliography">
```

**Comment by caramez** [comment]
@robertatakenaka seguem as correções:

Protótipo: http://scielohomolog.parati.ag/Artigo/biografia.html
Download: http://scielohomolog.parati.ag/2017-05-10-Artigo-Correcoes2.zip

**Comment by robertatakenaka** [comment]
resolvido 2017-05-10
