### ISSUE TITLE
Modelo de Editorial com assinatura

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#498]
Fazer o modelo para apresentação de assinatura
Exemplo: 
http://www.scielosp.org/pdf/csp/v32s1/1678-4464-csp-32-s1-eED01S116.pdf

**Comment by caramez** [comment]
@robertatakenaka @alexxxmendonca 
Segue a proposta para a página: http://scielohomolog.parati.ag/Artigo/editorial.html

**Comment by robertatakenaka** [comment]
Me refiro a apresentar um estilo para:

<img width="208" alt="captura de tela 2017-04-27 as 16 36 51" src="https://cloud.githubusercontent.com/assets/505143/25501099/dfd4b696-2b67-11e7-9143-aa3e13435684.png">

**Comment by caramez** [comment]
@robertatakenaka dá uma olhada.
http://scielohomolog.parati.ag/Artigo/editorial.html

**Comment by robertatakenaka** [comment]
isso mesmo

**Comment by robertatakenaka** [comment]
Resolvido na entrega 27-04-2017
