### ISSUE TITLE
Artigo com comentários

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#499]
Apresentar um modelo de artigo com comentários.
Exemplo: 
http://www.scielosp.org/pdf/rsp/v49/pt_0034-8910-rsp-S0034-89102015049005549.pdf
A partir de **Destaques** é o treco de comentários.

**Comment by caramez** [comment]
@robertatakenaka @alexxxmendonca 
A seção highlights no conteúdo atende a solicitação?
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
ok. Entrega do dia 2017-04-27
