### ISSUE TITLE
Atualizar a versão do Flask-Admin

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#50]
#### Problema:
A versão da dependência: Flask-Admin esta desatualizada. Atualmente estamos pinados com a versão 1.3.0 e o repositório oficial com a 1.4.0.

#### Objetivo:
- Visando não ficarmos com dependências antigas (ajustando o arquivo: ``requirements.txt``) devemos atualizar o Flask-Admin para a versão mais recente.
- Acrescentar uma regra no Makefile, para facilitar a atualização de todas as dependências. Ver: [regra ``deps`` no Makefile do SciELO Manager](https://github.com/scieloorg/scielo-manager/blob/beta/Makefile#L8).

**Comment by jfunez** [comment]
@jamilatta
Ajustei a descrição do issue para o formato definido. E adicionei a tarefa relacionada ao Makefile.
