### ISSUE TITLE
Tabela que contém link para as referências e link para a nota da própria a tabela

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#500]
Na tabela, fazer com que o link para as referências e para as notas tenham o mesmo comportamento que quando estão no texto.

![captura de tela 2017-04-19 as 11 44 06](https://cloud.githubusercontent.com/assets/505143/25191207/458f7340-2505-11e7-83fb-7f462b67597d.png)

HTML que contém a tabela mencionada.

[1020-4989-RPSP-40-05-332.en.html.zip](https://github.com/scieloorg/opac/files/936133/1020-4989-RPSP-40-05-332.en.html.zip)

**Comment by caramez** [comment]
@robertatakenaka @alexxxmendonca 
Segue a proposta de um modelo que contenha os 2 itens.
Justiticativa: Como a tabela já é flutuante não imaginamos algo flutuando por cima, pensamos em apenas acionar o scroll natural do modal.

http://scielohomolog.parati.ag/Artigo/#ModalTable1

**Comment by robertatakenaka** [comment]
Resolvido na entrega 27-04-2017
