### ISSUE TITLE
Problema na apresentação de muitos autores 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#501]
Tanto no Safari como no Firefox

![captura de tela 2017-04-19 as 13 46 30](https://cloud.githubusercontent.com/assets/505143/25191679/c2b77678-2506-11e7-8201-0697d722baf8.png)

HTML:
[0034-8910-rsp-S1518-87872017051006523.pt.html.zip](https://github.com/scieloorg/opac/files/936241/0034-8910-rsp-S1518-87872017051006523.pt.html.zip)

**Comment by caramez** [comment]
@robertatakenaka @alexxxmendonca 
Como já falei contigo, este problema pelo que percebemos está relacionado ao encoding do trecho. De qualquer forma, neste último pacote (que vai por e-mail) fizemos um fix para quebrar linha de qualquer jeito.

**Comment by robertatakenaka** [comment]
@caramez : aparentemente com a entrega do dia 27-04-2017 esta questão foi resolvida
