### ISSUE TITLE
Corrigir "Copiar link" do DOI

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#502]
scielohomolog.parati.ag/Artigo/
<img width="373" alt="captura de tela 2017-04-26 as 08 39 44" src="https://cloud.githubusercontent.com/assets/505143/25432746/10b71180-2a5c-11e7-8818-b8a65f828456.png">
Ao clicar em copiar link do DOI, o link do DOI não está sendo copiado.

**Comment by caramez** [comment]
@robertatakenaka @alexxxmendonca 
A correção está feita. 

Dêem uma olhada e testada:
http://scielohomolog.parati.ag/Artigo/

**Comment by alexxxmendonca** [comment]
Aparentemente a área sensível agora está mais completa, mas só vamos conseguir testar a cópia efetiva quando atualizarmos nosso ambiente de homologação.

**Comment by robertatakenaka** [comment]
copiar link ainda não funciona

**Comment by caramez** [comment]
@robertatakenaka teste de novo por favor.

**Comment by robertatakenaka** [comment]
agora funcionou

**Comment by robertatakenaka** [comment]
@caramez : foi  problema no js, correto? ou no html tb?

**Comment by caramez** [comment]
@robertatakenaka era no JS tivemos que utilizar algo novo, pois quando fizemos os htmls pela primeira vez o IE8 estava no escopo e ele não copiava para a área de trabalho só via flash. Naquele momento optamos por utilizar um plugin que gerava o flash que copiava para a área de trabalho (e não simplesmente programar algo para copiar).

Desconfiei que seu browsers não tinha flash habilitado, por isso não pegamos no teste aqui. E como o IE9 já consegue copiar via script optamos por algo mais moderno.

**Comment by robertatakenaka** [comment]
@caramez : então, aguardo a entrega do JS.

**Comment by robertatakenaka** [comment]
resolvido 2017-05-10 na entrega do JS
