### ISSUE TITLE
Apresentação de citação de referência dentro de notas de rodapé

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#503]
Quando há citação de uma referência dentro de notas, a apresentação não fica bem. 

![captura de tela 2017-04-26 as 13 13 02](https://cloud.githubusercontent.com/assets/505143/25444621/24157b9c-2a82-11e7-9ed9-34adfc5b8a52.png)

O código HTML referente é:
![captura de tela 2017-04-26 as 13 14 27](https://cloud.githubusercontent.com/assets/505143/25444666/4eee979a-2a82-11e7-8d85-ac5d767bc40f.png)

Em anexo o arquivo html completo.
[1851-8265-scol-12-02-00221.es.html.zip](https://github.com/scieloorg/opac/files/959070/1851-8265-scol-12-02-00221.es.html.zip)

**Comment by robertatakenaka** [comment]
@caramez : por favor, veja este com urgência porque está muito evidente o problema.

**Comment by caramez** [comment]
@robertatakenaka segue a versão de nota com citação, veja se está ok.

Protótipo: http://scielohomolog.parati.ag/Artigo/
Pacote: http://scielohomolog.parati.ag/2017-05-10-Artigo-Correcoes2.zip

![image](https://cloud.githubusercontent.com/assets/22373640/25903428/c4d2acf8-3572-11e7-9ef1-681c7e9f739d.png)

**Comment by robertatakenaka** [comment]
@caramez : onde está esta correção? em que html?

**Comment by caramez** [comment]
@robertatakenaka fechamos o item, está localizado:
- No mouseover de uma nota (nota em amarelo)
- No rodapé quando a nota aparece abaixo das lista de referências

Segue o link:
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
@caramez uma idéia que me ocorreu é cria um modal para cada referência (ou nota), de forma que se aparece mais de uma vez dentro do texto a menção à referência (ou nota), a ação é mostrar o modal. No caso dos intervalos, no modal da referência, apareceria um "botão/ícone/caracter" para visualizar o próximo e até mesmo o anterior.

**Comment by robertatakenaka** [comment]
Foi entregue 2017-05-29 mas teve efeitos colaterais registrados em #551 (ainda aberto)
