### ISSUE TITLE
"bundles" da página do artigo

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#504]
@caramez 

Precisamos que você nos facilite os bundles minificados de:
- um `bundle.css` com tudo o CSS da página do artigo (incluindo o `bootstrap.css` e `article-styles.css`  e as fontes);
- um `bundle-print.css` com o CSS (media=print) da página do artigo (*);
- um `bundle.js` com tudo o JS da página do artigo (incluindo: `jquery`, `bootstrap`, `jquery-ui`, `plugins` e `main.js`)

Assim na página do artigo podemos fazer: 

```html
<link rel="stylesheet" href="bundle.css">
<link rel="stylesheet" href="bundle-print.css" media="print">

...

<script src="bundle.js"></script>
``` 

(*) este arquivo já esta disponível (`scielo-print.css`) porém ainda não esta minificado

**Comment by roblesedu** [comment]
@jfunez 
Sobre o CSS, pelo que entendi, vamos separar um bundle por seções do site, é isto?

**Comment by jfunez** [comment]
@roblesedu vou me explicar melhor....
nós vamos gerar o HTML de cada págia do artigo e armazenar num servidor (separado do site) tipo um CDN. Só com o conteúdo necessário para a página do artigo... Porém precisamos ter todo o CSS e JS, imagens e fontes que é requerido para montar **a página do artigo**. O resto do site permanece igual.

Nesse nosso "CDN" além dos HTMLs esperamos armazenar: O CSS (normal) o CSS (para print) e o JS.
A questão que entra aí são as fontes e imagens referenciadas pelo CSS (caminhos: `fonts_news` e `img`). 

A nossa ideia era ter tudo "empacotado" na menor quantidade de arquivos possíveis (os CSS e JS minificado), as imagens num sprite (se for possível) e as fontes (onde de para deixar as fontes... só aquilo que precisamos e nada mais. A questão do peso/tamanho dos arquivos também é importantíssimo porque por exemplo SciELO Brasil tem >13 milhões de acessos por mês e não queremos desperdício de bytes trafegados. 

Acho que agora a nossa solicitação ficou mais clara. 
Fique a vontade para agregar seus comentários :)

**Comment by jamilatta** [comment]
@roblesedu e @jfunez 

O bundles resolve também esse ticket: https://github.com/scieloorg/opac/issues/494

Importante notar que teremos que carregar as CSS, JS e Fonts, independente do como estes estejam.... melhor que seja feito com um "maço".

**Comment by caramez** [comment]
@jfunez o pacote agora utiliza bundle:
http://scielohomolog.parati.ag/2017-05-10-Artigo-Correcoes2.zip

**Comment by caramez** [comment]
@jfunez @robertatakenaka @jamilatta 
Segue a proposta para a junção do bundle e uma versão standalone do artigo.

Geramos:
- Um pacote bundle do portal (CSS: 37.4Kb - Gzip; JS: 65Kb - Gzip)
- Um CSS e JS referente somente a parte do artigo (CSS: 5.8Kb - Gzip; JS: 1.7Kb - Gzip)
- Um CSS e JS para a execução do artigo em modo standalone (inclui dependências de jQuery, bootstrap, etc.) (CSS: 35.3 Kb - Gzip; JS: 58Kb - Gzip)

Aqui vai uma discussão, já que se gerou uma versão standalone do artigo precisa separar o artigo do bundle do Portal?

Links para visualização e análise de performance:
http://scielohomolog.parati.ag/Artigo/
http://scielohomolog.parati.ag/Artigo/article-standalone.html

Link para download:
http://scielohomolog.parati.ag/2017-05-22-ArtigoCorrecoes-Tk504.zip

**Comment by jamilatta** [comment]
Resolvido e implantado em homolog.
