### ISSUE TITLE
Apresentação de nota presente no título do artigo 

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#508]
Em notas referentes ao título do artigo, como por exemplo:

<img width="885" alt="captura de tela 2017-05-05 as 16 38 04" src="https://cloud.githubusercontent.com/assets/505143/25761465/473da10e-31b1-11e7-8e41-8c25214ecd4b.png">

o comportamento esperado é como de qualquer outra nota dentro do texto, ou seja, apresentar o texto da nota ao posicionar o cursor sobre o número 1 no caso.

O texto da nota é

```
    1

    O presente texto resume trabalho anterior, substancialmente mais extenso, visando compatibilizar o trabalho da Autora com as normas da revistaCiência e Saúde Coletiva.

```

Usando esta estrutura de HTML, não funciona. 

```html
<h1 class="article-title">Ciências Sociais e Saúde no Brasil: Três Décadas de Ensino e Pesquisa
        <span class="ref footnote"><sup class="xref">1</sup><span class="refCtt closed"><strong class="fn-title">1</strong> O presente texto resume trabalho anterior, substancialmente mais extenso, visando compatibilizar o trabalho da Autora com as normas da revistaCiência e Saúde Coletiva.</span></span>
</h1>
```

http://www.scielosp.org/pdf/csc/v3n1/1413-8123-csc-03-01-0131.pdf

**Comment by caramez** [comment]
@robertatakenaka 
Segue o link para avaliação:
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
resolvido na entrega 2017-05-29 com ajustes no html
