### ISSUE TITLE
Ajuste de layout para a página do artigo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#513]
Pessoal com os últimos ajustes realizados pelo designer é necessário refazermos a página do artigo com essa nova cara.

**Comment by jamilatta** [comment]
Pessoal com os últimos ajustes realizados pelo designer é necessário refazermos a página do artigo com essa nova cara.

**Comment by jamilatta** [comment]
@caramez poderia por gentileza realizar esse ajuste, achei que estavamos com o HTML errado porém esse erro se replica no site na Parati, ver: https://opac.scielo.org/journals/

**Comment by caramez** [comment]
@jamilatta este item é aquele que falamos na reunião, você utilizou a CSS nova?

**Comment by jamilatta** [comment]
@caramez 

Isso, é aquele comentamos em reunião ainda não aplicamos as novas CSSs. Iremos realizar em breve.

Correto esse ticket é nosso.

**Comment by jamilatta** [comment]
Implantado e resolvido, ver: https://homolog.opac.scielo.org
