### ISSUE TITLE
Ajustes e necessidades no empacotamento dos CSS e JS separando página do artigo

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#519]
@caramez @roblesedu vamos marcar uma reunião para deixar mais claro este assunto.
@jamilatta vai combinar uma data com vocês, @robertatakenaka e eu.

#### Portal:

Todas as páginas do OPAC

#### Página do artigo:

Página que mostra um artigo no OPAC

Incluindo aqui:

- Menu (principal e alternativo);
- Navegação para outras páginas do OPAC;
- Rodapé;
- Botão de serviços.

#### HTML do conteúdo do artigo:

Conteúdo principal de artigo, referências, menu lateral e modais que mostram: autores, imagens e tabelas
Não esta incluido aqui:

- Menu (principal e alternativo);
- Navegação para outras páginas do OPAC;
- Rodapé;
- Botão de serviços;
- Tudo que não for parte do *miolo* do artigo.

### Observações importantes:

O **HTML do conteúdo do artigo** é gerado por uma biblioteca nossa que constroi um html válido incluindo:

- Um arquivo CSS (normal);
- Um arquivo CSS (como media=print);
- Um arquivo JS.

##### Previsualização local para revisão/validação do artigo:

Esta biblioteca também permite que seja utilizada no processo de validação do artigo recebido pela SciELO.
Portanto as pessoas responsáveis pela construção do artigo e pela revisão/validação, podem fazer uso da ferramenta, gerando HTML localmente.
Então este HTML gerado localmente representa como será exibido o **conteúdo do artigo**.

##### Processamento e inserção do artigo no OPAC:

Outra funcionalidade requerida desta ferramenta e no processamento.
Durante a extração de dados e posterior processamento dos dados que serão expostos no OPAC, é gerado o **HTML do conteúdo do artigo** com a mesma ferramenta.
Finalmente, esta HTML gerado no processamento é inserido no HTML da **Página do Artigo**, para ficar disponível na web.

## Problema:

Como já foi solicitado (mas uma forma não tão clara) precisamos separar o CSS e JS do **portal** e do **HTML do conteúdo do artigo**.

## Nossa Proposta:

Separar nos seguintes arquivos:

#### arquivo: `scielo-portal.css`

Empacotamento de todas as CSS para mostrar o portal. Incluindo menu, navegação, sliders, etc.

#### arquivo: `scielo-portal-print.css`

Versão para imprimir do CSS: `scielo-portal.css`

#### arquivo: `scielo-portal.js`

Empacotamento de todo o código JS necessário para o portal. Incluindo menu, navegação, sliders, etc.

#### arquivo: `scielo-article.css`

Empacotamento de todas as CSS para mostrar o **HTML do conteúdo do artigo**.

#### arquivo: `scielo-article-print.css`

Versão para imprimir do CSS: `scielo-article.css`

#### arquivo: `scielo-article.js`

Empacotamento de todas as JS para mostrar o **HTML do conteúdo do artigo**.

### Cenários:

Temos então 3 cenários envolvendo os diferentes arquivos:

1. Nas páginas do Portal OPAC (com exceção da *página do artigo*):
 - Neste cenário precisamos carregar só os arquivos: `scielo-portal-*`
2. Na página do artigo dentro do OPAC:
 - Neste cenário precisamos carregar: `scielo-portal-*` e `scielo-article-*`
3. No HTML do artigo gerado localmente para revisão:
 - Neste cenário precisamos carregar só os arquivos: `scielo-article-*`

![scielo-opac](https://cloud.githubusercontent.com/assets/805749/25971836/192b4038-3674-11e7-80e3-2ca50f97cc50.jpg)

**Comment by jamilatta** [comment]
Enviado em **12/05/2017** e-mail para o Designer para conversamos sobre esse ticket.
