### ISSUE TITLE
Apresentação de link para Tabela ou Figura quando fica entre parênteses

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#522]
Sugeriram diminuir o espaço que há após o abre parênteses. Repare em Table 3.

<img width="456" alt="captura de tela 2017-05-15 as 16 06 04" src="https://cloud.githubusercontent.com/assets/505143/26074599/bf097b7a-3988-11e7-89ad-b886e706feb2.png">

**Comment by caramez** [comment]
@robertatakenaka dá uma olhada:
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
resolvido com aplicação de css e js da entrega 2017-05-29
