### ISSUE TITLE
Aumentar o tamanho da fonte das notas

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#524]
Aumentar o tamanho da fonte das notas, que pequenas demais em relação ao restante do texto.

<img width="1067" alt="captura de tela 2017-05-16 as 09 00 38" src="https://cloud.githubusercontent.com/assets/505143/26104894/30958cba-3a16-11e7-9aa5-616de91392da.png">

**Comment by caramez** [comment]
@robertatakenaka ali acredito que há um problema de marcação. Preciso ver este HTML.
Note como está no protótipo (anexo)
![image](https://cloud.githubusercontent.com/assets/22373640/26331044/4a0436e2-3f25-11e7-8cc8-c20a658fa0b1.png)

**Comment by robertatakenaka** [comment]
@caramez : é... pode ser que eu tenha feito algo errado.

[1415-790X-rbepid-18-02-00341.en.html.zip](https://github.com/scieloorg/opac/files/1022170/1415-790X-rbepid-18-02-00341.en.html.zip)

**Comment by caramez** [comment]
@robertatakenaka percebemos que no HTML que enviou o conteúdo da lista de notas ```ul.refList.footnote``` está fora do grid (col-md-12 col-sm-12), além disso, a grid deve também acompanhar a classe "ref-list", ficando assim com as classes "col-md-12 col-sm-12 ref-list"

**Comment by robertatakenaka** [comment]
corrigido o html
