### ISSUE TITLE
Problema no menu inferior direito após visualizar 1 tabela

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#525]
http://scielohomolog.parati.ag/Artigo/

<img width="587" alt="captura de tela 2017-05-16 as 13 54 43" src="https://cloud.githubusercontent.com/assets/505143/26118222/6e2dcc76-3a3f-11e7-8c3c-0de573b69a27.png">

O comportamento de visualizar Tabela está errado e diferente do de visualizar Figuras e outros elementos gráficos. Após visualizar 1 tabela, o modal que agrupa as Figuras, Tabelas e outros, desaparece.

**Comment by caramez** [comment]
@robertatakenaka fizemos uma correção:
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
@caramez: resolvido no javascript?

**Comment by robertatakenaka** [comment]
resolvido na entrega de 2017-05-29
