### ISSUE TITLE
Links longos que estouram o limite da borda da página do artigo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#527]
Acontece no Chrome.
Veja exemplo em anexo.

[2237-9622-ress-26-01-00051.en.html.zip](https://github.com/scieloorg/opac/files/1007584/2237-9622-ress-26-01-00051.en.html.zip)

**Comment by caramez** [comment]
@robertatakenaka aqui segue o exemplo do seu código com a correção:
http://scielohomolog.parati.ag/Artigo/artigo-link-longo.html

Aqui eu só queria deixar uma observação, pois a seção do topo está com estrutura diferente na seção do título, vocês colocaram um alinhamento e isto está resultando em quebra e notei que quis corrigir o problema adicionando uma classe na parte de autores. Se puder manter como é a demonstração fica inclusive mais fácil para detectarmos problemas.

**Comment by robertatakenaka** [comment]
@caramez : as diferenças do seu modelo para o que implanto não é intencional. Pode destacar no HTML do seu modelo e do meu o que está diferente?

**Comment by caramez** [comment]
@robertatakenaka esta coluna:
![image](https://user-images.githubusercontent.com/22373640/26932435-e009e2ba-4c39-11e7-84b5-6e178ac5b6b5.png)

Não existe no nosso código, toda a parte de título utiliza 100% do espaço da tela.
Dá só uma olhada no mesmo trecho no nosso código:
![image](https://user-images.githubusercontent.com/22373640/26932489-fd5334c0-4c39-11e7-9c4c-0103229decc6.png)

**Comment by robertatakenaka** [comment]
@caramez : Entendido.

**Comment by robertatakenaka** [comment]
siguido orientações, correções feitas no HTML
