### ISSUE TITLE
Apresentação de errata (artigo corrigido)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#528]
No site atual, há um destaque de quais artigos a ERRATA está corrigindo.
Por favor, fazer um modelo de errata que contenha este tipo de destaque.
 
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2016000500452&lng=en&nrm=iso&tlng=pt

<img width="851" alt="captura de tela 2017-05-18 as 15 23 24" src="https://cloud.githubusercontent.com/assets/505143/26217513/0e9ef7b2-3bde-11e7-8ef4-2345fd52a2c3.png">

**Comment by caramez** [comment]
@robertatakenaka e @alexxxmendonca segue a proposta de correção:
http://scielohomolog.parati.ag/Artigo/errata.html

**Comment by alexxxmendonca** [comment]
Para mim está ok!

Ainda não sei se a seção e legenda bibliográfica devem ficar centralizadas, mas isso é assunto para um outro ticket.

**Comment by francine-curivil** [comment]
Para mim está ok!

**Comment by RPostalli** [comment]
@robertatakenaka não sei se "Este conteúdo corrige:" é uma boa, existem erratas que incluem ou excluem texto, autor e etc, não deixa de ser uma correção, mas é uma correção/inclusão ou exclusão. De qualquer forma não tenho sugestão melhor. O desenho da errata ficou bem legal. Os artigos que são mencionados na caixa amarela terão também a indicação da errata na parte superior?

**Comment by robertatakenaka** [comment]
@RPostalli : OK, mas a pergunta sobre o visual, o layout. O texto mantenho o que vem ou o que já adotamos.

**Comment by caramez** [comment]
@robertatakenaka sobre o título é possível sabermos a condição (correção, inclusão ou exclusão) do conteúdo?

Além disso no texto que é corrigido acho que poderíamos incluir o quadro amarelo anunciando que: "Este conteúdo foi corrigido por:" no mesmo formato da errata. O que acha?

**Comment by RPostalli** [comment]
@robertatakenaka eu respondi sobre o layout, está OK.
@caramez concordo muito. Acho que a mesma caixa deve ser criada nos artigos que sofrem a correção, fazendo um link entre as publicações.
E não tem como saber do que se trata a errata, não existe nenhuma identificação "especial" nela para informar se é um caso de correção, exclusão ou inclusão. Teríamos que fazer a leitura do documento o que não acho viável :(

**Comment by robertatakenaka** [comment]
@RPostalli : o ideal é isso mesmo. Mas esta informação é gerada automaticamente no momento de gerar a página no site atual. Como o site é novo, outra aplicação, precisamos discutir a melhor solução para esta outra plataforma.

**Comment by RPostalli** [comment]
@robertatakenaka entendi, OK.

**Comment by robertatakenaka** [comment]
resolvido 2017-06-13
