### ISSUE TITLE
Exibição do ORCID ID

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#531]
@caramez acho que estamos atendendo, mas de qualquer forma, o ORCID atualizou recentemente o guia para display do ORCID ID: http://orcid.org/blog/2017/05/10/new-id-display-guidelines-journals-now-released

Quando puder, dê uma olhara para verificar se estamos seguindo as recomendações.

**Comment by robertatakenaka** [comment]
@alexxxmendonca : acredito que sim pois isso já foi informado a Caramez.

http://scielohomolog.parati.ag/Artigo/#ModalTutors

<img width="584" alt="captura de tela 2017-05-23 as 15 42 01" src="https://cloud.githubusercontent.com/assets/505143/26370525/77ee90f8-3fce-11e7-90b2-9519e194bae5.png">

**Comment by alexxxmendonca** [comment]
É só por que o guia foi atualizado em 16/05/2017.

Também acho que está tudo ok mas só para confirmar mesmo...

**Comment by caramez** [comment]
Acho que valeria retirar o "http://" pois na nova documentação parece-me que flexibilizou isto.

**Comment by alexxxmendonca** [comment]
Sim, está opcional.

**Comment by caramez** [comment]
@alexxxmendonca e @robertatakenaka fizemos a retirada de todo os "http" antes dos links para redes de autores.

Dêem uma olhada:
http://scielohomolog.parati.ag/Artigo/

**Comment by alexxxmendonca** [comment]
Está melhor! 👍 
Acho que podemos fechar esse ticket?
