### ISSUE TITLE
botão para copiar doi não está funcionando com artigo standalone

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#539]
[0034-8910-rsp-48-3-0451.pt.html.zip](https://github.com/scieloorg/opac/files/1039269/0034-8910-rsp-48-3-0451.pt.html.zip)

**Comment by caramez** [comment]
@robertatakenaka dá uma olhada, realmente faltou o item que executava a cópia:
http://scielohomolog.parati.ag/Artigo/article-standalone.html

**Comment by robertatakenaka** [comment]
resolvido com atualização de css e js
