### ISSUE TITLE
Como apresentar autores quando não há informação adicional sobre eles?

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#540]
@jamilatta , @jfunez , @caramez , @fabiobatalha , @solange-scielo, @alexxxmendonca 

Há caso de autores sem afiliação ou outros dados.

<img width="914" alt="captura de tela 2017-05-30 as 16 00 32" src="https://cloud.githubusercontent.com/assets/505143/26600091/22cf1e5c-4551-11e7-9cb3-23995cc31383.png">

<img width="616" alt="captura de tela 2017-05-30 as 15 58 17" src="https://cloud.githubusercontent.com/assets/505143/26600321/084e312a-4552-11e7-84e1-c1ffa9518815.png">

Qual seria o melhor modo de apresentar isso?
Não apresentar ABOUT THE AUTHORS?

**Comment by alexxxmendonca** [comment]
Acredito que o melhor seria não apresentar ABOUT THE AUTHORS.

**Comment by jamilatta** [comment]
Concordo com o @alexxxmendonca

**Comment by jamilatta** [comment]
@robertatakenaka esse item já foi realizado, podemos fechar esse ticket?

**Comment by jfunez** [comment]
resolvido no #625
