### ISSUE TITLE
Melhoria nos botões de filtragem da lista de períodicos

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#547]
@caramez 

por gentileza poderia melhor esses botões de filtragem na listagem, fizemos por aqui mas achamos que não ficou bom... ver: 

<img width="1261" alt="screenshot 2017-06-08 16 18 09" src="https://user-images.githubusercontent.com/373745/26946644-61e9db9c-4c66-11e7-85a9-4eecb2ec64f3.png">

Nessa solução não tem com informar para o usuário qual filtro foi selecionado :-()

**Comment by jamilatta** [comment]
Trecho que está gerando os botões: 

```html
<div class="btn-group" data-toggle="buttons">
      <label class="btn">
        <input type="radio" id="all_query_filter_areas" autocomplete="off" name="query_filter_areas" value="" checked="checked">Todos
      </label>
      <label class="btn active">
        <input type="radio" id="current_query_filter_areas" name="query_filter_areas" value="current" autocomplete="off">Títulos correntes
      </label>
      <label class="btn">
        <input type="radio" id="no_current_query_filter_areas" name="query_filter_areas" value="no-current" autocomplete="off">Títulos não-correntes
      </label>
    </div>
```

**Comment by caramez** [comment]
@jamilatta segue a proposta:
http://scielohomolog.parati.ag/Colecao/periodicos.html#tema

**Comment by jamilatta** [comment]
@caramez 

Show de bola, houve alguma alteração de css,  pois, se houve preciso das css(s), caso não aplico ajusto somente o HTML.

**Comment by jamilatta** [comment]
Atualizei o css e funfou!
