### ISSUE TITLE
Texto ultrapassa limites da caixa

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#548]
O texto de notas e de referências tiveram um problema similar: acabam ultrapassando o limite da caixa. A parte do texto que parece não quebrar corretamente é dos links. 

Exemplos abaixo de como fica a visualização no Chrome (onde o problema foi observado):

NOTAS
![0034-8910-rsp-s1518-87872017051006495](https://user-images.githubusercontent.com/26901197/27034318-88de0d96-4f53-11e7-80ec-21299517d6ff.png)
![0034-8910-rsp-s1518-87872017051006750](https://user-images.githubusercontent.com/26901197/27034319-890e4e70-4f53-11e7-81e9-d15f35d99260.png)

REFERÊNCIAS
![0042-9686-bwho-93-11-00785](https://user-images.githubusercontent.com/26901197/27034422-11cba2bc-4f54-11e7-8c54-bff09b9d2242.png)
![1555-7960-medicc-17-04-0001](https://user-images.githubusercontent.com/26901197/27034680-fd84f654-4f54-11e7-868e-0389da428e8f.png)

![1807-5762-icse-1807-576220140401](https://user-images.githubusercontent.com/26901197/27034912-d375a416-4f55-11e7-911e-602a5fe5d667.png)

**Comment by caramez** [comment]
@robertatakenaka problema corrigido:
![image](https://user-images.githubusercontent.com/22373640/27102948-776d695c-505d-11e7-92db-3b2fd5c2a0d0.png)

Link:
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
resolvido na entrega 2017-06-13
