### ISSUE TITLE
Erro no colunamento de tabela

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#549]
Os dados de uma coluna acabam invadindo a outra (visualização no Chrome). 

Exemplo de visualização do Chrome:
![0102-311x-csp-30-s1-0208](https://user-images.githubusercontent.com/26901197/27035362-688bf2e8-4f57-11e7-93e9-27393f63f046.png)

Link para download dos arquivos:
https://drive.google.com/open?id=0BwQS0ypeq1cxaWota1p0eXBfam8

**Comment by caramez** [comment]
@aline-cristina problema corrigido:
http://scielohomolog.parati.ag/Artigo/tk549.html#ModalTablet03

**Comment by robertatakenaka** [comment]
@aline-cristina @caramez : então melhor que não fique bem mesmo, já que o erro é no dado e não no desenho.

**Comment by caramez** [comment]
@robertatakenaka eram 2 aspectos, o erro de código e havia uma configuração no CSS que também complicava este caso. Fiz a limpeza, e agora pega o que tiver configurado.
