### ISSUE TITLE
Erro em linhas concatenadas em tabela

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#550]
Ao passar o mouse em linha que tenha outras concatenadas escurece apenas a primeira, conforme exemplo abaixo (visualização no Chrome).

Não sei se haveria um jeito de melhorar isso.

![linhasconc](https://user-images.githubusercontent.com/26901197/27035757-eab3f148-4f58-11e7-9ac1-b8f3aad24d28.png)

Link para download dos arquivos: https://drive.google.com/open?id=0BwQS0ypeq1cxa0hJWHVoN0xueW8
O erro acima reportado aconteceu na Tabela 3.

**Comment by caramez** [comment]
@aline-cristina @robertatakenaka neste caso não é possível resolver o problema pois está sendo utilizado um rowspan. Minha sugestão seria a de tirar o efeito na situação em que houvessem tabelas com este tipo de recurso.

Caso positivo, gostaria de saber se fazemos isto por javascript ou a Roberta processa tabela?
O que seria melhor?

**Comment by robertatakenaka** [comment]
@caramez : acho que isso é um problema do dado. Quanto menos interferência de desenho melhor.

Não sei se você sabe, mas as tabelas já vem dentro do XML do SciELO, cuja especificação é a de tabelas XHTML. Não deveríamos interferir demais na apresentação. Além disso, nosso objetivo é, em breve, disponibilizar uma ferramenta com a previsualização do artigo em HTML. Desta forma, o produtor de XML poderá adequar o conteúdo para que a apresentação dele fique melhor possível. Então, acho que a interferência de css e javascript sobre as tabelas devem ser mínimas, devem se limitar a espaçamento, tamanho, mas não em alinhamento de texto, ou outras coisas que podem afetar o conteúdo, entende?

Baseado nisso, o que pode ser feito para tabelas deste formato, indicado neste ticket. Você ajustaria css ou indica um formato de tabela melhor?
No entanto, vendo a tabela original, vejo que a representação em HTML dela não está correta. Não haveria necessidade de um rowspan. É uma tabela simples.


<img width="648" alt="captura de tela 2017-06-14 as 11 32 06" src="https://user-images.githubusercontent.com/505143/27137833-508ca332-50f5-11e7-8c9f-0fe6626239ba.png">

**Comment by caramez** [comment]
@robertatakenaka considerando os últimos tickets, as tabelas já não tem tanta influencia de layout.
Vou apresentar aqui o que retiramos:

- Alinhamento (agora vai ser apresentado conforme marcação no HTML, lembrando que o alinhamento padrão do HTMLé a esquerda)
- De aparência mantemos apenas a questão do mouseOver e a divisória do THEAD para o conteúdo. Tiro eles?

Quanto a esta tabela, acredito então que a marcação não tá legal. Pois ali tem um rowspan. Sendo que analisando a tabela original não deveria existir.

**Comment by alexxxmendonca** [comment]
@RPostalli você poderia nos ajudar com este ticket?

Não tenho certeza se a pessoa que abriu o ticket original ainda está trabalhando conosco.

De qualquer forma, precisaríamos saber qual artigo (link) o problema se refere ou se há casos semelhantes.

**Comment by RPostalli** [comment]
@alexxxmendonca. Vou pedir para a Cinthia verificar se encontra um artigo com marcação semelhante e se o problema ainda é válido.

**Comment by alexxxmendonca** [comment]
Muito obrigado @cinthia-vieira !

Considerando que a informação está disponível e considerando que o "erro" ocorre somente quando há o comportamento de mouseover e, memso assim, não impede o acesso à informação, estou fechando este ticket.

Poderemos reavaliar o caso em um outro momento.
