### ISSUE TITLE
Modificar a css para que considere uma classe no lugar de id para ModalTutors

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#553]
Há casos em que o artigo é composto por mais de um artigo. Cada artigo pode ter seu grupo de autores. Portanto, deve ser gerado um modal para cada grupo de autores. No entanto, na css está considerando estilos para o @id=ModalTutors. O outro modal fica sem a mesma apresentação/estilo.

<img width="377" alt="captura de tela 2017-06-13 as 13 04 07" src="https://user-images.githubusercontent.com/505143/27092150-d2562b76-5038-11e7-9783-112611267c7a.png">

ModalTutors
<img width="606" alt="captura de tela 2017-06-13 as 13 05 41" src="https://user-images.githubusercontent.com/505143/27092237-0b62f02a-5039-11e7-93bf-a2fca0e111da.png">

ModalTutorsS1
<img width="608" alt="captura de tela 2017-06-13 as 13 05 30" src="https://user-images.githubusercontent.com/505143/27092241-0d894e26-5039-11e7-830e-b913c0e74138.png">

[0042-9686-bwho-91-11-886.en.html.zip](https://github.com/scieloorg/opac/files/1072043/0042-9686-bwho-91-11-886.en.html.zip)

**Comment by caramez** [comment]
@robertatakenaka feito!
http://scielohomolog.parati.ag/Artigo/tk553.html

Percebi que o menu da lateral não está legal, de repente o certo seria pelo menos ter o segundo título. Ou ainda pensarmos em outro formato de exibição deste tipo de conteúdo (mas isto fica para outro ticket)

**Comment by robertatakenaka** [comment]
resolvido com entrega 2017-06-20
