### ISSUE TITLE
(css) Não modificar o alinhamento do texto no conteúdo da tabela

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#554]
Relacionado com #515 
Acho que ok intervir em espaçamento, no entanto, alinhamento do texto não é desejável. Veja o caso:

[1413-8123-csc-20-06-1667.en.html.zip](https://github.com/scieloorg/opac/files/1072249/1413-8123-csc-20-06-1667.en.html.zip)

Desejável
<img width="1027" alt="captura de tela 2017-06-13 as 14 03 08" src="https://user-images.githubusercontent.com/505143/27094754-884a7cfe-5041-11e7-9d9f-0c542361e79e.png">

Indesejável
<img width="1033" alt="captura de tela 2017-06-13 as 14 02 58" src="https://user-images.githubusercontent.com/505143/27094760-8aa66b8e-5041-11e7-8682-0774113d69a6.png">

**Comment by caramez** [comment]
@robertatakenaka problema corrigido:
http://scielohomolog.parati.ag/Artigo/

**Comment by robertatakenaka** [comment]
resolvido com entrega 2017-06-13
