### ISSUE TITLE
Menu de figuras/tabelas desconfigurado

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/opac#555]
O menu de figuras e tabelas fica com as abas de título desconfiguradas (grudadas) ao realizar a leitura em telas pequenas:

Abaixo, o menu em tela de tamanho grande:
![teste5_11](https://user-images.githubusercontent.com/27728729/27101045-99d2f568-5056-11e7-87cb-389999ad2bd5.png)

Agora, em uma tela pequena:
![teste5_4](https://user-images.githubusercontent.com/27728729/27101044-99d2c598-5056-11e7-89d5-b6258a0fb003.png)

**Comment by caramez** [comment]
@robertatakenaka me manda este HTML para eu verificar.

**Comment by caramez** [comment]
@cinthia-vieira e @robertatakenaka finalizamos a alteração por aqui:
http://scielohomolog.parati.ag/Artigo/#ModalTablesFigures

@robertatakenaka atenção pois esta alteração é de HTML, foram incluídas as classes específicas para o tratamento da resolução de tablet (col-sm-*)

**Comment by robertatakenaka** [comment]
resolvido com entrega 2017-06-20
