### ISSUE TITLE
(js) Problema no form de busca na home do OPAC

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#557]
@caramez Reparamos que o js que roda quando o usuário faz uma busca no campo search da home do OPAC parou de funcionar.... Estamos utilizando os bundles fornecidos no último zip (**7/6/2017**) .

Vimos que o código js do `main.js` (no último zip enviado) e comparando com o `main.js` do site: `search.scielo.org` vimos que esta diferente (`SearchForm` x `SearchFormBuilder`) ... além de ter bastante código comentado ou que não precisamos... (ex: `SearchHistory` ou também código para listagem alfabética e temática de periódicos) o que entendemos que pode ser removido.

**Comment by caramez** [comment]
@jfunez lembra-se que comentamos que haveria uma separação integral entre o search e o site. Quando falamos do bundle ficou acordado isto. Acho que precisamos normalizar esta história para não ficar ruídos.

Retiramos do bundle tudo o que era relacionado ao search.

**Comment by jfunez** [comment]
@caramez 
Sobre a separação estamos ok!
1 - a home do site, tem o campo de busca... portanto no js (`scielo-budle.js`) deveria ter o js para fazer funcionar os botões de busca, adicionar campos para buscar, etc... (isso que não esta funcionando);
2 - Acreditamos que no `scielo-bundle.js` ainda tem código do search (e foi nesse código que vimos coisas comentadas e que não precisamos como a listagem de periódicos). 

Para chegar nessa conclusão fizemos assim: 
 - descompactar o zip em questão (**7/6/2017**);
 - procuramos no `static/js/scielo-bundle.js` que inclui um `./main.js`
 - nesse `static/js/main.js` apartir da linha 349 tem o código com `SearchForm = { ... ` e mais abaixo o `SearchHistory`

O que precisamos:
- deixar funcionando o form de busca da home do OPAC;
- remover o que não precisamos do `scielo-bundle.js` ou seja do `main.js` para otimizar.

**Comment by caramez** [comment]
@jfunez agora entendi, realmente tem algumas coisas. É que tem as funções do form de busca, aquele para adicionar mais itens, e também o select com o autoheight

**Comment by caramez** [comment]
@jfunez analisei e há algumas funções que vocês desenvolveram no projeto para a SciELO no projeto do Search. Esta separação não tem a ver com a outra questão. Vamos ter que mudar a forma como está desenvolvida a busca para poder embarcar a solução.

Isto na verdade não foi desenvolvido pela Parati e sim pela equipe do Vini.
Vou tentar entender as diferenças para poder trabalhar nisso.

**Comment by caramez** [comment]
@jfunez conforme te falei fomos pegar o modelo de busca do Search. Isto impacta na forma como o HTML está escrito pois há algumas regras que ficariam do lado do bundle.

Dá uma analisada como ficou:
http://scielohomolog.parati.ag/Portal/
http://scielohomolog.parati.ag/Colecao/

**Comment by jfunez** [comment]
resolvido na entrega de 20/6
