### ISSUE TITLE
Nota no título no Chrome

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#558]
<img width="360" alt="captura de tela 2017-06-14 as 09 56 14" src="https://user-images.githubusercontent.com/505143/27134116-f1e47d78-50ea-11e7-909e-3dc660478e51.png">

**Comment by caramez** [comment]
@robertatakenaka onde foi que pegou esta situação, não consigo simular.

**Comment by robertatakenaka** [comment]
http://scielohomolog.parati.ag/Artigo/ no Chrome

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by caramez** [comment]
@robertatakenaka estranho, aqui não consigo ver:
![image](https://user-images.githubusercontent.com/22373640/27146179-c9f6aed4-510e-11e7-9827-81f7bcd494a2.png)
![image](https://user-images.githubusercontent.com/22373640/27146202-d9229454-510e-11e7-875b-f3f098c9d17b.png)
![image](https://user-images.githubusercontent.com/22373640/27146218-e62f6500-510e-11e7-9fb9-fc76069fd835.png)

**Comment by caramez** [comment]
@robertatakenaka como vamos fazer? não consigo de jeito nenhum pegar este erro.

**Comment by ednilson** [comment]
usando:
Ubuntu 16.04 LTS (Linux 4.4.0-79 generic)
Chrome version 58.0.3029.110

Para mim aparece como seta de rolagem, tanto que ao clicar o número da nota rola para cima ou para baixo, vejam:
![captura de tela de 2017-06-22 08-21-39](https://user-images.githubusercontent.com/454847/27431987-c8bde0de-5724-11e7-828f-f264a32327f0.png)

ampliando...
![captura de tela de 2017-06-22 08-22-36](https://user-images.githubusercontent.com/454847/27432000-d44d8c24-5724-11e7-8b79-edb17ab417e6.png)

**Comment by aline-cristina** [comment]
Utilizando:
Windows 7
Chrome 58.0.3029.110 (64-bit)

Vejo exatamente o mesmo erro:
![2017-06-21](https://user-images.githubusercontent.com/26901197/27432704-ae40497e-5727-11e7-886e-29c8bf1ce6dc.png)

**Comment by alexxpsilva** [comment]
@robertatakenaka o meu aparece igual ao da @aline-cristina, e também estou utilizando a mesma versão que ela.

**Comment by caramez** [comment]
@robertatakenaka @alexxpsilva podem conferir novamente no link:
http://scielohomolog.parati.ag/Artigo/

**Comment by alexxpsilva** [comment]
agora está aparecendo corretamente @caramez @robertatakenaka 


![opac](https://user-images.githubusercontent.com/15328777/27555773-6e825394-5a89-11e7-9bd9-43b808280fd5.png)

**Comment by ednilson** [comment]
@caramez @robertatakenaka agora está correto.
