### ISSUE TITLE
no issue TOC as seções dos artigos XML não aparecem

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#562]
No issue TOC quando tem artigos em XML, as seções não estão sendo carregadas.

**Comment by jamilatta** [comment]
Conversando e verificando com o @fabiobatalha identificamos que o article meta não estava processando as seções de alguns artigos o que provoca a ausência das seção no Issue TOC.

**Comment by jamilatta** [comment]
Estou aguardando a correção que o @fabiobatalha esta aplicando no Xylose para que possamos reprocessar e obter a lista de seções dos fascículos.

**Comment by patymori** [comment]
Corrigido #995.
