### ISSUE TITLE
ajustar urls do issue TOC para artigos do tipo: ahead (sem paginação)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#565]
exemplo:
https://homolog.opac.scielo.org/ress/2017.nahead/

**Comment by jfunez** [comment]
relacionado com: https://github.com/scieloorg/opac/issues/655

**Comment by jamilatta** [comment]
Para finalizar esse ticker é necessário termos a nova versão do URLLegendarium no Pypi.

**Comment by jamilatta** [comment]
Adicionamos um regra pra resolver esse ticket. 

No momento da geração do segmento da url estamos considerando também o doi e o order, ver: https://github.com/scieloorg/opac_schema/commit/256cd486857dd041d12ba63b11b98d586474c26b
