### ISSUE TITLE
Logo da FAP no rodapé está desatualizado

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#569]
O logo da FapUnifesp mudou. Acho que o @alexxxmendonca tem o novo em alta resolução.
http://www.fapunifesp.edu.br/

**Comment by jamilatta** [comment]
Grato @amandasramalho iremos atualizar.

**Comment by alexxxmendonca** [comment]
Sim! seguem os arquivos:

![logo_fap_principal]

(https://user-images.githubusercontent.com/4059679/27290567-009066fa-54e4-11e7-9849-46a90529ba10.png)

**Comment by jfunez** [comment]
Este issue trata sobre falta de conteúdo no site. A ferramenta de administração do site permite inserir tal conteúdo, que será feito pelo responsável de conteúdo.

Em reunião no dia 28/6/17 com Abel, foi definido que o responsável pelo conteúdo será @alexxxmendonca

Vamos agendar uma serie de reuniões para tratar a inserção de conteúdo como Alex e sua equipe.
