### ISSUE TITLE
Página "Contatos" está vazia

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#570]
Eu acessei o menu e entrei no link "Contatos".  A página está vazia. É assim mesmo?
https://homolog.opac.scielo.org/collection/about/

![image](https://user-images.githubusercontent.com/5446933/27289246-97a5d2aa-54df-11e7-8848-146ee10fba7f.png)

**Comment by jfunez** [comment]
Este issue trata sobre falta de conteúdo no site. A ferramenta de administração do site permite inserir tal conteúdo, que será feito pelo responsável de conteúdo.

Em reunião no dia 28/6/17 com Abel, foi definido que o responsável pelo conteúdo será @alexxxmendonca

Vamos agendar uma serie de reuniões para tratar a inserção de conteúdo como Alex e sua equipe.
