### ISSUE TITLE
Os logos do site em inglês e espanhol estão trocados

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#571]
Na interface em Espanhol, aparece o logo em inglês. 
Na interface em inglês, aparece o logo em espanhol.
Alterar também o texto "Sobre el SciELO Saúde Pública": Não deveria ser "Sobre el SciELO Salud Publica"?
E o texto "About SciELO Saúde Pública". Não deveria ser "About SciELO Public Health"?
![image](https://user-images.githubusercontent.com/5446933/27289450-5a231478-54e0-11e7-9bb9-60c5feb6cdf5.png)

**Comment by jfunez** [comment]
@amandasramalho agora sim esta corrigido! 
Pode conferir? 

Grato!

**Comment by amandasramalho** [comment]
@jfunez Os logos corrigiram, mas os abouts ainda não...

![image](https://user-images.githubusercontent.com/5446933/27290053-608ad4ca-54e2-11e7-90d6-d3778b01ab85.png)

**Comment by jfunez** [comment]
👍 OK!

Vamos revisar as traduções do site (continuamos este assunto no issue https://github.com/scieloorg/opac/issues/561) 

Grato pela ajuda!
