### ISSUE TITLE
Link para *www.scielo.br* em instruções de *Como Citar*

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#572]
Contexto:
https://homolog.opac.scielo.org/csp/1995.v11n4/543-551/pt/

No menu flutuante do canto inferior direito, opção "Como citar este artigo", o link gerado na parte "Available from" remete a um recurso diferente do que está sendo acessado.

<img width="1226" alt="screen shot 2017-06-19 at 11 10 52" src="https://user-images.githubusercontent.com/161335/27289693-39ff543a-54e1-11e7-8bea-f1aafbd8682a.png">

**Comment by jfunez** [comment]
Grato pelo feedback @gustavofonseca 

Pelo que entendo este conteúdo ainda esta "cravado" e suspeito que esteja no radar da @robertatakenaka para ser ajustado na geração da página do artigo...

**Comment by patrickhilt** [comment]
Ha uns erros nos nomes dos programa. Versão correta:
BibTeX
EndNote (=sem espaço)
RefWorks (=W majúscula)

ProCite e Reference Manager ja não se vendem e ja não há soporte pra eles.
Proponho adicionar Citavi (tem versão em PT e ES). Utiliza tb o formato RIS, como o Reference Manager.

**Comment by robertatakenaka** [comment]
@fabiobatalha @jamilatta @jfunez:
Vou fazer como combinamos, mas estou achando que a melhor solução seria clicar no como citar e já baixar o arquivo .ris, sem abrir esta janela, já que seria 1 único formato disponível.

**Comment by robertatakenaka** [comment]
@fabiobatalha @jamilatta @jfunez por enquanto, para quando há doi:

<img width="607" alt="captura de tela 2017-06-22 as 15 48 31" src="https://user-images.githubusercontent.com/505143/27450494-450fa91e-5762-11e7-8ea9-13f1cce5e4bd.png">

**Comment by jfunez** [comment]
👍 ótimo!
em breve ajustamos e processamos para ver os links direto pro artigo...

**Comment by jfunez** [comment]
resolvido!
