### ISSUE TITLE
Endereço DOI muito junto com o botão de "copiar URL"

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#575]
Os textos com o endereço do DOI estão muito junto com o botão. Não seria melhor colocar um espaço? Entre o nome do último autor e o botão de "Sobre os autores" existe espaçamento.

![image](https://user-images.githubusercontent.com/5446933/27297656-2f54aec0-54fc-11e7-99f0-6058d44b5bbd.png)

**Comment by jfunez** [comment]
👍

**Comment by robertatakenaka** [comment]
resolverá no próximo processamento dos artigos XML pelo opac_proc

**Comment by jfunez** [comment]
resolvido e verificado! 
ex. 👉 https://homolog.opac.scielo.org/csp/2017.v33n1/e00212016/en/

<img width="682" alt="screenshot 2017-06-27 14 21 36" src="https://user-images.githubusercontent.com/805749/27600969-fff56996-5b43-11e7-8289-36543c6bf0b6.png">
