### ISSUE TITLE
Sobre a exibição das referências (sugestão)

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#576]
As referências ficaram com uma área muito grande pelo fato do número estar em outra linha. Não ficaria melhor colocar o número na mesma linha da referência? Outra dúvida: os números aparecem como clicáveis, mas não vão pra lugar nenhum.

Teste com este artigo: https://homolog.opac.scielo.org/csp/2017.v33n5/e00172815/pt/

Esta assim:
![image](https://user-images.githubusercontent.com/5446933/27297910-1c9ad880-54fd-11e7-8241-a00007fea645.png)

Poderia ser assim:
![image](https://user-images.githubusercontent.com/5446933/27298029-7db72b82-54fd-11e7-82e9-9dbf3f64cc17.png)

**Comment by robertatakenaka** [comment]
será resolvido com o próximo processamento.

**Comment by jamilatta** [comment]
@robertatakenaka e @amandasramalho 

re-processamos e agora esta ok, por favor verificar, exemplo: https://homolog.ssm.scielo.org/media/assets/resp/v90/1135-5727-resp-90-e60001.html#

**Comment by robertatakenaka** [comment]
NO SSM, está OK... Talvez o problema possa ser na CSS do site se no site não fica de acordo.

https://homolog.ssm.scielo.org/media/assets/resp/v90/1135-5727-resp-90-e60001.html#

<img width="886" alt="captura de tela 2017-06-27 as 13 33 55" src="https://user-images.githubusercontent.com/505143/27598939-76644dec-5b3d-11e7-833c-204f6de4aeab.png">

**Comment by amandasramalho** [comment]
Os links das referências estão separados do link em texto.
![image](https://user-images.githubusercontent.com/5446933/27598943-779d0d2a-5b3d-11e7-9bf3-65c8664c9242.png)

E tem informação truncada:
![image](https://user-images.githubusercontent.com/5446933/27599002-a03bb97a-5b3d-11e7-8ad8-ed8bd8c63bd9.png)

**Comment by robertatakenaka** [comment]
@amandasramalho : 

Sim, os links ficam em destaque.
Algumas questões são problemas nos dados, como o citação sugerida que foi identificado como fn/label.

**Comment by amandasramalho** [comment]
@robertatakenaka Não seria melhor destacar o link no mesmo texto na URL? Da forma que está, a informação do link fica duplicada.

**Comment by jamilatta** [comment]
Segue link do exemplo no site: http://homolog.opac.scielo.org/resp/2016.v90/e60001/es/

**Comment by jfunez** [comment]
Eu verifiquei no Firefox e no Chrome do HOMOLOG do OPAC e esta ok! 
vamos fechar este issue, 
Agradeço a @amandasramalho se poder abrir um novo issue com a questão dos links nas referências... se não isso aqui vira uma confusão....

**Comment by robertatakenaka** [comment]
@amandasramalho : infelizmente isso não é possível, porque o texto da citação vem de um elemento do XML e o link vem de outro elemento. 
Por outro lado, uma sugestão seria que no lugar do link clicável estivesse um termo como "consulte o documento original" ou coisa parecida.
