### ISSUE TITLE
Link de submissão online não aparece no cabeçalho e menu flutuante

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#577]
![image](https://user-images.githubusercontent.com/4059679/27298232-3fc6ce76-54fe-11e7-9cd4-455fb828d628.png)

![image](https://user-images.githubusercontent.com/4059679/27298242-468c10a4-54fe-11e7-9171-d94fadb7bc3a.png)

**Comment by jfunez** [comment]
@alexxxmendonca quando o periódico não tem cadastrada uma url de submissão online, o link não aparece.

Pelo que você comentou no ticket https://github.com/scieloorg/opac/issues/355#issuecomment-309420797 tais dados não esta sendo cadastrados corretamente.

Para não dispersar tanto esta demanda, vou fechar esta ticket e seguimos a discussão no ticket #355 com este ticket como relacionado.

Grato pelo feedback! 👍

**Comment by alexxxmendonca** [comment]
👍 

Ok, eu imaginei que tivesse algo a ver, mas queria deixar registrado.

Apenas para constar: as URLs dos sistemas estão cadastradas no SciELO Manager e estão Ok.

**Comment by jfunez** [comment]
ótimo! vou destacar isso no ticket #355
