### ISSUE TITLE
Notificação ao visitante do OPAC sobre o motivo da despublicação

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#58]
#### Problema:
Falta de contexto quando se tenta acessar um documento (periódico, fascículo, artigo) que foi despublicado. O visitante só vê uma mensagem de erro 404, pouco informativa.

#### Objetivo:
Quando o visitante do site tentar acessar um documento (periódico, fascículo, artigo) despublicado, a página tem que mostrar o motivo da despublicação indicada pelo usuário webmaster no momento da despublicação.

**Comment by jamilatta** [comment]
Para finalizar essa tarefa de forma que a modulo ``views.py`` e ``controller.py`` permaneçam coesos, é necessário uma refatoração do ``controller.py``.

Dependente do ticket #67.
