### ISSUE TITLE
Texto em SciELO Perspectiva (home) está cortado no Chrome

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#581]
Dependendo do tamanho do texto a parte inferior da caixa de texto de "SciELO Perspectiva" fica cortado no Chrome, conforme print abaixo.

![scielo_persp](https://user-images.githubusercontent.com/26901197/27335981-9cbd06f8-55a4-11e7-8da5-01d920734752.png)

**Comment by aline-cristina** [comment]
O mesmo acontece em SciELO Press Release

![press](https://user-images.githubusercontent.com/26901197/27337511-fe83fd70-55a8-11e7-8694-3d3ba852f6c1.png)

**Comment by caramez** [comment]
@aline-cristina 
Criamos uma classe chamada **ellipsis** para truncar os textos. O @jamilatta pode deixar de truncar do lado. 

**Bloco Press-releases**
Adicionar a classe **ellipsis** no h3

**Bloco SciELO em perspectiva**
Adicionar a classe **ellipsis** no h3. Dentro da **div.info**, adicionar outra div com a classe **ellipsis**. E o link "continuar lendo" fico fora da div.ellipsis, para visualizar como ficou pode acessar o ambiente da Parati de homologação.

**Link**
http://scielohomolog.parati.ag/Colecao/

**Pacote**
http://scielohomolog.parati.ag/2017-07-10-Tk568-581-582.zip
