### ISSUE TITLE
Erro em título de Notícias nas página dos periódicos

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#582]
Na barra de "Notícias" dentro das páginas dos periódicos o título acaba estourando a caixa de texto no Chrome, conforme mostrado abaixo.

![scielo_noticias](https://user-images.githubusercontent.com/26901197/27336129-035e2414-55a5-11e7-947c-8b05b502fd63.png)

Na versão em espanhol, ainda no Chrome, pude notar que o título expande e fica por cima do texto, conforme mostrado abaixo.

![scielo_noticias2](https://user-images.githubusercontent.com/26901197/27336219-3f52475c-55a5-11e7-96e2-29ba76478b91.png)

**Comment by caramez** [comment]
@aline-cristina 
Idem ao ticket 581, criamos uma classe ellipsis para truncar os textos no h3. Como já existia a mesma classe nos textos, o comportamento já foi previsto no CSS. 

O @jamilatta pode deixar de truncar do lado dele neste caso.

**Link**
http://scielohomolog.parati.ag/Periodico/homepage.html

**Pacote**
http://scielohomolog.parati.ag/2017-07-10-Tk568-581-582.zip

**Comment by jamilatta** [comment]
@caramez estou ajustando.

**Comment by jamilatta** [comment]
@caramez estou ajustando.

**Comment by jamilatta** [comment]
Corrigido: https://github.com/scieloorg/opac/pull/649
