### ISSUE TITLE
Missão cadastrada em apenas um idioma não se repete

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#583]
Acontece no caso do periódico Annali dell'Istituto Superiore di Sanità: a missão está cadastrada apenas em inglês. No site oficial já publicado a missão em inglês se repete em todos os idiomas, mas no OPAC fica visível apenas em inglês - nos outros idiomas fica com a mensagem de "Periódico sem missão cadastrada".

Se possível, acredito que seria melhor se isso pudesse acontecer também no site novo, para não ficar parecendo que o periódico não tem missão. 

Seguem prints abaixo.

![missao3](https://user-images.githubusercontent.com/26901197/27336630-8bb2efba-55a6-11e7-9b38-06bf36691d37.png)
![missao2](https://user-images.githubusercontent.com/26901197/27336629-8bb210e0-55a6-11e7-8d1e-430635f44b79.png)
![missao1](https://user-images.githubusercontent.com/26901197/27336631-8bd6a1a8-55a6-11e7-80b3-e3f97a2feec2.png)

**Comment by jfunez** [comment]
Grato pelo feedback.

Realmente não temos mantido o mesmo comportamento, mas acredito que podemos levar isso a discussão na apresentação com a equipe.

**Comment by jfunez** [comment]
Em reunião com Abel e a equipe na quarta-feira 28/06/2017 foi definido que:
Caso não tenha conteúdo de "missão" no idioma que o usuário esta acessando, podemos mostrar em outro idioma, dando preferência ao idioma inglês.

A preferência de exibição ficaria:
missão no idioma que o visitante esta usando **>** missão em inglês **>** missão em outro idioma que tenha sido cadastrado

**Comment by jamilatta** [comment]
Iniciando a atividade.

**Comment by jamilatta** [comment]
Item realizado no opac_schema, ver PR: https://github.com/scieloorg/opac_schema/pull/50
