### ISSUE TITLE
Faltam links para páginas secundárias dos periódicos

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#584]
As páginas secundárias dos periódicos são "sobre nós", "corpo editorial", "instruções aos autores" e "assinaturas", porém só existe link para 3 no OPAC - "instruções aos autores", "sobre o periódico" e "contato".

O conteúdo das páginas secundárias ainda não está disponível para teste.

![pag_sec](https://user-images.githubusercontent.com/26901197/27337044-b039ae90-55a7-11e7-87aa-415f01684d0c.png)

![pag_sec2](https://user-images.githubusercontent.com/26901197/27337096-db566438-55a7-11e7-9fb3-6fdf54a162ef.png)

**Comment by alexxxmendonca** [comment]
A quantidade de páginas secundárias não vai bater com o site atual, mesmo.

"Assinaturas" não existirá no site novo e o corpo editorial será por fascículo, e também dentro do item "Sobre o periódico", eu imagino.

O conteúdo das páginas secundárias ainda está pendente de definição.

**Comment by jfunez** [comment]
Em reunião na quinta-feira 29/06/2017 foi definido com Abel e Alex, que precisamos um link para o Corpo Editorial, que será uma página secundária. E este conteúdo sera importado a partir do que temos hoje em metodologia, e ajustado posteriormente pelo @alexxxmendonca e outros responsáveis.

**Comment by jfunez** [comment]
@alexxxmendonca @jamilatta com os últimos ajustes na importação das páginas secundárias e o fix para urls de submissão online resolvidos... tem alguma outra coisa pendente? ou podemos fechar este issue?

**Comment by alexxxmendonca** [comment]
Sim. Porém, o ícone do Corpo Editorial precisa ser outro. Vou abrir um novo ticket para essa demanda.

**Comment by jfunez** [comment]
ótimo! vou fechar então... 👍
