### ISSUE TITLE
Não existe conteúdo em "Sobre o SciELO Saúde Pública"

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#585]
A página "Sobre o SciELO Saúde Pública" está vazia.

![sobre2](https://user-images.githubusercontent.com/26901197/27337396-b592dd52-55a8-11e7-879e-7c0e4509d4c8.png)

![sobre](https://user-images.githubusercontent.com/26901197/27337399-b7b1f6fe-55a8-11e7-9a72-afdf033742f7.png)

**Comment by jfunez** [comment]
Só esclarecendo, isso não é bug, e que não temos cadastrados esses dados, que pode ser feito pela interface de administarçaão (admin do site).

Já mostramos como cadastrar tais dados, e vamos reforçar isso na apresentação.

**Comment by jfunez** [comment]
Este issue trata sobre falta de conteúdo no site. A ferramenta de administração do site permite inserir tal conteúdo, que será feito pelo responsável de conteúdo.

Em reunião no dia 28/6/17 com Abel, foi definido que o responsável pelo conteúdo será @alexxxmendonca 

Vamos agendar uma serie de reuniões para tratar a inserção de conteúdo como Alex e sua equipe.
