### ISSUE TITLE
Visualização de caption na barra de busca

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/opac#586]
Há um pequeno espaço preenchido em azul marinho quando clicamos na barra de busca, entretanto não se pode ver seu conteúdo, pois a barra se sobrepõe a esta etiqueta. Esta etiqueta é clicável e leva a uma box suspensa de ajuda. Segue print do erro.

![site-novo_2](https://user-images.githubusercontent.com/27728729/27337289-588aa07c-55a8-11e7-9476-5ee0f3bb15d1.png)

O Navegador usado foi o Mozilla Firefox, numa tela de 1980x1080

**Comment by jfunez** [comment]
Grato pelo feedback! 
Já estou notificando o designer!

**Comment by jfunez** [comment]
@cinthia-vieira pode gentileza, pode dar uma olhada para verificar se problema foi resolvido?

Obrigado!

**Comment by cinthia-vieira** [comment]
Na página inicial sim, a caixinha para de aparecer.

Entretanto, não dá pra ver nas demais páginas porque ao entrar no ambiente de busca, aparece uma página com o CSS quebrado que não retorna nada; segue print.

![site-novo_6](https://user-images.githubusercontent.com/27728729/27591670-c3e609f8-5b28-11e7-9522-6821f6ee6acd.png)

**Comment by jfunez** [comment]
@cinthia-vieira sim, estamos cientes desse problema no site de busca, e vamos resolver em breve... 
No que diz respeito ao OPAC acho que podemos fechar este issue.

Grato pelo retorno!
