### ISSUE TITLE
Busca com erro

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#587]
Ao pesquisar qualquer palavra chave pelo Chrome na barra de busca, seja qual for a palavra sou direcionada para o link http://search.scielo.org/history/?lang=pt e a palavra que pesquisei se transforma em "Array", sem mostrar nenhum resultado. Ao entrar em "histórico de pesquisa" mostra a palavra pesquisada como "Array" com um monte de resultados que nunca apareceram.

Ao clicar no logotipo da SciELO para voltar à página principal, continuo no link http://search.scielo.org/history/?lang=pt e o menu não funciona.

![busca1](https://user-images.githubusercontent.com/26901197/27338243-0e160592-55ab-11e7-9520-b7b35ca1a602.png)

**Comment by jfunez** [comment]
Grato pelo feedback!

Já tinhamos reportado este problema aqui: 
https://github.com/scieloorg/opac/issues/557

Então vou fechar este issue, para continuar a discussão por lá
