### ISSUE TITLE
Problema na pagina de busca no periodico

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/opac#588]
Ao clicar em "Buscar" dentro da página de um periódico é pesquisado automaticamente o caractere "*" o que dá erro em algumas pesquisas - Já aparece logo de cara que não foi encontrado nenhum resultado, ou aparece algum resultado especificamente para aquele caractere. 

![busca2](https://user-images.githubusercontent.com/27728729/27338567-f918cb7e-55ab-11e7-955d-88cfd6290a15.png)

**Comment by jamilatta** [comment]
@cinthia-vieira grato pelo feedaback, porém esse ticket deve ser aberto no projeto do sistema de pesquisa, segue link: [search-journals](https://github.com/scieloorg/search-journals/issues)

Por gentileza re-abra esse ticket no link indicado para que possamos fechar esse no projeto do site.

**Comment by aline-cristina** [comment]
@jamilatta ticket #373 criado

https://github.com/scieloorg/search-journals/issues/373

**Comment by jamilatta** [comment]
Grato.
