### ISSUE TITLE
Redimensionamento de thumbnails

### ISSUE THREAD

**Issue by cinthia-vieira** [scieloorg/opac#589]
O redimensionamento de thumbnails nas páginas dos artigos deixa as imagens desproprorcionais e ilegíveis, principalmente no menu/box suspenso e em telas menores/paisagem.

O redimensionamento também distorce as imagens quando em tamanho grande, mas com um efeito menor.

> ![site-novo_4](https://user-images.githubusercontent.com/27728729/27339259-b35a45ac-55ad-11e7-8875-fa2c2d45f26d.png)
> _menu suspenso_

> ![site-novo_3](https://user-images.githubusercontent.com/27728729/27339260-b35b2742-55ad-11e7-9f41-dcf8014e8a4c.png)
> _Páginas grandes/texto "completo"_

> ![site-novo_5](https://user-images.githubusercontent.com/27728729/27339261-b35b58e8-55ad-11e7-9f4e-c2314c0a5bce.png)
> _tela reduzida/menor_

O mesmo erro acontece com fórmulas, quando exibidas no box/menu suspenso:

> ![teste5_2](https://user-images.githubusercontent.com/27728729/27339262-b35ec582-55ad-11e7-87e6-c2005b2d024f.png)
> _fórmulas no menu suspenso_

Seguem .zips dos HTML como exemplo.
**Imagens:** [2237-9622-ress-24-04-00771.pt.zip](https://github.com/scieloorg/opac/files/1088551/2237-9622-ress-24-04-00771.pt.zip)
**Fórmulas:** [0036-3634-spm-59-01-00095.en.zip](https://github.com/scieloorg/opac/files/1088561/0036-3634-spm-59-01-00095.en.zip)

**Comment by caramez** [comment]
@cinthia-vieira @robertatakenaka não há como adequarmos automaticamente, fizemos uma solução em que a imagem vai redimensionar na largura da caixa e se for maior verticalmente a imagem ficará cortada, ok?

Dêem uma olhada:
http://scielohomolog.parati.ag/Artigo/

**Comment by jfunez** [comment]
resolvido na entrega de ontem (26/6)
