### ISSUE TITLE
Corpo do texto sem separador entre Resumos (Abstracts) e texto

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/opac#590]
Em um artigo com `article-type="news"` não existe separador entre Resumo e texto, além do espaçamento estar incorreto (realizado teste fora do ambiente OPAC).

![abst](https://user-images.githubusercontent.com/26901197/27340267-724513dc-55b0-11e7-9546-d5c6adfbe40e.png)
Arquivos:
https://drive.google.com/file/d/0BwQS0ypeq1cxa0hJWHVoN0xueW8/view?usp=sharing

Na versão do site no ambiente OPAC, aparecem mais casos como esse em artigos diversos.

**Comment by jfunez** [comment]
obrigado pelo feedback... 👍 
em breve vamos reprocessar os artigos com as últimas mudanças da @robertatakenaka e suspeito que vai ficar solucionado... até lá vamos deixar este issue aberto para revisar

**Comment by robertatakenaka** [comment]
@caramez : pode dar prioridade para isso? Há Documentos em que não existe o "Título" Resumo no idioma correspondente. Para que fique explícito a ausência do dado, não geramos um título para que fique bonito. Então precisamos de uma solução que coloque uma linha e/ou um espaçamento maior entre os resumos.

[0042-9686-bwho-91-09-671.en.html.zip](https://github.com/scieloorg/opac/files/1091756/0042-9686-bwho-91-09-671.en.html.zip)

**Comment by caramez** [comment]
@robertatakenaka dá uma olhada no resultado:
http://scielohomolog.parati.ag/Artigo/tk590.html

Fizemos conforme comentamos hoje, com <HR>.

**Comment by robertatakenaka** [comment]
@caramez : acho que ok, mas percebi que ficou o mesmo entre os títulos e não acho que é adequado.

**Comment by robertatakenaka** [comment]
@caramez: Acharam que não foi o suficiente a linha separando, sugeriram colocar mais espaçamento.

**Comment by caramez** [comment]
@robertatakenaka aumentei o espaçamento tem como verificar com o pessoal se está de acordo:
http://scielohomolog.parati.ag/Artigo/tk590.html

**Comment by aline-cristina** [comment]
@caramez eu achei que ficou bem melhor, nos casos de resumos sem título, ficou claro onde termina um resumo e começa o outro -- porém, resumos que contém título para cada tradução também ficarão com esse espaçamento maior entre os resumos? Poderíamos ver um exemplo de como ficariam nesse outro caso?

**Comment by caramez** [comment]
@aline-cristina o caso que você diz é parecido com este?
http://scielohomolog.parati.ag/Artigo/tk589.html

**Comment by aline-cristina** [comment]
@caramez acho que o link do exemplo **tk589** não está funcionando

**Comment by caramez** [comment]
Comi bola no link:
http://scielohomolog.parati.ag/Artigo/Tk589.html

**Comment by aline-cristina** [comment]
Na minha opinião, ficou melhor assim. 
@robertatakenaka o que você acha?

**Comment by jamilatta** [comment]
@robertatakenaka @aline-cristina o que ficou definido desse ticket.

**Comment by jamilatta** [comment]
Item realizado, verificamos em ambiente de homologação: https://homolog.opac.scielo.org/article/ress/2016.v25nspe./7-86/pt/#
