### ISSUE TITLE
Menu não funciona em página de Busca na coleção 

### ISSUE THREAD

**Issue by suelylc** [scieloorg/opac#591]
O menu (superior esquerdo) passa a não funcionar quando estamos na página de busca acessada por esta opção.  
![erro_menu](https://user-images.githubusercontent.com/6921625/27351910-48e0834e-55d5-11e7-83cb-7a149bedd83e.JPG)

Link
http://search.scielo.org/?q=*&lang=pt&filter[in][]=spa

**Comment by jfunez** [comment]
Grato pelo feedback! 👍 

Se eu entendi direito, o menu hamburger não funciona quando esta no site de busca. certo?
Neste caso, o problema deve ser registrado no repositório da aplicação search.scielo.org (aqui: https://github.com/scieloorg/search-journals/issues/new) 

Por gentileza, poderia cadastrar o problema lá? e cobrar o @alexxxmendonca 😄

**Comment by suelylc** [comment]
Registro feito:
https://github.com/scieloorg/search-journals/issues/375

**Comment by jfunez** [comment]
muito obrigado @suelylc !!
