### ISSUE TITLE
Problema no comportamento de mouseOver de notas

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#594]
O comportamento de mouseOver de referências (azul) deve ser igual ao do de notas (laranja). A única diferença é a cor azul e laranja.
No caso do laranja conforme o arquivo em anexo note que a nota some quando o mouse fica sobre ela não podendo o usuário clicar no link que ela contém.

<img width="331" alt="captura de tela 2017-06-21 as 11 34 30" src="https://user-images.githubusercontent.com/505143/27389775-c120cb3e-5675-11e7-8d5d-2163a956200d.png">

[1020-4989-RPSP-40-02-124.en.html.zip](https://github.com/scieloorg/opac/files/1091801/1020-4989-RPSP-40-02-124.en.html.zip)

Aparentemente o problema está em  **footnote**

``<span class="ref footnote">``

**Comment by caramez** [comment]
@robertatakenaka não conseguimos pegar muito bem este bug, mas fizemos algumas alterações no Ticket 551 que pode ter interferido no resultado. Dá uma olhada:
http://scielohomolog.parati.ag/Artigo/tk594.html#ModalTablet0004

**Comment by robertatakenaka** [comment]
@caramez aparentemente resolveu

Entrega 2017-06-26
