### ISSUE TITLE
Diferentes suplementos do mesmo volume, ao serem abertos são direcionados para o mesmo link

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/opac#595]
Ao clicar em diferentes suplementos de volume, a URL criada tem como final: acrônimo/ano.volume e assim, não diferencia um suplemento do outro , fazendo com que suplementos do mesmo volume possuam links iguais. 

Ex: 
https://homolog.opac.scielo.org/spm/2015.v57/
https://homolog.opac.scielo.org/spm/issues/

**Comment by jamilatta** [comment]
@jenniferamato 

Grato pelo feedback, Muito boa a observação! irei fazer os ajustes necessários para garantir a indicação do número do suplemento na URL para garantir a distinção do suplemento para mesmo volume.
