### ISSUE TITLE
Número está sendo identificado como suplemento de volume

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/opac#596]
Número está sendo identificado como suplemento de volume no sumário, porém, ao clicar nele a URL é criada corretamente (com identificação de volume e número -
 https://homolog.opac.scielo.org/spm/2009.v51n3/). 

Ex:
![spm](https://user-images.githubusercontent.com/16937218/27439347-21a631ec-573e-11e7-945f-96639c6c12ce.png)

No site atual aparece da seguinte maneira:  

![spm2](https://user-images.githubusercontent.com/16937218/27439350-23e2d06e-573e-11e7-97c9-ef2d5c9b5c82.png)

Link do sumário: 
https://homolog.opac.scielo.org/spm/issues/

**Comment by jamilatta** [comment]
@jenniferamato 

Grato pelo feedback, estou verificando em que momento estamos identificando esse fascículo com suplemento.

**Comment by jamilatta** [comment]
@fabiobatalha 

Verifique junto ao article meta esse fascículo indica que é u suplemento, poderia por gentileza dar uma olhada, segue os links 

Link do grade errada no Novo site: https://homolog.opac.scielo.org/spm/issues/ (**Repare no volume 51**) 

Link para a grade no site antigo: http://www.scielosp.org/scielo.php?script=sci_issues&pid=0036-3634&lng=en&nrm=iso (**Repare no volume 51**) 

Link para o issue no article meta: http://articlemeta.scielo.org/api/v1/issue/?code=0036-363420090003&collection=spa (**Repare que esta indicando issue_type: "supplement"**)

**Comment by fabiobatalha** [comment]
@jamilatta 

Aparentemente o ArticleMeta e Xylose não identificam o fascículo como um suplemento. Esse tratamento deve estar no OPAC.

```python
In [1]: from articlemeta.client import ThriftClient
In [2]: cl = ThriftClient()
In [3]: doc = cl.document(code='S0036-36342009000300001', collection='spa')
In [4]: doc.issue.supplement_number
Out[4]: ''
In [5]: doc.issue.supplement_volume
Out[5]: ''
In [6]: doc.issue.number
Out[6]: '3'
In [7]: doc.issue.volume
Out[7]: '51'
```

**Comment by jamilatta** [comment]
Estranho da uma olhada: 
<img width="743" alt="screenshot 2017-06-23 12 00 45" src="https://user-images.githubusercontent.com/373745/27487958-b2ba8cdc-580b-11e7-8984-11319f9e2da7.png">


Obs.: Não seria mais fiel buscar pelo issue na API Thrift?, me refiro ao issue e não a um artigo.

**Comment by jfunez** [comment]
resultados após os últimos ajustes:

### Grade antes

![grade_antes](https://user-images.githubusercontent.com/805749/27552912-6bffb97c-5a7f-11e7-8b97-2842ceb67ad5.png)


### Grade depois

![grade_depois](https://user-images.githubusercontent.com/805749/27552917-71985f38-5a7f-11e7-8edd-88b9461a6793.png)

**Comment by jamilatta** [comment]
@jenniferamato

poderia por gentileza verificar em:https://homolog.opac.scielo.org/spm/issues/ para que possamos fechar esse ticket.

**Comment by robertatakenaka** [comment]
@jamilatta @jfunez @fabiobatalha 
No ISIS, está ok
spm 20091 51n1
spm 20092 51n2
spm 20093 51n3
spm 20094 51n4
spm 20095 51n5
spm 20096 51n6
spm 20097 51 s1
spm 20098 51 s2
spm 20099 51 s3
spm 200910 51 s4

--- 
Em http://articlemeta.scielo.org/api/v1/issue/?code=0036-363420090003&collection=spa,
há v131 com valor '', mas nem deveria existir este campo. É aí o problema.
```
{
    "code": "0036-363420090003",
    "issue": {
        "v991": [
            {
                "_": "1"
            }
        ],
        "v131": [
            {
                "_": ""
            }
```
        ],

**Comment by jenniferamato** [comment]
@jamilatta , na grade atual quando é suppl.0 , o zero não aparece. 
ex (ver volume 12): 
http://www.scielo.br/scielo.php?script=sci_issues&pid=1413-8123&lng=en&nrm=iso

na nova grade está: 
https://homolog.opac.scielo.org/csc/issues/

**Comment by jamilatta** [comment]
Adicionei um ticket no xylose informando que devemos reavaliar a regra de definição de suplemento: https://github.com/scieloorg/xylose/issues/141

**Comment by jfunez** [comment]
@jenniferamato por gentileza, pode revisar novamente a grade (com `supple.0` que você apontou) 
Agora deveria estar resolvido. 👉 https://homolog.opac.scielo.org/csc/issues/
Assim podemos fechar este issue.

**Comment by jenniferamato** [comment]
@jamilatta  e @jfunez , está ok agora.

**Comment by jamilatta** [comment]
Ok, Grato!
