### ISSUE TITLE
No modal como citar, o copiar não funciona

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#597]
http://scielohomolog.parati.ag/Artigo/#ModalArticles

<img width="599" alt="captura de tela 2017-06-22 as 15 40 15" src="https://user-images.githubusercontent.com/505143/27450199-43543dc0-5761-11e7-89b7-c538f406db2a.png">

**Comment by caramez** [comment]
@robertatakenaka fizemos a correção:
http://scielohomolog.parati.ag/Artigo/#ModalArticles

**Comment by jfunez** [comment]
Foi testado e verificamos que estaba funcionado em homologação do OPAC
