### ISSUE TITLE
Remover separador entre os títulos (css)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#604]
http://scielohomolog.parati.ag/Artigo/tk590.html

<img width="1091" alt="captura de tela 2017-06-27 as 13 28 06" src="https://user-images.githubusercontent.com/505143/27598651-860ae4b4-5b3c-11e7-8400-a892876c6ec1.png">

**Comment by robertatakenaka** [comment]
@caramez, os títulos traduzidos estão muito pequenos. Ficou "errado" após a entrega do dia 26-06-2017

**Comment by caramez** [comment]
@robertatakenaka segue a versão com as alterações:
http://scielohomolog.parati.ag/Artigo/tk590.html

**Comment by jamilatta** [comment]
Este item foi realizado e esta disponível em homologação.
