### ISSUE TITLE
Legenda bibliografica.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#610]
Ficou definido em reunião no dia 28/06/2017 que iremos adicionar no legendarium a capacidade de termos diferentes tipos de exibição da legenda bibliográfica com objetivo de definirmos uma junto a direção. 

Ticket no legendarium relacionado com essa atividade: https://github.com/scieloorg/legendarium/issues/42

**Comment by jamilatta** [comment]
@jfunez podemos fechar esse ticket?

**Comment by jfunez** [comment]
vou revisar/ajustar para conferir que esta tudo certo e se for o caso eu fecho!
