### ISSUE TITLE
Trocar ‘titulo’ e ‘revista’ por periódico

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#614]
Ficou definido em reunião no dia 28/06/2017 que devemos substituir todos os labels de **título** e **revista** por periódico.

**Comment by jamilatta** [comment]
@jfunez 

Acredito que nos ajustes que vc fez na lista de periódico esse item estaja finalizado correto?

**Comment by jfunez** [comment]
revisado em: https://github.com/scieloorg/opac/pull/657
