### ISSUE TITLE
[artigo] botão/link para voltar ao topo

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#623]
Em reunião com a Equipe (na quarta-feira: 28/06/17) foi definido que:

> é preciso ter um botão/link para voltar ao topo da página do artigo

O designer pode indicar alguma sugestão da localização e estilo de tal botão/link

**Comment by caramez** [comment]
@jfunez adicionamos na barra de ferramentas esta opção:
![image](https://user-images.githubusercontent.com/22373640/27843021-db3cb4cc-60e5-11e7-8bf3-d7bc897302b3.png)

Para ver funcionando:
http://scielohomolog.parati.ag/Artigo/

**Comment by jamilatta** [comment]
Boa!

**Comment by jamilatta** [comment]
Na reunião do dia 12/07/2017 ficou decidido que o botão "Voltar ao topo" deve ser colocado para a esquerda logo abaixo das seções do artigo, ver imagem: 

<img width="1528" alt="screenshot 2017-07-13 14 05 14" src="https://user-images.githubusercontent.com/373745/28178305-5ad482f6-67d4-11e7-821a-56cd5ed6bb57.png">

**Comment by caramez** [comment]
Segue sugestão

![image](https://user-images.githubusercontent.com/22373640/28438975-684bdcf2-6d76-11e7-9e86-b7b95bf49178.png)

![image](https://user-images.githubusercontent.com/22373640/28438982-71758ed6-6d76-11e7-8a94-5a97bf199097.png)

**Comment by jamilatta** [comment]
@caramez

Poderia por gentileza nos enviar os .zips para que possamos atualizar a instância de homolog

**Comment by paratiuid** [comment]
Segue o zip
http://scielohomolog.parati.ag/scielo-ticket-623.zip

**Comment by alexxxmendonca** [comment]
Continuado em #705
