### ISSUE TITLE
[artigo] remover temporariamente link para baixar o XML

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#624]
Em reunião com a Equipe (na quarta-feira: 28/06/17) foi definido que:
> será removido o link para baixar o XML do artigo

**Comment by amandasramalho** [comment]
Retirar o epub também... não sei se será aberto outro ticket para isso...

**Comment by jfunez** [comment]
👍

**Comment by jfunez** [comment]
resolvido!
