### ISSUE TITLE
[artigo] botão/link para obter a url curta ao lado do botão "copiar" (doi)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#626]
Em reunião com a Equipe (na quarta-feira: 28/06/17) foi definido que:

> devemos mostar um botão/link para obter a URL curta do artigo ao lado do botão "copiar" que copia o DOI

Precisamos que o designer faça sua sugestão copiando a funcionalidade do site atual ("permalink") 
<img width="230" alt="screenshot 2017-06-30 11 06 28" src="https://user-images.githubusercontent.com/805749/27739211-3676c6b2-5d84-11e7-8893-492c04ac0b1d.png">

#### Observação:

O botão de "COPIAR" (DOI) permanece inalterado.

**Comment by alexxxmendonca** [comment]
@caramez 

Tomar cuidado para não confundir com o copiar do DOI.

**Comment by jfunez** [comment]
vou comentar na descrição que: o botão de "COPIAR" (DOI) permanece inalterado.

**Comment by alexxxmendonca** [comment]
Na reunião de 28/07/2017, ficou decidido que o link do permalink deverá aparecer ao final do título do documento, apenas no comportamento _mouseover_.

O link deve aparecer no formato de ícone de link (corrente).

Ver exemplo: http://docs.scielo.org/

**Comment by paratiuid** [comment]
@alexxxmendonca @jamilatta 

Segue sugestão:

![mouseover-link](https://user-images.githubusercontent.com/22373640/29073348-b6729fe2-7c21-11e7-92bf-7859c056e6ce.jpg)

**Comment by alexxxmendonca** [comment]
Uma dúvida, pois no print isso não está claro: quando o mouse não estão em cima do título, o ícone desaparece?

**Comment by alexxxmendonca** [comment]
Certo. Então está ok! 👍

**Comment by jamilatta** [comment]
👍

**Comment by jamilatta** [comment]
Adicionado os estáticos correspondentes a essa tarefa.

Necessário realizar os ajustes de HTML na página do artigo.

**Comment by jamilatta** [comment]
@paratiuid adicionamos o **css** e o elemento **HTML** para este item, porém é necessário termos o javascript para realizar a consulta da URL curta. 

Para realizar essa tarefa é necessário utiliza o seguinte endereço: 

http://ref.scielo.org/api/v1/shorten?url=' + escape(document.URL) + '&callback=?

**OBS.:** Para essa atividade é necessário cross-domain (JSONP).

**Comment by jamilatta** [comment]
Em conversa com o @paratiuid estamos sentindo dificultades para realizar a copia da URL curta utilizando um clique, pois o clipboard.js impõe que o texto de copia já esteja no DOM. 

Tentei vários exemplos utilizando AJAX e não consegui que funcionasse com apenas um clique, até que me veio a idéia de utilizar mais de um evento para resolver esse problema e ai esta a solução: 


```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Copy Ajax</title>

    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">
    </link>
  </head>
  <body>

    <div class="container">

      <div class="row">

        <div class="col-md-12 text-center">

          <a class="copy">
            <i class="glyphicon glyphicon-link" style="font-size: 24px;"></i>
          </a>

        </div>

      </div>

    </div>

  </body>

  <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous">
  </script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
    crossorigin="anonymous">
  </script>

  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js">
  </script>

  <script type="text/javascript">
      var result = '';

      $('.copy').mouseenter(function(event) {
        $.ajax({
            type: "GET",
            async: false,
            url: 'http://ref.scielo.org/api/v1/shorten',
            data: 'url=' + escape('http://www.scielo.br'), //escape(document.URL)
            dataType: "jsonp",
            success: function(data){
              result = data;
            }
            //error:
          });
      });

      var clipboard = new Clipboard('.copy', {
          text: function(trigger) {
              return result;
              }
          });

      clipboard.on('success', function(e) {
          // Aqui podemos colocar um tooptip informando que "Copiado com sucesso"
          console.log('Sucess: ' + e);
      });

      clipboard.on('error', function(e) {
          // Aqui podemos colocar um tooptip informando que "Não foi possível realizar a copia no momento, por gentileza, realize a copia da URL completa....."
          console.log('Error: ' + e);
      });

  </script>

</html>
```
Resumo estou utilizando o evento mouseenter para realizar o AJAX e deixar o valor da variável ``result`` de escopo global no JavaScript (Share State), dessa forma quando acontecer o evento ``clique``  a variável ``result`` tem valor atribuito.

**Comment by jamilatta** [comment]
Dá para melhor isso adicionando uma validação se caso a variável ``result`` já estiver com valor atribuido, não realizamos outra solicitação para o http://ref.scielo.org.

**Comment by jamilatta** [comment]
@paratiuid 

Assim que possível me retorne sobre essa atividade.

**Comment by jamilatta** [comment]
@paratiuid 

Estamos aguardando essa atividade faz 5 dias :-(), tivemos algum avanço sobre essa atividade ou ainda estamos aguardando você terminarem outras atividades?

**Comment by paratiuid** [comment]
@jamilatta 
corrigido com o ajuste sugerido.

**Comment by jamilatta** [comment]
**escape** esta deprecado, devemos utilizar **encodeURI**, ver: https://www.w3schools.com/jsref/jsref_escape.asp

**Comment by paratiuid** [comment]
@jamilatta 
Corrigido conforme solicitação.

**Comment by jamilatta** [comment]
@paratiuid 

Talvez tenha realizado a alteração do encodeURI, mas no comentário: 

```
Dá para melhorar isso adicionando uma validação se caso a variável result já estiver com valor atribuido, não realizamos outra solicitação para o http://ref.scielo.org.
```

Informo que é possível evitar várias requisições para o ref.scielo.org, criando um variável que compartilha estado. 

Qualquer dúvida podemos conversar sobre.

**Comment by paratiuid** [comment]
@jamilatta 
Favor, verificar se na branch develop existe o seguinte commit:
https://bitbucket.org/parati_uid/portal-scielo/commits/684bbe2566de9d3948a179c911fe413f2957ce45

Obs.: Nela declaramos a variável  'result' fora do escopo da função ajax e antes de chamá-la verificamos se já está setada.

**Comment by jamilatta** [comment]
@paratiuid 

Correto mas precisamos de um **if** para garantir que não passamos pelo trecho do ajax, evitando várias requisições, ver:

```javascript

if (!result){
    $.ajax({
        type: "GET",
        async: false,
        url: 'http://ref.scielo.org/api/v1/shorten',
        data: 'url=' + escape(urlAtual), //escape(document.URL)
        dataType: "jsonp",
        success: function(data){
          result = data;
       }
      //error:
    });
}
```

**Comment by jamilatta** [comment]
Dessa forma somente entramos no trecho código do ajax quando a variável **result** estiver vazia.

**Comment by jamilatta** [comment]
Me parece que o **if(result == null)** esta sempre retornando verdade.

**Comment by paratiuid** [comment]
@jamilatta 
Foi feita a correção no código javascript de acordo com seu exemplo. 
Favor, verificar se está de acordo.

**Comment by jamilatta** [comment]
@paratiuid 

Ainda acessando várias vezes o encurtador e agora estamos com erro, ver: 


<img width="1680" alt="screenshot 2017-09-13 15 53 40" src="https://user-images.githubusercontent.com/373745/30395249-e6f47848-989b-11e7-8cc9-7f857fe25eaf.png">

**Comment by jamilatta** [comment]
É possível verificar o comportamento do link curto acessando o ambiente de [Homologação](http://homolog.opac.scielo.org):

**Comment by jamilatta** [comment]
Item realizado.
