### ISSUE TITLE
[Artigo] opções para trocar o logo da licencia CC

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#627]
Em reunião com a Equipe (na quarta-feira: 28/06/17) foi solicitado que:

> como Abel achou que o logo atual esta muito pequeno, gostaria de ver outras alternativas com logos maiores (sempre falando dos logos oficiais) da licencia CC

Neste ponto precisamos do auxilio do Designer, para mostrar as outras alternativas.

**Comment by caramez** [comment]
@jfunez fizemos uma alteração que implica em tornar os badge do Creative Common em ícones (utilizando ainda a versão oficial como recomenda o site, porém sem o selo).

Dá uma olhada:
http://scielohomolog.parati.ag/Artigo/
http://scielohomolog.parati.ag/Artigo/tk590.html (aqui uma versão do ícone para copyright)

O selos o Creative Common estão separados (BY, ND, SA e etc.) assim podem compor qualquer tipo de licença, dentro dele. Além disso, incluímos também um selo para "Domínio Público" caso eventualmente possa ser usado, baseado no ícone utilizado Creative Common.

**Comment by alexxxmendonca** [comment]
Eu gostei! 👍

**Comment by jamilatta** [comment]
Gostei também.

**Comment by jamilatta** [comment]
Esse ticket foi invalidado pelo tk: https://github.com/scieloorg/opac/issues/672
