### ISSUE TITLE
Importação das páginas secundárias 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#630]
Ficou definido em reunião no dia 28/06/2017, que devemos fazer uma migração das páginas secundárias atual, para que a equipe do Alex possa realizar os ajustes posteriormente.

**Comment by jamilatta** [comment]
Iniciando atividade.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Realizamos a importação das páginas secundárias verifiquem no ambiente de homologação. 

Exemplo: https://homolog.opac.scielo.org/rsp/about/#about

**Comment by alexxxmendonca** [comment]
A ordem correta deve ser:

- Sobre o periódico
- Corpo Editorial
- Instruções aos autores

É possível seguir essa ordem?

"Assinaturas" não precisa ser importada.

**Comment by jamilatta** [comment]
@alexxxmendonca as páginas secundárias estão disponíveis na instância de homologação considerando a sequência solicitada.

**Comment by alexxxmendonca** [comment]
Está aparecendo duplicado: https://homolog.opac.scielo.org/rsp/about/#about

**Comment by jamilatta** [comment]
Estou corrigindo.

**Comment by jamilatta** [comment]
Resolvido, por gentileza verifique em: https://homolog.opac.scielo.org/rsp/about/#about

**Comment by alexxxmendonca** [comment]
Agora está ok 👍
