### ISSUE TITLE
Link para PDF mais visível

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#652]
Recomendação do Anurag, do Google Scholar:

_It would be good to move the PDF download link from the menu and directly onto the page. That is by far the most common link clicked from the abstract/article page. Getting to fulltext is used way more often than say the Share links which are currently inlined._

Recomendação aprovada pela Equipe SciELO.

**Comment by jamilatta** [comment]
Na reunião do dia 12/07/2017 consideramos a observação enviada pelo Anurag (Google Scholar) e decidimos que devemos ter o link do PDF logo após o botão de "artigo seguinte" (Isso existia em mockups anteriores). 

Esse botão deve ser capaz de mostrar as versão de tradução dos PDFs. 

Além do botão de PDF devemos ter um botão para ePDF. 

Pensamos na seguinte sequência (logo após o botão "artigo seguinte"): 

PDF, epdf, icon de print, emial e compartilhamento (sendo o compartilhamento somente um botão que abri outra opções de compartilhamento)

**Comment by alexxxmendonca** [comment]
@caramez, se precisar alterar nas outras páginas, que não a página do artigo, não tem problema.

Sei que esse cabeçalho aparece em outras páginas do site então se precisar alterar nas outras páginas para manter a consistência, sem problemas.

**Comment by caramez** [comment]
Temos uma outra sugestão:
criar um botão entitulado "Download PDF, ePDF..." Ao clicar, abre o modal já existente no sistema, com as opções de download disponíveis. 
Dessa maneira mantemos a possibilidade de escolha do idioma ao baixar o arquivo.

Segue modelo abaixo.
![image](https://user-images.githubusercontent.com/22373640/28432666-23ebcdae-6d5f-11e7-91d7-98db3496f882.png)
![image](https://user-images.githubusercontent.com/22373640/28432670-2b2892a0-6d5f-11e7-90c9-6d139720e232.png)

No tablet
![image](https://user-images.githubusercontent.com/22373640/28432682-3963a4b8-6d5f-11e7-9fab-df395668407c.png)

**Comment by jamilatta** [comment]
@caramez 

Poderia por gentileza nos enviar os .zips para que possamos atualizar a instância de homolog.

**Comment by paratiuid** [comment]
segue link:
http://scielohomolog.parati.ag/scielo-ticket-652.zip

**Comment by jfunez** [comment]
implementando
