### ISSUE TITLE
Métricas mais visíveis

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#653]
Recomendação do Anurag, do Google Scholar:

_- It would be best to add the Scholar Metrics link back to the article in a visible place somewhere. The key value of the link is to let potential authors see the succeses of the journal quickly. So that they would be tempted to join the club of authors for the journal. Drawing in likely-to-be-successful authors is crucial for the continued ramp up of journal reputation/reknown._

Recomendação aprovada pela Equipe SciELO.

Havíamos conversado sobre algo parecido talvez com a PLOS:

![image](https://user-images.githubusercontent.com/4059679/28030217-32d06494-6579-11e7-841b-25b610e24f0f.png)

**Comment by jamilatta** [comment]
Esse ticket é inválido não iremos apresentar métricas no site.
