### ISSUE TITLE
Corrigir link para o PDF

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#654]
Atualmente o link para o PDF no TOC está exibindo o link para a nosso repositório de ativos. 

Devemos encapsular isso em um link do OPAC.

**Comment by jamilatta** [comment]
Lembrei que devemos manter e resolver o link para os PDFs do site atual, portanto nessa atividade o link(exemplo): http://www.scielo.br/pdf/abb/2016nahead/0102-3306-abb-2016abb0279.pdf deve ser resolvido pelo site novo.

**Comment by jfunez** [comment]
👍

**Comment by jamilatta** [comment]
Resolvido em: https://github.com/scieloorg/opac/pull/682
