### ISSUE TITLE
Faixa de métricas - home do periódico

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#668]
A disposição e layout das métricas na home do periódico foram reformuladas.

Elas serão dispostas na mesma faixa onde atualmente encontra-se a Missão do periódico:

![image](https://user-images.githubusercontent.com/4059679/28164586-76265620-67a6-11e7-9fce-7bb24a85d3c0.png)

A área da missão deve ser reduzida para 1/3 do espaço delimitado para o conteúdo, a fim de comportar melhor as métricas que ficarão ao lado esquerdo, dessa forma:

![img_5579](https://user-images.githubusercontent.com/4059679/28164758-323c5f30-67a7-11e7-9068-8cff1b88aed6.JPG)

![image](https://user-images.githubusercontent.com/4059679/28164963-1b120a98-67a8-11e7-80e4-eece06ca5351.png)

A quantidade de colunas com métricas não será limitado ao número acima, portanto, as colunas com as métricas devem ser dispostas em formato carrossel -- semelhante ao usado para o carrossel de press releases, blog SciELO etc.

Para conhecimento, elaboramos um guia mais detalhado sobre esse assunto:

https://docs.google.com/document/d/1_4_zw7Opn3xo781unfpiOlCgRZ4SVIstNFh8CGSWxBE/edit#

**Comment by caramez** [comment]
@alexxxmendonca tenho algumas dúvidas:
 -  qual o número mínimo de colunas? 
 -  a coluna JCR vai aparecer sempre?
 -  quais colunas aparecerão sempre?

**Comment by alexxxmendonca** [comment]
As 3 primeiras vão aparecer sempre:

- Publicação
- Downloads
- Google Métricas

As demais vão aparecer somente se o periódico dispor dos dados.

**Comment by alexxxmendonca** [comment]
Não tenho certeza da Google Métricas.

@fabiobatalha é correto afirmarmos que todos os nossos periódicos têm? Não me lembro se sim ou se "quase todos" tinham.

**Comment by caramez** [comment]
Pessoal, 
segue uma proposta.

Mudei de colunas para linhas. Dessa maneira, caso necessário, o crescimento ocorre mais naturalmente, gerando novas linhas abaixo das existentes.
Dei maior destaque ao dado em si, deixando o label menor, com menos destaque.

Na imagem temos o estado normal da linha e também com o efeito de mouse over.

Aguardo aprovação.

![image](https://user-images.githubusercontent.com/22373640/28529031-cebd6c66-7065-11e7-82dc-7272d64d1cf0.png)

![image](https://user-images.githubusercontent.com/22373640/28529042-d59d758a-7065-11e7-9da1-f85101a3c0be.png)

**Comment by paratiuid** [comment]
@alexxxmendonca 

![image](https://user-images.githubusercontent.com/22373640/28597651-86965446-7175-11e7-95c9-1833bb0d33fa.png)

![image](https://user-images.githubusercontent.com/22373640/28597653-8ab90b04-7175-11e7-9c1d-e6efd1f4c555.png)

![image](https://user-images.githubusercontent.com/22373640/28597657-8f3d856a-7175-11e7-8def-5451726859f0.png)


Segue uma nova proposta.

A primeira tela mostra o caso de haver no máximo 3 itens.
A segunda tela mostra o caso de haver quatro itens.
A terceira tela mostra o caso de haver mais de quatro itens.

Optamos por isso pois caso tenha menos de três quatro itens, ao usar o formato de card, teríamos um espaço em branco muito grande.

Dessa maneira, com uma simples contagem dos itens é possível utilizar um dos formatos citados acima.

**Comment by alexxxmendonca** [comment]
Proposta aprovada pela Direção 👍

**Comment by paratiuid** [comment]
@alexxxmendonca 

Segue o zip contendo as alterações.

http://scielohomolog.parati.ag/scielo-ticket-668.zip

Para este caso, como temos tres condições, criei um arquivo de homepage para cada condição.
São elas:

Exibir até tres itens:
Periodico/homepage-3-itens.html

Exibir quatro itens
Periodico/homepage-4-itens.html

Exibir mais de quatro itens
Periodico/homepage-4-mais-itens.html

**Comment by jamilatta** [comment]
Como conversado com a direção ficou decidido que não iremos adicionar métricas no site. Todas as requisição desse tipo deve ser realizado na ferramenta de analítica: https://analytics.scielo.org/
