### ISSUE TITLE
Trocar a posição do cadeado de acesso aberto no título.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#670]
Em reunião com equipe e Abel ficou decidido que o cadeado de acesso aberto que atualmente de encontra do lado esquerdo do título deve ficar em cima do título alinhado a esquerda. 

Atualmente: 

<img width="1358" alt="screenshot 2017-07-13 13 58 18" src="https://user-images.githubusercontent.com/373745/28178047-5c8ca246-67d3-11e7-93cf-60d7c1f0b9e6.png">

Peço para que o designer realize essa atividade para não termos diferente versão do mockup.

**Comment by jamilatta** [comment]
![screenshot 2017-07-12 15 20 22](https://user-images.githubusercontent.com/373745/28178841-45e35ae6-67d6-11e7-955b-5351a010c8b5.png)

**Comment by caramez** [comment]
![image](https://user-images.githubusercontent.com/22373640/28386588-71391e12-6ca2-11e7-901f-c9a9b1af1af6.png)

Pessoal, 
segue a alteração. Aguardo comentários.

Aplicamos o icone junto com a descrição para fazer mais sentido.

Realinhamos também todos os blocos de texto para ficar mais harmonioso.

**Comment by jamilatta** [comment]
@caramez 

A imagem não ficou muito boa para avaliarmos, poderia por gentileza enviar a imagem novamente. 

Grato.

**Comment by caramez** [comment]
Feito. Imagem corrigida

**Comment by alexxxmendonca** [comment]
Eu achei que ficou bom.

**Comment by caramez** [comment]
Ajuste realizado.
segue link atulizado
http://scielohomolog.parati.ag/Periodico/homepage.html

Se estiver ok, geramos o zip.
Aguardo.

**Comment by jamilatta** [comment]
@caramez 

Poderia por gentileza nos enviar os .zips para que possamos atualizar a instância de homolog

**Comment by paratiuid** [comment]
Segue link do zip:
http://scielohomolog.parati.ag/scielo-ticket-670.zip

**Comment by jfunez** [comment]
implementando no OPAC
