### ISSUE TITLE
Ajustes na página do artigo

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#672]
Na reunião de 12/07/2017 ficou decidido que devemos incluir o cadeado de acesso aberto do título do artigo. Esse cadeado deve conter um tootip indicando a licença do artigo, assim como o apresentado no http://search.scielo.org

Também decidimos que o icon do creative commons deve ficar no rodapé do artigo (Solicitamos ajuda do designer para a melhor disposição desse icon no rodapé). Também discartamos o uso do icone sugerido no link: http://scielohomolog.parati.ag/Artigo/, levando em conta que esse não é o icon oficial. 

O label da seção do texto completo deve ser alterado, para a esquerda juntamente com a legenda bibliografica que deve estar na mesma linha para que possmos ganhar espaço, conforme consideração enviadas pelo Anurag, ver ticket: https://github.com/scieloorg/opac/issues/651. Novamente peço apoio do designer.

**Comment by paratiuid** [comment]
Pessoal, 
seguem as telas contendo os ajustes.


Abaixo imagens referente ao icone open access com tooltip
![image](https://user-images.githubusercontent.com/22373640/28693251-26812122-72fa-11e7-89a4-484f14b06597.png)

![image](https://user-images.githubusercontent.com/22373640/28693257-2c1e2bf2-72fa-11e7-8851-c117dd4472c9.png)


Abaixo imagem referente ao icone do creative commons no footer
![image](https://user-images.githubusercontent.com/22373640/28693268-3bf0a726-72fa-11e7-844a-b8748123f180.png)


Abaixo imagem referente ao item C.
![image](https://user-images.githubusercontent.com/22373640/28693273-461ea644-72fa-11e7-85ed-0510e8457bc9.png)

![image](https://user-images.githubusercontent.com/22373640/28693282-4a1834a4-72fa-11e7-9de4-b38fa29a6b34.png)

**Comment by paratiuid** [comment]
item C que me referi diz respeito ao alinhamento do label da seção e legenda bibliografica.

**Comment by alexxxmendonca** [comment]
A parte relacionada ao Creative Commons foi aprovada na reunião de 28/07/2017.

A parte da seção e legenda bibliográfica sofreu alterações, que estão descritas no ticket #703.

**Comment by jamilatta** [comment]
Adicionado os estáticos correspondentes a essa tarefa.

Necessário realizar os ajustes de HTML na página do artigo

**Comment by jamilatta** [comment]
Item realizado e disponível no ambiente de homologação.
