### ISSUE TITLE
Altmetrics para periódicos

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/opac#684]
Para recuperar o score por periódicos utilizando a API do altmetrics, utilizar a biblioteca https://github.com/lnielsen/python-altmetric

A URL para periódicos deve ser:

https://www.altmetric.com/api/v1/journals/1y?key=apikey&issns=0104-5970

**Comment by jamilatta** [comment]
Como conversado com a direção ficou decidido que não iremos adicionar métricas no site. Todas as requisição desse tipo deve ser realizado na ferramenta de analítica: https://analytics.scielo.org/
