### ISSUE TITLE
Ícone para corpo editorial

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#692]
Com o advento do link do corpo editorial, é necessário definir um ícone para ele:

![image](https://user-images.githubusercontent.com/4059679/28633442-33394e9e-720a-11e7-8f7f-62f6443e1bde.png)

Sugestão: ícone usado para contato/pessoa.

Afim de manter a consistência no site, penso que também seria necessário incluir o ícone na relação de periódicos:

![image](https://user-images.githubusercontent.com/4059679/28633571-a4081fb0-720a-11e7-90e7-309b31d7badc.png)

**Comment by jamilatta** [comment]
Realizado em: [418556e]
