### ISSUE TITLE
Alterações no botão "Download PDF"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#702]
Após reunião em 28/07/2017, ficou decidido que o botão "Download PDF, ePDF" deve ser desmembrado em 2 botões distintos:

- PDF
- ePDF

Quando houver mais de uma versão/idioma disponível, abrir um menu suspenso para a escolha do usuário.

Quando houver apenas uma única versão, abrir direto o documento, sem o menu suspenso.

Sugiro usar os ícones oficiais dos formatos PDF e ePDF para facilitar a identificação pelo usuário.

**Comment by paratiuid** [comment]
segue a sugestão:

Para o caso de haver mais de um idioma.
![image](https://user-images.githubusercontent.com/22373640/29029563-7a38bcdc-7b5e-11e7-8f48-315e259da630.png)

![image](https://user-images.githubusercontent.com/22373640/29029579-8391eac4-7b5e-11e7-94da-f80c751fad4d.png)

**Comment by jamilatta** [comment]
Está ótimo, porém é possível que sejamos questionados sobre a escalabilidade dos botões, mas acho que devemos nos preocupar com isso no momento que tivermos que escalar para outras opções de download. 

Pode continuar nesse formato.

**Comment by paratiuid** [comment]
@jamilatta 
encontrei um problema ao testar com o tamanho de tela reduzido, no padrão de uso para tablet.
Nesta resolução, tive que ocultar os labels "home" e "PDF" e "ePDF".
Veja como ficou:

![screen shot 2017-08-07 at 2 37 29 pm](https://user-images.githubusercontent.com/22373640/29038511-4c5e9348-7b7e-11e7-95d9-8f13df330f89.png)

**Comment by paratiuid** [comment]
Exemplo de dropdown aberto

![image](https://user-images.githubusercontent.com/22373640/29039128-679d22d0-7b80-11e7-8517-f9761b12629e.png)
