### ISSUE TITLE
Reestruturação da primeira linha do texto completo (Seção, Legenda, DOI)

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#703]
Após reunião em 28/07/2017, ficou decidido que a primeira linha do texto completo deve conter os seguintes componentes:

Seção do artigo, legenda bibliográfica, DOI, botão de copiar DOI.

- Remover o sublinhado da seção e ajustar a opacidade em 75% (deixar mais apagado do que está atualmente, porém um pouco mais visível do que a legenda bibliográfica). Da forma como está atualmente, a seção está com muito destaque. 
- O tamanho da fonte talvez tenha de ser alterado, para ficar compatível com o tamanho da fonte da legenda bibliográfia e DOI.

Com essas alterações, espera-se ganharmos mais espaço no fold e também deixar o destaque para elementos mais importantes, como o título e resumo (ver ticket #672).

**Comment by paratiuid** [comment]
@jamilatta 

segue sugestão de ajuste:

![image](https://user-images.githubusercontent.com/22373640/29043213-8e7f9080-7b90-11e7-9892-c37ffb89bf87.png)

**Comment by alexxxmendonca** [comment]
Não dá para alinhar junto com o sumário? (Abstract...)

**Comment by paratiuid** [comment]
Versão para telas menores

![image](https://user-images.githubusercontent.com/22373640/29043258-c789d89a-7b90-11e7-9a2f-d75ffa793f27.png)

**Comment by paratiuid** [comment]
@alexxxmendonca 
Da sim.
Segue exemplo.
Alinhado a esquerda na mesma linha do abstract.

![screen shot 2017-08-07 at 5 01 38 pm](https://user-images.githubusercontent.com/22373640/29043568-0fd2702a-7b92-11e7-94cf-a668eed56a99.png)

**Comment by paratiuid** [comment]
Alinhado a esquerda na linha do abstract - versão para telas menores.

![screen shot 2017-08-07 at 5 03 06 pm](https://user-images.githubusercontent.com/22373640/29043609-3ec09bb4-7b92-11e7-9477-5bdf64f57f09.png)

**Comment by jamilatta** [comment]
@paratiuid e @alexxxmendonca 

O que vcs acham de deixa centralizado (segunda imagem) sendo que o botão copiar passa a ser somente uma ancora? 

@paratiuid isso que perguntei é possível?

**Comment by paratiuid** [comment]
Segue um ajuste.
Reduzida altura da linha, espaçamento interno dos botões "copy link" e "sobre os autores".

Acredito que essa seja a melhor opção.

Aguardo aprovação.

![screen shot 2017-08-07 at 6 07 00 pm](https://user-images.githubusercontent.com/22373640/29045790-33650b52-7b9b-11e7-9704-d6d29ede25be.png)

**Comment by alexxxmendonca** [comment]
Na verdade, eu quis dizer alinhado ao menu flutuante dos "tópicos" do artigo (Abstract, Fulltext, etc)

**Comment by alexxxmendonca** [comment]
Por ora está OK, mas vamos aguardar a aprovação da Direção.

**Comment by jamilatta** [comment]
@paratiuid acho que esse última opção esta ok.

**Comment by jamilatta** [comment]
@robertatakenaka 

Esse ticket teve alteração de css portando é necessários alteração no XSL. 

Segue as alterações realizadas: https://bitbucket.org/parati_uid/portal-scielo/commits/034ccdab0f7b0411b5b066695630eaff646c953e#chg-Artigo/index.html

**Comment by jamilatta** [comment]
Adicionado os estáticos correspondentes a essa tarefa no commit [https://github.com/scieloorg/opac/pull/713]. 

Necessário realizar os ajustes de HTML na página do artigo.

**Comment by robertatakenaka** [comment]
@paratiuid por gentileza me add no bitbucket roberta.takenaka@scielo.org

**Comment by robertatakenaka** [comment]
@paratiuid Como ficou o visual final? Onde eu poderia ver o resultado do HTML? Pois quero comparar com os HTML gerados a partir das XSL que eu modificar.

**Comment by jamilatta** [comment]
@robertatakenaka 

Ficou fechado a última versão/imagem.

**Comment by jamilatta** [comment]
Item realizado e ajustado em homolog: https://homolog.opac.scielo.org/csp/2017.v33n6/e00035316/#
