### ISSUE TITLE
Alinhar à esquerda ícone da Home do periódico p/ periódicos desindexados

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#704]
Se o periódico não estiver mais indexado na Coleção, o ícone da Home do periódico que aparece na relação de periódicos deve ficar alinhado à esquerda:

![image](https://user-images.githubusercontent.com/4059679/28730334-1ea1b06e-73a6-11e7-968c-e989122ff4e1.png)

**Comment by jamilatta** [comment]
Item realizado e disponível no ambiente de homologação: https://homolog.opac.scielo.org/journals/
