### ISSUE TITLE
Limitar a quantidade de autores apresentados na página do artigo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac#717]

**Comment by robertatakenaka** [comment]
Mostrando até 5 autores, com nomes completos
<img width="713" alt="captura de tela 2017-08-11 as 08 14 03" src="https://user-images.githubusercontent.com/505143/29212103-2a911874-7e73-11e7-88da-8f3b91a52167.png">

Mostrando até 10 autores, nomes completos
<img width="749" alt="captura de tela 2017-08-11 as 08 12 32" src="https://user-images.githubusercontent.com/505143/29212110-2ec32cb6-7e73-11e7-8900-7f6ab9494498.png">

Mostrando até 10 autores, nomes abreviados, ... indicando que há mais autores
<img width="806" alt="captura de tela 2017-08-11 as 08 11 09" src="https://user-images.githubusercontent.com/505143/29212112-31386fa6-7e73-11e7-9785-142f9488f6e7.png">

Mostrando até 10 autores, nomes abreviados, ... indicando que há **+n** autores
<img width="819" alt="captura de tela 2017-08-11 as 08 06 54" src="https://user-images.githubusercontent.com/505143/29212114-33cc564c-7e73-11e7-8a49-1f44445823cd.png">

**Comment by abelpacker** [comment]
Roberta, 

1. Vamos utilizar os nomes completos;

2. Tradicionalmente na lista de nomes de autores, os mais relevantes são o primeiro e o último

3. Então, vamos utilizar a solução da Nature:
Autor-1, [...], Autor-n

ao clicarse [...] se mostra todos os autores Veja por exemplo,

https://www.nature.com/articles/sdata201618

**Comment by jamilatta** [comment]
@paratiuid poderia por gentileza nos ajudar a realizar essa tarefa acredito que javascript seja a melhor opção para isso.

**Comment by jamilatta** [comment]
Item realizado e disponível em homologação.
