### ISSUE TITLE
Implantação do ambiente de homologação do OPAC.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#72]
#### Problema:
Atualmente não existe um ambiente de homologação para que possamos testar um infra-estrutura para o OPAC.

#### Objetivo:

**A idéia é testar a implantação e operação do OPAC**

Pontos que deve ser resolvido nesse ticket:
- Verificar e avaliar uma infra-estrutura mínima para o OPAC.
- Avaliar e definir a estrutura de diretórios bem como a organização dos script.
- Avaliar e definir um servidor web.

#### Observações:
- É necessário acompanhar com a equipe de infra estrutura toda a fase de instalação e implantação. 
- Importante observar e documentar os procedimentos de instalação e implantação.
- Documentar os pontos críticos ou abrir tickets para que passamos resolver.
 
#### Dependências/Impedimentos:
- Para iniciar essa atividade é importante que os testes para os módulos considerados críticos (admin.views, main.views, controller, main.errors, e algumas funções no models) estejam resolvidos.
- Depende de servidor.
- Depende de criar um provisionamento para OPAC.

**Comment by jamilatta** [comment]
Acredito que esse link pode ajudar: https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-centos-7

**Comment by jfunez** [comment]
a tarefa já foi realizada, e a documentação do processo de instalação esta [na wiki do projeto](https://github.com/scieloorg/opac/wiki/Configura%C3%A7%C3%A3o-e-instala%C3%A7%C3%A3o-%28ambiente-de-produ%C3%A7%C3%A3o%29).
