### ISSUE TITLE
Licença "Creative Commons" quebra de layout

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#721]
@paratiuid 

Ao colocarmos a licença "creative commons" na página do artigo identificamos que existe uma quebra do texto.

Ver: 
![screenshot 2017-08-14 09 55 39](https://user-images.githubusercontent.com/373745/29272577-0a3dc156-80d7-11e7-9054-995cb9322b1f.png)

**Comment by jamilatta** [comment]
Link de exemplo: https://homolog.opac.scielo.org/icse/2017.v21n62/543-552/

**Comment by paratiuid** [comment]
Segue correção:

![image](https://user-images.githubusercontent.com/22373640/29326356-9b0db64c-81c1-11e7-84bd-9f2399e3fb8b.png)

**Comment by jamilatta** [comment]
Resolvido.
