### ISSUE TITLE
Adicionar a quantidade de autores quando estiver escondido.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#730]
Recentemente adicionamos a funcionalidade "colapsar" os autores quando a quantidade for maior que 10 autores. 

Na reunião do dia 22/08/2017 ficou decido que devemos adicionar a quantidade total de autores antes de exibir todos.

**Comment by paratiuid** [comment]
@jamilatta 
Segue sugestão...
![2017-09-04-181016_1366x768_scrot](https://user-images.githubusercontent.com/22373640/30038552-7cd28dde-919c-11e7-9750-7ea6d5ee4576.png)

**Comment by jamilatta** [comment]
👍

**Comment by jamilatta** [comment]
Vou aplicar em homolog.

**Comment by jamilatta** [comment]
Apliquei porém não apareceu. 

@paratiuid existe a necessidade de mudanças no HTML para essa atividade?

**Comment by jamilatta** [comment]
Passou a aparecer um botão indesejável, ver: 


<img width="968" alt="screenshot 2017-09-06 10 02 35" src="https://user-images.githubusercontent.com/373745/30113289-9ca48492-92ea-11e7-80de-d7de34405286.png">

O botão copia ao lado do "About the authors", não deveria de aparecer!!!!

**Comment by paratiuid** [comment]
@jamilatta 
Enviamos somente um print como sugestão. Aguardamos aprovação para então codificar.
Sobre o botão vamos efetuar o ajuste.

**Comment by jamilatta** [comment]
@paratiuid 

Estamos de acordo, aprovamos esse formato para exibir a quantidade de autores.

**Comment by paratiuid** [comment]
@jamilatta 
Adicionamos o código. Favor, verificar a branch develop.
Com relação à palavra 'autores' como fazemos com relação aos idiomas?

**Comment by jamilatta** [comment]
Item realizado e disponível no ambiente homologação, exemplo: http://localhost:8000/article/resp/2016.v90/e60001/es/

**Comment by jfunez** [comment]
[Correção] link do exemplo: https://homolog.opac.scielo.org/article/resp/2016.v90/e60001/es/
