### ISSUE TITLE
Adicionar um "label" informando que o arquivo é versão anterior ao do XML.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#731]
Atualmente o site conta com duas versão de artigos uma em XML e outra não XML.

Na reunião do dia 22/08/2017 ficou decidido que devemos term um "label" e solicitamos ajuda para o designer indicando que o artigo é uma versão antiga. 

Exemplo de versão nova: https://homolog.opac.scielo.org/article/csc/2017.v22n6/1943-1954/

Exemplo de versão antiga: https://homolog.opac.scielo.org/article/csc/2001.v6n2/266-267/pt/

**Comment by paratiuid** [comment]
@jamilatta 
Segue como sugestão:
![2017-09-05-173121_1366x768_scrot](https://user-images.githubusercontent.com/22373640/30085645-de9d2502-926d-11e7-9398-9b3cd6ab678b.png)
![2017-09-05-173121_1366x768_scrot 1](https://user-images.githubusercontent.com/22373640/30085644-de9c258a-926d-11e7-9a93-b063fa273615.png)
![2017-09-05-175126_1366x768_scrot](https://user-images.githubusercontent.com/22373640/30085646-de9f4544-926d-11e7-9e2e-42ba596d8545.png)
![2017-09-05-175243_1366x768_scrot](https://user-images.githubusercontent.com/22373640/30085647-dea4d720-926d-11e7-92cf-de789d317621.png)

**Comment by jamilatta** [comment]
Item realizado. 

Definir juntamente com o Abel que iremos colocar o termo **"Artigo no formato de exibição antiga"**.

**Comment by alexxxmendonca** [comment]
Com a decisão de converter todos os artigos em HTML para XML, este ticket tornou-se inválido.
