### ISSUE TITLE
Ajuste da posição do botão flutuante.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#733]
Na reunião do dia 22/08/2017 com a direção ficou acordado que o botão flutuante deve ter sua posição em relação à margem do texto e não da tela. 

Verificamos que se a posição for em realização a tela em dispositivos maiores o botão flutuante fica muito distante do texto, dando a impressão de não ser ações referentes ao texto. 

Também decidimos que o botão flutuante deve ficar mais para para cima, ou seja mais para o meio da tela.

O botão com três pontinhos deve ficar na área do texto e não fora da área do texto

**Comment by paratiuid** [comment]
@jamilatta 
Segue sugestão:
![2017-09-05-112109_1366x768_scrot](https://user-images.githubusercontent.com/22373640/30065863-a11a089e-922c-11e7-9336-e4b3a3b01b3b.png)
![2017-09-05-112136_1366x768_scrot](https://user-images.githubusercontent.com/22373640/30065864-a11b4484-922c-11e7-8b4f-4f444c7e6748.png)

**Comment by jamilatta** [comment]
@paratiuid 

Não seria essa a idéia sugiro conversamos para te explicar melhor.

**Comment by jamilatta** [comment]
@paratiuid 

A atividade esta Ok, o que falta é remover o botão copiar que esta aparecendo do lado dos autores. 

Veja: 

<img width="1110" alt="screenshot 2017-09-19 09 40 25" src="https://user-images.githubusercontent.com/373745/30593461-f953af66-9d20-11e7-9f3f-d22a4dedbe61.png">

**Comment by jamilatta** [comment]
Item realizado e corrigido, sobre o botão **copiar** existe um ticket que descreve melhor o bug: https://github.com/scieloorg/opac/issues/752
