### ISSUE TITLE
Ajuste de divs no transformação do artigo 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#740]
Na página do artigo estamos com um problema de desenho, repare (A área da folha não esta alinhada com o botão "home"): 

<img width="1677" alt="screenshot 2017-09-19 11 25 35" src="https://user-images.githubusercontent.com/373745/30597529-a27fc938-9d2d-11e7-88ea-07de0ee5837b.png">

Identifiquei que estamos estamos duplicando as **divs**: articleCtt e a em seguida **container**, na imagem é possível ver isso. 

Para que seja possível verificar e testar esse ajuste estou enviando o arquivo do article-standalone.css em anexo. 
[standalone.zip](https://github.com/scieloorg/opac/files/1314649/standalone.zip)

**Comment by robertatakenaka** [comment]
Antes:
<img width="1279" alt="captura de tela 2017-09-19 as 13 26 52" src="https://user-images.githubusercontent.com/505143/30603578-57ccbd90-9d3e-11e7-86e3-68149304f485.png">

Depois:
<img width="1276" alt="captura de tela 2017-09-19 as 13 28 41" src="https://user-images.githubusercontent.com/505143/30603653-91e0d002-9d3e-11e7-87e0-d50ab2937408.png">

<img width="1290" alt="captura de tela 2017-09-19 as 13 29 09" src="https://user-images.githubusercontent.com/505143/30603644-8e93274c-9d3e-11e7-8656-e20ab91ab51f.png">

**Comment by jamilatta** [comment]
@robertatakenaka 

Cancela essa alteração consegui resolver removendo da **div** container.
