### ISSUE TITLE
Links do botão flutuante no mobile

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#746]
Percebemos que ao utilizar o site no Ipad identificamos que precisamos clicar duas vezes para que a ação de clique seja executada.

**Comment by jamilatta** [comment]
Isso ainda ocorre para todos os links que tem tooltip. 

Sugiro tentarmos remover os tooltip de todos os componentes quando estivermos utilizando o IPAD.

**Comment by jamilatta** [comment]
Item realizado porém existem vários links com o problema do duplo clique para efetivar a ação. 

@paratiuid poderia por gentileza verificar.

**Comment by paratiuid** [comment]
@jamilatta 
Efetuamos um ajuste no código javascript que detecta se o usuário está em dispositivo mobile para desativar os tooltips. 
Favor verificar.

Atenciosamente.

**Comment by jamilatta** [comment]
Vou verificar! 

Atenciosamente, 

Jamil Atta Junior

**Comment by jamilatta** [comment]
Esse ticket está finalizado a algum tempo.
