### ISSUE TITLE
Problemas com CSS das páginas secundárias

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#749]
@paratiuid o pessoal que cadastra o conteúdo das páginas secundárias encontrou um problema:

Eles inserem um link (sem classe, nem sem estilo) e na exibição aparece com "quebra de linha" (ex: https://opac.scielo.org/journal/csc/about/ lista de links)

Pelo que investiguei, vocês decidiram que todos os links das páginas secundárias deve ter a propriedade: `display: block` após a ancora. 

O certo (IMHO) é remover essa regra, e definir uma nova classe, para pode utilizar somente onde deve ser aplicado explicitamente. Até porque botar uma ancora num parágrafo (o que é habitual) não deveria ser exibido como bloco.

#### Situação atual:
<img width="1680" alt="screenshot 2017-09-26 15 06 18" src="https://user-images.githubusercontent.com/805749/30876698-bf8bfbb4-a2cd-11e7-9009-6b963be2eda3.png">

#### Situação esperada:
<img width="1680" alt="screenshot 2017-09-26 15 06 31" src="https://user-images.githubusercontent.com/805749/30876697-bf87a15e-a2cd-11e7-9e24-89f91728ca9c.png">

**Comment by paratiuid** [comment]
@jfunez 
Foi resolvido como sugerido. A alteração está disponível na branch develop.
Aguardando validação.
Obrigado!

**Comment by jamilatta** [comment]
Item resolvido.
