### ISSUE TITLE
Melhorar a apresentação dos links do artigo no Issue TOC no IPAD

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#769]
Os links do artigo na página do fascículo em muitos momentos tem uma quantidade grande e no IPAD fica estranho. 

Seria interessante que em caso de ser o IPAD colocar esses links na vertical para que fique com uma melhor disposição.

**Comment by jamilatta** [comment]
@paratiuid 

segue a imagem: 

![image1](https://user-images.githubusercontent.com/373745/31622693-e2b80944-b27b-11e7-86c1-f96a6de4d560.PNG)



O ideal nesse caso seria os link para os artigos nos diversos idiomas ficarem um em baixo do outro.

**Comment by paratiuid** [comment]
@jamilatta 
Segue sugestão toggle para mostrar/esconder links.
![2017-10-16-195825_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31637256-a2999eb4-b2ac-11e7-8cc8-5f9166724eb2.png)
![2017-10-16-195831_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31637257-a2c41c48-b2ac-11e7-8e96-f6ecca5943fa.png)

**Comment by paratiuid** [comment]
@jamilatta 
Segue mais uma sugestão.
Atenciosamente.
![2017-10-18-144411_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31731233-29bf1ace-b413-11e7-994c-83faaedcce34.png)
![2017-10-18-144414_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31731235-29f00c2e-b413-11e7-986a-0872651fc20b.png)
![2017-10-18-144526_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31731236-2a1ea016-b413-11e7-8761-7d80be93c525.png)
![2017-10-18-144530_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31731237-2a491ab2-b413-11e7-8782-b58a1724643a.png)

**Comment by jamilatta** [comment]
@paratiuid 

Irei levar essas opções para a equipe e te retorno,
