### ISSUE TITLE
Erro de interface no botões de PDF

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#775]
@paratiuid 

Por gentileza, poderia ajustar esse erro: 

<img width="1354" alt="screenshot 2017-10-17 17 30 08" src="https://user-images.githubusercontent.com/373745/31685226-f96bc7ee-b360-11e7-96a7-3e5426963bd7.png">

**Comment by paratiuid** [comment]
@jamilatta 
Verificamos que as sequência de classes na div que contém o menu difere do arquivo que está no repositório. 
Sugerimos mudar para a sequência "col-lg-1 col-md-2 col-sm-2" como na linha 125 da imagem em anexo e efetuar testes.
Estamos à disposição.
Atenciosamente.

![2017-10-20-201458_1366x768_scrot](https://user-images.githubusercontent.com/22373640/31843829-deb0e612-b5d3-11e7-80d9-d0e4dff318d1.png)

**Comment by jfunez** [comment]
@paratiuid @jamilatta mandei PR ajustando essa linha... só falta validar aí Jamil

**Comment by jamilatta** [comment]
Mesmo realizando a alteração o problema continua: 

<img width="1305" alt="screenshot 2017-10-24 08 50 15" src="https://user-images.githubusercontent.com/373745/31939277-9bea34a6-b898-11e7-876d-c20c857e21a0.png">

**Comment by paratiuid** [comment]
@jamilatta 
Fizemos o seguinte ajuste, como aparece na imagem em anexo, nas linhas 125 e 128, mudando as classe s de "col-lg-1" para "col-lg-2" e na linha 128 de "col-lg-6" para "col-lg-5".
Qualquer dúvida estamos à disposição!

Atenciosamente.

![screenshot from 2017-10-31 19-52-50](https://user-images.githubusercontent.com/22373640/32250929-a4874350-be75-11e7-9b98-909b5b34e520.png)

**Comment by jfunez** [comment]
@jamilatta fiz os ajustes indicados pela @paratiuid aqui: https://github.com/scieloorg/opac/pull/792

**Comment by jfunez** [comment]
@paratiuid o problema ainda não foi resolvido:

link: https://homolog.opac.scielo.org/article/rsp/2016.v50/8/es/

<img width="1680" alt="screenshot 2017-11-01 15 27 10" src="https://user-images.githubusercontent.com/805749/32287855-dbf2d368-bf10-11e7-87e7-0cacff8a4fa1.png">

**Comment by paratiuid** [comment]
@jamilatta e @jfunez 

Encontrei 2 erros que causam o problema de layout na página do Artigo na homolog da Scielo. São eles:


**Problema 1:** 

No corpo do artigo, a ordem correta de divs é a seguinte:

...
section class="levelMenu"
section class="articleCtt"
	div class="container"
		div class="articleTxt"



O código que está no homolog.opac.scielo.org contém alguns divs a mais. O que acaba causando um desalinhamento da "folha" do artigo.

...
section class="levelMenu"
section class="articleCtt"
	div class="container"
		div id="standalonearticle"       ------> retirar
			section class="articleCtt"   ------> retirar
				div class="container"    ------> retirar
					div class="articleTxt"


**Problema 2:**

A div que contém os botões de PDF, está com uma classe errada:

Como está hoje na homolog da scielo:
col-lg-2 col-md-2 col-sm-4 hidden-md

Como deve ser:
col-lg-3 col-md-2 col-sm-4 hidden-md

**Comment by jfunez** [comment]
@paratiuid @jamilatta 
vou realizar as modificações... já já envio um novo PR

**Comment by jfunez** [comment]
PR com o fix: https://github.com/scieloorg/opac/pull/795 (cc @jamilatta )
