### ISSUE TITLE
Espaçamento nas âncoras nas páginas secundárias

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#776]
Atualmente nas páginas secundárias, ao clicar nos links das seções (Sobre o periódico, Corpo editorial e Instruções aos autores) o conteúdo inicial é escondido pelo menu flutuante.

O código requer um tratamento para que, quando houver âncora, a página deve cair um pouco antes de onde está a âncora. Dessa forma, o menu superior flutuante não esconde o conteúdo inicial.

**Comment by alexxxmendonca** [comment]
Exemplo:

![image](https://user-images.githubusercontent.com/4059679/31785269-6514abd6-b4e3-11e7-9360-80a87d978e31.png)

Reparem que o menu suspenso está acima da linha onde começa o "Corpo editorial":

![image](https://user-images.githubusercontent.com/4059679/31785294-7672bdaa-b4e3-11e7-85aa-db131f40e974.png)

**Comment by paratiuid** [comment]
@alexxxmendonca , @jamilatta 
Fizemos o ajuste para resolver esta questão da seguinte forma:
- Colocamos uma âncora vazia acima do h2 (título do link) para usarmos como referência para a margem superior (60px). Isto foi feito baseado na solução do artigo onde o menu flutuante também ficava encobrindo os links.
Estamos à disposição!
Atenciosamente.

**Comment by alexxxmendonca** [comment]
👍

**Comment by jamilatta** [comment]
👍
