### ISSUE TITLE
Endereço do periódico nas páginas secundárias

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#777]
Incluir no rodapé das páginas secundárias o endereço do periódico. 

![image](https://user-images.githubusercontent.com/4059679/31769213-77340050-b4b1-11e7-9dd6-4bb966276bb7.png)

**Comment by paratiuid** [comment]
@alexxxmendonca 
Fizemos a inclusão dos blocos html que contêm as informações de endereço no rodapé das páginas dentro do diretório "/Colecao". A atualização já está na branch develop.

Qualquer dúvida estamos à disposição!
Atenciosamente.
