### ISSUE TITLE
Link "Contato" do periódico

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#778]
O link "Contato" nas páginas do periódico deve abrir um modal com um formulário simples para contato com o periódico.

Campos do formulário:

- Nome
- E-mail
- Mensagem

Incluir Captcha por segurança.

As mensagens devem ser enviadas para o e-mail do periódico cadastrado na base (SciELO/Journal Manager); se houver mais de um e-mail cadastrado, enviar para todos.

![image](https://user-images.githubusercontent.com/4059679/31769555-f339901a-b4b2-11e7-9d56-6da763e871dd.png)

**Comment by paratiuid** [comment]
@alexxxmendonca 
Adicionamos o modal como especificado (página /Periodico/atual.html) usando o google recaptcha.
Para configurá-lo no domínio correto e gerar as chaves com a conta google, basta seguir o passo a passo oficial:
https://developers.google.com/recaptcha/intro

Estamos à disposição.
Atenciosamente.

![screenshot from 2017-10-21 20-37-17](https://user-images.githubusercontent.com/22373640/31856493-20c8542c-b6a1-11e7-8e55-99ba27a763ca.png)

**Comment by alexxxmendonca** [comment]
É possível alterar o título da janela e incluir o título do periódico?

Algo como "Entre em contato com Memórias do Instituto Oswaldo Cruz".

Apenas para contextualizar o usuário.

**Comment by paratiuid** [comment]
@alexxxmendonca 
Sim, com certeza. Bastaria ser alterado o texto na linha 511 como na imagem abaixo.
A nossa dúvida é se você se refere a tornar dinâmico, dependendo da página que o usuário estiver, o título do modal seria respectivo a mesma.
Se você estiver solicitando esta alteração, a nossa ideia seria abrir o modal com uma função javascript passando como parâmetro o texto do título. Claro, para este caso em específico.

Estamos à disposição!
Atenciosamente.
![screenshot from 2017-10-23 11-31-04](https://user-images.githubusercontent.com/22373640/31891798-30f58662-b7e6-11e7-946d-f4c3f26d3d24.png)

**Comment by alexxxmendonca** [comment]
Sim, a ideia é que seja dinâmico.

Grato pelas orientações.

**Comment by paratiuid** [comment]
@alexxxmendonca 
Efetuamos a alteração e já publicamos na branch develop.
Para acrescentar o título do modal de acordo com a página, basta adicionar um atributo (chamado data-modal-title="...") na âncora que dispara a abertura do mesmo. 
Como segue na imagem, linha 95.

Qualquer dúvida estamos à disposição!
Atenciosamente.

![screenshot from 2017-10-23 12-27-17](https://user-images.githubusercontent.com/22373640/31894787-25e20f22-b7ee-11e7-8bf0-73da49136962.png)

**Comment by paratiuid** [comment]
@jamilatta 

tenho duas dúvidas referente a esse ticket:

1 - onde deve ficar o html do modal?

2 - onde eu incluo  o script do google, responsável por renderizar o captcha?

Para entender melhor minhas dúvidas, você pode acessar um commit antigo, onde esse ticket já havia sido resolvido. 
Lá, foi incluido a linha:
<script src='https://www.google.com/recaptcha/api.js'></script>

e o html:
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-hidden="true">
+			<div class="modal-dialog">
+				<div class="modal-content">
+					<div class="modal-header">
+						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
+						<h4 class="modal-title">Contato</h4>
+					</div>
+					<div class="modal-body">
+						<div class="form-group">
+							<label class="control-label">Seu Nome</label>
+							<input type="text" name="nome" value="" class="form-control" placeholder="Digite seu nome" />
+						</div>
+						
+						<div class="form-group">
+							<label class="control-label">Seu e-mail</label>
+							<input type="text" name="email" value="" class="form-control" placeholder="Digite seu email" />
+						</div>	
+
+						<div class="form-group">
+							<label class="control-label">Mensagem</label>
+							<textarea name="mensagem" class="form-control" placeholder="Digite sua mensagem"></textarea>
+						</div>
+
+						<div class="form-group">
+							<div class="g-recaptcha" data-sitekey="6LejVjUUAAAAABU6P_loTY7IAPg6JaQOxLaZug5l"></div>
+						</div>
+
+						<div class="btn-block">
+							<input type="button" value="Enviar Mensagem" class="btn btn-primary">
+						</div>
+					</div>
+					<div class="modal-footer">
+						
+					</div>
+				</div>
+			</div>
+		</div>

referentes a criação do modal.

Aguardo.

**Comment by jamilatta** [comment]
@paratiuid 

Respondendo suas as perguntas: 

1 - onde deve ficar o html do modal?

Adicionar um novo template em: **opac/webapp/templates/journal/includes**, chamado **contact.html**. 

E realizar o include desse novo arquivo no base.html das páginas do periódicos: **opac/webapp/templates/journal/base.html**

Repare que estamos garantindo que esse modal de contato será somente no nível de periódico, isso justifica o fato de adicionarmos abaixo do path "journal".

2 - onde eu incluo o script do google, responsável por renderizar o captcha?

É necessário adicionar o arquivo na pasta: **opac/webapp/static/js**

e adicionar uma nova linha no arquivo: **gulpfile.js**, dessa forma teremos o código do captcha no **scielo-bundle-min.js**. 

![screenshot 2018-04-06 14 04 21](https://user-images.githubusercontent.com/373745/38434065-75303464-39a3-11e8-8642-68abb70b4c5b.png)

Qualquer dúvida estou a disposição.

**Comment by jamilatta** [comment]
**Importante:** Manter o mesmo padrão de interface do formulário de "Share email".

**Comment by jamilatta** [comment]
Ambiente de homologação atualizado com esse atividade.

@alexxxmendonca 

Caso esteja tudo bem com esse desenvolvimento, por gentileza, fechar esse ticket.

**Comment by alexxxmendonca** [comment]
Creio que o texto "Entrar em contato com..." deva mostrar o título do periódico ao invés do nome do publicador.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Ok irei realizar essa alteração.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Ajuste realizado, poderia por gentileza, validar novamente.

**Comment by alexxxmendonca** [comment]
@jamilatta está ok, mas o Abel questiona que o ideal será condicionar a disponibilização do link para os periódicos que autorizarem o serviço. 

É possível fazermos isso?

**Comment by jamilatta** [comment]
Sim podemos adicionar um opção no admin para permitir o envio para o periódico ou não.

Mas para o caso do periódico não aceitar receber e-mails qual seria a nossa solução na interface removemos o link de contato ou enviamos para as páginas secundárias do periódico ou ainda mantemos o formulário e os e-mails para os periódicos que não querem receber e-mails enviamos para a conta do SciElO?

Preciso dessas respostas para finalizar essa atividade! 

Podemos conversar sobre esse assunto ainda hoje? 

Jamil Atta Júnior 

Em 9 de mai de 2018, à(s) 08:06, alexxxmendonca <notifications@github.com> escreveu:

**Comment by alexxxmendonca** [comment]
Resposta do Abel:

"Duas opções - link ativado ou não. Tudo o demais não temos controle. O contato para o SciELO deve estar no rodapé ou nos abouts. E deve sempre que possível estar contextualizados prioritariamente na operação da interface e não dos conteúdos. "

**Comment by jamilatta** [comment]
Atividade realizada.
