### ISSUE TITLE
ajustar dependência: packtools, para a versão oficial

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#78]
#### Problema:

O OPAC depende do packtools, em particular do utilitário: HTMLGenerator para gerar as paginas dos artigos. Essa dependência esta apontando ao branch no qual estava sendo desenvolvido.

#### Objetivo:

Ajustar no requirements.txt e wiki para que seja instalada o release oficial (versão: 0.9.0dev-20160202) que contém o HTMLGenerator.

#### Obs:

Segue anuncio do release, com informação da versão:
```
Pessoal,

Está disponível um release de desenvolvimento do packtools que contém
o utilitátio `htmlgenerator` que gera -- advinhem só -- a versão HTML
do documento XML que será publicada na nova versão do site SciELO.

Eu gostaria de convidá-los a testar esse utilitário e contribuir
reportando eventuais erros.

A instalação pode ser feita com o comando ``pip install
"packtools==0.9.0dev-20160202"``


Abraço,
-Gustavo
```

**Comment by ednilson** [comment]
Ajustes no Wiki realizado. 
Foi removida a instrução para instalação do packtools via line command, sendo que este agora faz parte do requirements.txt. Aguardando apenas aprovação do PR #86

**Comment by jfunez** [comment]
incorporado em https://github.com/scieloorg/opac/pull/86
