### ISSUE TITLE
Logo aparece colado no topo da página

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#789]
## Situação atual:

![screenshot 2017-10-30 15 51 52](https://user-images.githubusercontent.com/805749/32186815-eb149d1c-bd81-11e7-9fd6-500605a3a0b7.png)

## Trocando o css:

`.brandLogo h1` desabilitando a propriedade `margin`

![screenshot 2017-10-30 15 52 59](https://user-images.githubusercontent.com/805749/32187434-d6b5b052-bd83-11e7-8819-6334c92ee5a0.png)

**Comment by paratiuid** [comment]
@jfunez @jamilatta 
Fizemos o ajuste como reportado adicionando uma nova classe que remove a margem.
Como na imagem abaixo, linha 28, basta adicionar a classe a tag h1.
Qualquer dúvida estamos à disposição!

Atenciosamente.

![screenshot from 2017-11-01 12-33-37](https://user-images.githubusercontent.com/22373640/32279925-2fd0e624-bf01-11e7-828f-e498d503f345.png)

**Comment by jfunez** [comment]
@jamilatta @paratiuid vou aplicar e mando PR já já

**Comment by jamilatta** [comment]
OK
