### ISSUE TITLE
requisição indesejada na listagem de periódicos (js legado)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#791]
@paratiuid 

identificamos que quando é feita uma busca na listagem de periódicos é disparada 2 requisições ajax que geram um erro http 405 (método não permitido) por tentar fazer um `POST` na url: `/journals/`.

A seguir as informações do erro e onde localizar o ajax...
pelo visto esse código JS vem resistindo desde os primeiros JS (main.js?) dos mockups... o certo é remover ele.

## Requisições: 
<img width="1066" alt="screenshot 2017-10-31 16 17 55" src="https://user-images.githubusercontent.com/805749/32241823-e8401688-be4f-11e7-80cc-d366d494a493.png">

## stacktrace com a localização da chamada:

- as primeiras duas requisições (GET 200 OK) são as que nós fizemos para obter os dados do backend;
- as últimas duas requisições (POST 405) tem origem no JS legado.

<img width="1680" alt="screenshot 2017-10-31 16 22 05" src="https://user-images.githubusercontent.com/805749/32241852-fb627986-be4f-11e7-8766-65f47b56be1f.png">

## Passos para reproduzir o erro:

1. Acessar: https://homolog.opac.scielo.org/journals/ ;
2. abrir o Developer Tools / Firebug na aba: network ;
3. fazer uma busca na listagem (pelo menos 3 letras) ;
4. (aguardar um pouco) O erro deve aparecer no Developer Tools/Firebug com o erro.

**Comment by paratiuid** [comment]
@jfunez 
Realizamos o ajuste adicionando uma condição para evitar requisições ajax sem uma 'action' definida.
Solicitamos que realizem os testes e nos informem se o problema foi sanado.

Atenciosamente.

**Comment by jfunez** [comment]
👍 vou testar

**Comment by jfunez** [comment]
@paratiuid 
Acredito que possamos dar uma outra solução, pois pelo que vi o código da requisição não foi removido.
O que acham?

**Comment by paratiuid** [comment]
@jfunez 
Realizamos o desacoplamento do código js que efetuava as chamadas ajax (post) do arquivo main.js que é minificado para gerar o arquivo scielo-bundle. 
A alteração encontra-se na branch "homolog". 
Solicitamos que realizem os testes e nos informem se o problema foi sanado.

Atenciosamente.

**Comment by jfunez** [comment]
Ótimo @paratiuid !!
Vou proceder com os testes e confirmar para vocês...

**Comment by gustavofonseca** [comment]
Não são mais realizadas requisições ajax durante o carregamento da lista alfabética.
