### ISSUE TITLE
Corrigir grafia do índice "Título" na busca

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#800]
"Título" está com a grafia errada nos índices de busca ("Títutlo"):

![image](https://user-images.githubusercontent.com/4059679/32943187-7157bae6-cb72-11e7-8a33-3037cc3c780a.png)

**Comment by jamilatta** [comment]
@alexxxmendonca iriemos corrigir

**Comment by jamilatta** [comment]
@alexxxmendonca por gentileza validar: https://homolog.opac.scielo.org/ (homologação).

**Comment by alexxxmendonca** [comment]
Testado e aprovado em https://homolog.opac.scielo.org/
