### ISSUE TITLE
"Números recentes" - apenas periódicos ativos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#802]
Nesta faixa devem ser incluídos somente os periódicos ativos. Os descontinuados devem ser excluídos desta lista. 

Incluir somente os publicados nos últimos 90 meses. Data de publicação no SciELO. 

Critério de ordenação: do mais recente a mais antigo. Ordem alfabética por título se aplica somente quando as datas coincidem.

**Comment by jamilatta** [comment]
Pessoal estou iniciando essa atividade.

**Comment by jamilatta** [comment]
@alexxxmendonca poderia, por gentileza, validar em homolog: https://homolog.opac.scielo.org/

**Comment by alexxxmendonca** [comment]
Testado e aprovado em https://homolog.opac.scielo.org/
