### ISSUE TITLE
"Artigos recentes" - apenas periódicos ativos.

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#803]
Nesta faixa devem ser incluídos somente os periódicos ativos. Os descontinuados devem ser excluídos desta lista.

Incluir somente os publicados na última semana e até 90 dias. Data de publicação no SciELO. 

Critério de ordenação: do mais recente a mais antigo. Ordem alfabética por título se aplica somente quando as datas coincidem.

**Comment by alexxxmendonca** [comment]
Rever com o Abel.

**Comment by alexxxmendonca** [comment]
Confirmei com o Abel e a solução é remover a faixa "Artigos recentes".

Posteriormente, podemos avaliar como deixar mais evidente que o periódico foi descontinuado. Mas isso em outro ticket.

**Comment by alexxxmendonca** [comment]
![image](https://user-images.githubusercontent.com/4059679/52628080-f7952280-2e9d-11e9-9530-17a0ccc09f08.png)

**Comment by jamilatta** [comment]
Garantir que apenas os periódicos ativos tenham a faixa de **"Artigos mais recentes"**.

**Comment by patymori** [comment]
@alexxxmendonca, está disponível no ambiente de homologação. Pode verificar se está OK?

**Comment by alexxxmendonca** [comment]
@patymori testado e aprovado em homologação.
