### ISSUE TITLE
CSC: número mais recente não condiz com o atual

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#807]
O periódico **Ciência & Saúde Coletiva** já tem disponível o número v22n10, mas na lista de periódicos aparece que o fascículo mais recente é o v22n9.

![image](https://user-images.githubusercontent.com/4059679/33122921-c547f0a8-cf5f-11e7-8129-e9dd7624b6b9.png)

**Comment by jamilatta** [comment]
@alexxxmendonca 

Vou verificar!

**Comment by jamilatta** [comment]
@alexxxmendonca após o processamento é possível verificar que o número mais recente na lista alfabética está corrigido. 

Ver Grade: https://www.scielosp.org/grid/csc/

Lista alfabética: https://www.scielosp.org/journals/

**Comment by alexxxmendonca** [comment]
Ok! Obrigado 👍
