### ISSUE TITLE
Ícone do ORCID não aparece 

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#812]
O ícone do ORCID não está aparecendo nas afiliações:

https://scielosp.org/article/scol/2017.v13n1/19-34/es/#

Tanto na afiliação individual quanto no quadro de todos os autores.

**Comment by robertatakenaka** [comment]
@jamilatta @jfunez me parece que é quebra em CSS. Vocês cuidam disso?

<img width="526" alt="captura de tela 2017-11-28 as 08 37 19" src="https://user-images.githubusercontent.com/505143/33315315-81cc14fa-d417-11e7-86fd-7c54666ae81b.png">

**Comment by jamilatta** [comment]
@robertatakenaka 

Poderia por gentileza nos indicar aonde esta olhando esse link? para que possamos verificar com o designer!

**Comment by jamilatta** [comment]
@robertatakenaka 

Encontrei. Pelo que vi esta faltando o icone!

<img width="1680" alt="screenshot 2017-11-28 10 45 22" src="https://user-images.githubusercontent.com/373745/33320401-4195c87e-d429-11e7-9e58-2c304520ee8f.png">

Estou com um PR em andamento de aprovação já irei adicionar esse item.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia por gentileza validar: https://homolog.opac.scielo.org/article/scol/2017.v13n1/19-34/es/#ModalTutors

**Comment by alexxxmendonca** [comment]
Aprovado! 👍
