### ISSUE TITLE
Telefone do periódico no endereço

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#818]
O endereço do periódico atualmente não exibe o telefone. O telefone é mais uma forma de entrar em contato com o periódico tanto pela Equipe SciELO quanto por leitores do site.

Pensar numa maneira de incluir também esse dado junto ao endereço do periódico.

**Comment by paratiuid** [comment]
@alexxxmendonca 

segue sugestão
![screen shot 2019-02-21 at 3 36 08 pm](https://user-images.githubusercontent.com/22373640/53192971-84eb1c00-35ee-11e9-9b02-20197ed7da4a.png)

**Comment by alexxxmendonca** [comment]
@paratiuid aprovado.

**Comment by patymori** [comment]
@alexxxmendonca, este dado não está disponível para exibir no site. É necessário alterar o backend para que o dado fique visível, OK?

**Comment by alexxxmendonca** [comment]
@patymori ok, pelo menos já temos o design.

**Comment by alexxxmendonca** [comment]
Resolvido:
![image](https://user-images.githubusercontent.com/4059679/116889567-15780a80-ac03-11eb-9b54-d4a431ad1090.png)
