### ISSUE TITLE
Melhorar legibilidade do "Scientific Electronic Library Online" no logo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#822]
A legenda "Scientific Electronic Library Online" no logo não está muito legível.

![image](https://user-images.githubusercontent.com/4059679/33331280-54e13f52-d448-11e7-8930-32609dc39630.png)

Aumentar o tamanho da fonte.

**Comment by paratiuid** [comment]
seguem sugestões:

fonte tamanho 14px, como está agora:
![image](https://user-images.githubusercontent.com/22373640/33331423-b034c1bc-d448-11e7-8487-6c31ea71f8fa.png)

fonte tamanho 15px:
![image](https://user-images.githubusercontent.com/22373640/33331438-bad7d50a-d448-11e7-8f79-98cfb0c25706.png)

fonte tamanho 16px:
![image](https://user-images.githubusercontent.com/22373640/33331448-c431815a-d448-11e7-9051-d287d0c2cde9.png)

Aguardo retorno.

**Comment by alexxxmendonca** [comment]
É difícil avaliar, pois no meu navegador o comportamento é diferente. 

O print de "como está agora" é bem diferente do que eu vejo (ver print que eu postei).

Vamos alterar para 15px e ver como fica.

**Comment by paratiuid** [comment]
@alexxxmendonca 
a imagem que você postou está ainda no antigo formato (imagem).

As imagens que postei estão no novo formato (html + svg).
Acredito que somente esta mudança de formato ja melhore a leitura.

Eu sugiro testar o formato html + svg antes de fazermos uma alteração.
O que você acha?

**Comment by alexxxmendonca** [comment]
Acho que já está como texto:

![image](https://user-images.githubusercontent.com/4059679/33332424-61e7fe54-d44b-11e7-9ad5-ebb2055a081f.png)

**Comment by jamilatta** [comment]
Srs, essa mudança do .svg já esta disponível no: http://www.scielosp.org
