### ISSUE TITLE
Alterar ordem dos logos das instituições fomentadoras

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#823]
Permitir alterar no backoffice a ordem dos logos das instituições fomentadoras:

![image](https://user-images.githubusercontent.com/4059679/33332216-cadf459e-d44a-11e7-86f7-675e99195daa.png)

**Comment by jfunez** [comment]
Fechando porque esta duplicado (https://github.com/scieloorg/opac/issues/422)
