### ISSUE TITLE
Texto de financiamento truncado

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#827]
- Nome: @alexxxmendonca 
- Tipo: Defeito
- Descrição: Texto de financiamento truncado
- URL: https://www.scielosp.org/article/gs/2017.v31n3/253-254/

**Comment by patymori** [comment]
@paratiuid , tudo bem?

Para os casos onde o "label" de Notas é uma letra ou número, está OK, como neste caso:

![screen shot 2018-12-03 at 17 39 22](https://user-images.githubusercontent.com/18053487/49397451-c45a4880-f722-11e8-87ba-c0b956fa958d.png)

Porém, em casos como o do artigo aqui citado, o texto da tag é maior. Segue aqui um outro caso:

https://opac.scielo.org/article/gs/2017.v31n3/269-272/

![screen shot 2018-12-03 at 17 43 46](https://user-images.githubusercontent.com/18053487/49398013-472fd300-f724-11e8-913c-cd585670c359.png)

**Comment by paratiuid** [comment]
O que vocês acham de quebrar cada elemento em uma linha?
dessa maneira ficaria mais organizado.

Posso ainda aproximar mais os dois tópicos para eliminar esse espaço em branco que ficou.

Para isso, eu criaria uma classe de css exclusiva para aquele bloco.

![screen shot 2018-12-06 at 11 33 48 am](https://user-images.githubusercontent.com/22373640/49596233-feb12900-f960-11e8-926b-428e955c23fc.png)

Aguardo.

**Comment by jamilatta** [comment]
@patymori 

O que acha?

**Comment by patymori** [comment]
@paratiuid, acho que poderia eliminar mesmo o espaço em branco. @alexxxmendonca , pode validar?

**Comment by paratiuid** [comment]
@jamilatta @patymori @alexxxmendonca 
Ajustei os espaços em branco.
Vejam o que acham.

![screen shot 2018-12-06 at 4 52 06 pm](https://user-images.githubusercontent.com/22373640/49605346-5fe3f700-f977-11e8-9c58-38dab9a33dbf.png)

**Comment by alexxxmendonca** [comment]
Sim, diminuindo o espaço em branco ficou bem melhor.

Aprovado.

**Comment by patymori** [comment]
@alexxxmendonca e @paratiuid , continuamos no aguardo desta correção.

**Comment by patymori** [comment]
@alexxxmendonca, feita atualização da nova versão. Pode verificar em new.scielo.br? Peço desculpas mas não encontrei exemplos em BR onde essa situação ocorre.

**Comment by alexxxmendonca** [comment]
Testado e aprovado:

![image](https://user-images.githubusercontent.com/4059679/51334170-6a110f00-1a66-11e9-9262-16ccf86c0776.png)

https://new.scielo.br/article/abcd/2019.v32n1/e1417/pt/
