### ISSUE TITLE
Alterar texto “Número mais recentes” para “Números mais recentes”

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#828]
- Nome: @alexxxmendonca
- Tipo: Defeito
- Descrição: Alterar texto “Número mais recentes” para “Números mais recentes” (verificar nos 3 idiomas)
- URL: https://opac.scielo.org/

**Comment by alexxxmendonca** [comment]
Corrigido em PT.

Compatibilizar em ES: **Números** más recientes
Compatibilizar em EN: Latest **issues**

**Comment by jfunez** [comment]
Transifex atualizado, falta revisar e atualizar as traduções e atualizar no site

**Comment by patymori** [comment]
@alexxxmendonca, feita atualização da nova versão. Pode verificar em new.scielo.br?

**Comment by alexxxmendonca** [comment]
testado e aprovado!
