### ISSUE TITLE
RSS do Blog SciELO em Perspectiva não mostra os posts mais recentes (está desatualizado)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#829]
- Nome: @alexxxmendonca
- Tipo: Defeito
- Descrição: RSS do Blog SciELO em Perspectiva não mostra os posts mais recentes (está desatualizado)
- URL: https://opac.scielo.org/

**Necessário incluir no script de processamento (opac proc) a importação de blog e press release.**

**Comment by robertatakenaka** [comment]
@alexxxmendonca : Qual é a periodicidade de atualização do Blog?

**Comment by alexxxmendonca** [comment]
Publicamos no mínimo 1 post por semana (às vezes mais de um).

**Comment by robertatakenaka** [comment]
@alexxxmendonca 
Efetuado a importação manual dos itens do blog


@jamilatta @patymori 
Necessário incluir no script de processamento (opac proc) a importação de blog e press release.

**Comment by alexxxmendonca** [comment]
Fechando esse ticket pois o problema já foi resolvido.

**Comment by alexxxmendonca** [comment]
Reabrindo o ticket pois o problema voltou a acontecer.

O problema ocorre nos RSS do Blog e do Press Releases.

**Comment by patymori** [comment]
@alexxxmendonca, o problema está ocorrendo em BR e Saúde Pública?

**Comment by alexxxmendonca** [comment]
@patymori somente BR.

**Comment by carolinatanigushi** [comment]
Esse problema parece ter sido resolvido; os feeds estão atualizados para os blogs Geral e Press Releases.
