### ISSUE TITLE
Texto “About SciELO Saúde Pública” não está traduzindo o “Saúde Pública” para o EN. Mesma coisa acontece no ES

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#830]
- Nome: Amanda Ramalho
- Tipo: Tradução
- Descrição: Texto “About SciELO Saúde Pública” não está traduzindo o “Saúde Pública” para o EN. Mesma coisa acontece no ES.
- URL: https://opac.scielo.org/

**Comment by alexxxmendonca** [comment]
Corrigido.
