### ISSUE TITLE
Janela modal mostra que há versões em PT e EN do artigo, mas tais versões não existem

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#833]
- Nome: @alexxxmendonca
- Tipo: Defeito
- Descrição: Janela modal mostra que há versões em PT e EN do artigo, mas tais versões não existem
- URL: 
  - https://opac.scielo.org/article/csp/2017.v33suppl2/e00047517/#ModalVersionsTranslations
  - https://opac.scielo.org/article/rsp/2017.v51suppl1/10s/en/#ModalVersionsTranslations (exemplo de artigo com versões em PT e EN)

**Adendo de Carolina Tanigushi**:
> Mesmo quando existem as versões traduzidas, ao clicar no link, ele não redireciona para a tradução do artigo; ficando no idioma em que já estava.

**Comment by patymori** [comment]
@alexxxmendonca , feita correção na nova versão. Poderia validar em https://new.scielo.br/?

Obrigada.

**Comment by alexxxmendonca** [comment]
Testado e aprovado!

**Comment by jamilatta** [comment]
@alexxxmendonca e @patymori 

Estou verificando esse desenvolvimento e me parece que o problema persiste, vejam nos links: 

https://opac.scielo.org/article/csp/2017.v33suppl2/e00047517/#ModalVersionsTranslations

https://opac.scielo.org/article/rsp/2017.v51suppl1/10s/en/#ModalVersionsTranslations

**Comment by gustavofonseca** [comment]
> https://opac.scielo.org/article/csp/2017.v33suppl2/e00047517/#ModalVersionsTranslations

Este documento agora responde pela URL https://new.scielo.br/j/csp/a/MFcTxF6hPm9MPVMpFFMz5QR, e o problema não ocorre mais.
