### ISSUE TITLE
Na interface em espanhol alterar Saúde Pública en números para Salud Pública en números e na em inglês para Public Health

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#834]
- Nome: Javani Araujo
- Tipo: Defeito
- Descrição: Na interface em espanhol alterar `Saúde Pública en números` para `Salud Pública en números` e na em inglês para `Public Health`
- URL: https://opac.scielo.org/

**Comment by alexxxmendonca** [comment]
Corrigido.
