### ISSUE TITLE
Na “Lista Temática de Periódicos”, ao tentar mudar o idioma da página, ele muda para a Lista Alfabética.

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#835]
- Nome: Amanda Ramalho
- Tipo: Defeito
- Descrição: Na “Lista Temática de Periódicos”, ao tentar mudar o idioma da página, ele muda para a Lista Alfabética.
- URL: https://opac.scielo.org/journals/#theme

**Comment by patymori** [comment]
@alexxxmendonca e @amandasramalho, feita correção na versão nova. Poderia validar em https://opac.scielo.br/journals?

Obrigada

**Comment by alexxxmendonca** [comment]
Testado e aprovado.

As áreas estão sempre em inglês, é isso mesmo?


Agricultural Sciences (39)
Applied Social Sciences (39)
Biological Sciences (28)
Engineering (21)
Exact and Earth Sciences (10)
Health Sciences (93)
Human Sciences (88)
Linguistics, Letters and Arts (15)

**Comment by patymori** [comment]
@alexxxmendonca, neste momento está somente em inglês. Vamos abrir um ticket para corrigir este problema específico. Estou encerrando este.
