### ISSUE TITLE
Link no feed de noticias

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#836]
- Nome: @alexxxmendonca 
- Tipo: Sugestão
- Descrição: No RSS de Notícias na página do periódico, repetir comportamento do RSS do press release de tornar toda a área sensível ao clique, e não apenas o link “continue lendo”:
- URL: https://opac.scielo.org/journal/csp/

**Comment by patymori** [comment]
@alexxxmendonca, pode verificar no ambiente de homologação?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
