### ISSUE TITLE
Não aparecer na lista de últimos números publicados, periódicos descontinuados da coleção

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#837]
- Nome: Javani Araujo
- Tipo: Sugestão
- Descrição: Não aparecer na lista de últimos números publicados, periódicos descontinuados da coleção
- URL: -

**Comment by alexxxmendonca** [comment]
A lista de últimos números publicados foi removida do site e, portanto, este ticket perdeu a validade.
