### ISSUE TITLE
Links dos resumos vão diretamente para o texto (mas não necessariamente para o resumo do idioma indicado)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#838]
- Nome: Cinthia Vieira
- Tipo: Defeito
- Descrição: Links dos resumos vão diretamente para o texto (mas não necessariamente para o resumo do idioma indicado)
- URL: https://opac.scielo.org/article/rbepid/2017.v20n2/189-199/en/?abstract_lang=pt

**Comment by alexxxmendonca** [comment]
Esse problema não foi corrigido?

**Comment by alexxxmendonca** [comment]
A forma de apresentação dos resumos foi totalmente reformulada para contemplar a indexação no Google Scholar.

Este ticket perdeu a validade, portanto.

Ver #1762
