### ISSUE TITLE
Mudar layout do menu suspenso no canto inferior à esquerda

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#839]
- Nome: Cinthia Vieira
- Tipo: Sugestão
- Descrição: Mudar layout do menu suspenso no canto inferior à esquerda (talvez deixar “em pé”), e manter o menu na página até o fim dela, não somente enquanto há texto
- URL: -

**Comment by jamilatta** [comment]
@alexxxmendonca 

Estou tentando entender do que se trata esse ticket!

**Comment by alexxxmendonca** [comment]
@jamilatta acho que é o menu flutuante e acho que podemos fechar.

**Comment by jamilatta** [comment]
Ah sim! Podemos fechar sim.
