### ISSUE TITLE
Carga de documentos utilizando o **Article Meta**.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#84]
#### Problema:
Atualmente estamos testando e utilizando o OPAC em ambiente de desenvolvimento com uma massa de dados bastante pequena em comparação com o volume da dados que a aplicação deve atender. Hoje trabalhamos com um escopo de ~18 periódicos sendo que a aplicação deve trabalhar (se considerarmos os números atuais) com 344 periódicos.

#### Objetivo:
O objetivo desse atividade é criar uma forma de inserir uma massa de dados que seja equivalente com a quantidade de dados que a aplicação irá atender, para que possamos em fase de desenvolvimento identificar: **problemas de performance**, **diferentes tipos de documentos**, **problemas com a interface com grande volume de dados** etc, além de termos uma solução viável para entrada de dados.

#### Observações:
Iremos utilizar o Article Meta como fonte dados, ver: https://github.com/scieloorg/articles_meta

Exemplos de aplicação que utilizam o Article Meta como fonte de dados: 

* https://github.com/scieloorg/search-journals/
* https://github.com/scieloorg/citedby
* https://github.com/scieloorg/processing
* https://github.com/scieloorg/analytics

**Comment by jamilatta** [comment]
Para realizamos essa tarefa tivemos que contemplar recurso em outras camadas... 

Foi necessário adicionar 9 novos campos no Xylose criar teste etc, segue os campos adicionados: 

* mission
* copyrighter
* publisher_country
* online_submission_url
* other_titles
* sponsors
* publisher_state
* study_areas
* previous_journal_ref (Esse campo não está sendo importado ainda, pois em AM(Article Meta) ele é texto e em SM(SciELO Manager) ele é uma referência)

**Importante enfatizarmos que as nomenclaturas entre o Xylose e Opac_Schema são diferentes**

Irei documentar uma delas em que demorei um pouco para consegui encontrar: 

**subject_categories**(opac_schema) é igual a **subject_areas**(opac)
**study_areas**(opac_schema) é igual a **wos_subject_areas**(opac)

Os termos estão bastante ruins. "Precisamos em algum momento revisar"

**Comment by jamilatta** [comment]
Bom assim como comentado acima sobres a dificuldade para coletarmos os dados dos periódicos, existiu algumas dificuldade para cadastrarmos os fascículos, segue algumas delas: 

1. Conversamos com o Fábio para no dia 26/02/2016 para prover os metadados dos fascículos no articlemeta, a atividade foi realizada e disponibilizadas quase que instantaneamente;

2. Foi necessário alterarmos o modelo de issue, pois, verificarmos que alguns campos são desnecessário e que poderíamos utilizas as seções dos artigos;

3. Identificarmos que existe registros "Fantasmas" do fascículos no article meta, resolvemos isso validando se não é um **press release** (Consultamos o Fábio e prontamente ele nós ajudou)

4. Concluirmos que não é preciso cadastrar os **press release**, estes ficaram em outra APP que iremos apenas consultar via RSS.

5. Tivemos que ajustar o opac_schema para atender a alguns atributos ainda não comtemplados.

**Comment by jamilatta** [comment]
Também enfrentamos alguns problemas para realizar a coleta para os artigos: 

1. Verificamos que não é possível coletar nem o HTML nem o XML do articlemeta

2. Verificamos a possibilidade de realizarmos uma coleta híbrida AM e SM, porém optamos por aguardar uma maturidade dos serviços disponíveis pelo SM.

3. Optamos por hora termos um HTML de exemplo para todos os artigos para que possamos trabalhar na interface do Site.

4.Tivemos que ajustar o opac_schema para atender a alguns atributos ainda não comtemplados.

**Comment by jamilatta** [comment]
Estou trabalhando em adicionar no modelo de periódico o **last_issue**.

**Comment by scielo** [comment]
Não sei como você esta fazendo, mas ainda acho que persistir em banco de
dados o last issue é um caminho errado, a final esse dado teria que ser
atualizado constantemente e sem aviso prévio.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by jamilatta** [comment]
Fabio,

podemos marcar um reunião para analisarmos em conjunto eu e o Juan estamos
de acordo com essa abordagem... escutamos suas justificativa e ai vc escuta
nossas justificativas => chegamos a uma conclusão.



2016-03-09 9:53 GMT-03:00 SciELO RedDes <notifications@github.com>:

> Não sei como você esta fazendo, mas ainda acho que persistir em banco de
> dados o last issue é um caminho errado, a final esse dado teria que ser
> atualizado constantemente e sem aviso prévio.
>
> *Fabio Batalha C. Santos*
> Colegiado SciELO
> www.scielo.org
> FAPESP - CNPq - BIREME - FapUNIFESP
>
> On Tue, Mar 8, 2016 at 6:08 PM, Jamil Atta Junior <
> notifications@github.com>
> wrote:
>
> > Estou trabalhando em adicionar no modelo de periódico o *last_issue*.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scieloorg/opac/issues/84#issuecomment-193967063>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/opac/issues/84#issuecomment-194283059>.
>



-- 

Jamil Atta Junior

**Comment by scielo** [comment]
Ok Jamil.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-03-09 10:44 GMT-03:00 Jamil Atta Junior <notifications@github.com>:
