### ISSUE TITLE
Não apresenta seção dos artigos no sumário dos periódicos correntes,

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#842]
- Nome: Javani Araujo
- Tipo: Defeito
- Descrição: Não apresenta seção dos artigos no sumário dos periódicos correntes, contudo nos títulos descontinuados as seções aparecem no sumário
- URL: https://opac.scielo.org/toc/csc/2017.v22n9/

**Comment by RPostalli** [comment]
Conforme reunião em 1 de março de 2018 (Ata da reunião disponível no email com título: Conclusão da Reunião sobre Seções do Sumário (site novo) e outros temas relacionados), foi definido que: "Enquanto as seções não estiverem corretas, a funcionalidade de organização por seção não deve estar ativada".

**Comment by alexxxmendonca** [comment]
@RPostalli pode confirmar se este ticket continua válido? Suspeito que não.

**Comment by RPostalli** [comment]
@alexxxmendonca a função organizar por seção me parece OK. Mas ainda existem problemas com os idiomas.

Exemplo: https://www.scielo.br/j/csc/i/2021.v26n4/
![image](https://user-images.githubusercontent.com/6084959/119824385-3c58f200-becc-11eb-93e8-ac50ac1a381c.png)

Quando eu mudo o idioma da páginas os idiomas das seções não mudam. Não sei se isso está sendo tratado em outro ticket.

**Comment by alexxxmendonca** [comment]
@RPostalli pode dar uma olhada neste ticket? #1177

Acredito que o #1177 seja o que você está falando. Se sim, podemos fechar este ticket (842).

**Comment by RPostalli** [comment]
@alexxxmendonca é esse mesmo, isso ai!
