### ISSUE TITLE
Mesmo nos números que estão com as seções aparecendo, alguns dos artigos estão sem a seção ao lado do título

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#843]
- Nome: Carolina Tanigushi
- Tipo: Defeito
- Descrição: Mesmo nos números que estão com as seções aparecendo, alguns dos artigos estão sem a seção ao lado do título, mesmo ela estando no XML. Quando clico para mostrar os artigos da seção deste artigo destacado abaixo (Artículos de Investigación Original), ele não aparece na lista
- URL:
  - https://opac.scielo.org/toc/csc/2017.v22n9/
  - https://opac.scielo.org/toc/rpsp/2015.v38n5/
  - https://opac.scielo.org/toc/icse/2016.v20n56/

**Comment by alexxxmendonca** [comment]
Problema corrigido.
