### ISSUE TITLE
Na página do artigo em inglês e em espanhol, verificar tradução dos itens

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#845]
- Nome: Javani Araujo
- Tipo: Defeito
- Descrição: Na página do artigo em inglês e em espanhol, verificar tradução dos itens
- URL: -

**Comment by alexxxmendonca** [comment]
Há outros tickets abertos relacionados a revisão de tradução dos elementos da interface.

Estou fechando este ticket, mais genérico e sem especificações, em favor dos demais tickets que possuem mais detalhamento e são mais pontuais.
