### ISSUE TITLE
Na página de “about” ao invés de cada link levar para uma outra página, poderia abrir em formato “expandir/colapsar”

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#855]
- Nome: Amanda Ramalho
- Tipo: Sugestão
- Descrição: Na página de “about” ao invés de cada link levar para uma outra página, poderia abrir em formato “expandir/colapsar”.
- URL: https://opac.scielo.org/collection/about/

**Comment by alexxxmendonca** [comment]
Acho isso discutível. 

É possível que tenhamos sub-itens com hierarquias. Ter comportamento expandir/colapsar pode não funcionar muito bem.

Sugiro mantermos o comportamento atual.
