### ISSUE TITLE
em “Articles and Alikes”, abrir os links do G. Scholar em uma nova aba/janela

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#856]
- Nome: Cinthia Vieira
- Tipo: Sugestão
- Descrição: No menu suspenso que se abre a partir do menu do canto inferior esquerdo, em “Articles and Alikes”, abrir os links do G. Scholar em uma nova aba/janela
- URL: -

**Comment by gustavofonseca** [comment]
Feito
