### ISSUE TITLE
Quando há muito autores, mesmo clicando em “[...]” não aparecem todos os autores

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#857]
- Nome: Jennifer Amato
- Tipo: Defeito
- Descrição: Quando há muito autores, mesmo clicando em “[...]” não aparecem todos os autores.
- URL: https://opac.scielo.org/article/resp/2017.v91/e201703026/pt/

**Comment by patymori** [comment]
Problema corrigido e validado em produção na versão nova do OPAC.
