### ISSUE TITLE
Trocar o termo “summary” para “TOC” ou “Table of Contents” (página do artigo EN)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#859]
- Nome: Cinthia Vieira
- Tipo: Sugestão/Tradução
- Descrição: Trocar o termo “summary” para “TOC” ou “Table of Contents” (página do artigo EN)
- URL: -

**Comment by carolinatanigushi** [comment]
Na interface em espanhol, identificamos que deve ser trocado também para "Tabla de contenido", veja o scielo.br: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-330620180002&lng=es&nrm=iso

**Comment by gustavofonseca** [comment]
A descrição do ticket diz que efetuar a troca é uma _sugestão_.  @cinthia-vieira e @carolinatanigushi, o pedido de mudança é motivado por deixar o termo igual ao que é utilizado no site clássico ou há outra coisa?

**Comment by cinthia-vieira** [comment]
@gustavofonseca na verdade, a minha sugestão se deu pelo fato de "Table of Contents" ser o termo mais adequado pra esse tipo de uso (sumário/índice de algum periódico), e o mais utilizado pelos periódicos que publicam em inglês.

"Summary" é mais usado pra descrever "resumo" do que pra descrever "sumário".

**Comment by gustavofonseca** [comment]
Perfeito, @cinthia-vieira. E o uso do termo _Sumário_ na interface em português é adequado ou deveria ser alterado para _Tabela de conteúdos_ ou algo do tipo?

**Comment by cinthia-vieira** [comment]
@gustavofonseca Não creio que existam periódicos, ou bases, que usem o termo "Tabela de conteúdos" para especificar seus sumários o suficiente para embasar uma sugestão de mudança para "Sumário".

**Comment by gustavofonseca** [comment]
Legal, grato =]

**Comment by alexxxmendonca** [comment]
Estou de acordo.

**Comment by robertatakenaka** [comment]
Faltou um lugar para corrigir: na barra de navegação

https://homolog.opac.scielo.br/article/rsp/2014.v48n2/206-215/en/

**Comment by gustavofonseca** [comment]
> @gustavofonseca
> Faltou um lugar para corrigir: na barra de navegação
> 
> https://homolog.opac.scielo.br/article/rsp/2014.v48n2/206-215/en/
> 
> <img alt="Captura de Tela 2020-03-26 às 10 41 58" width="721" src="https://user-images.githubusercontent.com/505143/77653584-abe0f380-6f4e-11ea-8587-ea34eeb8f1b7.png">

@robertatakenaka, de fato. Vou corrigir e enviarei outro PR.

**Comment by gustavofonseca** [comment]
> @gustavofonseca
> Faltou um lugar para corrigir: na barra de navegação
> 
> https://homolog.opac.scielo.br/article/rsp/2014.v48n2/206-215/en/
> 
> <img alt="Captura de Tela 2020-03-26 às 10 41 58" width="721" src="https://user-images.githubusercontent.com/505143/77653584-abe0f380-6f4e-11ea-8587-ea34eeb8f1b7.png">

@robertatakenaka, o problema foi resolvido e o código integrado.
