### ISSUE TITLE
Logos do rodapé da página: alguns estão em escalas de cinza e o logo da FAPESP está colorido

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#860]
- Nome: Amanda Ramalho
- Tipo: Sugestão
- Descrição: Logos do rodapé da página: alguns estão em escalas de cinza e o logo da FAPESP está colorido. Não seria interessante adotar um padrão? Ou todos coloridos ou todos em escala de cinza (teríamos que verificar se podemos exibir os logos alterando a cor…)
- URL: -

**Comment by alexxxmendonca** [comment]
Problema resolvido.
