### ISSUE TITLE
Colocar alguma pontuação, ou quebra de linha, entre as informações “Publicação de:” e “Área”

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#862]
- Nome: Cinthia Vieira
- Tipo: Sugestão
- Descrição: Colocar alguma pontuação, ou quebra de linha, entre as informações “Publicação de:” e “Área” (o mesmo vale para as interfaces EN e ES)
- URL: -

**Comment by alexxxmendonca** [comment]
Duplicado: #1113
