### ISSUE TITLE
Mostrar o link de “Resumo/Resumen/Abstract” no sumário somente quando o artigo possuir resumo

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#863]
- Nome: Cinthia Vieira
- Tipo: Sugestão
- Descrição: Mostrar o link de “Resumo/Resumen/Abstract” no sumário somente quando o artigo possuir resumo
- URL: https://opac.scielo.org/article/rpsp/2017.v41/e68/en/?abstract_lang=en

**Comment by alexxxmendonca** [comment]
Esse aqui já não está resolvido?

**Comment by alexxxmendonca** [comment]
Problema resolvido.
