### ISSUE TITLE
Arquivos de áudio não aparecem na página do artigo

### ISSUE THREAD

**Issue by javani** [scieloorg/opac#866]
Os arquivos do último número do periódico Ciência e Saúde Coletiva possuem áudio, os quais não estão disponíveis na página do artigo. Há apenas a indicação de que o artigo possui áudio.
https://scielosp.org/article/csc/2017.v22n11/3499-3504/

Artigo no BR - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1413-81232017021103499&lng=en&nrm=iso&tlng=pt

```xml
<back>
      <fn-group>
                        <fn fn-type="other" id="fn1">
                                <p>
                                        <media mime-subtype="mp3" mimetype="audio" xlink:href="1413-8123-csc-22-11-3499.mp3">Este artigo também está disponível em áudio</media>
                                </p>
                        </fn>
                </fn-group>
</back>
```

**Comment by jfunez** [comment]
@robertatakenaka confirma para a gente que isso seria um ajuste no XSLT do artigo. certo?
