### ISSUE TITLE
adicionar auditoria nas pág informativas

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#868]
A equipe que da manutenção precisa manter controle das mudanças que serão feitas nas páginas informativas. 

Portanto devemos acrescentar o registro de auditorias para cada mudança feita nas páginas informativas.

Estes registros estarão acessíveis na interface de admin.

**Comment by RPostalli** [comment]
Conforme combinado, após reunião de páginas informativas, informo que 3 tickets foram escolhidos como prioridade para documentação no Guia de Páginas Informativas, este ticket é um deles (3).

**Comment by cinthia-vieira** [comment]
Página de auditoria funciona, apresentando exatamente o reportado neste ticket: data e horário da criação/edição/exclusão de páginas, usuário que realizou e qual a ação realizada.

Entretanto, gostaria de sugerir, se possível, apresentar os dados atualmente mostrados em HTML em um modo visual, uma vez que a apresentação por código é confusa e não é realmente possível visualizar as mudanças de forma clara. Destacar as mudanças de alguma forma, com negrito ou outra cor, também seria interessante.

O título de coluna "Data de criação" também é confuso e pode ser interpretado como data de criação da página modificada, sugiro uma nova nomeação; "Data da modificação", talvez.

**Comment by jfunez** [comment]
Olá @cinthia-vieira 
vou responder por partes:

> Página de auditoria funciona, apresentando exatamente o reportado no ticket #906 
👍 

> Entretanto, gostaria de sugerir, se possível,...
Não vou falar que é impossível, mas sim demorado... então vamos tratar isso como um outro ticket de melhoria.

> O título de coluna "Data de criação" também é confuso e pode ser interpretado como data de criação da página modificada, sugiro uma nova nomeação; "Data da modificação", talvez.
O campo tem essa etiqueta:  "Data de criação" porque é a data que o registro de autoria foi criado. 
O usuário (mesmo o administrador) não tem a possibilidade de "modificar" o registro, portanto "data de modificação" não aplica. Existem outras colunas no admin com a mesma etiqueta "Data de Criação" e sempre referem à data de criação do registro que o usuário esta visualizando. Portanto mudar essa etiqueta também impacta nos outros campos para manter a coerência. 

>Sugiro também que não haja a possibilidade de excluir registros nessa página, somente de criá-los.
Nossa, passou sem querer, foi habilitado só para testar rapidamente aqui. Vou desativar no próximo PR.
