### ISSUE TITLE
envio de email com relatório diário das mudanças que foram feitas nas páginas informativas

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#869]
No issue #868 será adicionado o controle de auditoria nas pág secundárias.
Para evitar que pessoas recebem um email para cada mudança (as vezes muitas mudanças serão feitas em um período curto de tempo), então pensamos em enviar um email no final do dia com um relatório das mudanças.

Os receptores de email serão indicados no admin (listagem de usuários), facilitando assim a gestão.

#### Impedimento:

Depende da finalização do issue: #868

**Comment by RPostalli** [comment]
Conforme combinado, após reunião de páginas informativas, informo que 3 tickets foram escolhidos como prioridade para documentação no Guia de Páginas Informativas, este ticket é um deles (2).
