### ISSUE TITLE
Visualização de HTML de pág informativa com indentação

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#874]
Atualmente, o editor WYSIWYG não mostra o HTML do corpo do texto da página informativa.
É preciso ter o HTML indentado para a equipe que faz a validação das páginas.

**Comment by alexxxmendonca** [comment]
Não é o #424 ?

**Comment by jfunez** [comment]
É e não é 😃 

Explico melhor:

Pode ser que a troca de editor resolva (acredito que sim), porém são duas tarefas diferentes... então primeiro vou trocar o editor e se resolver a indentação vou marcar este issue com resolvido também.

**Comment by alexxxmendonca** [comment]
👍 just checking

**Comment by RPostalli** [comment]
Conforme combinado, após reunião de páginas informativas, informo que 3 tickets foram escolhidos como prioridade para documentação no Guia de Páginas Informativas, este ticket é um deles (1).

**Comment by jfunez** [comment]
Em processo de avaliação em homologação.

**Comment by jfunez** [comment]
todas as modificações foram feitas e testadas em homologação.
Aprovado pela Cinthia
