### ISSUE TITLE
Data de última atualização | Páginas Informativas OPAC

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#879]
Criar automaticamente na página informativa dos periódicos nos 3 idiomas, a data da última atualização das páginas informativas (esta data não tem relação com a atualização de seus números). Esta demanda foi levantada por requisitos de DOAJ e atualmente (em BR) é inserido a mão e  passível de erros, como o caso a seguir: http://www.scielo.br/revistas/ape/iaboutj.htm A data consta como Updated: 29/09/2016, mas sabemos que houveram novas atualizações em 2017. Recomendo os seguintes textos a serem considerados:

Português:
Atualizado: DD/MM/YYYY

Inglês:
Updated: YYYY//MM/DD

Espanhol:
Actualizado: DD/MM/YYYY

Acredito que ficaria bom na parte superior direita da página das revistas, conforme segue exemplo da imagem a seguir:

![data_opac](https://user-images.githubusercontent.com/6084959/34262957-069bdfae-e655-11e7-957f-e2382a18bb81.jpg)

**Comment by alexxxmendonca** [comment]
Sim, muito importante 👍

**Comment by jfunez** [comment]
@jamilatta podemos ajustar na interface do admin (como mostra no PR #889) para formatar melhor a data, sem o que vem depois dos segundos...

@RPostalli vou atualizar homologação em breve para vocês poderem avaliar se esta, as datas de criação e atualização...  As páginas que não tem datas ainda, basta dar um `save` em cada uma que vai ter datas de criação e atualização do momento do save...

Após termos isso validado, podemos ajustar o template para o usuário ver a data de atualização e assim finalizar este issue...

**Comment by jfunez** [comment]
@RPostalli o site de homologação já esta atualizado, ficamos no aguardo do feedback

**Comment by RPostalli** [comment]
@jfunez eu estou colocando as datas, mas quando eu coloco ele muda para uma data padrão 2018-02-01, e se eu preencho apenas uma campo de data ele preenche os dois. (Para rsp estou colocando 13/10/2017)

As datas de criação podem ser todas iguais, que foi a data do lançamento do site. Isso você pode preencher automaticamente? E algumas revistas tem data de Uptadet outras não. (As atualizações são usuais para revistas BR/SP as só SP dificilmente pedem atualização)
