### ISSUE TITLE
Incluir emblema do ScienceOpen na página do artigo.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#881]
É necessário analisarmos se o emblema em questão é compatível e se pode ser acomodado pelo layout da página do artigo. 

Mais informação pode ser encontrada no arquivo [ScienceOpen Metrics Badge_171204.pptx](https://github.com/scieloorg/opac/files/1606511/ScienceOpen.Metrics.Badge_171204.pptx).

Esse requisito foi acordado junto a equipe do ScienceOpen no dia 04/07/2017.

**Comment by jfunez** [comment]
@gustavofonseca pelo que entendi, temos 3 opções de badges e podemos usar uma delas (a que fique melhor para nós), certo?

Se sim, podemos solicitar a @paratiuid para enviar 3 mockups das badges indicadas e o @alexxxmendonca pode avaliar e escolher uma. 

(@paratiuid pode ver a página 3 da apresentação anexada pelo @gustavofonseca e enviar os mockups para @alexxxmendonca avaliar?)

Gustavo, outras dúvidas sobre a página 4:
- sobre o snippet:  `<script id="UUID">` este `UUID`:
  - é válido? 
  - é único para todas a coleções/OPACs? se não, aonde posso obter a lista de UUIDs válidos?
  - está associado ao domínio?

- sobre o snippet: `<div data-id-type="scielo-sza">` este `="scielo-sza"`:
  - quais valores são válidos aqui? com prefixo: `scielo-` e o acrônimo da coleção? 

e finalmente: 
- quais coleções terão a integração? 
- tem alguma restrição de artigos ou periódicos que não vão ter essa badge?

**Comment by gustavofonseca** [comment]
> @gustavofonseca pelo que entendi, temos 3 opções de badges e podemos usar uma delas (a que fique melhor para nós), certo?

Sim, foi o que entendi também. Inclusive dei uma olhada rápida no código-fonte do script e por hora os valores possíveis são `1, 2 e 3`.

> Se sim, podemos solicitar a @paratiuid para enviar 3 mockups das badges indicadas e o @alexxxmendonca pode avaliar e escolher uma.
> 
> (@paratiuid pode ver a página 3 da apresentação anexada pelo @gustavofonseca e enviar os mockups para @alexxxmendonca avaliar?)

Sim, estou de acordo.

> Gustavo, outras dúvidas sobre a página 4:
> 
>     sobre o snippet: <script id="UUID"> este UUID:
>         é válido?
>         é único para todas a coleções/OPACs? se não, aonde posso obter a lista de UUIDs válidos?
>         está associado ao domínio?
> 
>     sobre o snippet: <div data-id-type="scielo-sza"> este ="scielo-sza":
>         quais valores são válidos aqui? com prefixo: scielo- e o acrônimo da coleção?

Vou descobrir.

> e finalmente:
> 
>     quais coleções terão a integração?
>     tem alguma restrição de artigos ou periódicos que não vão ter essa badge?

@alexxxmendonca, pode nos ajudar a elucidar essas últimas questões?

Valeu!

**Comment by alexxxmendonca** [comment]
> quais coleções terão a integração?

O ScienceOpen já indexa todo o conteúdo da Rede SciELO (https://www.scienceopen.com/search#collection/3f2fc474-1b89-4787-a968-69184d0cc2f9), de modo que não vejo problema em aplicarmos para toda a Rede, tendo em vista também que é gratuito (não é como o ReadCube que é pago).

> tem alguma restrição de artigos ou periódicos que não vão ter essa badge?

Não.

**Comment by jfunez** [comment]
Ótimo!

@alexxxmendonca contamos contigo para dar prioridade (se corresponde) e retornar com a avaliação dos mockups, assim que for feito pela @paratiuid 

Assim que for escolhido o mockup e entregue o HTML/CSS da @paratiuid, aplicarei no OPAC

Fico no aguardo!

**Comment by gustavofonseca** [comment]
@jfunez, sobre as dúvidas do comentário https://github.com/scieloorg/opac/issues/881#issuecomment-355546805: 

> sobre o snippet: <script id="UUID"> este UUID:
>     é válido?
>     é único para todas a coleções/OPACs? se não, aonde posso obter a lista de UUIDs válidos?
>     está associado ao domínio?

O UUID que consta na documentação de referência deve ser utilizado em cada uma das instâncias do site.

> sobre o snippet: <div data-id-type="scielo-sza"> este ="scielo-sza":
>     quais valores são válidos aqui? com prefixo: scielo- e o acrônimo da coleção?

Os valores do atributo `data-id-type` seguem a forma que você inferiu: concatenação do prefixo `scielo-` e o acrônimo da coleção conforme o valor do campo `code`, do endpoint `collections` no ArticleMeta.

Confirmei ainda a questão sobre termos 3 tipos de emblema para escolher.

**Comment by paratiuid** [comment]
@alexxxmendonca Seguem os modelos.
Aguardo comentários.

a)
![scielo-so-metrics-v1](https://user-images.githubusercontent.com/22373640/34948950-c517a13a-f9f5-11e7-87f4-fa10255b8a2e.jpg)

b)
![scielo-so-metrics-v2](https://user-images.githubusercontent.com/22373640/34948991-e144bae6-f9f5-11e7-9ad2-dcdee99b99b4.jpg)

c)
![scielo-so-metrics-v3](https://user-images.githubusercontent.com/22373640/34948997-e870a67c-f9f5-11e7-9fe0-2df6b64cc6d3.jpg)

**Comment by alexxxmendonca** [comment]
Segundo o Abel, esse emblema deve ficar junto com os demais indicadores de métricas, ou seja, no SciELO Analytics.

> O link deve ser agregado no conjunto das métricas. Não podemos gerar diferentes pontos ou seções para métricas.

Por ora, vou fechar esse ticket pois o emblema deve ser considerado em outro projeto, SciELO Analytics.

**Comment by alexxxmendonca** [comment]
@paratiuid retomando esse ticket, em anexo está um PPT com diretrizes para inserção do badge do ScienceOpen

[ScienceOpen Metrics Badge_171204.pptx](https://github.com/scieloorg/opac/files/2572514/ScienceOpen.Metrics.Badge_171204.pptx)

Ele deve ser inserido na janela modal de métricas do artigo,

**Comment by alexxxmendonca** [comment]
A equipe do ScienceOpen retomou o contato hoje (12/04/2019), em uma mensagem que diz que o badge que estava pendente foi desenvolvido e que exemplos podem ser encontrados no arquivo anexo.

[badge.html.zip](https://github.com/scieloorg/opac/files/3074612/badge.html.zip)

**Comment by gustavofonseca** [comment]
Por algum motivo a atividade não estava no quadro de atividades da equipe de desenvolvimento.

**Comment by jamilatta** [comment]
@gustavofonseca 

Está no **Backlog**, isso é urgente?, devemos mudar para a coluna "A Fazer" ?

**Comment by gustavofonseca** [comment]
Não é necessário alterarmos o planejamento da semana. Podemos deixar para o próximo ciclo.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Para realizar essa atividade podemos considerar a opção **c** enviado pela @paratiuid ?

**Comment by alexxxmendonca** [comment]
@jamilatta não. Isso tem que ficar dentro da seção métricas do artigo.

Ver https://github.com/scieloorg/opac/issues/881#issuecomment-437926742

**Comment by paratiuid** [comment]
@alexxxmendonca @jamilatta 

Acredito que seja possível via css deixar o badge nesse posicionamento:
![logo-reorganizado](https://user-images.githubusercontent.com/22373640/60462112-d2236e00-9c1e-11e9-9ba9-a88586292409.jpg)


O que acham?

**Comment by alexxxmendonca** [comment]
@paratiuid de acordo. Apenas alterar o texto "My custom link to ScienceOpen" para somente "ScienceOpen".

**Comment by cesarbruschetta** [comment]
@alexxxmendonca Essa funcionalidade ja esta no ambiente de [homologação](https://homolog.opac.scielo.br/), vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta alguns casos o link não aparece. Exemplo: https://homolog.opac.scielo.br/article/mioc/2007.v102n5/555-557/en/#metric_modal_id

Qual o critério para aparecer ou não aparecer?

**Comment by jamilatta** [comment]
@alexxxmendonca 

Quando o ícone não aparece significa que o conteúdo não foi encontrado no Scienceopen!.

O critério exibição é a existência do DOI no ScienceOpen. 

O comportamento de não exibição do badge do ScienceOpen para artigo que não estão presentes é correto.

**Comment by alexxxmendonca** [comment]
@jamilatta ok. Estranho pois até onde eu sei todo o conteúdo SciELO foi incorporado ao ScienceOpen, mas vou confirmar com eles.

Está aprovado em homologação.

**Comment by alexxxmendonca** [comment]
@jamilatta 

Ainda sobre essa questão, encontrei sim o artigo no ScienceOpen:

https://www.scienceopen.com/document?vid=8fe9edad-2b1a-4ca2-b4db-be63ac528299

Artigo no SciELO: https://homolog.opac.scielo.br/article/mioc/2007.v102n5/555-557/en/#

**Comment by jamilatta** [comment]
@alexxxmendonca 

Estou verificando mas provavelmente esse artigo não tem DOI!

**Comment by jamilatta** [comment]
@alexxxmendonca 

Verifiquei e tem DOI sim essa artigo, vou verificar se o ScienceOpen conhece esse DOI!

**Comment by jamilatta** [comment]
Em conversa com a equipe concordamos que o ScienceOpen deva ter o DOI como identificador de integração. 

O ScienceOpen não tem o DOI desse artigo: https://www.scienceopen.com/document?vid=8fe9edad-2b1a-4ca2-b4db-be63ac528299

O artigo tem DOI no SciELO: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02762007000500003
