### ISSUE TITLE
Link para pesquisa de artigos relacionados/similares não retorna resultados

### ISSUE THREAD

**Issue by amandasramalho** [scieloorg/opac#891]
Ao clicar no botão de artigos relacionados aparecem duas opções: Similares no Google e Citados no Google Scholar. Ambos não trazem resultados na pesquisa. Acredito que o dado pesquisado esteja errado, uma vez que está sendo incluída a URL para ser pesquisada.

Resultados via link:
![image](https://user-images.githubusercontent.com/5446933/35701592-9a84e6b8-077d-11e8-987b-dc6973a7d061.png)
![image](https://user-images.githubusercontent.com/5446933/35701772-3944f464-077e-11e8-84b9-9cc2b1bcf356.png)

Resultado quando eu fiz a pesquisa:
![image](https://user-images.githubusercontent.com/5446933/35701740-1e8cfc52-077e-11e8-8faf-51d30332ce5b.png)

**Comment by robertatakenaka** [comment]
O botão "Similares no Google" está usando "https://scholar.google.com/scholar?q=related:article_external_url"
O botão "Citados no Google Scholar" está usando "https://scholar.google.com/scholar?q=link:article_external_url"

**Comment by patymori** [comment]
@robertatakenaka , é necessário corrigir o tamanho do modal onde os botões ficam.

**Comment by patymori** [comment]
@amandasramalho e @alexxxmendonca, feita correção na versão nova. Poderiam verificar em https://opac.scielo.br?

Obrigada

**Comment by alexxxmendonca** [comment]
testado e aprovado!
