### ISSUE TITLE
OPAC - Problemas Encontrados

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#893]
Jamil e Juan, boa tarde.

Realizando algumas extrações do Kibana, e verificamos que a quantidade de documentos entre BR e SP não batiam, então realizamos uma verificação e descobrimos os seguintes problemas:

Fascículos aparecem na grade mas não possui os artigos publicados, precisam ser reprocessados:

csc v17n1
csc v17n7
csc v17n8
csc v17n10
csc v16n9
csc v15n2
csc v15n6
csc v14n3
csc v14n5
csc v14n6
csc v1n1

csc v15n5
Faltam 5 artigos, são eles:
	- Efeitos diante do convite de construir um espaço comum entre formuladores sobre gestão e planejamento em saúde no Brasil
	- É preciso politizar o SUS
	- Planejamento e gestão: para além da comunicação
	- Afinidades comunicativas e as políticas de saúde no Brasil
	- Os autores respondem

Também detectamos que 42 Press Releases da CSC não estão publicados, em BR eles entravam junto dos fascículos, como será a publicação destes PRs antigos?

v21n1
v21n2
v21n3
v21n4
v21n5
v21n6
v21n7
v21n8
v21n9
v20n1
v20n2
v20n3
v20n4
v20n5
v20n6
v20n7
v20n8
v20n9
v20n10
v20n11
v20n12
v19n1
v19n2
v19n3
v19n5
v19n6
v19n7
v19n8
v19n9
v19n10
v19n11
v19n12
v18n3
v18n4
v18n5
v18n6
v18n7
v18n8
v18n9
v18n10
v18n11
v18n12

Obrigada.

**Comment by jamilatta** [comment]
Verificando no [old.scielosp.org](http://old.scielosp.org/) esses fascículos estão funcionando :-()

**Comment by jamilatta** [comment]
Por hora pra ter certeza que não é no processamento do OPAC irei reprocessar toda a CSC. 

Caso não tenha qualquer mudança precisamos verificar o articlemeta.

**Comment by jamilatta** [comment]
Pelo que entendi o problema está no processamento, pois, o articlemeta está com os artigos, exemplo de um artigo que esta no articlemeta, porém não está no OPAC: http://articlemeta.scielo.org/api/v1/article/?collection=spa&code=S1413-81232012000100002

**Comment by jamilatta** [comment]
Pessoal estou trabalhando nisso!

**Comment by jamilatta** [comment]
@RPostalli 

Em breve o @jfunez irá atualizar a instância de homologação, assim é possível testar os seguintes fascículos da CSC: 

csc v17n1
csc v17n7
csc v17n8
csc v17n10
csc v16n9
csc v15n2
csc v15n6
csc v14n3
csc v14n5
csc v14n6
csc v1n1 (Item não existe nem em homolog e produção, nem em http://old.scielosp.org)

Te aviso assim que estiver liberado em homolog.

**Comment by jamilatta** [comment]
Referente aos pressreleases é importante definir juntamente com a equipe do @alexxxmendonca como será feita a migração, pois, atualmente esse conteúdo é gerenciado por eles com o wordpress.

**Comment by alexxxmendonca** [comment]
Press releases publicados anteriores à publicação no blog (pressreleases.scielo.org) não serão publicados no OPAC uma vez que é necessário que eles estejam no Wordpress.

Também não teremos mais press releases vinculados a fascículos. Após um período (2 meses, se não me falha a memória) o press release deixa de ser relevante e não deve mais aparecer no OPAC.

**Comment by RPostalli** [comment]
Não tem problema. Levantei a questão de PR pois acredito que a contagem destes documentos é feita no Analytics e desta forma quantidade de documentos da mesma revista entre BR e SP fica diferente. Vou verificar essa questão com o Gustavo. Obrigada pessoal

**Comment by alexxxmendonca** [comment]
Sem problemas! Acho que essa contagem sofrerá alterações haja vista que todos os press releases estão sendo publicados agora no Wordpress.

**Comment by jamilatta** [comment]
@RPostalli 

Por gentileza, verificar os fascículos em produção, após a validação fechamos esse ticket.

**Comment by RPostalli** [comment]
Testado. Tudo OK.
Obrigada.
