### ISSUE TITLE
Problemas com RESS no OPAC

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#902]
Verificar problemas em: https://www.scielosp.org/grid/ress/

- Os números v26n3, n4 e v27n1 estão sem PDF. 
- Existem 4 artigo na grade "Ahead of Print", que não já migraram para fascículos (Esta grade não deve existir).
v26n3
         Sex and Gender Equity in Research: rationale for the SAGER guidelines and recommended use
v26n4
        Use of health services among adults living in Manaus Metropolitan Region, Brazil: population-based survey, 2015
        Epidemiology and Health Services: history, achievements, and future (2x)
        Epidemiology and Health Services: 25 years in review
- No fascículo v26n4 o artigo "Epidemiology and Health Services: history, achievements, and future" aparece duas vezes.

Em SciELO Brasil não ocorrem estes problemas: http://www.scielo.br/scielo.php?script=sci_issues&pid=2237-9622&lng=en&nrm=iso

**Comment by jamilatta** [comment]
@RPostalli 

Irei avaliar esse ticket em breve.

**Comment by jamilatta** [comment]
Verifiquei que na base de dados não existe no registro do PDF para todos os idiomas.
 O que nos leva a acreditar que seja um problema no **processamento** :-(. 

Para descartar a possibilidade de uma instabilidade no processamento, estou reprocessando o ambiente de homologação para verificar se o problema é solucionado

**Comment by jamilatta** [comment]
Analisando descobrimos que o problema está no OPAC_PROC (processmento)

Ticket do opac_proc para esse bug: https://github.com/scieloorg/opac_proc/issues/252

**Comment by jamilatta** [comment]
Estou reprocessando para garantir que está funcionando.

**Comment by jamilatta** [comment]
@RPostalli 

É possível verificar a correção no link: https://homolog.opac.scielo.org/toc/ress/2017.v26n4/

Por favor, validar para que possamos aplicação em produção.

**Comment by RPostalli** [comment]
@jamilatta agora está OK.
:relieved:

**Comment by jamilatta** [comment]
OK.

**Comment by RPostalli** [comment]
@jamilatta o problema foi corrigido em homolog, mas não em produção, ainda se mantem os problemas:

- Existem 4 artigo na grade "Ahead of Print", que não já migraram para fascículos (Esta grade não deve existir).
v26n3
Sex and Gender Equity in Research: rationale for the SAGER guidelines and recommended use
v26n4
Use of health services among adults living in Manaus Metropolitan Region, Brazil: population-based survey, 2015
Epidemiology and Health Services: history, achievements, and future (2x)
Epidemiology and Health Services: 25 years in review
- No fascículo v26n4 o artigo "Epidemiology and Health Services: history, achievements, and future" aparece duas vezes.

**Comment by jamilatta** [comment]
@RPostalli irei verificar!

**Comment by jamilatta** [comment]
Conteúdo disponibilizado após o ajuste: https://github.com/scieloorg/opac_proc/commit/2f7767dfe89b2f57dc16fb4fc7ee68e7d3060aa4 no processamento.

**Comment by RPostalli** [comment]
@jamilatta quando atualizar em produção por favor pode me informar para testar?
Obrigada.

**Comment by jamilatta** [comment]
@RPostalli 

O conteúdo já está disponível.

**Comment by RPostalli** [comment]
@jamilatta então a correção não funcionou, os artigos continuam duplicados e a grade de ahead que não deveria existir, continuar a existir.

**Comment by jamilatta** [comment]
@RPostalli como esse ticket descrever vários pontos sugiro mantermos esse ticket fechado e adicionar outro ticket com a questão da duplicidade.
