### ISSUE TITLE
Adicionar o resumo no TOC.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#907]
Em discursões anteriores levantamos a possibilidade de adicionar o resumo no TOC.

Irei adicionar e verificar com a equipe o que acham.

**Comment by jamilatta** [comment]
Alteração solicitada pelo Abel me **5 de mar de 2018**: 

Jamil 

Preciso do acesso externo. Entretanto a funcionalidade é claro bem vinda. **A flecha no final do resumo deve ser para baixo quando oculto e para cima quando aberto**. 

Abc. Abel

**Comment by jamilatta** [comment]
Além desse ajuste é necessário verificar em ambiente de homologação se existe traduções para: 

**Resumo em Inglês**

**Resumo em Português**

**Resumo em Espanhol**

**Comment by jamilatta** [comment]
Realizei a atualização da aplicação com esse ajuste!

**Comment by jamilatta** [comment]
Verificando a funcionalidade identifiquei que ao realizar a ordenação os resumo ficam desordenados.

Vou corrigir!

**Comment by jamilatta** [comment]
Abel questiona sobre uma flecha no final do item collapsado: 
```
Jamil

Ficou muito bom. Mas, não deveria a flecha ir no final da chamada do resumo? 

Abc Abel 

```
Precisamos entender melhor o local e como iria sincronizar com os outros itens da interface.

**Comment by jamilatta** [comment]
Irei fechar esse ticket e criarei outro com o título "Reavaliar a posição das seta do resumo no issue TOC".

**Comment by gustavofonseca** [comment]
> Irei fechar esse ticket e criarei outro com o título "Reavaliar a posição das seta do resumo no issue TOC".

https://github.com/scieloorg/opac/issues/934
