### ISSUE TITLE
[BROPAC] Considerar uso de ISSN-L

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#916]
Atualmente nenhuma ferramenta de registro de SciELO (title e manager) permite registro do ISSN-L apenas ISSN impresso e online.

Por sermos uma base de dados online seria importante podemos registrar o ISSN-L e considerarmos para o novo site BR.

Mais informações: http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-l-for-publications-on-multiple-media/

**Comment by jamilatta** [comment]
@RPostalli 

Esse ticket pelo que me parece é um ticket para a Title Manager. O OPAC não é fonte primaria de dado. OPAC apenas exibi o conteúdo. Necessário criar esse ticket na Title Manager(@robertatakenaka ) e após as alterações na Title Manager adicionamos no OPAC para exibição. 

Vou manter esse ticket para fomentar uma discussão para que a @robertatakenaka possa contemplar isso na Title Manager.

De qualquer forma sugiro criar um ticket na **Title Manager**.

**Comment by RPostalli** [comment]
@jamilatta sim tem relação com manager mas também tem relação com BROPAC que é title PPE PROC. O site novo BR já tem repositório?

**Comment by RPostalli** [comment]
Replicado ticket
https://github.com/scieloorg/PC-Programs/issues/2936

**Comment by gustavofonseca** [comment]
Já que o ticket foi replicado para outro repositório, não vejo razão para continuar aqui portanto estou fechando. Caso necessário poderá ser reaberto a qualquer momento.
