### ISSUE TITLE
Reavaliar a posição das seta do resumo no issue TOC

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#934]
O Abel questiona a posição da seta no resumo do TOC: 

```
Jamil

Ficou muito bom. Mas, não deveria a flecha ir no final da chamada do resumo? 

Abc Abel
```

**Comment by alexxxmendonca** [comment]
Com a reformulação da página de resumo para permitir melhor indexação no Google Scholar, este ticket deixou de fazer sentido.

Ver #1762
