### ISSUE TITLE
Problema com Duplicidade de Artigos em Ahead of Print (AOP)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#937]
Existem 4 artigo da RESS na grade "Ahead of Print", que não já migraram para fascículos (Esta grade não deve existir).
v26n3
Sex and Gender Equity in Research: rationale for the SAGER guidelines and recommended use
v26n4
Use of health services among adults living in Manaus Metropolitan Region, Brazil: population-based survey, 2015
Epidemiology and Health Services: history, achievements, and future (2x)
Epidemiology and Health Services: 25 years in review
No fascículo v26n4 o artigo "Epidemiology and Health Services: history, achievements, and future" aparece duas vezes.

Em SciELO Brasil não ocorrem estes problemas: http://www.scielo.br/scielo.php?script=sci_issues&pid=2237-9622&lng=en&nrm=iso

Relação com #902

**Comment by RPostalli** [comment]
As interfaces novas não estão considerando a exclusão de ahead (tanto BR quanto SP)

Exclusão de ahead = artigo publicado em ahead que sai da grade de ahead e entra na grade do fascículo.

O que ocorre hoje é que os artigos ficam duplicados. Exemplo: https://www.scielosp.org/grid/icse/

FASCÍCULO
![image](https://user-images.githubusercontent.com/6084959/49870898-e7a88600-fdfb-11e8-9275-8ce51b27ea00.png)


AHEAD
![image](https://user-images.githubusercontent.com/6084959/49871038-43730f00-fdfc-11e8-8e49-880d42546171.png)

**Comment by patymori** [comment]
@RPostalli, pode validar em new.scielo.br?

**Comment by RPostalli** [comment]
@patymori testado em BR, está OK.
Em SP o problema continua.

**Comment by patymori** [comment]
@RPostalli, a correção foi feita somente na nova versão. Com a migração para a nova versão o problema em SP será resolvido.
