### ISSUE TITLE
Exibição de métricas do Dimensions e PlumeX no nível do periódico e do artigo.

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#957]
Na implementação atual, ao clicar no botão _Métricas_ na página do periódico ou do artigo somos levados diretamente às métricas relacionadas no SciELO Analytics. A idéia é que ao clicar nesses botões, seja exibido um modal -- nos mesmos moldes do que é exibido para o serviço _Versões e traduções_, na página do artigo --, onde o usuário poderá escolher entre as fontes de métricas _SciELO Analytics, Dimensions e PlumeX_. 

Para o _Dimensions_ deverá ser exibido um badge parecido com:
<img width="346" alt="screen shot 2018-05-15 at 17 01 10" src="https://user-images.githubusercontent.com/161335/40080544-ab36d180-5861-11e8-988e-d89609415f94.png">
https://app.dimensions.ai/details/publication/pub.1084501348?or_facet_year=2016&or_facet_year=2015&or_facet_publication_type_literal=article

E para o _PlumX_ um badge parecido com:
![](https://rcaap.files.wordpress.com/2016/08/plumx.png)
A caixa à direita aparece apenas quando o mouse está sobre o bagde do _PlumX_ (este apenas no nível do artigo).

**Comment by ednilson** [comment]
**Dimensions**
Descrição para criação do badges:
http://badge.dimensions.ai/

Segue alguns exemplos:
Tamanho pequeno:

`<span class="__dimensions_badge_embed__" data-doi="10.1590/1413-81232015207.07122015" data-hide-zero-citations="true" data-style="small_circle"></span>`

Retangulo

`<span class="__dimensions_badge_embed__" data-doi="10.1590/1413-81232015207.07122015" data-style="large_rectangle"></span>`

**PlumX**
Descrição para criação de badges:
https://plu.mx/plum/developers/widgets

https://plu.mx/scielo/a/?doi=10.1590%2F1413-81232015207.07122015
clilcar em _Embed widget_ na parte superior direita.

**Comment by patymori** [comment]
Foram acordadas as seguintes alterações nesta issue:

- Por existirem métricas no Dimensions e no PlumX somente no nível do Artigo neste momento, o modal está acessível somente nas páginas de Artigo.
- Foram desabilitados os detalhes dos badges. Portanto, os dados não serão exibidos ao posicionar o mouse sobre eles.

**Comment by jfunez** [comment]
Ficou ótimo!

testado com estes artigos no Firefox e no Chrome:
- https://homolog.opac.scielo.org/article/csp/2000.v16n4/951-961
- https://homolog.opac.scielo.org/article/csp/2012.v28n11/2095-2105/
- https://homolog.opac.scielo.org/article/csp/2008.v24n4/853-861/

**Comment by gustavofonseca** [comment]
Conforme comentei com a @patymori, falta apenas ajustar a grafia de SciELO (na implementação está apenas com letras minúsculas) e incluir o hyperlink dos badges nos nomes dos serviços. Mas eu concorco com o @jfunez, está ficando ótimo ;)

**Comment by alexxxmendonca** [comment]
Está mesmo! 👍 
Mas tenho a impressão que o logo do PlumX está ligeiramente maior que os demais? 

O do SciELO e do Dimensions está ocupando uma área de 100x100 px enquanto que o do PlumX está ocupando uma área de 120x120 px.

Poderiam ajustar isso?

**Comment by gustavofonseca** [comment]
Estou reabrindo esse issue para tratar dos últimos comentários.

**Comment by patymori** [comment]
@alexxxmendonca, ajustes feitos. Poderia validar?
Obrigada

**Comment by alexxxmendonca** [comment]
@patymori tudo certo agora! 👍
