### ISSUE TITLE
Corrigir os testes do ``admin.views`` que criam registros.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#96]
#### Problema:

Atualmente estamos com erros nos teste de registro de usuário e não temos teste de criação de sponsor.
#### Objetivo:

Corrigir os testes para cadastro de usuário e criar teste de cadastro de sponsor, com dados validados e inválidos.

**Comment by gustavofonseca** [comment]
Não há atualmente nenhum teste que deve ser corrigido, portanto estou fechando este ticket.
