### ISSUE TITLE
Número de periódicos deve ser sempre o de periódicos ativos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/opac#972]
Na página inicial, o número de periódicos deve ser sempre o de periódicos ativos:

![image](https://user-images.githubusercontent.com/4059679/42288636-efeda004-7f91-11e8-80a2-08f7ac307a37.png)

Os demais quadros (números, artigos, citações) devem levar em consideração a Coleção completa (ativos e não ativos).

**Comment by gustavofonseca** [comment]
É importante ter ciência de que a relação de proporcionalidade entre os valores será deformada de maneira negativa. 

Para ser mais claro, eu leio essa caixa da seguinte forma: _"A coleção Saúde Pública conta com um catálogo de 20 periódicos que juntos publicam 40459 artigos em seus 2201 números. Somados, os artigos citam 517733 fontes."_ 

Com a mudança solicitada a relação entre esses valores deixa de ser a consistente, o que torna inválida a forma de leitura anterior.

**Comment by jamilatta** [comment]
@gustavofonseca 

Concordo.

Devemos questionar novamente sobre esse ticket.

**Comment by alexxxmendonca** [comment]
Caros,

Concordo e tive o mesmo questionamento. Fiz questão de perguntar se era esse o entendimento mesmo.

Fiquem à vontade para questionarem.

**Comment by gustavofonseca** [comment]
Resolvido em https://github.com/scieloorg/opac_proc/commit/43bb85ae3d40ac1cf776ffb454cd0560c19968aa
