### ISSUE TITLE
Links para páginas informativas não estão funcionando

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#974]
Os links "Sobre o periódico", "Corpo editorial" e "Instruções aos autores" não estão levando a lugar nenhum.

 
<img width="891" alt="screen shot 2018-07-05 at 14 34 30" src="https://user-images.githubusercontent.com/161335/42338557-919aa36a-8060-11e8-922f-a5abeb3e544c.png">

**Comment by jfunez** [comment]
tem cara de regressão isso aí :(

**Comment by jfunez** [comment]
investigando sobre o problema encontrei o seguinte:
Neste commit feito pela @paratiuid : https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d 
foi ajustado o seguinte:
- adicionado `class="scroll"` nas ancoras (sobre o periódico, corpo editorial e instruções):

#### opac/webapp/templates/journal/includes/alternative_header.html
  - https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-0b4088e17a206a55d7154cf07fce7bebR122
  - https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-0b4088e17a206a55d7154cf07fce7bebR127
  - https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-0b4088e17a206a55d7154cf07fce7bebR132

####  opac/webapp/templates/journal/includes/header.html
- https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-86008371866bb380ad120abdd304b894R87
- https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-86008371866bb380ad120abdd304b894R87
- https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-86008371866bb380ad120abdd304b894R97


Também foi adicionado um código JS no arquivo: `opac/webapp/static/js/main.js` que *evita que o evento click seja executado normalmente*:
- https://github.com/scieloorg/opac/commit/f2d25978c76d9ba0884acf04391a0ee79de0451d#diff-553afcdeab89253e76f4edf642e8cb23R1007

concretamente a chamada do `e.preventDefault();` nesse trecho:
```js
$(".scroll").on("click",function(e) {
    e.preventDefault();

    var d = $(this).attr("href");
    var g = d.split("#")[1];				
    var p = $("a[name="+g+"]").offset();

    $("html,body").animate({
        scrollTop: (p.top-70)
    },500);

```

Acredito que podemos passar este issue para que a @paratiuid conserte.

**Comment by jfunez** [comment]
@gustavofonseca ajuste da @paratiuid foi instalado em homologação para validar.

no caso pode acessar o periódico CSP que tem pag. informativa atualizada (com ancoras corretas) copiada do site de produção (somente acessando em idioma inglês)

https://homolog.opac.scielo.org/journal/csp/

**Comment by alexxxmendonca** [comment]
Só o primeiro link (sobre o periódico) funciona. É isso mesmo?

**Comment by gustavofonseca** [comment]
@alexxxmendonca, o idioma da interface está em inglês, conforme @jfunez indicou?

Ao responder para vc identifiquei um problema: à partir da página do periódico (https://homolog.opac.scielo.org/journal/csp/), idioma definido para inglês, clico em "instructions to authors", sou levado para o conteúdo correto com a âncora correta, entretanto a barra superior não é exibida.
![screen shot 2018-07-31 at 09 35 01](https://user-images.githubusercontent.com/161335/43459801-0f675100-94a5-11e8-8dd5-a94fa81aa779.png)

**Comment by alexxxmendonca** [comment]
Opa, falha minha! Não tinha testado na interface EN.

Está tudo certo na interface EN, mesmo.

Não consegui identificar esse erro no Chrome, @gustavofonseca. Aqui a barra superior apareceu.

**Comment by gustavofonseca** [comment]
Hm, entendi. Só pra deixar registrado, eu estou usando Firefox 62.0b12 (64-bit).
