### ISSUE TITLE
Atualização de dependência: packtools (versão 1.0 liberada)

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#98]
#### Problema:

A dependência "packtools" esta desatualizada.

#### Objetivo

Atualizar dependência "packtools" no ``requirements.txt`` para a nova versão 1.0.

#### Observações:
- versão mais recente: https://pypi.python.org/pypi/packtools

**Comment by jamilatta** [comment]
@jfunez 

essa tarefa muda o uso da biblioteca?

**Comment by jfunez** [comment]
@jamilatta nop! 
a lista completa de mudanças este no [HISTORY.md do repo de packtools](https://github.com/scieloorg/packtools/blob/master/HISTORY.rst)

**Comment by ednilson** [comment]
Aguardando aprovação do PR #99

**Comment by jfunez** [comment]
resolvido em: d8fe179bc284529040731ca12ee1631c9e79791c
instalada a versão mais recente: 1.0.1 do packtools
