### ISSUE TITLE
Adicionar uri para imagem que é esperarada pelo PubMed

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#980]
@RPostalli apontou a seguinte reclamação do PubMed:

eles esperar que o site: scielosp.org sirva uma imagem no seguinte endereço: 
- http://www.scielosp.org/img/scielo.gif

Atualmente esta retornando um erro 404 (not found)
A imagem em questão é servida nessa URL no site de Metodologia, por exemplo: 
- http://old.scielosp.org/img/scielo.gif

**Comment by jamilatta** [comment]
@RPostalli 

Imagem disponível: https://www.scielosp.org/img/scielo.gif

**Comment by jamilatta** [comment]
Pessoal para entendermos melhor o por que é necessário essa imagem no site. 

Questionei isso com a @RPostalli e ela me passou que o PubMed (não o PubMed Central), utiliza isso para apresentar no site.

Ver: 

<img width="1407" alt="screenshot 2018-08-03 09 45 52" src="https://user-images.githubusercontent.com/373745/43644867-950f187a-9706-11e8-9b1e-579c26e1f246.png">

Reparem no canto direito está a imagem que adicionamos. 

Outra informação importante é que o PubMed pega a imagem "On the fly". 

Ele monta uma URL nesse formato: https://www.ncbi.nlm.nih.gov/corehtml/query/egifs/http:--www.scielosp.org-img-scielo.gif

O ambiente de homologação e produção do novo **Site SciELO SP** está com essa correção.

Grato @RPostalli pela explicação.

**Importante** saber a diferença entre PubMed Central e PubMed, vejam: https://www.ncbi.nlm.nih.gov/pmc/about/faq/#q2
