### ISSUE TITLE
Desvincular obrigatoriedade de tag de other para dar order na publicação do site BR novo

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#987]
O site BR atual só publica artigos que possuem paginação eletrônica (elocation-id), ahead of print (sem paginação) e paginação romana ou outros tipos de paginação (diferente da fpage + lpage - numérica) com a tag de other, exemplo da tag inserida no XML::

```<article-id pub-id-type="other">00602</article-id>```

Esta tag é o que da a ordenação dos artigos dentro do sumário. Toda sua gestão e feita internamente e dividida por seção ```<subject>``` (cada centena esta condicionada a uma seção diferente) e estes números não podem se repetir. Devido ao aumento da modalidade PC, a gestão dessa numeração de order é um processo gigantesco dentro na unidade de produção e como todo o processo manual, passível de muitos erros o que causa reprocessamento (retrabalho).

A nova interface deve ser capaz de:
- Organizar os artigos por seção que estará descrita na tag ```<subject>``` que é obrigatória nos XMLs SciELO
- Organizar os artigos por data de publicação da mais nova para a mais antiga (atualmente ocorre ao contrário).

**Comment by robertatakenaka** [comment]
@RPostalli Aqui analisamos que há 2 problemas diferentes:
1. é a obrigatoriedade da tag publication-id (other) - que no momento não é possível remover, pois quem depende desta tag é o processamento do site antigo que alimenta ArticleMeta que provê os dados para o site novo. Somente quando quebrarmos esta dependência (ainda este ano) será possível não inserir este dado.
2. a ordenação no site novo. Isso sim poderá ser resolvido. É isso que será resolvido neste issue.

**Comment by patymori** [comment]
@RPostalli, feita atualização da nova versão. Pode verificar em new.scielo.br?

**Comment by RPostalli** [comment]
@patymori testei PC e AOP, e está sendo considerado a data da mais nova para mais antiga.

O único problema (que talvez nem seja um problema) é que não está considerando esta ordenação por seção para os casos AOP. @gustavofonseca Sugiro discutir está questão em reunião. Será mesmo necessário agrupar os artigos por seção no toc uma vez que a interface permite a escolha do botão só por seção?

Eu queria testar um fascículo regular que tem arquivos com paginação normal + paginação romana, mas o fascículo não está no ar é a RBCCV-v33n6 https://new.scielo.br/grid/rbccv/

Já está no old: http://www.scielo.br/scielo.php?script=sci_issues&pid=0102-7638&lng=en&nrm=iso

Deveria estar no new também.

**Comment by RPostalli** [comment]
Achei um caso de fascículo regular onde o editorial tinha paginação romana e possuía other.

No site novo a sequência está como deveria ser:

https://new.scielo.br/toc/abo/2018.v81n6/

No old:

http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0004-274920180006&lng=en&nrm=iso

**Comment by gustavofonseca** [comment]
@RPostalli, este ticket pode ser fechado? Vejo que a atividade diretamente relacionada a ele já foi realizada.

**Comment by RPostalli** [comment]
@gustavofonseca como comentei na última reunião GT, eu não achei que eu deveria fechar, achei que o responsável por fazer a atividade fechava após o teste. Mais ou menos como eu faço no SPS. Mas sim pode, vou fechar.
