### ISSUE TITLE
Ticket de Atenção - Seções para XML para novo site BR

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#988]
Nem sempre as seções que estão registradas na title e vinculadas a um fascículo são as mesma seções descritas dentro do XML. Usualmente as diferenças estão entre singular e plural, mas podem ocorrer outras diferenças, pois o sistema deixa processar, apenas acusa erro na diferença, não bloqueia.

No site BR atual:
A seção registrada na title é a que aparece no sumário [1]
A seção que é marcada no XML é a seção que aparece no Artigo na interface [2]

[1]
NA TITLE
![image](https://user-images.githubusercontent.com/6084959/43973554-3f5ac228-9cae-11e8-8a6c-557c389ba93e.png)

NO SUMÁRIO
![image](https://user-images.githubusercontent.com/6084959/43973050-b57c5b44-9cac-11e8-9677-6d0b315ed5cf.png)

[2]
NO XML:
![image](https://user-images.githubusercontent.com/6084959/43973068-c2fa4646-9cac-11e8-919d-a01340c725d4.png)

NO ARTIGO NA INTERFACE:
![image](https://user-images.githubusercontent.com/6084959/43973256-5b0e59fe-9cad-11e8-8ced-9cd3cec3fad1.png)

Eu recomendo que seja considerado para nova interface BR apenas as seções descritas no XML, uma vez que este dado passou por controle de qualidade e bate com seu original em PDF e esta registrada no arquivo que é fonte de metadados. 

Além disso acredito que em caso de correções/divergências, a correção também seria mais prática do que corrigir na title.

**Comment by gustavofonseca** [comment]
O novo site considera apenas as seções descritas no XML, e as trata como etiquetas associadas aos documentos.
