### ISSUE TITLE
Interface BR nova não apresenta número de suplemento na grade

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#989]
Interface BR nova não apresenta número de suplemento na grade

Site Atual: http://www.scielo.br/scielo.php?script=sci_issues&pid=0001-3765&lng=en&nrm=iso
![image](https://user-images.githubusercontent.com/6084959/43977126-7f428c58-9cb9-11e8-970a-7e9c47c4e12c.png)

Site Novo: https://opac.scielo.br/grid/aabc/
![image](https://user-images.githubusercontent.com/6084959/43977178-aab95876-9cb9-11e8-9e84-c62f5dd8b2c8.png)

Para conhecimento; é possível ter:

suplemento de número = X suppl.
    - Exemplo: scie v10n03s01

suplemento de volume suppl. X
    - Exemplo: scie v10s01

Quando não existe menção de informação numérica para o suplemento de volume, exemplo suplemento zero, a informação númerica não acompanha o registro suppl.

Exemplo para scie v10s00, na grade fica =  suppl.

**OBS: Seria legal se pudêssemos reordenar alguns suplementos de lugar, a regra aplicada atualmente é que se for suplemento de volume, entra sempre ao final da grade, se for suplemento de número entra logo após o número. MAS, muitos suplementos de número de outras revistas estão ao final, ou por erro de quem criou a title ou porque o próximo número do ano chegou antes do suplemento do número anterior não tendo espaço para  criar na title. Não temos como prever as publicações de suplementos e números especiais.

**Comment by jamilatta** [comment]
@RPostalli 

Poderia validar em ambiente de homologação: https://homolog.opac.scielo.br/scielo.php?script=sci_issues&pid=0001-3765&lng=en&nrm=iso

**Comment by gustavofonseca** [comment]
@jamilatta e @RPostalli, verifiquei a seguinte amostra de periódicos e está funcionando corretamente: 

* Anais da academia brasileira de ciências
* Acta Botanica Brasilica
* Brazilian Journal of Biology (exceto no ano 2012 que apresenta duplicação no `3 suppl.`)
* Arquivo Brasileiro de Medicina Veterinária e Zootecnia
* Pesquisa Veterinária Brasileira

**Comment by jamilatta** [comment]
Verifiquei o caso "**Brazilian Journal of Biology (exceto no ano 2012 que apresenta duplicação no 3 suppl.)**"

Descobrir que quem indica que é um suplemento é o AM.

Abri um ticket: https://github.com/scieloorg/articles_meta/issues/142

**Comment by RPostalli** [comment]
@jamilatta @gustavofonseca 

Verifiquei o link de homologação enviado pelo Jamil mais a abc e está OK!

No entanto o problema ocorre também com números especial (ver RLAE)
site atual
![image](https://user-images.githubusercontent.com/6084959/45570897-d2db4700-b83a-11e8-81e4-c94f2efa6350.png)

site novo
![image](https://user-images.githubusercontent.com/6084959/45570914-e4bcea00-b83a-11e8-990b-3578b0016d6a.png)

**Comment by patymori** [comment]
@RPostalli , poderia validar?

**Comment by RPostalli** [comment]
@patymori testei a rlae em homologação, agora está OK.
