### ISSUE TITLE
Problemas na apresentação de label de correspondência em artigos no site novo BR

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#992]
Problemas detectados consultando o artigo: https://opac.scielo.br/article/rbort/2018.v53n3/267-275/en/#ModalTutors

Problema 1: O label está distante do texto

Exemplo: 
![image](https://user-images.githubusercontent.com/6084959/44033885-1a71aa54-9ee2-11e8-813d-04f1cd50a23c.png)

Manter o texto na mesma linha do label.

Problema 2: A nova interface desconsidera o label inserido para identificar autor correspondente.

Veja que no [PDF](https://opac.scielo.br/pdf/rbort/2018.v53n3/267-275/en), existem dois autores correspondentes:
![image](https://user-images.githubusercontent.com/6084959/44033979-63723ee4-9ee2-11e8-8a03-a0984cddc02c.png)

![image](https://user-images.githubusercontent.com/6084959/44034038-841058a2-9ee2-11e8-8530-855fcf5de070.png)

Na interface nova não dá pra entender quem são estes autores.
![image](https://user-images.githubusercontent.com/6084959/44034081-a018257a-9ee2-11e8-9661-0329a9fa0166.png)

É preciso manter os labels (diferentes de ref-type="aff") na caixa "About the authors", pois são importantes indicativos, não só para afiliação mas para [outras notas relacionadas a autor](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-fn.html#elemento-fn-notas-autores) e sempre são interligadas com label.

**Comment by patymori** [comment]
Levar em consideração casos como este:

https://opac.scielo.br/article/acb/2018.v33n11/975-982/#ModalTutors

XML:
```xml
<author-notes>
        <corresp id="c1">
                <label>Correspondence:</label> Delano Gurgel Silveira Avenida Beira Mar,3960/2304 60165121 Fortaleza - CE Brasil Tel.: (55 85)98822-9299 <email>delanogs@gmail.com</email>
        </corresp>
        <fn fn-type="conflict" id="fn1">
                <label>Conflict of interest:</label>
                <p> none </p>
        </fn>
</author-notes>
```


XML do artigo exemplo citado no issue:
```xml
<author-notes>
        <corresp id="c1">
                <label>*</label>Corresponding author: Dr Abdelouahab Kenoufi - E-mail: <email>kenoufi@s-core.fr</email>
        </corresp>
</author-notes>
```

**Comment by RPostalli** [comment]
Importante considerar também possíveis labels relacionados aos seguintes tipos de fn-type **em authot-notes**. https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-fn.html#notas-de-autor

**Comment by patymori** [comment]
@RPostalli , pode validar em new.scielo.br?

**Comment by RPostalli** [comment]
@patymori testado. Está OK!
