### ISSUE TITLE
Problema com apresentação de afiliação no novo site BR

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#993]
Quando um autor possui duas afiliações descritas em um único conjunto, ou seja, a equipe editorial não identifica cada afiliação para o autor em separado, é obrigatório que a marcação XML tenha este dado identificado, então é criado uma aff "fechada" nova sem a identificação de original para contemplar o metadado, uma vez que aff só permite um orgname.

Exemplo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2179-84512017000300385&lng=en&nrm=iso&tlng=en

São 3 autores:
![image](https://user-images.githubusercontent.com/6084959/44035172-37fae57e-9ee5-11e8-8dc3-0eadd7e91b36.png)

Onde o segundo autor tem 2 afiliações (mas só um label)
![image](https://user-images.githubusercontent.com/6084959/44035449-ee86da0a-9ee5-11e8-8021-a4ad0415a559.png)

A marcação em XML fica com uma xref fechada a mais (acréscimo de label):
![image](https://user-images.githubusercontent.com/6084959/44035584-30ce9ec0-9ee6-11e8-9d91-b32f4247c913.png)

E a identificação da segunda afiliação deste autor fica sem o original:
Afiliação 1:
![image](https://user-images.githubusercontent.com/6084959/44035705-765d2808-9ee6-11e8-9476-d9e77719154f.png)

Afiliação 2:
![image](https://user-images.githubusercontent.com/6084959/44035762-a18847c4-9ee6-11e8-9833-5f8b53cd1335.png)

O problema é que a interface atual considera o original para apresentação no site, já a interface nova funciona de forma diferente a afiliação ficou com uma afiliação duplicada e com espaços estranhos:
https://opac.scielo.br/article/tema/2017.v18n3/385-403/en/#ModalTutors

![image](https://user-images.githubusercontent.com/6084959/44035920-f71cb102-9ee6-11e8-9dac-7be8bf46b703.png)

**Comment by patymori** [comment]
@RPostalli, pode verificar em new.scielo.br?

**Comment by RPostalli** [comment]
@patymori testado. Está OK!
