### ISSUE TITLE
Seções não aparecem em site novo BR

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/opac#995]
As seções não aparecem no site BR novo, nem na lista nem ao lado dos títulos dos artigos:

Site atual sumário
http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-311X20180001&lng=en&nrm=iso

![image](https://user-images.githubusercontent.com/6084959/44096005-94a4bf68-9fb0-11e8-9435-da462d3bec28.png)

Sito novo sumário
https://opac.scielo.br/toc/csp/2018.v34n1/

![image](https://user-images.githubusercontent.com/6084959/44096051-b25206ce-9fb0-11e8-9839-125235cc39b9.png)

O comportamento do aparecimento das seções está "estranho", os fascículos em HTML (2013 para baixo) parece que considera todas as seções. Os XMLs (2014 para frente) aparecem aparentemente até os fascículos publicados final de 2016 até 2017, desta data em diante param de aparecer.

Exemplos: 

Primeiro fascículo de 2016 - BJMBR
https://opac.scielo.br/toc/bjmbr/2016.v49n1/

![image](https://user-images.githubusercontent.com/6084959/44096267-44379e82-9fb1-11e8-995a-1b0f306c05ea.png)

Último fascículo de 2016 - BJMBR
https://opac.scielo.br/toc/bjmbr/2016.v49n12/

![image](https://user-images.githubusercontent.com/6084959/44096319-5edb79c0-9fb1-11e8-9d8c-e228549443f7.png)

Existem casos que alguns artigos aparecem com a etiqueta outros não. Exemplo:

![image](https://user-images.githubusercontent.com/6084959/44096438-a387941e-9fb1-11e8-8049-f0faae3fa230.png)

Os dois artigos que não aparecem possuem o registro da seção:

![image](https://user-images.githubusercontent.com/6084959/44096482-bd3b844c-9fb1-11e8-9d50-fc8d6d5f9eb5.png)

![image](https://user-images.githubusercontent.com/6084959/44096501-ca2f02fa-9fb1-11e8-8c25-55c2aefa30ed.png)

Sugestão: A melhor forma de considerar as seções, é utilizando as mesmas como etiquetas (recomendo extração da tag [subject](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-subj-group.html) disponível no XML) onde o usuário poderá agrupar apenas os artigos nas seções de seu interesse e acrescentar outros filtros, como data de publicação.

IMPORTANTE: Ver a relação com ticket: "[Ticket de Atenção - Seções para XML para novo site BR"](https://github.com/scieloorg/opac/issues/988)

**Comment by robertatakenaka** [comment]
solução: https://github.com/scieloorg/xylose/pull/164
será necessário reprocessar, a partir da etapa "transform".

**Comment by patymori** [comment]
O problema foi corrigido. @RPostalli, poderia validar?

**Comment by RPostalli** [comment]
@patymori aparentemente o problema foi corrigido em BR, mas não em SP.

CSP - br
https://new.scielo.br/toc/csp/2018.v34n1/

CSP - sp
https://www.scielosp.org/toc/csp/2018.v34n1/

Não entendi pq uma seção aparece na lista em dois idiomas. O idioma da seção não deveria mudar com o idioma da interface e no caso de não ter considerar o inglês igual é feito na interface antiga?
Veja como aparece (usei o  ------):

 Todas las secciones «
 Article ------
 Artigo------
 Comunicação Breve
 Editorial
 Errata
 Methodological Issues
 Perspectivas
 Resenha
 Review

A sequência destas seções estão respeitando qual regra? Está diferente do site antigo, por exemplo Errata sempre é a última seção. Vejam: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-311X20180001&lng=en&nrm=iso

**Comment by patymori** [comment]
@RPostalli, seguem as respostas:

- O correção não está aplicada ainda em SP. BR está com a última versão da aplicação e, com a atualização de SP o problema é resolvido.
- Não existe uma correspondência de nomes de seções determinadas na Title e nos XMLs dos artigos e a aplicação consegue fazer essa relação para exibir conforme o esperado. Existem tickets abertos para tratar desse problema em específico: #988 e #919

Estou encerrando este ticket e acompanharemos o problema reportado acima nos tickets relacionados.

**Comment by RPostalli** [comment]
👍
