### ISSUE TITLE
Função *Como citar este artigo* não está funcionando corretamente

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac#999]
Passos para a reprodução do problema:

1. Acesse a página de leitura do artigo em HTML
2. Clique no círculo azul no canto inferior esquerdo
3. Clique na opção "Como citar este artigo"

Repare que o modal contendo as formas de citação não é exibido.

O problema foi percebido no artigo https://www.scielosp.org/scielo.php?script=sci_arttext&pid=S1413-81232012000100018&lang=pt

**Comment by alexxxmendonca** [comment]
Problema corrigido:

![image](https://user-images.githubusercontent.com/4059679/119720956-f73bae00-be40-11eb-8f35-42bf873e5f89.png)
